### ISSUE TITLE
Subscribe to a given partition 

### ISSUE THREAD

**Issue by amarjeetanandsingh** [confluentinc/confluent-kafka-go#1001]
Description
===========
Is there a way to subscribe to a given partition of a topic?

Currently I see only subscribe topics api which doesn’t accept partition. 

‘’’
    func (c *Consumer) SubscribeTopics(topics []string, rebalanceCb RebalanceCb) (err error) {
	err = c.verifyClient()
	if err != nil {
		return err
	}
	    ctopics :=     C.rd_kafka_topic_partition_list_new(C.int(len(topics)))
    	defer C.rd_kafka_topic_partition_list_destroy(ctopics)

	for _, topic := range topics {
		ctopic := C.CString(topic)
		defer C.free(unsafe.Pointer(ctopic))
		   C.rd_kafka_topic_partition_list_add(ctopics, ctopic, C.RD_KAFKA_PARTITION_UA)
	}

	e := C.rd_kafka_subscribe(c.handle.rk, ctopics)
	if e != C.RD_KAFKA_RESP_ERR_NO_ERROR {
		return newError(e)
	}

	c.rebalanceCb = rebalanceCb

	return nil
    }
‘’’

/cc
@edenhill @emasab

**Comment by milindl** [comment]
You can just use Assign,and not call SubscribeTopics.

For instance, 
```go
c, err = NewConsumer(...)
// check err
err = consumer.Assign(<list of topic partitions>)
// don't call subscribe at all before or after this.
```

Please reopen this if there are any more questions, thanks!
