### ISSUE TITLE
Error.IsFatal() not working as expected

### ISSUE THREAD

**Issue by holgerson97** [confluentinc/confluent-kafka-go#1003]
Description
===========
I have written a Golang application which consumes messages from a Kafka topic. When polling messages I want to handle errors, therefore I want to restart the consumer if the error is not fatal (e.g. a timeout occurred).

When catching the error and calling the `IsFatal()` function it return false, but the corresponding logline says:
`sasl_ssl://pkc-zpjg0.eu-central-1.aws.confluent.cloud:9092/bootstrap: SASL authentication error: Authentication failed (after 5428ms in state AUTH_REQ)` .

This line is followed by the Golang application to crash: 
`fatal error: unexpected signal during runtime execution`.

If I check the error code directly against: `kafka.ErrAuthentication` it works perfectly.

Is this the expected behaviour? From my understanding the error is fatal, since the application crashes, but it's not considered to be fatal by the client.

If you`ve got more information about Handling Kafka Errors I would be more than happy if you would share them with me.
Thank you in advance!

How to reproduce
================
This is my ConfigMap:

```go
consumer, err := kafka.NewConsumer(&kafka.ConfigMap{
	"bootstrap. Servers":  cfg.BootstrapServers,
	"group.id": cfg.GroupID,
	"client.id": hostname,
	"security. Protocol": "SASL_SSL",
	"sasl.mechanisms":  "PLAIN",
	"sasl.username": cfg.SaslUsername,
	"sasl.password": cfg.SaslPassword,
	"auto.offset.reset": "latest",
	"enable.auto.commit": "false",
	"partition.assignment.strategy": "range",
	"log_level": "0",
})
```

This is my function that consumes:
```go
for {
	event := router.ConsumerClient.Consumer.Poll(kafkaConfig.PollIntervall)

	switch e := event.(type) {
	case *kafka.Message:

		if err := router.topicRouter(e); err != nil {
			return fmt.Errorf("routing message: %w", err)
		}

		_, err := router.ConsumerClient.Consumer.Commit()
		if err != nil {
			return fmt.Errorf("conusme error: %w", err)
		}

	case kafka.Error:
		router.logger.Error("consumer error occurred:", e)

		if e.Code() == kafka.ErrAuthentication {
			return fmt.Errorf("fatal error occurred: %w", err)
		}

                 // Not working: Prints: false
		if e.IsFatal() {
			fmt.Println(e.IsFatal())
		}
		router.ConsumerClient.RestartConsumer()
	}
}
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):  github.com/confluentinc/confluent-kafka-go v1.9.3-RC3
 - [x] Apache Kafka broker version: I am running on confluent-cloud. 
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system: macOs 13.2.1 (22D68)
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
Thanks for reporting this.

Most errors (including ErrAuthentication) are considered non-fatal errors by the library, and the library itself does not crash in these cases, and keeps retrying. (The library should not even crash for fatal errors, just that the particular instance of the consumer/producer becomes non-functional thereon).

In general, the error is exposed to the user of the library, who can take action for specific errors and treat them as fatal/retriable (like you're doing for ErrAuthentication).

So: what I'm really concerned about is that your application crashes when authentication fails. That should not happen. The 'fatal error' mentioned in "fatal error: unexpected signal during runtime execution" is from the go runtime, and not the library.

1. How is your application being built? Are there any flags that are apart from the usual `go build` ?
2. Can you share the logs in the debug mode? (add "debug": "all" to your configuration if possible).

**Comment by milindl** [comment]
Closing this - please update with the new information requested if the issue persists.
