### ISSUE TITLE
Support of metadata properties for data contracts

### ISSUE THREAD

**Issue by Korzhenevskyi** [confluentinc/confluent-kafka-go#1006]
Description
===========
This is not a bug/issue report but rather a question (or feature request).

I can find metadata properties in the documentation https://docs.confluent.io/platform/7.4/schema-registry/fundamentals/data-contracts.html#metadata-properties. However, I don't see it in the code here.

Is there a plan to support this? Or maybe, I just didn't find the correct place...
If I understand correctly, it must be included in https://github.com/confluentinc/confluent-kafka-go/blob/master/schemaregistry/schemaregistry_client.go#L77, but I am not sure.

**Comment by rayokota** [comment]
Yes, this is planned to be added

**Comment by rayokota** [comment]
Fixed by https://github.com/confluentinc/confluent-kafka-go/pull/1199
