### ISSUE TITLE
Channel producer appears to have a very high latency

### ISSUE THREAD

**Issue by matthiasdv** [confluentinc/confluent-kafka-go#102]
Description
===========

I am producing messages to Kafka using the confluent-kafka-go wrapper. This works as expected on a local development machine, but when connecting my program to a larger AWS-based cluster things become slow. 

To produce messages I am using the channel based producer as follows; 

```
func (o *KafkaOutput) Start(done chan int, dataChannel chan core.Data, errorsChannel chan error) error {
	go func() {
		run := true

		for run == true {
			select {
			case <-done:
				logrus.Info("Stopping Kafka Output On User Request")
				run = false

			case evt := <-o.producer.Events():
				switch ev := evt.(type) {
				case *kafka.Message:
					m := ev
					if m.TopicPartition.Error != nil {
						logrus.Errorf("delivery failed: %v\n", m.TopicPartition.Error)
						o.metrics.IncrementCounter("output.kafka.delivery_failed")
					} else {
						logrus.Debugf("delivered message to topic %s [%d] at offset %v with key %s",
							*m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset, m.Key)
						o.metrics.IncrementCounter("output.kafka.delivered")
					}

					ts, _ := o.cache.Get(string(m.Key))
					o.cache.Remove(string(m.Key))
					duration := time.Now().Sub(ts.(time.Time))
					logrus.Debugf("roundtrip time: %s", duration)
					o.metrics.LogIntegerGauge("output.kafka.latency", duration.Nanoseconds())


				default:
					logrus.Debugf("ignored event: %s\n", ev)
				}

			case dataEvent := <-dataChannel:
				if dataEvent == nil {
					continue
				}

				o.producer.ProduceChannel() <- &kafka.Message{
					TopicPartition: kafka.TopicPartition{Topic: &o.dataTopic, Partition: kafka.PartitionAny},
					Timestamp:      time.Now(),
					TimestampType:  kafka.TimestampLogAppendTime,
					Key:            dataEvent.GetKey(),
					Value:          dataEvent.GetValue(),
				}

				o.cache.Add(string(dataEvent.GetKey()), time.Now())

				o.metrics.IncrementCounter("output.kafka.written")

			case errorEvent := <-errorsChannel:
				if errorEvent == nil {
					continue
				}

				o.producer.ProduceChannel() <- &kafka.Message{
					TopicPartition: kafka.TopicPartition{Topic: &o.errorTopic, Partition: kafka.PartitionAny},
					Timestamp:      time.Now(),
					TimestampType:  kafka.TimestampLogAppendTime,
					Value:          []byte(errorEvent.Error()),
				}

				o.metrics.IncrementCounter("output.kafka.errors")
			}

		}
	}()

	return nil
}
```
When a message is sent to the Producer channel, the current timestamp is recorded in a cache. Later, when Kafka sends it's acknowledgement message, the timestamp is deserialised from cache and a comparison is made. 

When I connect the program to a local single-node development instance of Kafka this duration is typically in the order of microseconds. 

However, when I connect the program to an AWS based cluster consisting of three nodes this jumps orders of magnitude and takes several seconds. Even worse, when the program is deployed to an AWS instance, this duration increases over time to several minutes. 

This very closely resembles the following issue:
https://github.com/confluentinc/confluent-kafka-go/issues/43 

Triage
================

- none of the Kafka nodes, nor the instance that runs the program appear to be experiencing significant load. The Kafka nodes do have the greater part of their memory reserved by the page cache, which I am supposing is normal. 
- when I measure the execution times of the channel communication in the Go program they all appear to be in the order of microseconds 
- i believed this to be a problem related to the librdkafka config, so I tried the following settings to no avail: 
* "go.batch.producer": true,
* "queue.buffering.max.ms": 100,
* "queued.min.messages": 100,
* "request.required.acks": 1, 
- it appears that something, somewhere is either blocking or buffering messages. Or backpressure is being generated. But since I believe I have the rdkafka config correct, the Go program doesn't appear to be blocking anywhere, and not a signle instance is experiencing load I'm at a loss. 

Do you have any general pointers on where this issue may be originating? 

I'm not quite sure the confluent-kafka-go wrapper or my code that interacts with it are to blame, but I'm at a loss as to where it might be coming from

Thanks

Checklist
=========

 - confluent-kafka-go v0.11.0 and librdkafka 0.11.0
 - OS: Kafka: Ubuntu 16.04 |  Go program instance: Amazon Linux AMI 2017.03.g x86_64 ECS 

> time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372952259s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372933085s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372914643s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372907623s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372888357s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372771565s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372764874s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372756678s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372749807s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.37267849s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372671868s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372628479s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372572023s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372563728s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372541262s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.37252881s"
time="2017-10-10T22:13:25+02:00" level=debug msg="roundtrip time: 2.372489552s"

**Comment by edenhill** [comment]
Did you find the issue?

**Comment by matthiasdv** [comment]
I did not actually; Accidentally closed the issue while using my mobile. I'll be spending some time digging into this. 

Do you have any pointers or ideas as to where to start? 

Thanks!

**Comment by edenhill** [comment]
You'll want to figure out where the latency is:
 * broker processing
 * network
 * librdkafka
 * Go

The Stats events will give you some of that information:
 * enable statistics by setting `"statistics.interval.ms": 1000`
 * handle the `*Stats` event on the p.Events() channel
 * monitor the per-broker `int_latency` and `rtt` metrics

See: https://github.com/edenhill/librdkafka/wiki/Statistics

You can also enable `debug` `broker,protocol,msg` to get a live view of what is going on. Pay special attention to ProduceResponse rtt printouts.

You could also try setting `socket.blocking.max.ms` to a low value, e.g., 1 or 1.

**Comment by matthiasdv** [comment]
The metrics returned by enabling librd statistics seem normal. typically 7ms latency. So the internals are absolutely fine. 

Enabling librd producer debug messages indicates a typical rtt of 500ms, which is what I'd expect over a VPN. I suppose this will be much lower on AWS infrastructure. 

To meaure and monitor message roundtrip times time.now() is written to an LRU cache, _for each individual message_. When Kafkas ack message returns the timestamp is read from the cache and a comparison is made. 

My hypothesis is that Kafka is working fine, but the LRU cache read and writes on a per message basis are causing backpressure. I think I'll be reviewing how this RTT monitoring works.

If i assume correctly, then the internals of librd send messages to Kafka in batches (when enabled) and then propagates acknowledge messages back to the relevant Kafka-go channel for _every single message_, is that right? 

So then I'd have to decouple acknowledged / not acknowledged metrics on a per message basis, and relevant round trip times reported by librd on a batch basis.

**Comment by matthiasdv** [comment]
The timestamp type of messages returned by Kafka is `NotAvailable`. 

The statistics produced by librdkafka roundtrip times, but these seem to be significantly different from the latency of the acknowledge messages displayed by enabling producer debug. Is there any way I can read the ack time produced by enabling debug?

**Comment by edenhill** [comment]
librdkafka provides per-message latency metrics with the rd_kafka_message_latency() API:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L954

This is not yet exposed in the Go client but if you're up for a tiny cgo adventure you can add a call here:
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/message.go#L155

**Comment by matthiasdv** [comment]
Thanks, I'll look into it!
