### ISSUE TITLE
Bug: mock_schemaregistry_client does not return the id from the cache

### ISSUE THREAD

**Issue by shalinibani** [confluentinc/confluent-kafka-go#1026]
While writing a unit test, I discovered that `Register()` mock does not return the value from the cache that has been previously registered.
```
if ok {
		return id, nil
	}
```

https://github.com/confluentinc/confluent-kafka-go/blob/262be150ec849f485f0fda85de196a2ca188e094/schemaregistry/mock_schemaregistry_client.go#L86C2-L88

Shouldn't this be `return idCacheEntryVal.id, nil`?

**Comment by milindl** [comment]
Thank you for finding this. Yes, it should return `return idCacheEntryVal.id, nil`

Would you like to make a PR for this change?

**Comment by shalinibani** [comment]
Yes, I would like to but I don't have permission to create a PR or push the changes.

**Comment by milindl** [comment]
That's odd, you should be able to fork the repository, and then create a PR from your forked repository, similar to this PR for instance: #1020 . Is there some permissions issue with that flow?

**Comment by milindl** [comment]
Ah, I see there is already a PR for this issue. #971.

**Comment by milindl** [comment]
Closed with #971
