### ISSUE TITLE
how to use sasl_ssl with gssapi

### ISSUE THREAD

**Issue by k1ng87** [confluentinc/confluent-kafka-go#103]
just like the title says...how do you config the go client with sasl_ssl and gssapi?

**Comment by edenhill** [comment]
confluent-kafka-go is based on librdkafka so you could start with the following wiki pages:
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka
https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka
