### ISSUE TITLE
Too many dependencies in `go.sum` when using the v2 client

### ISSUE THREAD

**Issue by faheel** [confluentinc/confluent-kafka-go#1040]
Description
===========

The v1 client (v1.9.2) already had around 211 dependencies, but in the v2 client they've increased by more than 10x to around 2417 dependencies.

Any module that uses `confluent-kafka-go` gets all these 2000+ dependencies added into its `go.sum`, whereas most of them seem like test dependencies and are not relevant to the users of `confluent-kafka-go`.

How to reproduce
================

1. Create 2 separate Go modules - one using `confluent-kafka-go/v2` client (v2.2.0) and the other using the v1 client (v1.9.2)
1. Create a consumer or producer exactly as mentioned in the README (this step might be optional)
1. `go get` the respective Kafka clients and then check the size of `go.sum` in both the modules (`cat go.sum | wc -l`)

`go.sum` in the module using the v1 client has 211 dependencies, whereas for the module using the v2 client has 2417 dependencies.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 2.2.0
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: N/A
 - [x] Operating system: macOS 13.4
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by faheel** [comment]
Targeting Go 1.17 or higher might help, as Go 1.17 introduced [Module graph pruning](https://go.dev/ref/mod#graph-pruning)

**Comment by milindl** [comment]
Thanks for bringing this up!
This could be related to #1048, the testing dependencies. I'm taking a look at that. I'll give this one a look again after that's fixed.

**Comment by milindl** [comment]
Fixed with #1074, please reopen if it persists (it will be released soon in the 2.3 release)
