### ISSUE TITLE
Message header support

### ISSUE THREAD

**Issue by sheeysong** [confluentinc/confluent-kafka-go#105]
Description
===========
We have upgraded to Apache kafka 0.11 on broker server side, and using confluent-kafka-go example to pub/sub message with header which set to Message.Opaque, however, we didn't get Opaque back from the consumer side.

producer_channel_example.go:
        value := "Hello Go!"
	headers := make(map[string]interface{})
	headers["x-topsy-fence-key"] = "FenceValue1"
	fmt.Printf("headers= %v \n", headers)
	p.ProduceChannel() <- &kafka.Message{TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny}, Opaque: &headers, Value: []byte(value)}

consumer_channel_example.go:
      case ev := <-c.Events():
			switch e := ev.(type) {
			case kafka.AssignedPartitions:
				fmt.Fprintf(os.Stderr, "%% %v\n", e)
				c.Assign(e.Partitions)
			case kafka.RevokedPartitions:
				fmt.Fprintf(os.Stderr, "%% %v\n", e)
				c.Unassign()
			case *kafka.Message:
				fmt.Printf("%% Message on %s:\n%s\n",
					e.TopicPartition, string(e.Value))
				fmt.Printf("header= %v", e.Opaque)
			case kafka.PartitionEOF:
				fmt.Printf("%% Reached %v\n", e)
			case kafka.Error:
				fmt.Fprintf(os.Stderr, "%% Error: %v\n", e)
				run = false
			}
		}

Can you provide example code on header? can I use Opaque as the header field?
How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
Confluent-GoKafka version: 721151, 0.11.0
 - [ ] Apache Kafka broker version:
Kafka v0.11.0.0
 - [ ] Client configuration: `ConfigMap{...}`
same as your exmaple
 - [ ] Operating system:
MacPro
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Message headers are not yet implemented in the Go client (but we are working on it!).

The per-message opaque is a local value to let you map a Produce request to a Delivery report

**Comment by sheeysong** [comment]
Thank you for the prompt response, truly appreciate it!
Oh- I see. When can I have it? Java client already supports it since Aug release.

**Comment by edenhill** [comment]
We're looking at releasing header support in librdkafka end of Q4 the earliest.
The higher level language bindings (.NET, Python, Go) will follow shortly after.

**Comment by adamkennedy** [comment]
I work with @sheeysong at Apple. We're planning to push a couple of petabytes a month through this once it is available. If there's anything we can do to assist in ensuring a successful release (development, testing, assistance, etc) please let us know.

**Comment by sheeysong** [comment]
Thanks for prompt response!
I am a bit surprise the Header type is not Map<String, byte[]> in Java. 
I am not sure if ordering is matter in Headers, usually it's meta-data of that message, ordering shall between messages event in the Queue. Don't see meta-data need ordering in Header entries.
If it's HashMap type, then no need to support duplicated name neither and don't see there is a need.
In Go client, I  think can be simply define Message struct as:
type Message struct {
	TopicPartition TopicPartition
	Value          []byte
	Key            []byte
	Timestamp      time.Time
	TimestampType  TimestampType
	Opaque         interface{}
        Headers      map[string]interface{}
}

and add Headers bytes[] to end of wire protocol.

**Comment by edenhill** [comment]
There's unfortunately no discussion in KIP-98 on why headers must retain ordering and duplicates keys must be supported, but that is still a requirement.

This means the Headers can't be a map but must be an array type, or provide a specific API to access the headers.

Also, to adhere to `There must be no performance penalty for users that don't need to get or set headers.` I think the headers can't be pre-populated in the Message, but an accessor method should be added to extract them.

**Comment by ctrochalakis** [comment]
Not a Go expert, I am slowly learning the language myself, but how about something like:

```go
type Header struct {
        Key string
        Value []byte
}

type Headers []Header

func (hs *Headers) Add(key string, value []byte) {
        *hs = append(*hs, Header{key, value})
}

func (hs *Headers) Last(key string) ([]byte, bool) {
        for _, h := range *hs {
                if h.key == key {
                        return h.value, true
                }
        }

        return nil, false
}

func (hs *Headers) Del(key string) {
}
```

It mostly hides the `Header` struct and provides methods using native types, so the API feels simpler. But, anyone is free to use the `[]Header` slice for more complicated use-cases. Headers can by exposed via Message.Headers() in a lazy manner.

Something else, record headers remind me of http headers and url parameters[0], they both are multi valued key-pairs. Both types are modeled in go's stdlib as `map[string][]string // headers[key] => [value1, value2]` and probably in other languages as well. But, by treating Kafka's headers in such a way would break the ordering guarantee: we can still have ordering per header key, but not global ordering as KIP-82 suggests.

[0] https://golang.org/src/net/url/url.go#L766

**Comment by edenhill** [comment]
Underlying C API for reference:
https://github.com/edenhill/librdkafka/blob/headers/src/rdkafka.h#L893

**Comment by edenhill** [comment]
Message headers are being worked on in the `headers` branch, which is now ready for review and testing.

We went with an initial simple interface where headers are represented as a slice of Header elements.

https://github.com/confluentinc/confluent-kafka-go/pull/120

**Comment by townsendbt** [comment]
Hi,
Is there any progress  on this feature?
Many thanks,
Brian.

**Comment by edenhill** [comment]
Message headers are available in the latest release and master.
https://github.com/confluentinc/confluent-kafka-go/blob/b2918d4d9d4f29ca4e92431325dcff49c4afe61a/examples/producer_example/producer_example.go#L54
