### ISSUE TITLE
Seeking guidance :: TopicPartitioner does not respect the partition settings; instead using the zero value of kafka.Message.TopicPartition.Partition

### ISSUE THREAD

**Issue by SamsadSajid** [confluentinc/confluent-kafka-go#1051]
Description
===========
Version
---
confluent-kafka-go 2.2.0

Kafka set up
---
1 broker running locally. 1 topic called "mytopic" with 10 partitions. The Kafka broker version is 2.8.0

Base assumption
---
Messages with the same key will go to the same partition. Messages with a null key will be randomly partitioned.

Code
---
producer configuration

```
kafka.ConfigMap{
	"bootstrap.servers": "localhost:9092",
	"client.id":          "myapp",
	"sasl.password":    "password",
	"sasl.username":    "client",
	"security.protocol":  "SASL_PLAINTEXT",
        "linger.ms":          "10",
        "delivery.timeout.ms": "10000",
}
```

Message producing code

Produce five messages with the same key in one iteration. Sleep 10 seconds. Repeat two times.

```
totalMsgCnt := 2

msgcnt := 0

for msgcnt < totalMsgCnt {
  i := 0
  
  for i < 5 {
	  value := fmt.Sprintf("Producer example, message #%d", msgcnt)
	  msg := []byte(value)
  
	  // here we use the message key to ensure that all messages with the same key are sent to the same partition
	  key := strconv.Itoa(msgcnt)

          deliveryChan := make(chan kafka.Event)
  
	  err := producerClient.Produce(&kafka.Message{
		TopicPartition: kafka.TopicPartition{Topic: topic},
		Value:          msg,
		Key:            key,
	  }, deliveryChan)

	  if err != nil {
		  // error handling
	  }

          event := <-deliveryChan
     
          m := event.(*kafka.Message)

          if m.TopicPartition.Error != nil {
		fmt.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
	  } else {
		fmt.Printf("Delivered message to topic %s partition [%d] at offset %v\n",
			*m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
	  }
  
          close(deliveryChan)

	  i++
  }
  
  msgcnt++
  
  time.Sleep(10 * time.Second)
}
```

Output
---
```
key 0
Delivered message to topic mytopic partition [0] at offset 257

key 0
Delivered message to topic mytopic partition [0] at offset 258

key 0
Delivered message to topic mytopic partition [0] at offset 259

key 0
Delivered message to topic mytopic partition [0] at offset 260

key 0
Delivered message to topic mytopic partition [0] at offset 261

key 1
Delivered message to topic mytopic partition [0] at offset 262

key 1
Delivered message to topic mytopic partition [0] at offset 263

key 1
Delivered message to topic mytopic partition [0] at offset 264

key 1
Delivered message to topic mytopic partition [0] at offset 265

key 1
Delivered message to topic mytopic partition [0] at offset 266
```

Investigation
---
As you can see messages with the same key are not going to the same partition. Everything is going into partition 0.

My assumption was as I don't explicitly set the `partition` configuration in the `kafka.ConfigMap`, `confluent-kafka-go` sets the default value `consistent_random` as it is defined in the `librdkafka` config [here](https://github.com/confluentinc/librdkafka/blob/v2.2.0/CONFIGURATION.md#:~:text=used.%0AType%3A%20boolean-,partitioner,-P)

I come from the Java world. The Java Apache kafka producer library sets it by default if I don't set it.

It seems like this is not the same for confluent-kafka-go-lib. So, I explicitly set the partitioner and did the above experiment again.
My new config was 

```
kafka.ConfigMap{
	"bootstrap.servers": "localhost:9092",
	"client.id":          "myapp",
	"sasl.password":    "password",
	"sasl.username":    "client",
	"security.protocol":  "SASL_PLAINTEXT",
        "linger.ms":          "10",
        "delivery.timeout.ms": "10000",
        "partitioner" :      "consistent_random"
}
```

However, it did not fix the issue. I think the root cause is this line 

```TopicPartition: kafka.TopicPartition{Topic: &topicName}```

 As I am not explicitly setting `TopicPartition.Partition`, the zero value of `TopicPartition.Partition` is set. The type of `TopicPartition.Partition` is `int32`. So the zero value is `0`.

Seeking guidance
---
What can I do to mitigate this issue? I would like to publish messages with the same key to go to the same partition and messages with a null key to be randomly partitioned.

How to reproduce
================
If you follow the above approach locally, you can reproducer the same output.

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 2.2.0
 - [X] Apache Kafka broker version: 2.8.0
 - [X] Client configuration: Shared above
 - [X] Operating system: Mac, M1 chip
 - [X] Provide client logs (with `"debug": ".."` as necessary): shared above
 - [] Provide broker log excerpts
 - [] Critical issue

**Comment by milindl** [comment]
it should be something like this: 
```
producerClient.Produce(&kafka.Message{
			TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny},
			Value:          []byte(word),
		}, deliveryChan)
```

you can see it in the [example here](https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/producer_custom_channel_example/producer_custom_channel_example.go#L106).

The partition value needs to be explicitly set to `PartitionAny`.

Hope this helps.

**Comment by SamsadSajid** [comment]
Thanks a lot, @milindl. `PartitionAny` solved the issue—a quick question. 

My assumption was that if I don't explicitly set the `partitioner` configuration in the `kafka.ConfigMap`, confluent-kafka-go sets the default value `consistent_random` as it is defined in the librdkafka config [here](https://github.com/confluentinc/librdkafka/blob/v2.2.0/CONFIGURATION.md#:~:text=used.%0AType%3A%20boolean-,partitioner,-P)

Would this be the correct assumption? Or do I need to set that explicitly? i.e., for any producer configuration, if I don't set them explicitly, does `confluent-kafka-go` set the default value by itself?

**Comment by milindl** [comment]
Yes, this is the correct assumption, you don't need to set it explicitly. The same configs (and defaults) as librdkafka will be used unless changed.

**Comment by SamsadSajid** [comment]
Thanks again @milindl. This has been super useful.
