### ISSUE TITLE
Possible to send heartbeat without calling ReadMessage or Poll

### ISSUE THREAD

**Issue by AdrielVelazquez** [confluentinc/confluent-kafka-go#1057]
Description
===========

General Question. 

Is it possible to send a heartbeat without needing to ReadMessage or Poll?

 - [ ] Apache Kafka broker version: 3.3.2

**Comment by milindl** [comment]
A consumer will keep sending heartbeats on its own without Poll or ReadMessage being called after it joins the consumer group (to join the group, it's needed to call Poll or ReadMessage once after subscribing). 
But remember that calling ReadMessage or Poll less frequently than max.poll.interval.ms will lead to the consumer leaving the consumer group
