### ISSUE TITLE
Cannot install the library using go get 

### ISSUE THREAD

**Issue by sheshankkodam** [confluentinc/confluent-kafka-go#106]
Description
===========
When tried to install this library using command

> go get -u github.com/confluentinc/confluent-kafka-go/kafka 

Following error is received 
# pkg-config --cflags rdkafka
pkg-config: exec: "pkg-config": executable file not found in $PATH

Note: librdkafka 0.11.0 is installed 

How to reproduce
================
- Run go get -u github.com/confluentinc/confluent-kafka-go/kafka

Checklist
=========
Please provide the following information:
 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
         librdkafka 0.11.0 
        confluent-kafka-go - How do I find this version? Its the current code from master . 
 
 - [ ] Apache Kafka broker version: 0.11.0
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: Mac OS Sierra 
        Darwin IN0LE0055544MAC.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the Checklist above, in particular the operating system you are on.

I would also suggest to install pkg-config (using your native package manager, e.g. apt-get) since it is required to build the Go client.

**Comment by sheshankkodam** [comment]
@edenhill Updated the checklist. I have installed

**Comment by seeker44** [comment]
Possibly odd replying to a closed issue, but for anyone else that finds this I had the same problem on Mac and the answer was to install pkg-config from homebrew

`brew install pkg-config`
