### ISSUE TITLE
Confluent Schema Registry Client does not honor HTTPS_PROXY environment variable

### ISSUE THREAD

**Issue by finncolman** [confluentinc/confluent-kafka-go#1064]
Description
===========

The Confluent Schema Registry Client does not honor the HTTPS_PROXY environment variable. This means that if you have a firewall rule only allowing outbound HTTPS traffic via a proxy them the schema registry client will break if you switch to using the confluent schema registry client instead of third party schema registry clients such as https://github.com/riferrei/srclient.

This is happening because the http transport is being set here:

(https://github.com/confluentinc/confluent-kafka-go/blob/master/schemaregistry/rest_service.go#L206)

This overrides the default transport with a custom transport but it does not set the Proxy attribute.

In the DefaultTransport this is set to:

`Proxy: ProxyFromEnvironment`

How to reproduce
================

Set environment variable HTTPS_PROXY. This will not be honored. The request will go direct instead.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v2.2.0 and ibrdkafka-static-bundle-v2.2.0.tgz
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: linux (glibc and musl)
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by fspinolo** [comment]
I am also running into this issue. It looks like there hasn't been any movement on https://github.com/confluentinc/confluent-kafka-go/pull/1065 for a couple of weeks, can we get it merged?

**Comment by milindl** [comment]
Should be closed with #1065 being merged, it'll be available in the next release
