### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference in v2

### ISSUE THREAD

**Issue by yashas-zivame** [confluentinc/confluent-kafka-go#1069]
Description
===========
This issue is arising when trying to produce the message with v2. But works well in v1

How to reproduce
================
upgrade github.com/confluentinc/confluent-kafka-go to github.com/confluentinc/confluent-kafka-go/v2

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
Hi @yashas-zivame , could you share the code which causes the nil ptr deference and the exact version of the library? Along with any more details, like the error printed out.

**Comment by milindl** [comment]
Closing this as there's no other information, please reopen with code/debug logs, exact library version and other details etc. if it occurs again.
