### ISSUE TITLE
Retrieve committed offsets?

### ISSUE THREAD

**Issue by derrickburns** [confluentinc/confluent-kafka-go#107]
Description
===========
Question: Is there a way to retrieve the committed offsets for a given consumer in the latest version of confluent-kafka-go.  It appears that this interface is support in librdkafka:

```
RD_EXPORT rd_kafka_resp_err_t rd_kafka_committed | ( | rd_kafka_t * | rk,
  |   | rd_kafka_topic_partition_list_t * | partitions,
  |   | int | timeout_ms
  | )
```

However, I do not see that it it used.

**Comment by edenhill** [comment]
The Consumer.Committed() API is available on master branch:
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/consumer.go#L481
