### ISSUE TITLE
Build is failing on Mac and Linux

### ISSUE THREAD

**Issue by KGKallasmaa** [confluentinc/confluent-kafka-go#1070]
Description
===========

This docker file has worked for many months. 
Last week when I wanted to start working on it, the docker compose failed.

I got this error

<img width="990" alt="Screenshot 2023-10-03 at 21 12 47" src="https://github.com/confluentinc/confluent-kafka-go/assets/29797627/a5ec825d-25a1-40be-8609-d2d819ba0a62">

How to reproduce
================
**Step1. Create a docker file**

FROM golang:1.21.1-alpine3.18 AS builder
WORKDIR /app
COPY ./src/go.mod /app
COPY ./src/go.sum /app
RUN go mod download
RUN apk update && apk upgrade && \
    apk add --no-cache pkgconf git bash build-base sudo clang openssl openssl-dev cyrus-sasl-dev
RUN git clone https://github.com/confluentinc/librdkafka.git && cd librdkafka && ./configure --prefix /usr --enable-sasl && make && make install
RUN echo "openssl_conf = openssl_init" > /etc/ssl/openssl.cnf \
    && echo "[openssl_init]" >> /etc/ssl/openssl.cnf \
    && echo "cipher_suites = ECDHE-ECDSA-AES128-GCM-SHA256" >> /etc/ssl/openssl.cnf \
    && echo "ssl_conf = ssl_init" >> /etc/ssl/openssl.cnf \
    && echo "[ssl_init]" >> /etc/ssl/openssl.cnf \
    && echo "security.protocol = SASL_SSL" >> /etc/ssl/openssl.cnf
COPY ./src /app
RUN go build -tags dynamic -o /docker-gs-ping .
FROM alpine:3.18 AS runner
WORKDIR /
COPY --from=builder /usr/lib /usr/lib
COPY --from=builder /usr/lib/sasl2 /usr/lib/sasl2
COPY --from=builder /docker-gs-ping /docker-gs-ping
ENTRYPOINT ["/docker-gs-ping"]

Step2: Run docker-compose up --build

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v2.2.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}` return kafka.ConfigMap{
		"bootstrap.servers":     clusterUrl,
		"sasl.mechanisms":       "PLAIN",
		"security.protocol":     "SASL_SSL",
		"sasl.username":         clusterApiKey,
		"sasl.password":         clusterApiSecret,
		"session.timeout.ms":    90_000,
		"group.id":              "example",
		"auto.offset.reset":     "smallest",
		"heartbeat.interval.ms": 20_000,
	}
 - [ ] Operating system: Mac M1
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
Thanks for pointing this out. It seems like rd_ts_t isn't a part of the publicly exposed types here, let me check this.

**Comment by milindl** [comment]
I would guess this is due to the merge of https://github.com/confluentinc/librdkafka/pull/4422 .

**Comment by milindl** [comment]
Fixed by https://github.com/confluentinc/librdkafka/pull/4458, please reopen if this continues to happen. 
Thanks for the report!
