### ISSUE TITLE
Update Deps with High Security Alerts

### ISSUE THREAD

**Issue by frankgreco** [confluentinc/confluent-kafka-go#1079]
Description
===========
There are some high security alerts that originate from deps in this package.

How to reproduce
================
You can generate this report with Snyk

<img width="2025" alt="Screenshot 2023-10-16 at 5 20 03 PM" src="https://github.com/confluentinc/confluent-kafka-go/assets/22604233/7d0cf1d9-f73e-4509-ae78-a3279081a635">

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion(v2.2.0)`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by frankgreco** [comment]
@emasab (finding a random contributor to ping) since this is security related, could we prioritize this?

**Comment by frankgreco** [comment]
Friendly bump on this.

**Comment by frankgreco** [comment]
Bump

**Comment by milindl** [comment]
Going to update a bunch of dependencies in the next release, will look into updating these with them.

**Comment by frankgreco** [comment]
@milindl any idea on when this next release is going to be?

**Comment by milindl** [comment]
It should be there this week, we've tested the RC out.

**Comment by janjwerner-confluent** [comment]
@milindl 
Can you please close this out.

**Comment by milindl** [comment]
Yep
This is done as the release is out.
