### ISSUE TITLE
Schema registry support with libserdes

### ISSUE THREAD

**Issue by MrDHat** [confluentinc/confluent-kafka-go#108]
Description
===========
It seems like this package does not support using a schema registry directly.
I recently came across `libserdes` which is a way described by confluent to support schema registry for `librdkafka` clients. I am not sure how to make it work with `kafka-go` client. Any pointers?

**Comment by edenhill** [comment]
I think it probably makes more sense to implement a pure Go schema-registry client.

There are a couple of existing implementations that you might want to look at:
https://github.com/datamountaineer/schema-registry
https://github.com/elodina/go-kafka-avro

Disclaimer: we're not involved, nor endorse, any of those projects.
