### ISSUE TITLE
"Local: Queue full", and Producer.Poll() missing from librdkafka Go bindings

### ISSUE THREAD

**Issue by jeremydonahue** [confluentinc/confluent-kafka-go#109]
Description
===========

Hi there,

I'm wondering why _confluent-kafka-go_ doesn't expose the Producer `poll()` method like the [_confluent-kafka-python_](https://docs.confluent.io/current/clients/confluent-kafka-python/index.html#confluent_kafka.Producer.poll) bindings? 

I'm seeing the error `Local: Queue full`, and [some googling](https://github.com/edenhill/librdkafka/issues/998) says to use the `poll()` method of the Producer instance, which seems to be missing from the Go bindings. I can prevent this error from occurring with Go if I use `Producer.Flush(100)` in a goroutine loop with `queue.buffering.max.messages: 1000000`, however I'm wondering if that's the best way to implement this given the blocking nature of `Flush()` (as mentioned in the docs). Maybe that's not an issue because of the goroutine?

_Note_: I'm using the Function Based Producer. Is the Channel Based Producer doing something special to avoid the requirement of calling the Producer `poll()` method periodically?

Thanks!
Jeremy

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): HEAD
 - [x] Apache Kafka broker version: 0.11.0
 - [x] Client configuration: 
```
"compression.codec":            "snappy",
"group.id":                     group,
"message.send.max.retries":     10000000, // max
"linger.ms":                    100,
"queue.buffering.max.kbytes":   2097151,
"queue.buffering.max.messages": 1000000,
```
 - [x] Operating system: Ubuntu Trusty (kernel version: 4.4.0-62-generic)
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
`queue.buffering.max.messages` accounts for:
 * messages in queue to be sent to broker
 * messages in-flight to the broker
 * acked messages enqueued for application DeliveryReport

Regardless of which producer API strand you use you will need to read from the `producer.Events()` channel to serve delivery reports (and other events) - which effectively calls poll() underneath.

If you are not interested in delivery reports (which you should be!), you can disable them by setting `go.delivery.reports` to `false`, and then you will not need to read from the Events() channel. But you will have no idea if your messages were successfully produced or not.
