### ISSUE TITLE
Consumer group offsets lost after hard kill between SendOffsetsToTransaction & CommitTransaction

### ISSUE THREAD

**Issue by pmagix** [confluentinc/confluent-kafka-go#1093]
Using EOS, if a hard kill happens between the calls to SendOffsetsToTransaction & CommitTransaction, it appears that the consumer group committed offsets on the kafka cluster for the partitions passed to SendOffsetsToTransaction are lost, meaning when the application starts up again the consumer starts consuming from the beginning of the partitions.

Specifically, we have noticed several times, for a (long) running application which is consuming from one topic with 8 partitions and producing to one topic (one consumer(group) & one producer), and has already committed countless transactions (each with a prior SendOffsetsToTransaction call), that if a hard kill then occurs between a given pair of SendOffsetsToTransaction & CommitTransaction calls, that the committed offset for each of the partitions passed to SendOffsetsToTransaction are entirely lost - with the non-involved partitions not being affected

Could someone indicate based on how librdkafka behaves if this is indeed a possible explanation.

confluent-kafka-go v1.8.2

**Comment by milindl** [comment]
If the transaction is not committed, it's expected that the offsets sent as a part of the transaction will not be committed either. This comes from the [KIP-98](https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging#KIP98ExactlyOnceDeliveryandTransactionalMessaging-4.Theconsume-transform-produceloop), which defines these method semantics.

In particular, from SendOffsetsToTransaction
```
   * Sends a list of consumed offsets to the consumer group coordinator, and also marks
   * those offsets as part of the current transaction. These offsets will be considered
   * consumed only if the transaction is committed successfully.
```

**Comment by milindl** [comment]
Closing, please reopen if any further questions.
