### ISSUE TITLE
support kafka 0.11.x?

### ISSUE THREAD

**Issue by jinleileiking** [confluentinc/confluent-kafka-go#111]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yes, confluent-kafka-go (and any librdkafka-based client) supports all broker versions >= 0.8.
Some newer features may be missing though, such as EOS.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility
