### ISSUE TITLE
Issue with missing leader epoch when storing offsets

### ISSUE THREAD

**Issue by nkostoulas** [confluentinc/confluent-kafka-go#1113]
Since v2.1.0, if the leader epoch is not explicitly set in the TopicPartition field when storing offsets and there has been a leader epoch change then consumers fail to store offsets. It should be clear in the documentation that in order for the above to work we either need to use the TopicPartition field from the message or populate all required fields if constructing this field manually. This has since been fixed upstream in librdkafka v2.3.0 (https://github.com/confluentinc/librdkafka/pull/4442). It would be nice to include information both on the issue and the fix in the corresponding confluent-kafka-go releases.

**Comment by milindl** [comment]
Hi @nkostoulas, we provide a link to the corresponding version of the librdkafka release notes with each of our release notes, since those contain many such bug fixes, and enhancements which are often made without any changes to the Go client code itself.

**Comment by milindl** [comment]
Closing this with the above comment, let me know if there are any more issues with this.
