### ISSUE TITLE
query/change topic configs

### ISSUE THREAD

**Issue by llamahunter** [confluentinc/confluent-kafka-go#113]
Description
===========

Need a way to query and change topic configs

How to reproduce
================

No api exists (AFAICT) to do so.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
latest
 - [ ] Apache Kafka broker version:
0.11.0.2
 - [ ] Client configuration: `ConfigMap{...}`
n/a
 - [ ] Operating system:
n/a
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
n/a
 - [ ] Provide broker log excerpts
n/a
 - [ ] Critical issue
major missing functionality

**Comment by edenhill** [comment]
The configuration is immutable after the construction of the client and there is no API to retrieve config values post construction either.

What is it that you are trying to do?

**Comment by llamahunter** [comment]
Use the go library to inspect/modify kafka topic configs.  They are not immutable on the broker.  Basically, use https://kafka.apache.org/protocol
- DescribeConfigs API (Key: 32):
- AlterConfigs API (Key: 33):

**Comment by edenhill** [comment]
Oh sorry, I thought you mean the client's topic configuration.

Support for broker topic configuration, aka the Topic Admin API, is not yet implemented but on the roadmap and tracked in issue #76
