### ISSUE TITLE
[schema registry] - unsupported protocol scheme

### ISSUE THREAD

**Issue by bruno-holanda15** [confluentinc/confluent-kafka-go#1137]
Description
===========
I am trying to use schema registry with my producer.go, which I followed up the instructions with [Kafka and Go](https://developer.confluent.io/get-started/go/#build-producer), but every time I run my producer I got an error with like this:

`Failed to serialize payload: Post "my.bootstrap.server.config:///subjects/orders-value/versions?normalize=false": unsupported protocol scheme "my.bootstrap.server.config"`

Some part of the code bellow, It is falling in the error of `ser.Serialize`
![image](https://github.com/confluentinc/confluent-kafka-go/assets/54423596/e8d13297-2589-423d-9690-c9f15b8b3d03)

How to reproduce
================
- First you need to setup a cluster in Confluent Platform
- Enable Schema Registry for this Cluster
- Get the API keys to add in your getting-started.properties like the example - https://developer.confluent.io/get-started/go/#configuration
- You can clone the repo https://github.com/bruno-holanda15/confluent_schema_registry_tutorial/tree/feat/test_schema_registry

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`1.9.2`):
 - [x] Apache Kafka broker version: Used Confluent Topic and Client Producer as the repository bellow
 - [x] Client configuration: `Should setup personally in your account like https://developer.confluent.io/get-started/go/#configuration`
 - [x] Operating system - Ubuntu 22:
 - [x] Provide client logs (`Failed to serialize payload: Post "my.bootstrap.server.config:///subjects/orders-value/versions?normalize=false": unsupported protocol scheme "my.bootstrap.server.config"`)
 - [x] Provide broker log excerpts - not used
 - [ ] Critical issue

**Comment by fzmoment** [comment]
Based on the error message it looks like you're passing an incorrect value for your `URL_SCHEMA_REGISTRY` parameter. What are you using for that?
