### ISSUE TITLE
Offset management for consumer without a group

### ISSUE THREAD

**Issue by sapei** [confluentinc/confluent-kafka-go#114]
Description
===========

I would like to have a standalone kafka consumer (without a group), which reads from a specific partition only. Therefore I assign specific topic and partition to the consumer, consume messages, and commit offsets manually. However when I restart the consumer and call the Committed() API, I get no committed offset at all.

 
How to reproduce
================

Start the client and consume few messages. Afterwards restart the client and check out the committedOffsets returned from Kafka.
`
kafkaConsumer, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers":        broker,
		"group.id":                 group,
		"session.timeout.ms":       6000,
		"go.events.channel.enable": true,
		"enable.auto.commit":       false,
		"default.topic.config": kafka.ConfigMap{"auto.offset.reset": "earliest"}})

	committedOffsets, _ := kafkaConsumer.Committed([]kafka.TopicPartition{{Topic: &consumerTopic, Partition: partition}}, 10)
	fmt.Printf("Read committed offsets from kafka: %v\n\n", committedOffsets)

	err = kafkaConsumer.Assign([]kafka.TopicPartition{{Topic: &consumerTopic, Partition: partition}})

		select {
		case ev := <-kafkaConsumer.Events():
			switch e := ev.(type) {
			case *kafka.Message:
				committedPartitions, _ := kafkaConsumer.CommitMessage(e)
				fmt.Printf("Committed partitions: %v\n", committedPartitions)
			}
		}
`
Log:
First run:
Committed partitions: [WSDeClickstreamTopic[0]@664640081]
Committed partitions: [WSDeClickstreamTopic[0]@664640082]
Committed partitions: [WSDeClickstreamTopic[0]@664640083]

After restart:
Read committed offsets from kafka: []

Committed partitions: [WSDeClickstreamTopic[0]@664640081]
Committed partitions: [WSDeClickstreamTopic[0]@664640082]
Committed partitions: [WSDeClickstreamTopic[0]@664640083]

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you using the same group.id for both invocations? (you will need to do this)

You can enable debugging to see why it is not being able to use the committed offsets by setting the `debug` config property to `cgrp,topic`.

**Comment by sapei** [comment]
I always use the same group.id for both invocations.

I ask Kafka for the latest committed offsets after creating the consumer. If I put a delay before asking the latest committed offsets, I get a response from Kafka (either unset or the latest committed offsets). However putting a delay before asking the latest committed is erroneous. Therefore I ask kafka for the latest committed offsets repeatedly until I get a response as follows:

`
	kafkaConsumer, err := kafka.NewConsumer()

	var lastOffsets []kafka.TopicPartition
	for len(lastOffsets) == 0 {
		lastOffsets, _ = kafkaConsumer.Committed([]kafka.TopicPartition{{Topic: &conf.Consumer.Topic, Partition: conf.Consumer.Partition}}, 10)
	}
`

It seems that the consumer needs time to establish connection to kafka. As long as the connection has not been successfuly established, the consumer gets an empty slice from the Committed() API. Would you please confirm if this is the case?

**Comment by edenhill** [comment]
Which version of librdkafka are you running? (LibraryVersion())

**Comment by sapei** [comment]
I am currently using librdkafka v0.11.1.

`librdkafka++1/now 0.11.1~1confluent4.0.0-1 amd64 [installed,local]
  library implementing the Apache Kafka protocol (C++ bindings)

librdkafka-dev/now 0.11.1~1confluent4.0.0-1 amd64 [installed,local]
  library implementing the Apache Kafka protocol (development headers)

librdkafka1/now 0.11.1~1confluent4.0.0-1 amd64 [installed,local]
  library implementing the Apache Kafka protocol`

**Comment by edenhill** [comment]
I believe this issue has been fixed on librdkafka master and will be available in the next release (mid february)
