### ISSUE TITLE
Extremely slow protobuf deserialization and serialization for schema registry

### ISSUE THREAD

**Issue by fzmoment** [confluentinc/confluent-kafka-go#1146]
Description
===========
When using protobuf schemas we've noticed that the drop in performance is much worse than expected. For example, compared to the baseline of just a regular protobuf Unmarshal call, which takes on the order of <10 us:

![Screenshot 2024-03-01 at 11 16 20 AM](https://github.com/confluentinc/confluent-kafka-go/assets/146033899/72ceda7d-b5b7-4962-963f-7a88e9f3022b)

Using the confluent kafka go library, we see a over 2500x increase in processing time:

![Screenshot 2024-03-01 at 12 41 35 PM](https://github.com/confluentinc/confluent-kafka-go/assets/146033899/f421ba9d-92a1-43f1-bac2-dbf35f13716d)

Furthermore, we know that this decrease is specifically **not** due to communication with the schema registry. In this example, we are deserializing the same schema over and over again and thus only make a request to the registry once before the result is cached - in general, the schema ID lookup takes ~2us:

![Screenshot 2024-03-01 at 12 47 11 PM](https://github.com/confluentinc/confluent-kafka-go/assets/146033899/e18d1a5b-40b3-464e-8e98-9f821ea82c46)

The bottleneck is the [`ToFileDesc`](https://github.com/confluentinc/confluent-kafka-go/blob/d8d41367d60ed909847c82112755d412725ec7c8/schemaregistry/serde/protobuf/protobuf.go#L417) function which is parsing the schema string back to a file descriptor.

![Screenshot 2024-03-01 at 12 44 45 PM](https://github.com/confluentinc/confluent-kafka-go/assets/146033899/1a155f88-a999-4c9b-8a3e-b300b1dd5579)

this can take up on the order of seconds:

![Screenshot 2024-03-01 at 12 49 58 PM](https://github.com/confluentinc/confluent-kafka-go/assets/146033899/d481f9f1-f526-4aba-91d2-f29b0054365a)

Is this a known issue/are there any workarounds? We see similar behavior on the write side (where the bottleneck is the conversion from the file descriptor to a string, **not** looking up the schema ID for a schema given the caching), though not quite as drastic as the above examples. Any pointers would be appreciated.

How to reproduce
================

Run a consumer that uses the confluent kafka go library to deserialize all the messages on a given topic. In our setup, the topic schema only contains one message. Can provide a minimal repro example if this gains some traction.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rayokota** [comment]
Did you try this fix? https://github.com/confluentinc/confluent-kafka-go/pull/1128

**Comment by rayokota** [comment]
Closing this for now as the main bottleneck has been addressed

**Comment by fzmoment** [comment]
Thanks Robert! That fix definitely seems to get rid of the bottleneck that we identified in our trace (`ToFileDesc`) - performance now seems to be pretty close to the raw unmarshal.

I was wondering if we could apply a similar approach on the serialization side as well, where things seem to be slow also because of file descriptor <=> string conversions:

<img width="986" alt="Screenshot 2024-03-07 at 11 38 02 AM" src="https://github.com/confluentinc/confluent-kafka-go/assets/146033899/a6daff40-b85c-4a83-b7e7-b8aefa0bd7f2">

What do you think about adding a similar cache on the serialization side, mapping from `desc.FileDescriptor` to `SchemaInfo` (or better yet, to schema ID)? Happy to create a PR for this for you to review if the general approach seems reasonable to you. I think once we resolve things on the serialization side that should address this ticket.
