### ISSUE TITLE
Producer working, but consumer isn't

### ISSUE THREAD

**Issue by qrpike** [confluentinc/confluent-kafka-go#115]
Description
===========
Admittedly I am new to Kafka, but I have a 6 broker cluster up and working. I have mutliple topics and have written a channel based producer which is working great. The yahoo kafka manager is showing the partitions being filled etc. 

However, anytime I try to consume these topics nothing I do seems to work. I have even used both the example code untouched, and the producer says it delivered to topix X with offset Y. However having the consumer example running on the same topic, nothing shows up.

How to reproduce
================
Run both producer channel and consumer channel example code, untouched.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - librdkafka: 0.11.3
 - kafka-go: 721919 0.11.3
 - [ ] Apache Kafka broker version:
 - 0.9.0.1
 - [ ] Client configuration: `ConfigMap{...}`
 - untouched example file
 - [ ] Operating system:
 - macOS High Sierra. Kafka cluster is on CoreOS linux. 
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - `Failed to create consumer: Invalid value for configuration property "debug"`
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by qrpike** [comment]
Turns out my `__consumer_offsets` replication was set to 1, and my min.insync.replicas was set to 2. Which means it would never start the group. Fixing that fixed the issue.

**Comment by qrpike** [comment]
```[2017-12-23 00:30:22,789] ERROR [ReplicaManager broker=0] Error processing append operation on partition __consumer_offsets-49 (kafka.server.ReplicaManager)
org.apache.kafka.common.errors.NotEnoughReplicasException: Number of insync replicas for partition __consumer_offsets-49 is [1], below required minimum [2]
``` 

This is the message incase someone ends up searching google for this error.

**Comment by greysond** [comment]
@qrpike I in fact googled this error and your solution fixed my problem, so thank you!
