### ISSUE TITLE
What's the difference between `producer.Events()` chan and `deliverChan`

### ISSUE THREAD

**Issue by yanmxa** [confluentinc/confluent-kafka-go#1163]
Description
===========

Since the `producer.Produce` has provided a `deliverychan` to check the sending result, why use another chan `producer.Events()` in the [sample](https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/producer_custom_channel_example/producer_custom_channel_example.go#L51-L67)? 

How to reproduce
================

Sample: https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/producer_custom_channel_example/producer_custom_channel_example.go#L51-L67

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
There are specific control and error events which are not associated to any particular message. For example - authentication issues or connection issues.

**Comment by yanmxa** [comment]
Thanks @milindl!
