### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by eliaslevy** [confluentinc/confluent-kafka-go#117]
It has been almost six months since the `Pause()`, `Resume()`, `Committed()` and `OffsetForTimes(), and StoreOffsets()` APIs were added.  Would it be possible to tag a new release?

**Comment by eliaslevy** [comment]
@edenhill how is it coming along?

**Comment by vinceprignano** [comment]
Any updates?

**Comment by edenhill** [comment]
Max 2 more weeks

**Comment by eliaslevy** [comment]
Ping

**Comment by jeffwidman** [comment]
Based on what I see in https://github.com/confluentinc/confluent-kafka-go/releases, it looks like this issue can be closed.
