### ISSUE TITLE
 Topic-Level Configs

### ISSUE THREAD

**Issue by Ianwww** [confluentinc/confluent-kafka-go#122]
Description
===========
Can I set these topic level configuration properties, and if so how?  https://kafka.apache.org/documentation/#topicconfigs
Or only the items listed here: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#topic-configuration-properties

**Comment by edenhill** [comment]
You may only set the librdkafka configuration properties.

We will add support for the topic admin API during Q2.

**Comment by edenhill** [comment]
dup of #76
