### ISSUE TITLE
EventTime and ProcessingTime from kafka message

### ISSUE THREAD

**Issue by MrDHat** [confluentinc/confluent-kafka-go#124]
Description
===========
There doesn't seem to be a way to get EventTime & ProcesingTime for an event from the message object.

The time property in the object shows just the CreateTime.

How to reproduce
================
Start a consumer & send a message with any schema. Here is the code:

```golang
...

for run == true {
		select {
		case sig := <-sigchan:
			log.Println(sig)
			run = false
		case ev := <-kops.Consumer.Events():
			log.Println("ev", ev)
			switch e := ev.(type) {
			case kafka.AssignedPartitions:
				log.Println("kafka.AssignedPartitions", e)
				kops.Consumer.Assign(e.Partitions)
			case kafka.RevokedPartitions:
				log.Println("kafka.RevokedPartitions", e)
				kops.Consumer.Unassign()
			case *kafka.Message:
				log.Println(e.TopicPartition, e.Value, e.Key, e.Timestamp, e.TimestampType)
			case kafka.PartitionEOF:
				log.Println(e)
			case kafka.Error:
				log.Println(e)
				run = false
			}

		}
	}
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): master branch for both
 - [x] Apache Kafka broker version: `0.11.0`
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Docker
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Kafka only supports one timestamp per message, which is either CreateTime (e.g., event time, source time, producer time), or LogAppendtime (broker receive time). The default is CreateTime.

**Comment by MrDHat** [comment]
So what is the best practice for getting the current processing time for a received message? I do not want to depend on the consumer. I want a single source of truth of time (without the use of an NTP server if possible). Maybe some setting in kafka could add this?

To explain a bit more, I'll be using LogAppendtime (or CreateTime) as the time when an event was added and perform an action say, 30 mins after that. I want to be able to calculate if 30 mins have elapsed using some metadata inside the message without depending on the consumer clock.

**Comment by edenhill** [comment]
You could use [OffsetsForTimes](https://github.com/confluentinc/confluent-kafka-go/blob/9f5af4225f71044489783d9726429e8d911304f0/kafka/offset.go#L121) to query the broker for the earliest message given a message timestamp.

**Comment by MrDHat** [comment]
Makes sense. Thanks for the help!
