### ISSUE TITLE
Receive ProduceResponse only after timed out 

### ISSUE THREAD

**Issue by sapei** [confluentinc/confluent-kafka-go#126]
Description
===========

Right after starting the application, messages were written continuously to the producer's channel. However after five minutes (default value for message.timeout.ms), we got a lot of delivery reports with error messages "Local: Message timed out". The timed out messages are currently ignored (not re-published). After the timeout, the producer tried to reconnect to the broker and it received connection suddenly. Afterwards the producer could send messages and also receive responses from the broker without any problem. 

I've tried to set the message.timeout.ms to the maximum value, i.e.: 900000. However it does not help at all.

As far as I understood, the librdkafka tries to reconnect to the broker only after the timeout and socket.max.fails (default value 1 was used in this case) have been achieved. During the retry (defined by message.send.max.retries) within five minutes, the producer does not try to reconnect to the broker. Would it be possible to force the producer to reconnect to the broker during retry? What is the role of socket.timeout.ms for producer in publishing messages to kafka?

Is there a way to republish the the timed out messages automatically and preserve the order of messages?

How to reproduce
================

It seems that this case can be reproduced randomly depending on the network traffic. 

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion(v0.11.3)`):
 - [x] Apache Kafka broker version: 0.11.0.1
 - [x] Producer configuration: `ConfigMap{"debug": "all", "bootstrap.servers": "brhstprd01:9092,brhstprd02:9092,brhstprd03:9092,brhstprd04:9092,brhstprd05:9092","go.batch.producer": false, "go.delivery.reports": true, "queue.buffering.max.ms": 1000, "max.in.flight.requests.per.connection": 2, "acks": "all"}`
 - [x] Operating system: Ubuntu 16.04
 - [x] Provide logs (with `"debug": "all"` as necessary)
`{"_t":"2018-02-08T13:13:56+0100", "_p":"1", "_l":"ERR", "_n":"~", "_m":"Failed delivering kafka messages", "err":"Local: Message timed out"}
%7|1518092039.267|CONNECT|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: broker in state DOWN connecting
%7|1518092039.271|CONNECT|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Connecting to ipv4#10.29.6.112:9092 (plaintext) with socket 38
%7|1518092039.271|STATE|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Broker changed state DOWN -> CONNECT
%7|1518092039.271|BROADCAST|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: Broadcasting state change
%7|1518092039.272|CONNECT|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Connected to ipv4#10.29.6.112:9092
%7|1518092039.272|CONNECTED|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Connected (#14)
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Using (configuration fallback) 0.9.0 protocol features
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature MsgVer1: Produce (2..2) NOT supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature MsgVer1: Fetch (2..2) NOT supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Disabling feature MsgVer1
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature MsgVer2: Produce (3..3) NOT supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature MsgVer2: Fetch (4..4) NOT supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Disabling feature MsgVer2
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature ApiVersion: ApiVersion (0..0) NOT supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Disabling feature ApiVersion
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature BrokerGroupCoordinator: GroupCoordinator (0..0) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Enabling feature BrokerGroupCoordinator
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature BrokerBalancedConsumer: GroupCoordinator (0..0) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature BrokerBalancedConsumer: OffsetCommit (1..2) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature BrokerBalancedConsumer: OffsetFetch (1..1) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature BrokerBalancedConsumer: JoinGroup (0..0) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature BrokerBalancedConsumer: SyncGroup (0..0) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature BrokerBalancedConsumer: Heartbeat (0..0) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature BrokerBalancedConsumer: LeaveGroup (0..0) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Enabling feature BrokerBalancedConsumer
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature ThrottleTime: Produce (1..2) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature ThrottleTime: Fetch (1..2) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Enabling feature ThrottleTime
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature Sasl: JoinGroup (0..0) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Enabling feature Sasl
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature SaslHandshake: SaslHandshake (0..0) NOT supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Disabling feature SaslHandshake
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature LZ4: GroupCoordinator (0..0) supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Enabling feature LZ4
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5:  Feature OffsetTime: Offset (1..1) NOT supported by broker
%7|1518092039.272|APIVERSION|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Disabling feature OffsetTime
%7|1518092039.272|STATE|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Broker changed state CONNECT -> UP
%7|1518092039.272|BROADCAST|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: Broadcasting state change
%7|1518092039.272|METADATA|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: Skipping metadata refresh of 1 topic(s): connected: already being requested
%7|1518092039.272|SEND|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Sent partial ProduceRequest (v1, 0+83880/373026 bytes, CorrId 51)
%7|1518092039.272|SEND|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Sent partial ProduceRequest (v1, 83880+97860/373026 bytes, CorrId 51)
%7|1518092039.273|SEND|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Sent partial ProduceRequest (v1, 181740+87527/373026 bytes, CorrId 51)
%7|1518092039.273|SEND|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Sent ProduceRequest (v1, 373026 bytes @ 269267, CorrId 51)
%7|1518092039.273|SEND|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Sent partial ProduceRequest (v1, 0+93906/999747 bytes, CorrId 52)
%7|1518092039.278|SEND|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Sent partial ProduceRequest (v1, 93906+162168/999747 bytes, CorrId 52)
%7|1518092039.286|SEND|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Sent partial ProduceRequest (v1, 256074+87959/999747 bytes, CorrId 52)
%7|1518092039.306|RECV|rdkafka#producer-2| [thrd:brhstprd05:9092/bootstrap]: brhstprd05:9092/5: Received ProduceResponse (v1, 67 bytes, CorrId 51, rtt 33.59ms)`
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There's been a number of fixes on master branch for the producer retry logic, previous to these fixes the retries would be fired off immediately (not after the backoff), if the connection was down it would mean the message timed out prematurely because the retry count was quickly exhausted. I think this is what you are seeing.

We're aiming to release a new version (with these fixes) end of february. If you would like to try it out before that we would be very interested to know  the results.

Thanks
