### ISSUE TITLE
Can't provide my own http.Client to schemaregistroy.Client via schemaregistry.Config

### ISSUE THREAD

**Issue by stewartboyd119** [confluentinc/confluent-kafka-go#1261]
Description
===========

With the recent update to 2.5, the type `schemaregistry.Config` had its fields provided via an embedded struct defined in the internal package.

I had written service code that provided an instrumented http client (telemtry) and default retry policy. I don't see a way of specifying that any longer. Any suggestions? 

How to reproduce
================

Try and compile the following in a package external to confluent-kafka-go
```go
	cliCfg := schemaregistry.Config{
		SchemaRegistryURL:   regConfig.SchemaRegistryUrl,
                 // imagine this was a juiced up http client, not the default
		HTTPClient:                 &http.Client{},
	}
	 cli, _ := schemaregistry.NewClient(&cliCfg)

```

Checklist
=========
Please provide the following information:

 - [ X ] confluent-kafka-go=2.5 and librdkafka version (`LibraryVersion()`):
 - [ X ] Apache Kafka broker version: n/a
 - [ X ] Client configuration: `ConfigMap{...}` n/a
 - [ X ] Operating system: n/a
 - [ X ] Provide client logs (with `"debug": ".."` as necessary): n/a
 - [ X] Provide broker log excerpts: n/
 - [ X ] Critical issue - No

**Comment by rayokota** [comment]
@stewartboyd119 , try

```
	c := schemaregistry.NewConfig(url)
	c.HTTPClient = &http.Client{}
```

**Comment by stewartboyd119** [comment]
embarassed. That worked like a charm, ty
