### ISSUE TITLE
go get couldn't download kafka

### ISSUE THREAD

**Issue by jungladicitta** [confluentinc/confluent-kafka-go#1263]
Description
===========
I just simply run go get for kafka:
`go get -u github.com/confluentinc/confluent-kafka-go/v2/kafka`
and I've got this error:
`go: downloading github.com/confluentinc/confluent-kafka-go v1.9.2
go: downloading github.com/confluentinc/confluent-kafka-go/v2 v2.5.0
go: github.com/confluentinc/confluent-kafka-go/v2/kafka: github.com/confluentinc/confluent-kafka-go/v2@v2.5.0: Get "https://storage.googleapis.com/proxy-golang-org-prod/6f966bda3d325046-github.com:confluentinc:confluent-kafka-go:v2-v2.5.0.zip?Expires=1722335612&GoogleAccessId=gcs-urlsigner-prod%40golang-modproxy.iam.gserviceaccount.com&Signature=h8cuM1OCMM8qhj%2Bp1%2B5VaYZxskWoZgtj2C%2FNij%2BVFlDDCND1Gnz2DyDBb7ROQUhE8dlvAyLwdyrkgGLV2xQ7X3Kh%2FgXIeTA45rWQ8KU4uM9UHuUgSna2hrkKlD37oqYtTsosJmm0nTWt4F9OCuDTL9m%2FedJu2VHUfxZWXB9nKydAF6Z0qF3OEggXJua8uLhk%2B%2FjoHKUt3TNLmppK1O8DddXhiEh9bgU0QZ5INB6pNee4QUwPq3k8kjxgqWt3rlXAPJkH9dd4JCsm%2BGyeU1s%2Fjh7jJE88NyGkGd5yxj7%2FLa1PhWaAa61hMF%2BmXYlrAjYNHmxnvxFdnodWXNTnUPwefA%3D%3D": read tcp [2a03:d000:7102:f8b7:6c69:9c93:225d:a45d]:52620->[2a00:1450:400f:80a::201b]:443: read: connection reset by peer`

Before, all my `go get` commands were finished successfully.
Is this just common github problem or it's somehow related to this repo?

How to reproduce
================
Just try to run
`go get -u github.com/confluentinc/confluent-kafka-go/v2/kafka`

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Ubuntu 22.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jungladicitta** [comment]
tried on the next day, download finished successfully, no errors.

**Comment by guotie** [comment]
I use docker, golang:1.23-alpine, same problem occers

**Comment by guotie** [comment]
> [builder 8/8] RUN make:                                                                                                                                                                                         
0.098 go get -tags musl -v github.com/confluentinc/confluent-kafka-go/v2/kafka                                                                                                                                     
1.784 go: downloading github.com/confluentinc/confluent-kafka-go v1.9.2
