### ISSUE TITLE
[Question] How to link on travis-ci

### ISSUE THREAD

**Issue by urban-1** [confluentinc/confluent-kafka-go#127]
Description
===========
We have a Go project that depends on this kafka implementation but we fail to link properly against `librdkafka.so` on travis. We now use a Makefile which is building `librdkafka` from source and exports the correct `LD_LIBRARY_PATH`. This works as expected when building locally on a Linux box but refuses to link on travis:

```
# github.com/confluentinc/confluent-kafka-go/kafka
../../confluentinc/confluent-kafka-go/kafka/generated_errors.go:106:36: could not determine kind of name for C.RD_KAFKA_RESP_ERR__NOENT
../../confluentinc/confluent-kafka-go/kafka/generated_errors.go:104:39: could not determine kind of name for C.RD_KAFKA_RESP_ERR__READ_ONLY
../../confluentinc/confluent-kafka-go/kafka/generated_errors.go:108:40: could not determine kind of name for C.RD_KAFKA_RESP_ERR__UNDERFLOW
FAIL	github.com/urban-1/gopipe/input [build failed]
make: *** [tests] Error 1
```

I believe we are missing something simple - any help would be appreciated

Cheers,
Andreas

PS: Sorry for the early submit (Ctrl+Enter by habit... updated this issue)

How to reproduce
================
Please check out our logs and Makefile:

- Logs can be found at: https://travis-ci.org/urban-1/gopipe
- Our Makefile: https://github.com/urban-1/gopipe/blob/tests_draft/Makefile#L46

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):

    - We are linking against librdkafka v0.11.3
    - confluent-kafka-go : we are using the version that `go get` fetches (I assume is the latest)

 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Ubuntu 14.04.5 LTS (locally) / Various flavors tested on travis
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by urban-1** [comment]
Update: It seems that the problem is the latest commit:

```
~/go/src/github.com/confluentinc/confluent-kafka-go$ git log
commit da30423f069c3209c14c0fac76b7474bcb24faa1 (HEAD -> master, origin/master, origin/HEAD)
Merge: e363814 82d4853
Author: Magnus Edenhill <magnus@edenhill.se>
Date:   Fri Feb 9 19:16:08 2018 +0100

    Merge pull request #120 from confluentinc/headers

    Message headers support

commit e363814bb4acfa3561ea9c259da6d21739bab0b6
Merge: 467fbea afaa3d8
Author: Magnus Edenhill <magnus@edenhill.se>
Date:   Fri Feb 9 19:01:02 2018 +0100

    Merge pull request #125 from chstout/master

    explicit call out that you may need pkg-config
```

Checking out `e363814bb4acfa3561ea9c259da6d21739bab0b6` links as expected. The errors arise from an auto-generated file:

```
git diff HEAD^ -- kafka/generated_errors.go
```

As a workaround we checkout the tag `v0.11.0` before building:

```
(cd $$GOPATH/src/github.com/confluentinc/confluent-kafka-go && git checkout v0.11.0)
```

Feel free to close this issue when you want

**Comment by edenhill** [comment]
The Go client master branch depends on functionality only on librdkafka master, see this comment:
https://github.com/confluentinc/confluent-kafka-go/issues/61#issuecomment-303746159

**Comment by urban-1** [comment]
Completely missed that!! Thanks -  Closing this then
