### ISSUE TITLE
Refresh Schema-Cache state with according to schemaregistry.GetLatestSchemaMetadata invocation

### ISSUE THREAD

**Issue by nicolaspastorbueno-yape** [confluentinc/confluent-kafka-go#1274]
Description
===========

Hello guys, hope you're so well!

When `schemaregistry.GetLatestSchemaMetadata` method is called, it method manage the internal cache (`latestToSchemaCache`) when this retrives the latest version if a schema-metadata. It is great!, it can be more great if there is some manner to manage the internal state of  `latestToSchemaCache`.

We are implementing a manner that manages this situation in a new method, in order to call get-schema-metadata with `/subjects/<<subject-to-search>>/versions/latest`

How to reproduce
================

N/A

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): [v2.5.0](https://github.com/confluentinc/confluent-kafka-go/releases/tag/v2.5.0)
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: macOS
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by nicolaspastorbueno-yape** [comment]
the implementation should be like whis

```
func (c *client) RefreshLatestSchemaMetadataCache(subjects ...string) (err error) {

	var errors error

	for _, subjectIter := range subjects {
		sm := &SchemaMetadata{}
		err = c.restService.HandleRequest(internal.NewRequest("GET", internal.Versions, nil, url.PathEscape(subjectIter), "latest"), &sm)
		if err != nil {
			errors = multierror.Append(errors, err)
			continue
		}
		c.latestToSchemaCacheLock.Lock() // lock r/w due to we need to be aware of the possible latest schema-metadata update
		c.latestToSchemaCache.Put(subjectIter, &sm)
		c.latestToSchemaCacheLock.Unlock()
	}

	return errors
}
```

**Comment by rayokota** [comment]
Hi @nicolaspastorbueno-yape , I've added the ability to clear the latest caches.  Hopefully it will address your use case
https://github.com/confluentinc/confluent-kafka-go/pull/1305
