### ISSUE TITLE
could not determine kind of name for C.RD_KAFKA_RESP_ERR__NOENT

### ISSUE THREAD

**Issue by eyeofthefrog** [confluentinc/confluent-kafka-go#130]
Description
===========
When I run `go get github.com/confluentinc/confluent-kafka-go/kafka`, I get the following errors:
```
src/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:106:36: could not determine kind of name for C.RD_KAFKA_RESP_ERR__NOENT
src/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:102:38: could not determine kind of name for C.RD_KAFKA_RESP_ERR__PARTIAL
src/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:104:39: could not determine kind of name for C.RD_KAFKA_RESP_ERR__READ_ONLY
src/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:108:40: could not determine kind of name for C.RD_KAFKA_RESP_ERR__UNDERFLOW
```

Do we need a new version of librdkafka? We're using the latest from the ubuntu repos. 

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): latest master of confluent-kafka-go and 0.11.0-1 of librdkafka
 - [x] Operating system: Ubuntu 17.10

**Comment by edenhill** [comment]
Upgrade to librdkafka master, or check out v0.11.0 of the Go client.

**Comment by eyeofthefrog** [comment]
Ok, thanks.
