### ISSUE TITLE
[Help wanted] Issues getting setup with Go and confluent-kafka-go

### ISSUE THREAD

**Issue by snovakov** [confluentinc/confluent-kafka-go#132]
I'm having trouble building my go program using the github.com/confluentinc/confluent-kafka-go library.

I start up a ubuntu vagrant vm, using "ubuntu/trusty64".
In my bootstrap, I run "sudo apt-get update"
I install go, git, and some other dev tools.

Then:
sudo apt-get install -y build-essential pkg-config
wget -qO - http://packages.confluent.io/deb/3.2/archive.key | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/3.2 stable main"
sudo apt-get update && sudo apt-get install -y confluent-platform-2.11
sudo apt-get install -y librdkafka-dev

I cd into my project-path.
I then run "dep init" to get all the dependencies using go, which are installed into vendor/ sub directory.
this is how I get the confluent-kafka-go library.
I then run "go build ."

I get the error:
<project-path>/vendor/github.com/confluentinc/confluent-kafka-go/kafka
vendor/github.com/confluentinc/confluent-kafka-go/kafka/consumer.go:320:94: could not determine kind of name for C.RD_KAFKA_EVENT_STATS

I've referenced:
https://github.com/confluentinc/confluent-kafka-go#getting-started
https://docs.confluent.io/current/installation/installing_cp.html#installation-apt

Just wondering what I could be missing, and if you have any suggestions.

Thanks!

**Comment by edenhill** [comment]
confluent-kafka-go master depends on librdkafka master.

If you don't want to use master you can checkout the latest v0.11.0 tag of confluent-kafka-go, but you still need a newer version of librdkafka than the one in Confluent Platform 3.2.
Try referencing packages.confluent.io/deb/4.0 instead

**Comment by snovakov** [comment]
Great!  Thanks.  It worked when I run "go build ."
I get my binary and it works as expected! :)

Unfortunately, I'm having trouble in with static builds.
As outlined in the documentation, I run "go build -tags static ."

I get the error:
#  <project-path>/vendor/github.com/confluentinc/confluent-kafka-go/kafka
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lsasl2
collect2: error: ld returned 1 exit status


Furthermore, when I run "go build -tags static_all ."
I get the error:
# <project-path>/vendor/github.com/confluentinc/confluent-kafka-go/kafka
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lsasl2
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/librdkafka.a(rddl.o): In function `rd_dl_open':
(.text+0xef): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/librdkafka.a(rdaddr.o): In function `rd_getaddrinfo':
(.text+0x58b): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

Any ideas what might be the problem?

**Comment by edenhill** [comment]
Your system is missing static libraries for zlib, openssl, libcrypto and libsasl2.
You will also not be able to use interceptors (such as the confluent monitoring-interceptor) with a statically linked librdkafka.

**Comment by snovakov** [comment]
Thanks for your help.
