### ISSUE TITLE
Bug with v2.6.0 during version negotiation.

### ISSUE THREAD

**Issue by misalcedo** [confluentinc/confluent-kafka-go#1320]
When we use version 2.6.0, the api version negotation fails to correctly set the fetch request's version to something the server supports. We use an internal Redis-backed implementation of Kafka for testing in Docker containers that only supports up to v7 of the Fetch request. However, the newest client fails to select the correct version and instead sends v12 for fetch requests.

The same problem occurred on our production Kafka cluster running Kafka version 2.6.1 with a TLS connection. All other interactions between the consumer and the cluster seemed to work correctly.

The problem does not occur when we use version 2.5.3.

**Comment by milindl** [comment]
Thanks for filing this, we fixed it here: https://github.com/confluentinc/librdkafka/pull/4871 . The fixed version is not released yet.

**Comment by misalcedo** [comment]
Thank you so much for fixing it so quickly. I look forward to having a new release that includes the fix.

**Comment by misalcedo** [comment]
This was fixed in [2.6.1](https://github.com/confluentinc/confluent-kafka-go/releases/tag/v2.6.1)
