### ISSUE TITLE
Messages sometimes dropped during a rebalance

### ISSUE THREAD

**Issue by danpurpura** [confluentinc/confluent-kafka-go#1322]
Description
===========
We run our consumers with both `enable.auto.commit` and `enable.auto.offset.store` set to `true`. We also have `auto.offset.reset` set to `latest`. During a release, as new consumers come and go and partitions get re-assigned, we've seen that occasionally the offset will jump ahead and messages will be missed. It looks like it's storing the last message that was pre-fetched by the library and not the last one returned to the consumer via Poll.

Looking at the consumer example, should we be setting to `enable.auto.offset.store` to `false` and be calling `StoreMessage` after receiving/processing the message? From my testing, this does appear to prevent the issue.

We run `v1.9.3-RC3` but I've also reproduced this with `v2.6.0`. Kafka version is `7.5.4`.

Logs can be provided, but just want to verify if it's user error first.

How to reproduce
================
* have a topic with 2 partitions
* setup two consumers in the same group to consume from the topic
  * have both `enable.auto.commit` and `enable.auto.offset.store` set to `true`
* produce messages into the topic
* shutdown one of the consumers
* after the partition is re-assigned notice that it starts consuming later than the last offset that was consumed by the terminated consumer

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
Yes, that is the correct expectation and the default behaviour, you can use StoreMessage to ensure that doesn't happen. An example of at-least once processing can be ensured is given in the repository here: https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/consumer_example/consumer_example.go#L100

**Comment by danpurpura** [comment]
Thanks for the clarification
