### ISSUE TITLE
Disconnected while requesting ApiVersion issue

### ISSUE THREAD

**Issue by hoahm-ts** [confluentinc/confluent-kafka-go#1343]
Description
===========

- Go v1.22
- Aiven Kafka on GCP cloud (asia-southeast1)
  + Apache Kafka 3.7.1
  + Karapace 3.15.0

I'm using Golang to build an application that produce/consume Kafka message. It works well before. Now we deploy this service on another cloud platform (GCP) and use Aiven Kafka. When starting, it raise a lot warning:

```
%6|1732161336.476|FAIL|rdkafka#producer-1| [thrd:kafka:25502/bootstrap]: kafka:25502/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 1ms in state APIVERSION_QUERY, 4 identical error(s) suppressed)
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): [confluent-kafka-go:v2.6.1](https://github.com/confluentinc/confluent-kafka-go/releases/tag/v2.6.1) and [librdkafka](https://github.com/confluentinc/librdkafka/releases/tag/v2.6.1).
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:distroless/static-debian12 
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by bbq2100** [comment]
@hoahm-ts i am facing the same error log when deploying to a new env... my config looks fine though. what was the issue in your case?

**Comment by git-ljm** [comment]
me too
