### ISSUE TITLE
Having issues with GO 1.9.4 darwin/amd64

### ISSUE THREAD

**Issue by ColinClark** [confluentinc/confluent-kafka-go#135]
Description
===========
WunderMac5000:src cclark$ go get -u github.com/confluentinc/confluent-kafka-go/kafka
# github.com/confluentinc/confluent-kafka-go/kafka
github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:106:36: could not determine kind of name for C.RD_KAFKA_RESP_ERR__NOENT
github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:104:39: could not determine kind of name for C.RD_KAFKA_RESP_ERR__READ_ONLY
github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:108:40: could not determine kind of name for C.RD_KAFKA_RESP_ERR__UNDERFLOW

How to reproduce
================
WunderMac5000:src cclark$ brew install librdkafka
Warning: librdkafka 0.11.3 is already installed

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
mac os x high sierra version 10.13.3
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The go client master branch tightly follows librdkafka's master branch, so you either need to upgrade to librdkafka master, or use the v0.11.0 release tag of the go client (and remain at librdkafka 0.11.3)

**Comment by binary132** [comment]
This causes `go get github.com/confluentinc/confluent-kafka-go/kafka` to result in these error messages.  Perhaps `librdkafka` in Homebrew should be updated, or the `go get` default should be pinned to a tag that matches the `librdkafka` version?

**Comment by edenhill** [comment]
Yeah, the latter option sounds good.
We're aiming for formal releases in about two weeks time.

**Comment by ColinClark** [comment]
great - thank you.

**Comment by amourshmuel** [comment]
Hi,

I have the same problem.
Do we have an answer for that?


I tried also to make the librdkafka w/o success to install it
