### ISSUE TITLE
Allow users to search offsets by timestamp on partitions

### ISSUE THREAD

**Issue by turtlemonvh** [confluentinc/confluent-kafka-go#14]
As of 0.10.0.1 the java library lets users seek to offsets based on timestamp.

https://kafka.apache.org/documentation#upgrade_1010_notable

**Comment by edenhill** [comment]
offsets_for_times() support was just added to librdkafka, will be added to the Go client soon.

**Comment by turtlemonvh** [comment]
@edenhill Did this make it in?  I may be missing something but I don't see it in [the docs](http://docs.confluent.io/3.2.0/clients/confluent-kafka-go/index.html#NewOffset) or in these tests:
https://github.com/confluentinc/confluent-kafka-go/blob/0.9.4.x/kafka/kafka_test.go

**Comment by edenhill** [comment]
Whoop, closed the wrong issue.
No, offset_for_times is not yet added. Will be added for the next release.

**Comment by Ishiihara** [comment]
@edenhill Will the release in June have this feature?

**Comment by edenhill** [comment]
Sorry, not for this release. Will be available in the next one.

**Comment by edenhill** [comment]
OffsetsForTimes is now available on master.

**Comment by turtlemonvh** [comment]
Awesome: http://godoc.org/github.com/confluentinc/confluent-kafka-go/kafka#Consumer.OffsetsForTimes

Thanks @edenhill!
