### ISSUE TITLE
could not determine kind of name for (go build)

### ISSUE THREAD

**Issue by fcuencaML** [confluentinc/confluent-kafka-go#140]
Hi, i have this error when i do go build

# github.com/confluentinc/confluent-kafka-go/kafka
./generated_errors.go:106:36: could not determine kind of name for C.RD_KAFKA_RESP_ERR__NOENT
./generated_errors.go:104:39: could not determine kind of name for C.RD_KAFKA_RESP_ERR__READ_ONLY
./generated_errors.go:108:40: could not determine kind of name for C.RD_KAFKA_RESP_ERR__UNDERFLOW

i have librdkafka 0.11.3, updated by homebrew.
Thanks

**Comment by edenhill** [comment]
Golang master depends on librdkafka master (or the upcoming 0.11.4 release).
Either upgrade to librdkafka master, or use v0.11.0 of the go client.

**Comment by fcuencaML** [comment]
done, thank you very much !
