### ISSUE TITLE
suppor using consumer examples

### ISSUE THREAD

**Issue by fcuencaML** [confluentinc/confluent-kafka-go#141]
Hi!, im using 4 different docker containers to mount zookeeper, kafka, connect and mysql using debezium.io config.

Now, i want to test consume messages using just an example provided by you (i.e. consumer_example)
but when i do .
/consumer_channel_example 1 1 dbserver1.inventory.customers, i receive this output.
Created Consumer rdkafka#consumer-1
%3|1519074130.752|ERROR|rdkafka#consumer-1| [thrd:1:9092/bootstrap]: 1/1 brokers are down

Do you know what am i doing wront? or where do i found the correct input data? :(

Thanks !

**Comment by edenhill** [comment]
is `1` really your broker's hostname?
