### ISSUE TITLE
Versioning issues with librdkafka

### ISSUE THREAD

**Issue by ness2u** [confluentinc/confluent-kafka-go#142]
Description
===========
Unable to build using latest version of `confluent-kafka-go` and `librdkafka`, both on osx and ubuntu; with `go get ...` and `govendor ...`.

What am I doing wrong? How should I build this thing?
Is my only option to manually compile librdkafka?

I have a suite of internal kafka utilities, we call the toolshed.
One of the tools depends on calling `consumer.Commited(...)`, implemented here: https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/consumer.go#L541
This function is not implemented in `v0.11.0.x`, requiring that I use latest.

How to reproduce
================
Osx:
```
$ brew upgrade librdkafka
Error: librdkafka 0.11.3 already installed
```
```
$ go get -u github.com/confluentinc/confluent-kafka-go/kafka
# github.com/confluentinc/confluent-kafka-go/kafka
src/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:106:36: could not determine kind of name for C.RD_KAFKA_RESP_ERR__NOENT
src/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:104:39: could not determine kind of name for C.RD_KAFKA_RESP_ERR__READ_ONLY
src/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:108:40: could not determine kind of name for C.RD_KAFKA_RESP_ERR__UNDERFLOW
```
Pulling out the headers from brew, it looks like those consts really are not defined.
Looking at source, they're only defined in master (not `v0.11.0.x`): https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L342

Ubuntu: fresh docker container, using confluent's deb archives.
```Dockerfile
from ubuntu

# ubuntu stuff
run apt-get update \
     && apt-get install -y software-properties-common git wget vim pkg-config apt-transport-https

# lib rdkafka (kafka go dependency)
run wget -qO - http://packages.confluent.io/deb/4.0/archive.key | apt-key add - \
	 && add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/4.0 stable main" \
 	 && apt-get update && apt-get install -y librdkafka-dev

# golang
run wget https://storage.googleapis.com/golang/go1.10.linux-amd64.tar.gz \
       && tar -C /usr/local -xzf go1.10.linux-amd64.tar.gz \
       && rm go1.10.linux-amd64.tar.gz
env PATH="${PATH}:/usr/local/go/bin"
```
```
docker build -t toolshed .
... snip ...
docker run --rm -ti toolshed bash -c "cat /usr/include/librdkafka/rdkafka.h | grep RD_KAFKA_VERSION"
#define RD_KAFKA_VERSION  0x000b01ff
```
 .... this is version 11.1, which also does not contain the headers missing above.

What are my options?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
`v0.11.0.x` doesn't have what I need; but I can't run latest.
`librdkafka `0.11.1` and `0.11.3` do not have headers master expects.
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Golang client master depends on librdkafka master (or the upcoming v0.11.4 release).
Either upgrade librdkafka to master (by manually downloading, compiling and installing - make sure to remove the homebrew/ubuntu packages first), or pin the Golang client to v0.11.0 (but use librdkafka v0.11.3)

**Comment by ness2u** [comment]
Thank you Eden.
Did that dependency change recently, or was it just by fluke that our code was working?

I've updated my scripts + Dockerfile to grab master and compile rdkafka.

Thank you.

**Comment by edenhill** [comment]
That dependency has been stated in the README for some while, but we actually asserted this dependency last week when merging PRs for message headers, et.al.
