### ISSUE TITLE
Transactional Production

### ISSUE THREAD

**Issue by samv** [confluentinc/confluent-kafka-go#143]
Description
===========
I was looking into this and noticed that Kafka 0.11+ transactional production of messages is not yet supported by this library, though seems to be supported in librdkafka.  Are there any plans to add this, including AddOffsetsToTxn for full atomic exactly once processing?

**Comment by edenhill** [comment]
Transactional producer is not yet supported in librdkafka or the Go client, we're looking to implement it in Q2 or Q3.

**Comment by ishworgurung** [comment]
Hey folks, Could we know what the status of tx producer is ? thanks.

**Comment by edenhill** [comment]
Support for the Idempotent Producer will be released in Q4.
Transaction support in 2019.

**Comment by yahudev** [comment]
Any update on this feature @edenhill ? thanks.

**Comment by edenhill** [comment]
The idempotent producer is now available in release v1.0.0.

Transaction support has been delayed awaiting actual customer and community use-cases.

**Comment by yahudev** [comment]
where shall I log community use-case to? :)

**Comment by edenhill** [comment]
Post a comment here on how you are planning to use transactions so we can learn your requirements, thanks

**Comment by ervitis** [comment]
Hi @edenhill, in our platform using event storming and event sourcing we need this feature. Thanks!

**Comment by bernardoVale** [comment]
+1

**Comment by ervitis** [comment]
Hi @edenhill, great news! Would it be available transactionality in the consumer too?

**Comment by edenhill** [comment]
Starting with librdkafka v1.2.0 the consumer is already transaction aware when configured with `isolation.level=read_committed`

**Comment by sneko** [comment]
Hi @edenhill,

Any news on the transactional producer?

Thank you,

**Comment by edenhill** [comment]
Transactional producer will be merged to librdkafka master this week, after that work on the Go API will start. cc @rigelbm

**Comment by maeglindeveloper** [comment]
Sounds like a really good news ! good job @edenhill 👍
Looking forward to test it ;)

**Comment by edenhill** [comment]
Full EOS and Transactional Producer released in v1.4.0
