### ISSUE TITLE
unclear revoke before reassignment cleanup guarantees during rebalances

### ISSUE THREAD

**Issue by daniel-fanjul-alcuten** [confluentinc/confluent-kafka-go#146]
After reading the examples and the godoc, it is still unclear to me how to handle a proper cleanup during rebalances. I would have written to a mailing list but I could not find one, sorry if I should have.

When the rebalance starts, I need to run a piece of code that handles cleanup of the internal application state between the RevokedPartitions and AssignedPartitions events with the following constraint: I need all consumers in the group to finish running that code before any of them starts consuming from the newly assigned partitions.

In the java client, this is provided by the ConsumerRebalanceListener: "It is guaranteed that all the processes in a consumer group will execute their onPartitionsRevoked(Collection) callback before any instance executes its onPartitionsAssigned(Collection) callback."
https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html

Is this an undocumented feature of the type RebalanceCb? If I run the cleanup code in this callback when the event is RevokedPartitions, will every consumer in the group wait until the callback finishes before calling the callback for the AssignedPartitions event?

**Comment by daniel-fanjul-alcuten** [comment]
Using the channels approach, the RebalanceCb function I pass in the Susbscribe() does not get invoked. However, I noticed that all consumers of the group wait until all of them have returned from c.Unassign() upon reception of a RevokedPartitions.

 - [X] confluent-kafka-go and librdkafka version: both v0.11.0
 - [X] Apache Kafka broker version: kafka_2.12-0.10.2.1
 - [X] Client configuration: provided below
 - [X ] Operating system: Ubuntu 16.04.3 LTS
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

client config: &kafka.ConfigMap{
		"bootstrap.servers":               "kafka1:9092",
		"group.id":                        "test",
		"enable.auto.commit":              false,
		"fetch.message.max.bytes":         10 * 1024,
		"go.application.rebalance.enable": true,
		"go.events.channel.enable":        true,
		"go.events.channel.size":          0,
		"default.topic.config":            kafka.ConfigMap{"auto.offset.reset": "earliest"}}

**Comment by edenhill** [comment]
> "It is guaranteed that all the processes in a consumer group will execute their onPartitionsRevoked(Collection) callback before any instance executes its onPartitionsAssigned(Collection) callback."

That quote should be amended to say "within `session.timeout.ms`", meaning that existing members of a group have up to `session.timeout.ms` to do whatever they need to clean up before their partitions might be assigned to a new member of the group.
In practice the time is much shorter, because as soon as all members have handled their respective Revoked partitions the group will rebalance and assign partitions to new members.


The same is true for the Go client as well.

`Unassign()` is used by the application to signal to the client, and sub-sequently to the group, that the revoke has been handled.

I'm not sure why are not seeing rebalance events on the Events channel, perhaps the use of a blocking channel (channel.size=0) has something to do with it.

**Comment by daniel-fanjul-alcuten** [comment]
Yes, I knew about the `session.timeout.ms` and it makes full sense.

I actually see the rebalance events on the Events channel, that is when I invoke `Unassign()`; it is the callback of the `Subscribe()` that does not get invoked.

Thank you very much for your reply. The behavior of `Unassign()` you have described solves my problem. It would be good that it gets documented.

**Comment by edenhill** [comment]
The rebalance callback only kicks in if you call Poll(), not when reading Events from the .Events channel.

**Comment by DoubleLuck** [comment]
> The rebalance callback only kicks in if you call Poll(), not when reading Events from the .Events channel.

Thank you! This helps me a lot!
