### ISSUE TITLE
RevokedPartitions event on "Unknown member" error, how to handle sync commit

### ISSUE THREAD

**Issue by JeanMertz** [confluentinc/confluent-kafka-go#147]
I have a situation where I am handling the `RevokedPartitions` event manually. In it, I first call `consumer.Commit()` and then, if that succeeds, `consumer.Unassign()`.

The problem is that I can get into a situation where (for some reason) the heartbeat response returns an `Broker: Unknown member: actions Permanent` error, which in turn triggers a repartition. This repartition then triggers `RevokedPartitions`, which triggers `consumer.Commit()`, but since the established connection is bad, this request fails as well:

```
OffsetCommit for 1 partition(s): manual: returned: Broker: Unknown member
```

Now, in this application, if an error occurs on this final commit, we hard-crash the application, since we'd like to be on the safe side, and rather reprocess the messages that weren't committed to the broker.

My question is: in a situation like this, how should I deal with this? I guess first of all would be figuring out why the heartbeat response failed (could be a timeout setting that's too low, this is a test environment where I am seeing this), but other than that, if this does ever happen, is there a graceful way to deal with a situation like this? If I simply ignore this error, and let the unassignment continue, those uncommitted offsets are lost, but I also see no way to make that request eventually go through once an error like this is returned.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): HEAD
 - [x] Apache Kafka broker version: 1.0
 - [x] Client configuration: `ConfigMap{...}`

```json
{
  "config": {
    "auto.commit.interval.ms": 500,
    "default.topic.config": {
      "auto.offset.reset": "beginning"
    },
    "enable.auto.commit": true,
    "enable.auto.offset.store": false,
    "enable.partition.eof": false,
    "go.application.rebalance.enable": true,
    "go.events.channel.enable": true,
    "group.id": "TestMessage_Ackrs3s",
    "heartbeat.interval.ms": 150,
    "metadata.broker.list": "127.0.0.1:9092",
    "session.timeout.ms": 1000
  }
}
```

**Comment by edenhill** [comment]
Sorry for the slow response.

I think your issue is with the extremely low session.timeout.ms of 1s.
This leaves your application 1s to do its final processing, rebalancing and committing offsets before it looses its assignment and right to commit.

Using a longer session timeout is my suggestion, it will also provide you with more resilient consumer groups.
