### ISSUE TITLE
confluent-kafka-go requires librdkafka v0.11.4 or later

### ISSUE THREAD

**Issue by chaevnicher** [confluentinc/confluent-kafka-go#158]
$ go get -u github.com/confluentinc/confluent-kafka-go/kafka

# github.com/confluentinc/confluent-kafka-go/kafka
/Users/chaevnicher/go/src/github.com/confluentinc/confluent-kafka-go/kafka/00version.go:43:2: error: "confluent-kafka-go requires librdkafka v0.11.4 or later. Install the latest version of librdkafka from Homebrew by running `brew install librdkafka` or `brew upgrade librdkafka`"
#error "confluent-kafka-go requires librdkafka v0.11.4 or later. Install the latest version of librdkafka from Homebrew by running `brew install librdkafka` or `brew upgrade librdkafka`"
 ^
1 error generated.

$ brew upgrade librdkafka
Error: librdkafka 0.11.3 already installed

**Comment by adyach** [comment]
same for me

```
brew info librdkafka                                                                                                                                    2 ↵
librdkafka: stable 0.11.3 (bottled), HEAD
The Apache Kafka C/C++ library
https://github.com/edenhill/librdkafka
/usr/local/Cellar/librdkafka/0.11.3 (14 files, 1.9MB) *
  Poured from bottle on 2018-03-21 at 16:02:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/librdkafka.rb
```

**Comment by adyach** [comment]
https://github.com/edenhill/librdkafka/pull/1734

**Comment by edenhill** [comment]
v0.11.4 has not been released yet (this week)

**Comment by nid90** [comment]
I have the latest librdkafka (0.11.4), it still throws the same error.

```
#error "confluent-kafka-go requires librdkafka v0.11.4 or later. Install the latest version of librdkafka from Homebrew by running `brew install librdkafka` or `brew upgrade librdkafka`"

± brew info librdkafka                                                                                                                                                                                                        
librdkafka: stable 0.11.4 (bottled), HEAD
```

**Comment by edenhill** [comment]
@nid90 It look like it is picking up an older version of librdkafka installed somewhere else?
Try:
`find /usr -name rdkafka.h 2>/dev/null`

Does it find more than one? If so, grep those files for RD_KAFKA_VERSION, uninstall/remove any version that is less than 0x000b04ff (0.11.4)

This might also be of interest:
`pkg-config --cflags rdkafka`

**Comment by nid90** [comment]
@edenhill Ah yes, I had an older version installed from source. Removed that and it worked. Thanks.
