### ISSUE TITLE
Cannot commit offsets using high-level consumer

### ISSUE THREAD

**Issue by cresny** [confluentinc/confluent-kafka-go#160]
Description
===========

I'm using the very basic code from the README with the following config

		"bootstrap.servers":        "server:9092",
		"group.id":                 "myGroup",
		"offset.store.method":      "file", //this is preferred; I also tried default "broker"
		"enable.auto.commit":       true,
		"auto.offset.reset":        "earliest",
		"enable.auto.offset.store": true,
		"auto.commit.interval.ms":  1000,

I've tried several combinations of config, but no offsets ever commit. Based on the debug logs it looks likecommits are attempted, but looking at the code it looks like the high level consumer is not supported since there are several checks like below. 

```
if (!rd_kafka_is_simple_consumer(rktp->rktp_rkt->rkt_rk))
                   return;
```

Searching issues and documentation seems to indicate autocommit is supported for the high-level consumer.  What am I missing?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
11.4
 - [x] Apache Kafka broker version:
1.0
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system:
Linux
 - [x] Provide client logs (with `"debug": ".."` as necessary)
%7|1521669663.977|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic mmy.topic [0]: stored offset 4118, committed offset 4118
%7|1521669663.977|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic mmy.topic [0]: setting offset INVALID for commit
%7|1521669663.977|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic mmy.topic [1]: stored offset 4348, committed offset 4348
%7|1521669663.977|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic mmy.topic [1]: setting offset INVALID for commit
%7|1521669663.977|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic mmy.topic [2]: stored offset 4615, committed offset 4615
%7|1521669663.977|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic mmy.topic [2]: setting offset INVALID for commit

 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you provide some example code?
Do note that the legacy file-based offset committer is not meant to be used with the High-level consumer, use the default (broker) storage method instead·
