### ISSUE TITLE
NewProducer and NewConsumer mutate the configuration

### ISSUE THREAD

**Issue by vlad-alexandru-ionescu** [confluentinc/confluent-kafka-go#162]
Description
===========

Both NewProducer and NewConsumer mutate the configuration passed to them. They remove all `go.*` items from them. I'm sure this is not news for the maintainer, but let me explain how this can be very dangerous. (Also, this behavior is not documented anywhere.)

We've been chasing our tail for days on end to find this problem, causing many eng-hours to be wasted. Hopefully this prevents others from running into the same issue.

#### Example 1: Consumer

Say we have a consumer config with `go.events.channel.enable` set to `true`. First such consumer you start works fine. Second time you want to start a consumer with the same configuration, consumer starts ok, no error reported, but it doesn't receive any messages. Worse, there is no way for the library to inform the user that it is misusing the API as a channel consumer, when the library is expecting to be used as a function consumer. No error anywhere, yet things do not work.

This setup can be used in following situations:

* Consumer died and want to create again, using the "same" configuration as used the first time around.
* Multiple consumers need to be created and want to reuse the same configuration for each of them.

#### Example 2: Producer (maybe)

(Note: Not 100% sure that this particular example happens exactly as described.)

Say we have a producer config with `go.delivery.reports` set to `true`. First producer works correctly. Second producer created with this config hangs forever when using a delivery channel:

```
p.Produce(msg, deliveryChannel)
<- deliveryChannel // Hangs here forever.
```

And again, no error anywhere, yet things do not work. (suggestion: make this call return an error if passed in a delivery channel but delivery reports are off).

Again, this setup can be used when:

* Producer is recreated using the "same" configuration
* Multiple producers need to be created and want to reuse the same configuration for each of them

#### Possible symptoms for anyone googling this

* Messages not being delivered (not technically true, but leads you to believe this)
* Consumer not consuming messages
* Producer not receiving delivery confirmations

#### Workaround

Either:

* Do not reuse configuration passed to `NewProducer` or `NewConsumer`; or
* Set `go.*` config items every time a call to `NewProducer` or `NewConsumer` is made

How to reproduce
================

1. Initialize configuration with `go.*` items in it
2. Call either `NewProducer` or `NewConsumer` with that configuration.
3. Call either `NewProducer` or `NewConsumer` **again** with the same configuration
4. The second producer/consumer does not get the `go.*` configuration items.

Suggested fix
================

Clone the configuration before mutating it.

Happy to contribute myself if this looks reasonable. Let me know.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):

confluent-kafka-go: `v0.11.0`

 - [x] Apache Kafka broker version:

0.11.0

 - [x] Client configuration: `ConfigMap{...}`

Anything with `go.*` in it.

 - [x] Operating system:

N/A

**Comment by edenhill** [comment]
> We've been chasing our tail for days on end to find this problem, causing many eng-hours to be wasted. 

Sorry about that!

It does indeed seem like a bad idea to mutate the passed ConfigMap (without documenting that this is the case).

As to your suggestion, we should definitely make a copy of the ConfigMap so the user's isn't mutated, this seems like the most intuitive thing to do.

Would you like to submit a PR for this?

Great report btw!
