### ISSUE TITLE
Request: Example of Re-using of Producer for Synchronously produced messages

### ISSUE THREAD

**Issue by StevenACoffman** [confluentinc/confluent-kafka-go#168]
Description
===========
These bindings do not make it obvious how to produce messages (e.g. for web requests) while re-using the producer. I have read [Why there is no sync produce interface](https://github.com/edenhill/librdkafka/wiki/FAQ#why-is-there-no-sync-produce-interface). I would like to have a GoLang example of the [Librdkafka Sync producer wrapper and Delivery report callback](https://github.com/edenhill/librdkafka/wiki/Sync-producer)

Using this repo's examples naively creates a producer for every set of messages produced, and quickly fails under load. An example synchronously producing message re-using the producer for different messages batches would be very helpful.

For instance, in another golang kafka library like Sarama, [this is simple in a few lines](https://github.com/wadearnold/golang-kafka-templates/blob/master/producer-wordcount-api/main.go). I am pretty sure the same thing is possible here, but it's harder to figure out the mechanism. Pointers would be very welcome.

**Comment by mcqueary** [comment]
@StevenACoffman I may be misunderstanding your request, but [producer_example.go](../blob/master/examples/producer_example/producer_example.go) gives an example of exactly what you're asking for. It produces a message and then waits for an Event on deliveryChan to determine whether the operation succeeded or failed.

While this is an intentionally trivial example that immediately closes its delivery channel and exits, there is no reason you couldn't re-use the `Producer` to send more messages. You could create your own wrapper function like so (forgive any typos, I didn't try to compile this, but hopefully you get the idea):

```go
func sync_produce(p *kafka.Producer, m *kafka.Message, ch chan kafka.Event, ) *kafka.Message {
	p.Produce(m, ch)
	e := <-ch
	return e.(*kafka.Message)
}
```
You could of course make this more useful this by adding a [timeout func and a `select` statement](https://blog.golang.org/go-concurrency-patterns-timing-out-and), but that's an implementation detail.

You could then call this function in a loop:

```go
[...]
for i := 0; i < 10; i++ {
	m := sync_produce(p, &kafka.Message{
		TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny},
		Value:          []byte(i),
		Headers:        []kafka.Header{{"myTestHeader", []byte("header values are binary")}},
	}, deliverChan)

	if m.TopicPartition.Error != nil {
		fmt.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
	} else {
		fmt.Printf("Delivered message to topic %s [%d] at offset %v\n",
			*m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
	}	
}
[...]
```

**Comment by StevenACoffman** [comment]
@mcqueary Thank you! That is very helpful!
The use case I have in mind is that a batch of messages are sent restfully (via HTTP POST), and I need to respond with a status code indicating whether they were all produced successfully. I was concerned that counting the producer's events for delivery reports equal to the messages produced would be confused with the delivery reports for concurrently sent messages, so when I produce I send reports to a private channel for that batch. I also sent `p.Flush(0)` to flush the queue. The timeout idea is a very good one, that I need to implement.

This was my first pass before I saw your message:

```
func SendBatchToKafka(messageBatch []MessageWithTopic, kafkaConfig kafka.ConfigMap, p *kafka.Producer) bool {
	eventChannel := make(chan kafka.Event, len(messageBatch))

	productionErrors := 0
	// Produce messages to topic (asynchronously)
	for _, messageWithTopic := range messageBatch {
		err := p.Produce(&kafka.Message{
			TopicPartition: kafka.TopicPartition{Topic: &messageWithTopic.Topic, Partition: kafka.PartitionAny},
			Value:          []byte(messageWithTopic.Message),
		}, eventChannel)
		if err != nil {
			log.WithError( err).Error("Producing failed")
			productionErrors++
		}
	}

	// Wait for deliveries
	p.Flush(0 * 1000)

	var successes int = 0

	for i := 0; i < len(messageBatch) - productionErrors; i++ {
		e := <-eventChannel
		switch ev := e.(type) {
		case *kafka.Message:
			if ev.TopicPartition.Error == nil {
				successes++
			}
		}
	}
	close(eventChannel)

	result := successes == len(messageBatch)
	log.Infof("Successes: %v Len: %v Result: %v \n",
		successes, len(messageBatch), result)
	return result
}
```
Yours is enviably more elegant.

**Comment by amanpateldiy** [comment]
@mcqueary . I dont understand how this is sync producer. 
```
p.Produce(m, ch)
e := <-ch
```
Here we are waiting for delivery signal for each Produce right, dosent that make it async ? Please help here

**Comment by BadgerBadgerBadgerBadger** [comment]
I'm reading everything right, the idea of this being a sync producer is that you produce, and then wait for the delivery notification to be returned before moving on in your code. Even though the underlying mechanism is async, you are calling it in a synchronous fashion.

**Comment by Digl** [comment]
@mcqueary your code example for synchronous producing looks pretty nice but wouldn't a
`p.Flush(0)`
 be needed after 
`p.Produce(m, ch)`?
Thanks
