### ISSUE TITLE
Kafka consumer lags always

### ISSUE THREAD

**Issue by arriqaaq** [confluentinc/confluent-kafka-go#169]
Description
===========
Kafka consumer starts lagging behind if run continuously on a high traffic topic

How to reproduce
================

Run multiple consumer groups, on a topic with multiple partitions, having high throughput, the Events function does not get messages at the same rate as before

Checklist
=========
Please provide the following information:

 - confluent-kafka-go and librdkafka version (`LibraryVersion()`):
    
 - Apache Kafka broker version:0.11
 - Client configuration: `
ConfigMap{
		"bootstrap.servers":         "broker",
		"group.id":                         "group",
		"session.timeout.ms":              6000,
		"go.events.channel.enable":        true,
		"go.application.rebalance.enable": true,
		"enable.auto.commit":              true,
		"default.topic.config":            kafka.ConfigMap{"auto.offset.reset": "latest"}}
`
 - Operating system: Ubuntu 14

**Comment by arriqaaq** [comment]
Hey @edenhill 

My topic produce rates varies from 1-2k per second, and the time spend processing each message varies currently from (40-300) ms

**Comment by edenhill** [comment]
Back of envelope calculation:

produce rate: 1000 .. 2000 msgs/second
consumer processing rate: 1000/300 .. 1000/40 = 3 .. 25 msgs/second

You would thus need to run 2000/25 to 1000/2 = 80 to ~300 consumer instances to be able to cope with the load. Do you?

**Comment by edenhill** [comment]
Are you running 10 consumers?

**Comment by arriqaaq** [comment]
Yes

**Comment by edenhill** [comment]
Individually measure the time it takes to get a new message from the Event channel, your processing, and any manual commits, to see where time is being spent.

**Comment by arriqaaq** [comment]
As I've mentioned, the time is coming from the event channel, when I check on kafka, when the produce rate is 1-2k records/sec, the consumption rate decreases linearly with time until I restart it. The problem is not with the code after consumption, I am trying to understand why the event channel is lagging.

**Comment by edenhill** [comment]
I would still like you to measure how long your program sits waiting for a new message from the Events channel, use microsecond precision if possible.

Please also share some of your code.

Thanks

**Comment by edenhill** [comment]
@arriqaaq Any updates on this?
