### ISSUE TITLE
Calling Flush() on producer could cause out of order events in channel?

### ISSUE THREAD

**Issue by szli** [confluentinc/confluent-kafka-go#172]
I noticed this when reading the code and want to confirm my understanding. In the producer.go, p.handle.eventPoll is called in Flush() function and poller() function. poller() is called from a separate goroutine, hence Flush() and poller() can be called from different goroutines. When that happens, both function tries to poll event from librdkafka's queue and push to p.events channel at the same time. I think this could cause the events in p.events channel in a different order from librdkafka's queue. Is it actually the case? It is probably not a big problem because this only affects delivery confirmations.

**Comment by edenhill** [comment]
Your observation is correct, this needs to be fixed.
Thanks for your report!

**Comment by edenhill** [comment]
Since delivery report ordering is not considered critical we'll close this.
