### ISSUE TITLE
Expose stats through callback function

### ISSUE THREAD

**Issue by yxu-valleytider** [confluentinc/confluent-kafka-go#174]
Description
===========
Currently stats in confluent-kafka-go is exposed as Stats event (pull request #57), instead of through a stats_cb function, per the [librdkafka documentation](https://github.com/edenhill/librdkafka/wiki/Statistics).

Allowing for passing a callback function would be very useful for importing confluent-kafka-go as a library.  It appears such support is readily available inside confluent-kafka-python. Just wonder if there is similar plan for confluent-kafka-go? 

Thanks in advance!

How to reproduce
================

Looking through Pull request #57 

Checklist
=========
Please provide the following information:

 - [0.11.4] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ any ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ x] Critical issue

**Comment by edenhill** [comment]
I thought I'd answered this but the response must have gotten lost:

It is problematic to trigger callbacks from C to Go so we chose to expose
everything as events on the Events channel.
What you can do is have a routine poll for events and then dispatch them to separate
channels or trigger go-routines based on event type.
So in this case you would do something like:
```
        for ev := range p.Events() {
                switch e := ev.(type) {
                case *Stats:
                   go my_stats_callback(e.String())
                ...
```
