### ISSUE TITLE
Question about optimizing consumer ingest performance

### ISSUE THREAD

**Issue by replay** [confluentinc/confluent-kafka-go#176]
Description
===========

I'm writing a service which needs to consume between `2` and `8` partitions on one kafka topic and i'm trying find the right settings to maximize the ingest rate. In my test environment with 8 cores (4 physical) I could get the ingest rate up to about 400k msgs/sec with one single confluent consumer. But I can reach an even higher rate of about 600k msgs/sec if i instantiate multiple confluent consumers, assign one partition to each of them, and make all of them consume in parallel.
Now I'm trying to understand why this is the case, is it because librdkafka does not multi-thread its internal consumer loop, so the only way to multi-thread is by instantiating multiple consumers? Is this the recommended way to max out ingest performance, or is there a better way to multi-thread librdkafka?

Versions:
===========

librdkafka version: 13befa7053c43593fd6f2effdffbd83c3ea52eb7
confluent-kafka-go version: 5e4d04e05fc319ce5996a867aafef29059f26862
kafka version: 0.10.0.1
OS: Linux
example configMap: 
```
&map[
    bootstrap.servers:kafka:9092
    queue.buffering.max.ms:100 
    group.id:default-mdm-partition-0 
    go.events.channel.size:100000 
    go.application.rebalance.enable:true 
    fetch.min.bytes:1 
    max.in.flight.requests.per.connection:100000
    queue.buffering.max.messages:1000 
    enable.auto.commit:false 
    session.timeout.ms:10000 
    enable.partition.eof:false 
    enable.auto.offset.store:false 
    batch.num.messages:10000 
    go.events.channel.enable:true 
    compression.codec:snappy 
    fetch.message.max.bytes:32768 
    fetch.wait.max.ms:1000 
]
```

**Comment by edenhill** [comment]
librdkafka is multi-threaded internally and there shouldn't be much problem maxing out a gigabit connection with it.

What I think you are seeing is the CGo overhead, each call from Go into C is quite costly (stacks are being copied, et.al.). We've tried really hard to minimize the number of calls required per message and there is not much else we can do at this point than to hope for the Go maintainers to optimize the CGo calls.

What you could try is calling ReadMessage() from multiple go-routines for the same consumer, make sure GOMAXPROCS is > 1.

**Comment by replay** [comment]
Thanks for that explanation @edenhill 

Your suggestion to have multiple go routines consuming from one consumer instance is actually what we previously already did. We had multiple (8) go routines which were all consuming from the `Events()` channel of one single consumer instance. When I changed that so that each of those go routines gets its own consumer instance the ingest rate ~doubled.

**Comment by edenhill** [comment]
That makes sense, the Events channel is served by a single Go routine that calls the C code, so reading the Events channel from multiple go routines will not speed up the C calls.

If instead of using the Events channel you call ReadMessage(), which itself calls C directly, it means that more threads are calling C at the same time, theoretically improving thruput.

**Comment by replay** [comment]
Thanks for your help, that helped a lot. I will close this issue here

**Comment by jiminoc** [comment]
> That makes sense, the Events channel is served by a single Go routine that calls the C code, so reading the Events channel from multiple go routines will not speed up the C calls.
> 
> If instead of using the Events channel you call ReadMessage(), which itself calls C directly, it means that more threads are calling C at the same time, theoretically improving thruput.

wow, can confirm... quick test on my target hardware took me from being able to pull 160K EPS on a single node up to 360K EPS with much more CPU utilization using the new ReceiveMessage API vs the Events Channel with the same number of go routines.
