### ISSUE TITLE
Reusing of Consumer

### ISSUE THREAD

**Issue by mahinko** [confluentinc/confluent-kafka-go#177]
Description
===========
I'm trying to reuse a consumer. It should always read the last committed message. Though it acts like every read message is committed in scope of a consumer instance. On a consumer re-initialization it reads as expected from the last committed entry.

`	

	// Get offset of the last commited message
	lastOffsets, _ := c.Committed([]kafka.TopicPartition{{Topic: &topic, Partition: 0}}, 5000)

	// Assign offset to the consumer
	o = lastOffsets[0].Offset
	c.Assign([]kafka.TopicPartition{{Topic: &topic, Partition: 0, Offset: o}})

	// Read first uncommitted message from the beginning
	select {
	case ev := <-c.Events():
		switch e := ev.(type) {
		case *kafka.Message:
			// Process message
		}
	}
` 

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 722175 - 0.11.4-2-g13befa
 - [ ] Apache Kafka broker version:
 - [x] Client configuration: `ConfigMap{...}`:
		"bootstrap.servers":        config.KafkaHost,
		"group.id":                 "BlincSync",
		"session.timeout.ms":       6000,
		"go.events.channel.enable": true,
		"enable.auto.commit":       false,
		"default.topic.config":     kafka.ConfigMap{"auto.offset.reset": "earliest"}

 - [x] Operating system:
Ubuntu
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The committed offset is the last processed message's offset + 1, so when you restart your consumer to start off from the last committed offset you will start reading at the first message produced after the one you've already processed.
If you want to re-read the same message you committed you should do `offset - 1` for your Assign call.
