### ISSUE TITLE
[Q] Best Practice for recovering from temporary errors

### ISSUE THREAD

**Issue by MrDHat** [confluentinc/confluent-kafka-go#185]
Description
===========
I have a consumer which listens to a topic, performs some computations and commits the message. Now, sometimes those computations fail temporarily and I do not commit the message. Now, as far as I know, that message won’t ever come back to the same consumer but I still want to process it, what is the recommended way of handling this?

**Comment by edenhill** [comment]
There are typically two ways you can do this:
 * Set `enable.auto.offset.store=false` and explicitly call StoreOffsets() after you've successfully processed a message. This prohibits the auto commiter from committing offsets you have not yet processed. The default is to store the offset of the message given to the application at the time the application reads, the stored offset is then committed automatically in the background according to `auto.commit.interval.ms`. By disabling the auto offset store you can control which offsets are committed. Do note that offset commits are like a water mark level, you don't commit individual messages but a watermark at where you will begin consuming if the consumer is restarted.
 * When message processing fails, forward the message to a dead-letter-box (e.g., a kafka topic) for later investigation or processing.

**Comment by JoshKCarroll** [comment]
This is helpful :) Thank you! This library is awesome, excited to integrate it for our use case. If we are processing say 50 messages in parallel in similar scenario as OP described (e.g. to amortize latency for some long running processing) and want to have highly reliable processing, presumably we would track each and confirm that all messages up to a water mark were successfully handled before calling StoreOffsets() as you described. Are you aware of any example code doing something like this we might be able to reference in implementation?

**Comment by edenhill** [comment]
Sorry for the long delay; but yeah, you will need to keep track of the watermark offset to commit per partition, as you describe, i.e., the highest consecutive offset that has been successfully processed.

I'm not aware of any generally available code doing that.
