### ISSUE TITLE
Readme does not reflect documented API 

### ISSUE THREAD

**Issue by trevorlinton** [confluentinc/confluent-kafka-go#190]
Description
===========
The readme shows an example here: https://github.com/confluentinc/confluent-kafka-go/blame/master/README.md#L61 that uses `c.ReadMessage(-1)` on the consumer which doesn't exist in the documented api here: https://docs.confluent.io/current/clients/confluent-kafka-go/index.html

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Those docs unfortunately did not make the last doc update.

You can use godoc.org for now: https://godoc.org/github.com/confluentinc/confluent-kafka-go/kafka#Consumer.ReadMessage
