### ISSUE TITLE
Paused partitions must be resumed after a rebalance

### ISSUE THREAD

**Issue by eliaslevy** [confluentinc/confluent-kafka-go#193]
Description
===========

Paused partition remain paused after a rebalance and one must call resume on during the `AssignedPartitions` event to resume consumption.  The documentation fails to mention this and it is unclear if this should be the expected behavior.  During the `RevokedPartitions` event all previous partition are revoked, thus the expectation is the the state of partitions when assigned is a fresh one.  Instead it seems to use the state it had before the revoke.

How to reproduce
================

Consume form a topic with some partitions.  Pause them.  Start another consumer.  Observe the first consumer no longer receives messages for the partitions it was assigned after the rebalance.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 721919 0.11.3
 - [x] Apache Kafka broker version: 0.11.0.0
 - [x] Client configuration: `ConfigMap{...}`
```
&kafka.ConfigMap{
		"bootstrap.servers":               s.conf.Kafka.Servers,
		"client.id":                       s.conf.Kafka.ClientId,
		"group.id":                        s.conf.Kafka.GroupId,
		"session.timeout.ms":              s.conf.Kafka.SessionTimeoutMs,
		"go.events.channel.enable":        true,
		"go.application.rebalance.enable": true,
		"enable.auto.commit":              false,
		"default.topic.config":            kafka.ConfigMap{"auto.offset.reset": s.conf.Kafka.DefaultOffsets},
		"statistics.interval.ms":          1000,
		"queued.min.messages":             100,
		"fetch.wait.max.ms":               1000,
		"queued.max.messages.kbytes":      1000000,
		"socket.keepalive.enable":         true,
		"socket.nagle.disable":            true,
		"log.connection.close":            false,
	})
```
 - [x] Operating system: CentoOS 7
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Good observation.

The reason the partitions remains paused across rebalances is that if the user does not handle the rebalances (but leave that to the client) it wouldn't want its partitions resumed spontanenously after an internally handled rebalance.
I would also say the same is true when the application handles the rebalance as well; the app paused the partitions for a reason and we should not make any assumptions on what that reason was or when it no longer holds true.
What do you think?

Either way, the documentation needs updating :+1:

**Comment by eliaslevy** [comment]
I understand the choice if the library is left to handle the rebalances.  But if the application takes charge, given that you first receive a revoke that supposedly revokes all previously assigned partitions, I would expect fresh state after partitions are reassigned.  Presumably an application could repause the partition during the assignment.

But either way, the docs needs updating.

**Comment by edenhill** [comment]
There is a fix for this in librdkafka (unpause branch) that unpauses (which is not resume, it simply clears the pause flag but does not resume fetching) whenever a partition is stopped (such as when re-assign()/unassign():ing).
It will not make it into the v0.11.5 release, but the other one after that.

**Comment by elizabethhong** [comment]
I don't quite understand the conclusion @edenhill in last message.

So will the topic_partition remain paused even after it is rebalanced to a different consumer? Will new consumer need to pause again and call resume to resume consuming or auto resumed?

Another question, can consumer resume topic_partition that it's not assigned to?

**Comment by edenhill** [comment]
@elizabethhong pause/resume is local to the consumer, it does not propagate to other consumers.

resuming partitions that are not paused will simply be ignored.

**Comment by messense** [comment]
Is this issue fixed in librdkafka?
