### ISSUE TITLE
Shutdown Kafka broker led to 5 mins resume publishing on the Conflurent-Go-client side

### ISSUE THREAD

**Issue by sheeysong** [confluentinc/confluent-kafka-go#196]
Description
===========
We had broker outage in PROD (1 broker was down out of 6 nodes).
Once restarted the broker, we observed the Conflurent-Go-client (ProducerChannel based) took 5 mins to resume publishing messages to the remote kafka server (remote Kafka cluster pub rate went back to normal after 5 mins, not right away)

Why didn't client know that broker was down and start to publishing messages to other alive nodes? how can I shorten this 5 mins window?
We have topic.metadata.refresh.interval.ms == 300000. Is this the correct parameters to tune?

How to reproduce
================
Publishing ACK=1 (leader Ack), replica=3. go.produce.channel.size=1000
use default message.timeout.ms=300000 (5 mins)
use topic.metadata.refresh.interval.ms = 300000.
shudtwon a node out of 6-node cluster, wait for 3 mins, and bring back on that dead node, then measure total remote kafka-cluster pub rate. It took 5 mins to get back to original pub rate.
It seems the client side has cached the dead node info and thinking it's still available to publish messages. 
This case happened to publish messages with/without key. 

Checklist
=========
Please provide the following information:

 - [ 0.11.0] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [1.0.1 ] Apache Kafka broker version:
 - [see above ] Client configuration: `ConfigMap{...}`
 - [Ubuntu 14.04.4 LTS ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
We use ProduceChannel() <- message, afetr queue full, it threw "queue is full" error as expected.
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you using librdkafka 0.11.0? If so, please upgrade to v0.11.4 (both librdkafka and Go client), there's been a number of producer retry fixes in v0.11.4

**Comment by sheeysong** [comment]
Thanks for the prompt response @edenhill , just check our Ubuntu again, we are using librdkafka 0.11.4.
Sorry about wrong version above.
We repeated twice shutdown (kill -9) a broker, consistently seeing 5 mins recover time on pub rate.

**Comment by sheeysong** [comment]
Hi @edenhill -- do you have any insights on this? This is the important feature for PROD, and the reality that we are facing in PROD on daily basis, I would like to make sure I get this right or the librdkafka does the right job.
Thank you very much!
~Jing

**Comment by sheeysong** [comment]
@edenhill -- what is this topic.metadata.refresh.interval.ms == 300000 for? what kinds of  topic.metadata? Does the Go-client or librdkafka has the cache in the process, when a node down, I expect the dead node shall be removed from the cache. Who will send the notification to the Go-client on node down? or the Go-client ping the brokers on a configurable interval?

**Comment by edenhill** [comment]
`topic.metadata.refresh.interval.ms` tells the client how often to refresh the cluster metadata, namely what brokers are available and which brokers are leaders for what partitions.

In case of error the client will refresh metadata at a faster interval to resume operation as soon as possible.
In your case it seems like it takes the cluster 5 minutes to make a new leader available, which is odd.
