### ISSUE TITLE
kafka.Message set/getTimestamp

### ISSUE THREAD

**Issue by vdepatla** [confluentinc/confluent-kafka-go#197]
Description
===========

I see kafka message as below.

// Message represents a Kafka message
type Message struct {
	TopicPartition TopicPartition
	Value          []byte
	Key            []byte
	Timestamp      time.Time
	TimestampType  TimestampType
	Opaque         interface{}
	Headers        []Header
}

I am using channel based producer, when producing a message can I set Timestamp and TimestampType ?  eg : 	msg := &kafka.Message{TopicPartition: tp, Value: content, Key: []byte(partitionKey), Timestamp: time.Now(), TimestampType: kafka.TimestampCreateTime}
	p.producer.ProduceChannel() <- msg

when I read delivery report from Events() channel, I am always getting back the time stamp of a message "as not available" how can I set timestamp of the message so when I read the message from Events() channel it is available ?

**Comment by edenhill** [comment]
`msg.Timestamp` is used (when-nonzero) in the Producer API (and channel), but the delivery report event does not expose the timestamp, it will always be unset there.
What is your use case for timestamps on delivery reports?

**Comment by vdepatla** [comment]
use case : trying to measure the time difference between writing a message to channel and receiving it (success or error delivery report).

**Comment by yxu-valleytider** [comment]
@edenhill  Just wonder if this issue will be fixed in the next release. We have a similar use case which could potentially benefit this.  

Thanks a lot.

**Comment by irfn** [comment]
@edenhill 
Use case: Trying to reconcile the messages which were produced vs the ones which are considered delivered to kafka(ones which are having a success delivery report).
Method: Use hash(m.K,m.V,m.Timestamp) to uniquely identify and reconcile with ones sent.

Any thoughts on this?

**Comment by edenhill** [comment]
Do note that timestamps are at millisecond precision, so they should not be considered unique in any way.

**Comment by irfn** [comment]
@edenhill started using `Opaque` for this purpose. Do you see any problems with that?

**Comment by edenhill** [comment]
@irfn That's what it is for, an application-specific per-message value/pointer.
