### ISSUE TITLE
librdkafka panic after PARTITION_LEAVE 3 times

### ISSUE THREAD

**Issue by shanipribadi** [confluentinc/confluent-kafka-go#199]
Description
===========
librdkafka panic with `*** ./rdkafka_queue.h:188:rd_kafka_q_destroy0: assert: rkq->rkq_refcnt > 0 ***` bringing down the app after multiple times being kicked out of the consumer group.
From the logs it seems to happen after 3 times PARTITION_LEAVE showing up.

I am using Consumer Group that loops using consumer.ReadMessage(time.Second)
I am consuming from 3 topics, each having 12 partitions.

When I consume from only 1 or 2 topics, librdkafka does not crash, regardless the number of time PARTITION_LEAVE happens.

How to reproduce
================
Consume using consumer.ReadMessage from 3 topics, with low enough session.timeout.ms
so that the consumer is kicked out of the group.
After 3 times being kicked out, it crashes.
(I'll try making a simpler test code to reproduce this)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 0.11.4
 - [x] Apache Kafka broker version: 1.0.0
 - [x] Client configuration: `ConfigMap{...}`
	config := &kafka.ConfigMap{
		"bootstrap.servers":              bootstrapServers,
		"group.id":                       groupID,
		"auto.offset.reset":              autoOffsetReset,
		"socket.keepalive.enable":        true,
		"api.version.request.timeout.ms": 10000,
		"session.timeout.ms":             6000,
		"heartbeat.interval.ms":          1000,
		"metadata.request.timeout.ms":    60000,
		"socket.timeout.ms":              60000,
		"api.version.request":            true,
		"enable.auto.commit":             true,
		"auto.commit.interval.ms":        1000,
		"default.topic.config":           kafka.ConfigMap{},
	}
 - [x] Operating system: Mac OS X Sieraa 10.13.4
 - [x] Provide client logs (with `"debug": ".."` as necessary) logs attached with debug: protocol,broker,cgrp
[panic.log](https://github.com/confluentinc/confluent-kafka-go/files/2074951/panic.log)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by shanipribadi** [comment]
[panic.log](https://github.com/confluentinc/confluent-kafka-go/files/2075777/panic.log)
```
package main

import (
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/confluentinc/confluent-kafka-go/kafka"
	"go.uber.org/zap"
)

type KafkaConsumer interface {
	Shutdown() error
	ReadMessage(time.Duration) (*kafka.Message, error)
}

type kafkaConsumer struct {
	logger   *zap.Logger
	consumer *kafka.Consumer
}

func NewKafkaConsumer(logger *zap.Logger, bootstrapServers string, groupID string, autoOffsetReset string, topics []string, debug string) (KafkaConsumer, error) {
	defer logger.Info("KafkaConsumer Initialized", zap.String("bootstrap_server", bootstrapServers), zap.String("group_id", groupID), zap.String("auto_offset_reset", autoOffsetReset), zap.Strings("topics", topics))
	config := &kafka.ConfigMap{
		"bootstrap.servers":              bootstrapServers,
		"group.id":                       groupID,
		"auto.offset.reset":              autoOffsetReset,
		"socket.keepalive.enable":        true,
		"api.version.request.timeout.ms": 10000,
		"session.timeout.ms":             6000,
		"heartbeat.interval.ms":          1000,
		"metadata.request.timeout.ms":    60000,
		"socket.timeout.ms":              60000,
		"api.version.request":            true,
		"enable.auto.commit":             true,
		"auto.commit.interval.ms":        1000,
		"default.topic.config":           kafka.ConfigMap{},
	}
	if debug != "" {
		config.SetKey("debug", debug)
	}
	c, err := kafka.NewConsumer(config)
	if err != nil {
		return nil, err
	}
	err = c.SubscribeTopics(topics, nil)
	if err != nil {
		return nil, err
	}

	return &kafkaConsumer{
		logger:   logger,
		consumer: c,
	}, nil

}

func (c *kafkaConsumer) Shutdown() error {
	c.logger.Info("Shutting Down KafkaConsumer")
	defer c.logger.Info("KafkaConsumer Done")
	return c.consumer.Close()
}

func (c *kafkaConsumer) ReadMessage(timeout time.Duration) (*kafka.Message, error) {
	m, err := c.consumer.ReadMessage(timeout)
	if err != nil {
		if m == nil {
			if kerr, ok := err.(kafka.Error); ok {
				if kerr.Code() == kafka.ErrTimedOut {
					return nil, nil
				}
			}
			c.logger.Error("error consuming message", zap.Error(err))
		} else {
			c.logger.Error("error consuming message from partition", zap.Error(err), zap.NamedError("topic_partition", m.TopicPartition.Error))
		}
		return nil, err
	}
	return m, nil
}
 
func main() {
	logger, _ := zap.NewDevelopment()
	groupID := "bi-shani"

	bootstrapServers := "p-mainstream-mirror-kafka-a-01:6667"
	topics := []string{"GO_RIDE-booking-log","GO_CAR-booking-log", "GO_BIRD_COMBO-booking-log"}

	// topics := []string{"xx1", "xx2", "xx3"}
	// bootstrapServers := "localhost:9092"

	c, err := NewKafkaConsumer(logger, bootstrapServers, groupID, "latest", topics, "protocol,broker,cgrp")
	if err != nil {
		panic(err)
	}


	done := make(chan struct{})
	go func() {
		sig := make(chan os.Signal, 1)
		signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
		<-sig
		done <- struct{}{}
	}()

	for {
		select {
			case <-done:
				c.Shutdown()
				return
			default:
				c.ReadMessage(time.Second)
				time.Sleep(time.Millisecond * 500)
		}
	}
}
```

Source code to reproduce the issue, including the log for the crash produced by it.
This time it only took 2 PARTITION_LEAVE before crashing

**Comment by shanipribadi** [comment]
I am able to reproduce the above against a local broker by using https://github.com/sitespeedio/throttle to simulate slow network

throttle  --rtt 300 --up 100 --down 100

and then running the go program
while producing some random message to the topic
```
➜  py cat kk.py
import time
while True:
    print("hello world lalalalalalala isuhfdsofijdsofisjfosijfs ofijs fosijf soidj doijsdo ijdoasidjad")
    time.sleep(0.05)

➜  py python3 kk.py | kafkacat -P -b localhost:9092 -t xx1
```

**Comment by earthelf** [comment]
Any progress now?

**Comment by edenhill** [comment]
Sorry for the enormous delay, we completely missed this issue.

Please try to reproduce this on v1.0.0 and we shall look into a fix if it is still occurs.

Thanks
