### ISSUE TITLE
Is it possible to set per-topic config variables?

### ISSUE THREAD

**Issue by grantr** [confluentinc/confluent-kafka-go#20]
I see that it's possible to set default config for topics using the config key `default.topic.config`, but is it possible to set non-default config for specific topics?

**Comment by mhowlett** [comment]
In librdkafka it's possible to set config per topic, however it looks to me like this capability has not been exposed in the go client (doing a search for rd_kafka_topic_new gives one result: https://github.com/confluentinc/confluent-kafka-go/blob/53f5291b979f88d58fce124c84fc84b42ad226b2/kafka/handle.go#L123 which sets the conf parameter to null). @edenhill ?

Interested in your use case for this.

**Comment by edenhill** [comment]
@mhowlett You're right, we decided to not implement per-topic configuration to keep the complexity down, the default topic config is sufficient for most use cases.

I'm also curious on @grantr's use case.

What I've been thinking of is exposing per topic configuration pretty much the same way the defualt topic config is done, something like:
```
 conf = ConfigMap{ "bootstrap.servers": my_brokers,
                               "default.topic.config": &ConfigMap{"acks": "all"},
                               "topic.config": &ConfigMap{"my_special_topic": &ConfigMap{"acks": 1} } }
```

(A lot of config maps in there)

**Comment by grantr** [comment]
My use case is exploratory, so nothing concrete yet. I'm implementing a producer proxy that might need to configure topics with varying reliability and performance goals. If per-topic config isn't available, I could probably start separate kafka clients for each unique topic config (unless multiple clients in a process is discouraged).

**Comment by edenhill** [comment]
Even if you would be able to specify per-topic configuration, the underlying C library doesn't currently allow changing topic configuration after its first use, so you would still need to create new Producers if a topic's config was to change.

**Comment by grantr** [comment]
Sorry, *varying* was the wrong word; I meant *different*. Dynamically changing topic configuration after client creation isn't a use case. Creating a single client with different (though not variable) behavior for multiple topics is.

**Comment by edenhill** [comment]
@grantr Did your exploratory endeavours lead you to a conclusion in regards to this issue? Is topic-specific configuration still a feature you would like to see?

**Comment by grantr** [comment]
@edenhill the project was delayed, so I don't have any concrete evidence that this feature is required.

Intuitively, it seems that that the number of topic configurations for a single cluster would be relatively small, making the multiple client approach mentioned in https://github.com/confluentinc/confluent-kafka-go/issues/20#issuecomment-266109198 a reasonable workaround.

**Comment by edenhill** [comment]
Thanks @grantr, I'll close this issue for now. Reopen if a use-case emerges
