### ISSUE TITLE
Producer : set key.serializer and value.serializer 

### ISSUE THREAD

**Issue by vdepatla** [confluentinc/confluent-kafka-go#204]
Description
===========
Question : Wondering what are key.serializer and value.serializer values set to when publishing message to kafka ? Are they set in librdkafka  ? how I can check ? I see in java client for example these can be set explicitly     props.put("key.serializer",
            "org.apache.kafka.common.serialization.StringSerializer");
    props.put("value.serializer",
            "org.apache.kafka.common.serialization.ByteArraySerializer");

type Message struct {

    TopicPartition TopicPartition

    Value []byte

    Key []byte

    Timestamp time.Time

    TimestampType TimestampType

    Opaque interface{}

    Headers []Header

}

**Comment by edenhill** [comment]
There's currently no serializer interface in the Go client, we're aiming to release serializers, avro and schema-registry support in Q3.

**Comment by keshavmaheshwari** [comment]
Is this functionality release ?
