### ISSUE TITLE
Detect Brokers down with out producing message - Question

### ISSUE THREAD

**Issue by vdepatla** [confluentinc/confluent-kafka-go#205]
How can detect brokers down with out producing a message ? I see in my local testing I get below when brokers are down on stdout

%3|1529024523.005|ERROR|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: 1/1 brokers are down

How can catch this in code ?

Reading from here : https://github.com/edenhill/librdkafka/wiki/Error-handling, 
https://github.com/edenhill/librdkafka/wiki/Error-handling,https://github.com/confluentinc/confluent-

1. **global errors, e.g., all brokers down, are passed to the error_cb callback, you need to call rd_kafka_poll() regularly to receive them (e.g. RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN).** 

I don't see a Poll() in go client .. is there an equivalent to cheive this ?

2. In here  https://github.com/confluentinc/confluent-kafka-go/issues/58 you mentioned this **"If your application really needs to do something when all brokers are down (or unable to connect to), then you can check for Error events with the code set to ErrAllBrokersDown,"**

Currently I read from Events() channel for topic partition errors, does ErrAllBrokersDown events gets sent to the same channel or it its something different ?

**Comment by edenhill** [comment]
You should see a kafka.Error event on the Events() channel with the error code set to ErrAllBrokersDown.

**Comment by vdepatla** [comment]
I am reading through  producer.Events() channel but I am not receiving kafka.Error events, Is there some configuration that need to be set ? 

This also seem to be similar issue https://github.com/confluentinc/confluent-kafka-go/issues/200

**Comment by edenhill** [comment]
Oh yes, you are right, the error events are Not exposed on the events channel, this needs to be fixed.

**Comment by edenhill** [comment]
Dup of #200
