### ISSUE TITLE
Go get security error

### ISSUE THREAD

**Issue by learner4** [confluentinc/confluent-kafka-go#207]
Description
===========
Getting an error on go get -u command
On windows 7 
Fatal: UriFormatException encountered.
 actualUrl
Fatal: unable to access 'https:...
InitializeSecurityContext failed: SEC_E_INTERNALERROR (x80090304) - the local security authority cannot be contacted
Package GitHub.com/confluentinc/confluent-kafka-go/Kafka : exit status 128

How to reproduce
================
Run go get -u command 

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: windows
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This looks like a Go tooling problem not related to the Go client.
