### ISSUE TITLE
Can I intercept logs?

### ISSUE THREAD

**Issue by grantr** [confluentinc/confluent-kafka-go#21]
Log messages from librdkafka seem to go directly to stdout. Is it possible to intercept these? Seems like librdkafka provides `log_cb` for this purpose.

**Comment by ewencp** [comment]
@grantr The log callback hasn't been exposed yet. It would definitely be a welcome addition (as would, e.g., `error_cb` and friends.

**Comment by edenhill** [comment]
What we'll probably do is expose logs as events on the Events channel.

**Comment by edenhill** [comment]
There is now support for event-based logs in librdkafka.

**Comment by edenhill** [comment]
Dup of #54 or vice versa
