### ISSUE TITLE
Kafka library interferes with Stdin

### ISSUE THREAD

**Issue by michihenning** [confluentinc/confluent-kafka-go#213]
Description
===========
It seems that the Kafka library interferes with standard input. Specifically, `bufio.Scanner.Scan()` blocks indefinitely on a closed file descriptor if the library is used, but correctly returns an error otherwise. I'm seeing this while Kafka isn't even running.

How to reproduce
================

Below is a simple test program that uses `Scan()`. Run the code from bash with

`./testprog 0<&-`

This runs `testprog` with standard input closed. The output is exactly as expected:

```
Scan() returned false
read /dev/stdin: bad file descriptor
```

Now uncomment the commented sections and try again. With that change, the output is:
```
version: 0.11.5-PRE5-12-g310c55
```
and the code blocks in the call to `Scan()`.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 0.11.5-PRE5-12-g310c55
 - [ ] Apache Kafka broker version: No broker running
 - [ ] Operating system: Ubuntu 16.04

Code
====

```go
package main

import (
    "bufio"
    "fmt"
    //"github.com/confluentinc/confluent-kafka-go/kafka"
    "os"
)

func main() {
    /*
    _, version := kafka.LibraryVersion()
    fmt.Println("version:", version)
    */

    lineReader := bufio.NewScanner(os.Stdin)
    if ok := lineReader.Scan(); ok {
        msg := lineReader.Text()
        fmt.Println("msg:", msg)
    } else {
        fmt.Println("Scan() returned false")
        err := lineReader.Err()
        if err != nil {
            fmt.Fprintln(os.Stderr, err)
            os.Exit(1)
        }
        fmt.Println("EOF")
    }
}
```

**Comment by edenhill** [comment]
Works for me with Golang 1.10.1
```
$ ./test 0<&-
version: 0.11.5-RC1
Scan() returned false
read /dev/stdin: bad file descriptor
```

**Comment by michihenning** [comment]
Thank you for checking! It turns out that this was caused by an older version of confluent-kafka-go in our repo. With the current master from github, it works just fine.
