### ISSUE TITLE
Question - when to call producer.Flush()

### ISSUE THREAD

**Issue by vdepatla** [confluentinc/confluent-kafka-go#216]
I am producing messages continuously(channel based producer) in one go routine, and listening on delivery reports in another go routine.  

Do I need to call Flush() after each message ? (does librdkadka internally uses flush after every batch?) is it recommended/more performant to call Flush() at regular intervals while producing ? or only if we need to know outstanding messages on a producer before close?
 
I see below for eventPoll 
// eventPoll polls an event from the handler's C rd_kafka_queue_t,
// translates it into an Event type and then sends on `channel` if non-nil, else returns the Event.

what does rd_kafka_queue_t contain ? does it contain the events sent out from producerChannel but not yet acknowledged  ?

**Comment by mhowlett** [comment]
`eventPoll` provides information (the delivery report) on prior produce requests as soon as their success/failure is known (possibly after a number of retries, as managed by librdkafka).

`Flush` should not be called regularly. it blocks until the delivery report corresponding to all produce requests has been delivered to your application or until the timeout has elapsed. It's not used internally. You should typically call it prior to closing your producer to ensure all in-flight messages are delivered (or have resulted in a non-retryable error).
