### ISSUE TITLE
Unable to get Stats Info

### ISSUE THREAD

**Issue by analog76** [confluentinc/confluent-kafka-go#217]
Description
===========
I am trying to print metrics info of Kafka producer but I am unable to print. 
I am not sure if I am missing any configuration? I don't see stats information are printed. But I can see the Kafka.message event being printed on the console.

My code looks like this
```

Config :
        "statistics.interval.ms":"1000"


        
func sendMessage(message *kafka.Message) {
 	doneChan := make(chan kafka.Event)
 
	err := ProducerConn.Produce(message, doneChan)
	if err != nil {
		logger.Logger.Println(" unable to deliver the message  ", err)
	}
 	
 	go handleCallback(doneChan) 
}
 


func handleCallback(callbackChannel chan kafka.Event) {
	defer close(callbackChannel) 
	for ev := range callbackChannel {
		switch e := ev.(type) {
		case *kafka.Stats:
			logger.Logger.Println("Stats: ", e) 
		case *kafka.Message:
			if e.TopicPartition.Error != nil {
				logger.Logger.Println(" unable to handle the request ", e.TopicPartition.Error) 
			} else { 
					logger.Logger.Printf("Delivered message to topic %s [%d] at offset %v\n",
						*e.TopicPartition.Topic, e.TopicPartition.Partition,
						e.TopicPartition.Offset) 
			}
		default:
			logger.Logger.Println("Ignored event: ", e)
		}
	}

}
```

How to reproduce
================
I follow the instruction as per this ticket https://github.com/confluentinc/confluent-kafka-go/issues/174.  I couldn't get the stats info.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): - 0.11.4
 - [ ] Apache Kafka broker version: 1.0.0
 - [ ] Client configuration: `ConfigMap{...}` 
        "statistics.interval.ms":"1000"

 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
take a look at this test as an example of getting the stats events: https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/stats_event_test.go

**Comment by analog76** [comment]
Thanks @mhowlett . I am able to get this printed out.


```
func A(){
....
go handleStatsCallback(ProducerConn.Events())
producerConn.producer(message)
}


func handleStatsCallback(eventCh chan kafka.Event) {
	for ev := range eventCh {
		switch e := ev.(type) {
		case *kafka.Stats:
			logger.Logger.Println("Stats: %v", e)
		default:
			logger.Logger.Println("Ignored event 1 : %v", e.String)
		}
	}
}

```

In the example, Does the goroutine called for every message but Stats gets printed out based on "statistics.interval.ms"configuration?

Say for an example, I have Stats.interval is set as 1s but during that time, I have 100K requests then that goroutine will be called 100K times?

**Comment by mhowlett** [comment]
the goroutine will be called only once a second.
