### ISSUE TITLE
Duplicate symbol errors when importing confluent-kafka-go in main package and in imported package

### ISSUE THREAD

**Issue by minitauros** [confluentinc/confluent-kafka-go#221]
Description
===========
As asked [here](https://stackoverflow.com/questions/51880026/duplicate-symbol-errors-when-running-go-run-main-go-when-using-kafka-with-librdk), I am getting "duplicate symbol" errors when running main.go (`go run main.go`). Inside my main project I import confluent-kafka-go, and inside one of the libraries I import (an external library owned by myself) I also import confluent-kafka-go (this external library contains some util methods for working with your library).

When I copy the external library (the one owned by myself) to my main project, nothing goes wrong, which leads me to believe that the Go compiler detects in both projects (both the main and the imported one) that confluent-kafka-go is imported, and therefore imports the librdkafka C libraries twice.

I was wondering if you have any advice on the situation and/or how to fix/prevent it.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): latest and 0.11.4
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: macOS
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Is this still an issue?

**Comment by minitauros** [comment]
I do not know. We resolved the issue by not importing confluent-kafka-go in both the project and the imported library; everything now comes from the imported library. That did fix the problem.

If you want to close this issue, that would be fine by me.

**Comment by edenhill** [comment]
Thanks for the update

**Comment by ahawtho** [comment]
Leaving this here in case someone searches for it: we received this same message after we upgraded from the original `gopkg.in/confluentinc/confluent-kafka-go.v1` to `github.com/confluentinc/confluent-kafka-go/kafka` . We had both packages in our `go.mod` file because of a stray reference to the old module in one of our source files.
