### ISSUE TITLE
Multiple clients loose data.

### ISSUE THREAD

**Issue by ctrix** [confluentinc/confluent-kafka-go#228]
Description
===========

I have a few microservices running reading from a topic. The microservices run forever and store the data into a database. In the meanwhile, i log the number of items processed per second.

I have, at the same time, a chart that shows a comparison of the data entering the topic and the data retrieved by the microservices.

What happens is that, after a few hours, the data out of kafka are less than the injected records.

Stopping the microservices and restarting them seems generates a big spike on the client side (so the data were in kafka and are being processed again). The process starts working as expected and after a few hours it starts to lag again.

I've tried to look at the ccurrent issues. Can it be related at some auto-pause without a resume of some consumers on some partitions ?

How to reproduce
================

I don't exactly know how to reproduce. My logs do not say anything peculiar.
The code is quite simple, and it's taken from the examples.
I've tried with the Events() API and now i'm using the Poll() API. Both of them show the same issue.

`go

    c.reader, _ = kafka.NewConsumer(&kafka.ConfigMap{
        "bootstrap.servers":  c.Brokers,
        "group.id":           c.GroupID,
        "session.timeout.ms": 6000,
        "auto.offset.reset": "earliest",
        "fetch.error.backoff.ms": "500",
        "compression.codec": "lz4",
    })

    c.reader.SubscribeTopics([]string{ c.Topic }, nil)
`

`go

    sigchan := make(chan os.Signal, 1)
    signal.Notify(sigchan, syscall.SIGINT, syscall.SIGTERM)

    run := true

    for run == true {
        select {
            case sig := <-sigchan:
                log.Printf("Caught signal %v: terminating\n", sig)
                run = false
                c.stopped = 1
            default:
                ev := c.reader.Poll(100)
                if ev == nil {
                    continue
                }

                switch e := ev.(type) {
                    case *kafka.Message:
                        //log.Printf("%% Message on %s:\n%s\n", e.TopicPartition, string(e.Value))
                        c.out <- string(e.Value);
                        /*
                        if e.Headers != nil {
                            log.Printf("%% Headers: %v\n", e.Headers)
                        }
                        */
                    case kafka.PartitionEOF:
                        log.Printf("%% Reached %v\n", e)
                    case kafka.Error:
                        log.Printf("%% Error: %v\n", e)
                        run = false
                    default:
                        log.Printf("Ignored %v\n", e)
                        c.stopped = 1
            }
        }
    }
`

ADDITIONAL NOTES
===============

I have another consumer group of microservices that read from the same topic and store data elsewhere. The code, in this case, is pure C, using rdkafka (same version, same server, same library).

In this case i do not notice any issue.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):

confluent-kafka-go.              latest fetch from github
librdkafka1:amd64                 0.11.5-1~bpo9+1

 - [x] Apache Kafka broker version:
kafka                           2.0.0-0~mc1

 - [x] Client configuration: `ConfigMap{...}`
(see code)

 - [x] Operating system: Debian Stretch

 - [ ] Provide client logs (with `"debug": ".."` as necessary)
None relevant.

 - [ ] Provide broker log excerpts
None relevant

 - [X] Critical issue

**Comment by ctrix** [comment]
Update: it seems that the problem happens only (or mainly) when the code is dockerized. I've not yet seen this happen while running a few consumers in screen sessions.

This brings me to some signal being filtered by docker ?

**Comment by mhowlett** [comment]
you would expect all records to be re-read on restart since you are not committing offsets and the `auto.offset.reset` property is set to `earliest`.

when the problem is occurring, are you seeing PatitionEOFs?, errors?

'filtering' due to use of docker won't explain your problem I don't think.

it would be interesting to compare the offset associated with the retrieved messages and the offset in the delivery reports created on message production (I believe on the golang client they should both be available). also check for errors on production.
