### ISSUE TITLE
create multiple consumers for same topic

### ISSUE THREAD

**Issue by CKFVL** [confluentinc/confluent-kafka-go#230]
Description
===========
How to create multiple consumers for kafka topic in go lang?
Any example provided to get an overview of running multiple consumers in a consumer group for the same topic?

How to reproduce
================

confluent-kafka-go and librdkafka version (LibraryVersion()):
 Apache Kafka broker version:
 Client configuration: ConfigMap{...}
 Operating system:
 Provide client logs (with "debug": ".." as necessary)
 Provide broker log excerpts
 Critical issue

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by CKFVL** [comment]
Any consumer factory (to generate N consumers) available in confluent-kafka to read same topic (with partitions)?

**Comment by edenhill** [comment]
There is no such factory.

Why do you need multiple consumers and not one?

**Comment by CKFVL** [comment]
I want to see how it works with multiple consumers (*in one consumer group) reading from different partitions of same topic. 

@edenhill  Just out of cusriosity, will there be any issues creating multiple consumers for the same topic?

**Comment by edenhill** [comment]
The partitions will be balanced among the consumers in the group, it will work fine.

**Comment by zanderwong** [comment]
There’s a reference implementation for this architecture based on decades of hard won experience with high performance distributed systems, called the Kafka Consumer Group.  This reference implementation is shipped with Apache Kafka as a JAR and is well documented, although it is possible to implement a Consumer Group application in any language.

**Comment by edenhill** [comment]
confluent-kafka-go implements the balanced Kafka consumer groups.
