### ISSUE TITLE
How can I install older version of go?

### ISSUE THREAD

**Issue by kparadkar** [confluentinc/confluent-kafka-go#232]
We are at older version of librdkafka and need to install go on top of it.
'go get' command mentioned installs from the master which needs symbols introduced in later versions of librdkafka. 

I am aware of the other way which is cloning the source and doing checkout of older branch and manually building (also if you could clarify the exact steps to build).

But is there any way I can provide 'tag-id' or 'branch' to the go install something like 'go get -u <repo> <tag>'

**Comment by kparadkar** [comment]
https://gopkg.in/confluentinc/confluent-kafka-go.v0/kafka has v0 which points to the latest version on go. Is there any way to get the older rev? What are the build instruction to build from source (so that I can build older version)?

**Comment by rnpridgeon** [comment]
I recommend migrating to dep for package management. 

https://github.com/golang/dep

Run `dep init` from your projects root directory to set up the initial manifest. For larger projects this may take some time. Once it completes edit the constraint for `confluent-kafka-go` in your Gopkg.toml with the desired version number. 

```
[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "=0.11.0"
```

Then execute `dep ensure` to update your Gopkg.lock file. Lastly execute `dep status` to verify the contents. 

```
dep status
PROJECT                                     CONSTRAINT  VERSION  REVISION  LATEST   PKGS USED
github.com/confluentinc/confluent-kafka-go  0.11.0      v0.11.0  f696f02   v0.11.0  1
```
