### ISSUE TITLE
not remove lag in topic

### ISSUE THREAD

**Issue by myskbj** [confluentinc/confluent-kafka-go#233]
Description
===========

We have used the [exmple code](https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/consumer_example/consumer_example.go) to write test code to consuming specific topics. (The topic has 10 partitions in total)
Then, we checked and output the returned message. However, the lag of the imported topic still remains unchanged. I do not know why.

How to reproduce
================
```
import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/confluentinc/confluent-kafka-go/kafka"
	"github.com/vmihailenco/msgpack"
)

const bootstrapServers = "server1,server2"

func subscribe(servers, groupId string, topics []string) {

	sigchan := make(chan os.Signal, 1)
	signal.Notify(sigchan, syscall.SIGINT, syscall.SIGTERM)

	c, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers": servers,
		"group.id":          groupId,
		"auto.offset.reset": "earliest",
	})
	if err != nil {
		logger1.Fatalln(err)
	}

	c.SubscribeTopics(topics, nil)
	defer c.Close()

	run := true
	for run == true {
		select {
		case sig := <-sigchan:
			logger1.Println("Caught signal", sig, " terminating")
			run = false
		default:
			ev := c.Poll(100)
			if ev == nil {
				continue
			}
			switch e := ev.(type) {
			case *kafka.Message:
				valueMap := make(map[string]interface{}, 0)
				err = msgpack.Unmarshal(e.Value, &valueMap)
				if err != nil {
					logger1.Println(err)
				}
				log.Println(valueMap)
			case kafka.AssignedPartitions:
				log.Println(e.Partitions)
			case kafka.PartitionEOF:
				log.Println(e)
			case kafka.Error:
				log.Println(e)
			default:
			}
		}
	}
	os.Exit(10)
}

```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Hello @myskbj, 

Just to ensure I understand you correctly your saying that you can see the consumer consuming messages; Perhaps by monitoring stdout or some other mechanism. After confirming that the consumers that make up the group identified by `groupId` you are finding that lag is being incorrectly reported. 

If you could please confirm the following: 
1. How are you measure/monitoring lag
2. Reproduce this behavior this time with `debug: "consumer, cgrp, topic, fetch"`; provide the resulting output.
