### ISSUE TITLE
Creating new topic

### ISSUE THREAD

**Issue by ldrrp** [confluentinc/confluent-kafka-go#234]
Description
===========

Creating new topic with non-Default settings.

How to reproduce
================

I want to make a topic to store a custom consumer settings in kafka. But i want 50 replication and 1 partition. My default kafka settings are 3 replication and 48 partitions. I want anyone to use this code without having to make the topics manually before running my consumer.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): NA
 - [ ] Apache Kafka broker version: NA
 - [ ] Client configuration: `ConfigMap{...}`  NA
 - [ ] Operating system: NA
 - [ ] Provide client logs (with `"debug": ".."` as necessary) NA
 - [ ] Provide broker log excerpts NA
 - [ ] Critical issue NA

**Comment by rnpridgeon** [comment]
There is a PR currently under review to add Topic Admin functionality to the golang client but it has not yet been merged.

https://github.com/confluentinc/confluent-kafka-go/pull/173

In the interim you will need to use the tooling which ships with Kafka. 

https://kafka.apache.org/documentation/#quickstart_createtopic

**Comment by dbudworth** [comment]
Anyone have a sense as to when this may get merged in?  Looks like there's a bunch of back and forth on it, but nothing since Aug 7

not having admin support means we have to use sarama along side this driver so we can create our topics on the fly.

**Comment by edenhill** [comment]
@dbudworth Within a week, there is just a bit of API renaming left to get it accepted (the Java API uses NewTopic, etc, for types, which doesn't rhyme well with Golang)

**Comment by edenhill** [comment]
Dup of #76
