### ISSUE TITLE
Kafka NewConsumer keeps looping over SASL authentication faliure if you provide incorrect credentials

### ISSUE THREAD

**Issue by amikar** [confluentinc/confluent-kafka-go#236]
Description
===========
I made a consumer to connect to the topics and be able to read through the kafka messages. The sasl.username , sasl.password and group.id are some of the fields that are taken as user input from a form.
If the user provides the right information the kafka starts a scheduler to keep fetching from the topic every 20 seconds. And upon giving credentials that isn't authenticated I would like to let the user know the authentication wasn't successful. 
Problem is there doesn't seem a way to find out if the servers authentication failed. 

How to reproduce
================

kafkaInputs.GroupId:= user entered groupid
kafkaInputs.KafkaUsername:= user entered KafkaUsername
kafkaInputs.KafkaPassword:= user entered KafkaPassword

hou9, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers": "random-server",
		"security.protocol":"SASL_SSL",
		"sasl.mechanism":"SCRAM-SHA-512",
		"group.id":kafkaInputs.GroupId,
		"sasl.username":kafkaInputs.KafkaUsername, 
		"sasl.password":kafkaInputs.KafkaPassword,
	})
if err != nil{
	log.Printf("Error at creating Kafka Consumer %s" ,  err)
	return
}

the err == nil even when the three information entered are wrong. 
Subscribing to the topic or not doesn't affect the looping.

Log info:
%3|1539814774.871|ERROR|rdkafka#consumer-2| [thrd:sasl_ssl://random-server]: sasl_ssl:random-server: SASL authentication failure: Disconnected: check client SCRAM-SHA-512 credentials and broker logs (after 135ms in state AUTH)
%3|1539814774.871|ERROR|rdkafka#consumer-2| [thrd:sasl_ssl://random-server]: 1/1 brokers are down

//Sorry if there is something I am missing here. I have just started with kafka

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by amikar** [comment]
Also, if I provide the right credentials there doesn't seem to be a problem.

**Comment by edenhill** [comment]
You should get an kafka.Error event on the Events() channel with the code set to ErrAuthentication

**Comment by amikar** [comment]
upon adding the function

`func handleStatsEvent(hou4 *kafka.Consumer, statsReceived chan bool) {
	log.Printf("handling stats 3")

	for ev := range hou4.Events() {
		switch e := ev.(type) {
			case *kafka.Error:
				log.Printf("handling stats 4")
				log.Printf("Stats: %v", e)
				close(statsReceived)
				return
		}

		}
	}`
 
and adding this to the main 

`	statsRecieved := make(chan bool)
	log.Printf("handling stats")
	go handleStatsEvent(hou4, statsRecieved)`

I never hit "handling stats 4" with the code. 

updated contents of the configmap 

           `"bootstrap.servers": "some server",
		"security.protocol":"SASL_SSL",
		"sasl.mechanism":"SCRAM-SHA-512",
		"group.id":kafkaInputs.GroupId,
		"sasl.username":kafkaInputs.KafkaUsername, 
		"sasl.password":kafkaInputs.KafkaPassword,
		"go.events.channel.enable": true,
		 "statistics.interval.ms":50,
		"go.application.rebalance.enable": true,
		"default.topic.config":  kafka.ConfigMap{"auto.offset.reset": "earliest"},`

**Comment by edenhill** [comment]
What version are you on? Error events require a master version after jun 15 (5690c413c27721cca1a9665fd359942897c7d9ef)

**Comment by amikar** [comment]
librdkafka v0.11.6

I seem to have the newest one 
  revision = "5e4d04e05fc319ce5996a867aafef29059f26862"
  version = "v0.11.4"

**Comment by amikar** [comment]
Thanks! I saw it was the right version and assumed I had the latest pull. 
All good now
