### ISSUE TITLE
Connection Drop

### ISSUE THREAD

**Issue by bshafiee** [confluentinc/confluent-kafka-go#237]
Description
===========
I have an application which has a librdkafka consumer and producer. Often time I see the following errors in the logs: 
```Erro Producer: ssl://***.com:9093/0: Disconnected (after 600003ms in state UP)```
and
```
 Error Consumer: ssl://***.com:9093/39: Disconnected (after 1200394ms in state UP)
```
Here is my consumer configs: 

```consumer, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers":        brokers,
		"group.id":                 "my-consumer-group",
		"client.id":                "my_client",
		"enable.auto.commit":       "true",  
		"auto.commit.interval.ms":  "100",
		"enable.auto.offset.store": "false",
		"api.version.request":      "true",  
		"default.topic.config": kafka.ConfigMap{
			"auto.offset.reset": "earliest",
		},
		"socket.keepalive.enable":  "true",
		"compression.codec":        "snappy",
		"security.protocol":        "ssl",
		"ssl.certificate.location": os.Getenv("KAFKA_CLIENT_CERT"),
		"ssl.key.location":         os.Getenv("KAFKA_CLIENT_KEY"),
		"ssl.ca.location":          "/etc/ssl/cert.pem",
	})
```

and my producer:

```
producer, err := kafka.NewProducer(&kafka.ConfigMap{
		"bootstrap.servers":   "brokers",
		"client.id":           "producer_client",
		"api.version.request": "true", 
		"default.topic.config": kafka.ConfigMap{
			"acks":        "all",
			"partitioner": "murmur2_random", 
		},
		"socket.keepalive.enable":  "true",
		"message.send.max.retries": "100", 
		"compression.codec":        "snappy",
		"security.protocol":        "ssl",
		"ssl.certificate.location": os.Getenv("KAFKA_CLOUD_AGGREGATE_CLIENT_CERT"),
		"ssl.key.location":         os.Getenv("KAFKA_CLOUD_AGGREGATE_CLIENT_KEY"),
		"ssl.ca.location":          "/etc/ssl/cert.pem",
	})
```

I checked the broker logs and couldn't find anything! so somehow the client drops the connection silently :(

Is there any debug flag I can turn on on the client to see why it's dropping the connection? BTW, both consumer and producers are almost constantly fully utilized at about 40-50K msg/sec. 

How to reproduce
================
I see them regularly every 10 or minutes which happen to be the default socket timeout too (60k sec). I did set `socket.keepalive.enable` to true and really can't think of anything else 😛

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
master branch for both go and librdkafka C
 - [x] Apache Kafka broker version:
2.0.0
 - [x] Client configuration: `ConfigMap{...}`
provided
 - [x] Operating system:
alpine linux docker image
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [x] Provide broker log excerpts
Nothing
 - [x] Critical issue

**Comment by edenhill** [comment]
It could be the connection idle reaper on the broker or load balancer:
https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected

**Comment by bshafiee** [comment]
Thank you so much for quick response @edenhill. And apologies for my ignorance and not checking the FAQ first. I will try to see if I can ask our Kafka maintenance team to change `connections.max.idle.ms` and see if makes any difference (since there is really no loadbalancer in between). Meanwhile, maybe I try to reduce the `jitter` so at least it will reconnect faster.

**Comment by bshafiee** [comment]
> Are you sure these disconnects actually trigger a rebalance?

Yes, I have several metrics and logs when rebalances happen, all all periodically and when disconnects happen. 

This in fact has a significant adverse effect on my application. My loop is like:
```
msgs := Consumer.poll()
process(msgs)
Procuder.produce(msgs)
OnSuccessfulDeliver(msg)-->Consumer.markDone(msg)
OnFailureDelivery(msgs)-->Consumer.Rebalance() or Consumer.Seekback()
```
The disconnect in consumer is fine since it just triggers a rebalance and the app carries on, but the disconnect in producer will invalidate everything in queue and inflight and in-order to reprocess those I have to reset the offset (via rebalance, since current consumer group pointer just keeps moving) or seek-back. Both of these means way more duplicates that necessary. 

I rewrote the very same loop with  Sarama client and the same brokers, and it doesn't drop the connection. I will try with debug on to get more information.

**Comment by edenhill** [comment]
It would be useful with debug logs (`debug=broker,cgrp`) to understand what is going on here.

**Comment by bshafiee** [comment]
I'm on vacation and will run it with with debug flags on when I am back.

**Comment by aravish** [comment]
Were you able to fix this problem, I have a similar case where there are disconnects after 15 minutes
