### ISSUE TITLE
Do you have a TLS and username/password authentication?

### ISSUE THREAD

**Issue by didip** [confluentinc/confluent-kafka-go#243]
Description
===========

I couldn't find an example on how to connect securely to Kafka using this client.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

I have not installed dependencies yet. I am just reading documentations for now.

**Comment by rnpridgeon** [comment]
It's not clear if you are looking to enable TLS for wire encryption, or you wish to use TLS for both wire encryption and client authentication. Please provide additional information on what it is you are trying to achieve so we can better assist you. 

In the meantime the following links should prove useful: 

Enabling TLS: https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka
Enabling SASL Mechanisms(Authentication): https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

**Comment by didip** [comment]
Thanks for the quick reply, it's for both wire encryption and client authentication.
