### ISSUE TITLE
How to install the librdkafka.redist on windows?

### ISSUE THREAD

**Issue by marcofranssen** [confluentinc/confluent-kafka-go#244]
I'm trying to install the `librdkafka.redist` package on Windows 10.

I'm working on a golang program which doesn't compile atm as it is missing the `librdkafka.redist`.

I tried running the Install-Package cmdlet in my powershell but it just does not work.
Is there anyone out there who knows how to install the nuget package on my OS?

Currently I get following error when compiling the golang app.

```
# pkg-config --cflags  -- rdkafka
pkg-config: exec: "pkg-config": executable file not found in %PATH%
```

**Comment by edenhill** [comment]
confluent-kafka-go is not yet supported on Windows, so you will need to follow this community-driven thread on how to get it up and running:
https://github.com/confluentinc/confluent-kafka-go/issues/128

**Comment by marcofranssen** [comment]
Are there any plans for supporting this on windows? The cool stuff about go is it works on all platforms. Would be great if this lib would do as well. You are locking out lot of devs currently who would be able to contribute.

Having it installable via chocolatey or scoop would be great. Both are package managers for windows, similar like homebrew, apt and yum.
