### ISSUE TITLE
High level API to get number of partitions in a topic

### ISSUE THREAD

**Issue by SuchithArodi** [confluentinc/confluent-kafka-go#245]
Description
===========
I want to consume each partition in a topic separately in go routines. I am planning to create consumer instances which are equal to number of partitions so that each consumer instances read from a single partition in a topic. Basically, in my setup I am trying to read a single partition with each consumer instances. 

1) Is this a good way of reading the individual partitions? Will my setup be affected by the rebalancing? 
2) If so, then is there any API where I pass in the topic name and I get back number of partitions in that topic at the API level (By code and not contacting the Zookeeper directly)? 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
1. If possible, try to reuse a single consumer for all your partitions, it will be more effective.  Use `Assign()` to manually set the partitions to consume, then use `ReadMessage()` or `Poll()` to read the messages. Based on the message partition you could then pass the message on per-partition channels to per-partition workers.
 2. Use GetMetadata() to return the partition list for a topic (or all topics): https://docs.confluent.io/current/clients/confluent-kafka-go/index.html#Consumer.GetMetadata

**Comment by SuchithArodi** [comment]
Thank you for the information.

**Comment by GMac2890** [comment]
Hi @edenhill, I was going through reading data efficiently from kafka while I came across this. For your point #1, why is it effective to have one consumer to read from all partitions? We currently have an independent goroutine to read from each partition as they'll be able to read/process data concurrently. Am I missing something here?
