### ISSUE TITLE
kafkaProducer.Events() stops sending callback events, then kafkaProducer.ProduceChannel() fills and and becomes blocked indefinitely.

### ISSUE THREAD

**Issue by kurtostfeld** [confluentinc/confluent-kafka-go#251]
Description
===========

Sporadic issue where Kafka Go client works fine for days, then hits an issue where it stops sending callback events to `kafkaProducer.Events()`, then minutes later, `kafkaProducer.ProduceChannel()` becomes blocked and stops taking new messages. The Go app will never send or accept more messages until the Go app is manually restarted.

How to reproduce
================

It takes days of running in production for this issue to occur. It's happened multiple times. I don't have a way to reproduce easily.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): librdkafka1 version librdka0.11.6~1confluent5.0.1-
 - [ ] Apache Kafka broker version: Kafka 2.0.0. Confluent Platform 5.0.0.
 - [ ] Client configuration: `&kafka.ConfigMap{
		"bootstrap.servers": strings.Join(bootstrapServers,","),
	})`
 - [ ] Operating system: Ubuntu 16.04.5
 - [ ] Provide client logs (with `"debug": ".."` as necessary): None.
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Interesting. And this is regardless of any error events in the cluster, such as a broker going down or partition leader becoming unavailable?

**Comment by kurtostfeld** [comment]
If there is an issue within the Kafka cluster, it only affects a single client server at a time, and is remedied by a manual restart.

There are multiple server instances running the exact same code sending messages to the same Kafka cluster. One will hit this issue and require a manual restart to resume sending to the Kafka cluster, while the others will not experience any hiccups and run completely smoothly.

**Comment by trtg** [comment]
@edenhill I am seeing a similar issue except more accelerated- producer stops working after a few hours running. I have a sample bit of code that reproduces the issue consistently. It's just a minimal webserver that writes the body of incoming requests into a topic.
```
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	_ "net/http/pprof"
	"github.com/confluentinc/confluent-kafka-go/kafka"
)

type KafkaProxy struct {
	kafkaHandle *kafka.Producer
}

func (kProxy *KafkaProxy) handler(w http.ResponseWriter, r *http.Request) {
	body, err := ioutil.ReadAll(r.Body)
	if err != nil {
		fmt.Println("problem reading body")
	}
	topic := "moments"
	kProxy.kafkaHandle.Produce(&kafka.Message{
		TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny},
		Value:          []byte(body),
	}, nil)
}

func main() {
	p, err := kafka.NewProducer(&kafka.ConfigMap{"bootstrap.servers": "kafka.internal"})
	if err != nil {
		panic(err)
	}
	proxy := &KafkaProxy{kafkaHandle: p}
	http.HandleFunc("/", proxy.handler)
	fmt.Println("Listening on port 8177")
	log.Fatal(http.ListenAndServe(":8177", nil))
	defer proxy.kafkaHandle.Close()
}
```

**Comment by edenhill** [comment]
@trtg You don't seem to read from the producer's Events channel, which causes it to fill up with delivery reports.
Either disable `go.delivery.reports`, or (preferably) add a go-routine to serve the Events channel.

**Comment by trtg** [comment]
@edenhill thanks for the clarification, I didn't realize consuming the delivery reports was required. I'll rework things to do that. Just out of curiosity, however, where would go.delivery.reports be set? It's not mentioned in CONFIGURATION.md

**Comment by edenhill** [comment]
It is a go-level config property, it is documented in the NewProducer docs.
You specify it as any other configuration property though, in the ConfigMap.

**Comment by kurtostfeld** [comment]
@edenhill, any comment on the above. Is there anything else that I can try? I guess start adding logs+breakpoints to the confluent-kafka-go code to debug into that?

**Comment by namitmr** [comment]
@kurtostfeld we are facing a similar issue where, we face the error message `local_queue_full` (notably the librdkafka queue) and cannot produce any further. Is this particular issue specific to the 0.11.6 release or did you face this on the previous versions as well ? 
Note : As mentioned the above issue not particularly reproduce-able

**Comment by AlexJF** [comment]
Hi everyone,

We were apparently hitting the same issue after upgrading to librdkafka 0.11.6

Over the course of 3 days, 5 of our 300 consumers/producer experienced an unexpected "hang" (no further processing was done and there was one core at 100% cpu usage). Some of these producers were also complaining of full queues. This happened at apparent random times. If you grabbed a profile from one of these stalled apps, it would look like the following:

![image](https://user-images.githubusercontent.com/373323/53731117-0c038400-3e7a-11e9-9694-0800f0ddc21d.png)

We've tracked this down to these 2 issues:
* https://github.com/edenhill/librdkafka/issues/2108
* https://github.com/edenhill/librdkafka/issues/2208

Given that these fixes are very simple and have already been merged into master but haven't been released in a stable version, we patched them into the 0.11.6 release, rebuilt librdkafka with them and haven't had another stall for over 5 days now.

```
  cd /tmp
  curl -OL https://github.com/edenhill/librdkafka/archive/v0.11.6.tar.gz
  echo "9c0afb8b53779d968225edf1e79da48a162895ad557900f75e7978f65e642032  v0.11.6.tar.gz" | sha256sum -c -
  tar -xf v0.11.6.tar.gz -C /usr/local/src
  # TODO: Remove when updating to librdkafka 1.x.x
  # Backport important fixes for deadlock
  # https://github.com/edenhill/librdkafka/commit/672dbf42d2a0ab8694be160740dad48554178a7c
  # https://github.com/edenhill/librdkafka/commit/d62dd0e7f16cde184e7c809a01ed5aa06861b660
  # https://github.com/edenhill/librdkafka/issues/2108
  # https://github.com/edenhill/librdkafka/issues/2208
  curl -OL https://github.com/edenhill/librdkafka/commit/672dbf42d2a0ab8694be160740dad48554178a7c.patch
  echo "c88a090ea674d7197e7104f8a6aa28a855c37a38f5479d08464916fe0eda3e19  672dbf42d2a0ab8694be160740dad48554178a7c.patch" | sha256sum -c -
  curl -OL https://github.com/edenhill/librdkafka/commit/d62dd0e7f16cde184e7c809a01ed5aa06861b660.patch
  echo "4af86643b31f1c698f61029cec6eec0d54056696db79e724bd7f044f9e965a96  d62dd0e7f16cde184e7c809a01ed5aa06861b660.patch" | sha256sum -c -
  cd /usr/local/src/librdkafka-0.11.6
  # TODO: Remove when updating to librdkafka 1.x.x
  patch -p1 < /tmp/672dbf42d2a0ab8694be160740dad48554178a7c.patch
  patch -p1 < /tmp/d62dd0e7f16cde184e7c809a01ed5aa06861b660.patch
  ./configure --prefix=/usr
  make
  make check
  make install
```

**Comment by edenhill** [comment]
@AlexJF That's great! Thank you!

We'll have a new v1.0.0 release (with the fixes) of both librdkafka and confluent-kafka-go within a week or two

**Comment by jpiper** [comment]
FWIW I'm still seeing the issues in 1.0.0 and 1.10 in alpine3.10 - is there anything I can do to help debug this?

**Comment by saifat29** [comment]
I too have the exact same issue.
One core at 100% CPU usage and rest others at around 60%.
I use the following-
Broker - v2.3.0
librdkafka - v1.1.0
confluent-kafka-go - v1.1.0
