### ISSUE TITLE
Consumer Channels Breaks At-Least-Once Semantics

### ISSUE THREAD

**Issue by sachnk** [confluentinc/confluent-kafka-go#256]
Description
===========
When using a consumer with channel consumption, you can break at-least once semantics. Successive runs of an app that uses such a consumer seems to drop messages presumably because the queued messages in the channel are lost. 

How to reproduce
================
Build the bundled `examples/consumer_channel_example`. Run the app against a topic that already has published data. Then re-run it again:

First run:

```
$ ./consume localhost:9092 mygroup mytopic
Created Consumer rdkafka#consumer-1
% AssignedPartitions: [mytopic[0]@unset]
% Message on mytopic[0]@12607:
% Message on mytopic[0]@12608:
% Message on mytopic[0]@12609:
% Message on mytopic[0]@12610:
% Message on mytopic[0]@12611:
% Message on mytopic[0]@12612:
% Message on mytopic[0]@12613:
% Message on mytopic[0]@12614:
% Message on mytopic[0]@12615:
^C% Message on mytopic[0]@12616:
% Message on mytopic[0]@12617:
Caught signal interrupt: terminating
Closing consumer
```

Second run:
```
$ ./consume localhost:9092 mygroup mytopic
Created Consumer rdkafka#consumer-1
% AssignedPartitions: [mytopic[0]@unset]
% Message on mytopic[0]@12620:
% Message on mytopic[0]@12621:
% Message on mytopic[0]@12622:
% Message on mytopic[0]@12623:
^C% Message on mytopic[0]@12624:
% Message on mytopic[0]@12625:
Caught signal interrupt: terminating
Closing consumer
```

The first run consumed offset 12617. Regardless of whether 12617 was committed or not, the second run should start at an offset <= 12617. Instead, the second run starts 12620, effectively dropping offsets in [12618, 12619]. This, I reckon, violates at-least-once semantics, or am I missing something?

One possible explanation is that, under the hood, we're popping messages off a queue, and then pushing them onto our go channel. Once pushed onto the channel, the message is considered "consumed" and so our auto-commit commits that offset. However, if the app dies while there are events in the channel, those messages are effectively lost.

Changing `go.events.channel.size` to 1 reduces the lost messages, but doesn't prevent it. If this is intended behavior, definitely should be in bold-red in the docs...

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
Both 0.11.6 
 - [x] Apache Kafka broker version:
Docker Image: `confluentinc/cp-kafka:latest`, latest tag is at `5.0.1`
 - [x] Client configuration: `ConfigMap{...}`
```
"bootstrap.servers":               broker,
"group.id":                        group,
"session.timeout.ms":              6000,
"go.events.channel.enable":        true,
"go.events.channel.size":          1,
"go.application.rebalance.enable": true,
"default.topic.config":            kafka.ConfigMap{"auto.offset.reset": "earliest"}})
```
 - [x] Operating system:
 MacOS mojave, running docker engine 18.09.0
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your analysis is correct, and this is the reason why're looking at deprecating the channel-based consumer in favour of the functional one. It just makes it really hard to guarantee correctness.

**Comment by sachnk** [comment]
@edenhill Thanks.

To confirm, if I switch to the standard `Poll(timeout int)` method, then auto-commit requests would only be sent when I call `Poll()`, correct? In other words:

```go
for {
  select {
  default:
    ev := c.Poll(100)
    if ev == nil {
      continue
    }

    // ...
    
    // commit request sent by auto-commit logic 
    // on next call to c.Poll() if "auto.commit.interval.ms" has elapsed 
  }
}
```

Want to make sure that auto-commits aren't processed or buffered elsewhere, because that can lead to similar problems...

I suspect this must be true, but just want to sanity check :)

**Comment by edenhill** [comment]
No, auto commits are performed on a background thread, no need to call Poll to trigger them.

**Comment by sachnk** [comment]
Oh. That's contrary to my understanding of how auto-commit works based on things I've read (https://stackoverflow.com/questions/38230862/need-clarification-about-kafka-auto-commit-and-auto-commit-interval-ms).

If auto-commit happens in a background thread, then dropped messages are also possible for the same reason why channels break. Consider:

```
ev := c.Poll(100) 
if ev == nil {
  continue
}

// ** auto-commit happens here and app dies

handleMessage(ev) 
```

If `Poll` returns a message at, say, offset 10, but before executing `handleMessage`, the auto-commit thread saves offset 10, and then my app dies, I've lost offset 10 because I never actually handled it. This is another version of the same problem with channels, no?

If this is true, then auto-commits can also break at-least-once semantics?

**Comment by edenhill** [comment]
Yes!
And the workaround for that is to set `enable.auto.offset.store=false` and then implicitly call StoreOffsets() *after* message processing.

StoreOffsets stores the offset to auto-commit.

**Comment by sachnk** [comment]
Understood. Thanks so much for clarifying!
