### ISSUE TITLE
Requires librdkafka 1.0.0, which doesn't exist.

### ISSUE THREAD

**Issue by genzgd** [confluentinc/confluent-kafka-go#257]
Description
===========
See title

How to reproduce
================
Try to build with librdkafka 0.11.6 (latest release) and current master of confluent-kafka-go.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by devantoine** [comment]
Yes, what are we supposed to do? librdkafka v1.0.0 isn't released yet which means we cannot use the Go library :/

**Comment by genzgd** [comment]
I've been able to build using the v1.0.0-RC4 version.

**Comment by edenhill** [comment]
We're sorry about this hassle, we're moving to an off-master development branch. Until then we'll relax the version requirements.

**Comment by edenhill** [comment]
There, master should now be back to requiring librdkafka >=v0.11.5
