### ISSUE TITLE
Question about the consumer example

### ISSUE THREAD

**Issue by namco1992** [confluentinc/confluent-kafka-go#258]
Hi @edenhill ,

Recently I refer to the consumer example again and realized that the example code will exit when there is an error received, like the snippet below:
```go
			switch e := ev.(type) {
			case *kafka.Message:
				fmt.Printf("%% Message on %s:\n%s\n",
					e.TopicPartition, string(e.Value))
				if e.Headers != nil {
					fmt.Printf("%% Headers: %v\n", e.Headers)
				}
			case kafka.Error:
				fmt.Fprintf(os.Stderr, "%% Error: %v\n", e)
				run = false
			default:
				fmt.Printf("Ignored %v\n", e)
			}
```
I'm wondering what's the reason behind? Is it because the `kafka.Error` means some errors which can't be recovered and the consumer has to be stopped? If so, may I know where I can find more details about the underlying errors?

**Comment by edenhill** [comment]
Those examples needs to be updated, the recommendation is for an application to treat Errors as informational only, the underlying client will do its best to automatically recover.
Generally, given that the configuration is correct, there should not be any permanents errors.

**Comment by namco1992** [comment]
Thank you for the reply, I also read this from the comments, then I assume the example code is not reflecting the real purpose of the Kafka error since it looks like you will terminate the consumer if there is an error.

The reason I look into this is that our consumer was terminated unexpectedly when we hit a Kafka error, some other users who is new to this might also refer to the example code and fail to handle the error properly. Do you think I can make changes to the examples and create a PR? If I can do it then how do you like to handle the error? Should the loop just continue and log the error?

Thanks.

**Comment by edenhill** [comment]
A PR would be great!
I suggest just printing the error, and then continuing the loop, adding a comment that:
"Errors should generally be considered as informational, the client will try to automatically recover"

**Comment by namco1992** [comment]
Sure, I will create a PR tonight, thanks.

**Comment by chuyeow** [comment]
Looks like this is done in https://github.com/confluentinc/confluent-kafka-go/pull/259, we can close this issue now :)
