### ISSUE TITLE
Kafka Consumer Pause and resume

### ISSUE THREAD

**Issue by amitdix** [confluentinc/confluent-kafka-go#260]
Description
===========
Does Kafka Consumer Pause stop polling to kafka? What happens to connection ?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):0.11.14
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
pause() stops the fetcher and purges the local queue of pre-fetched messages. The application will not receive any messages (but possibly rebalance events) until resume() is called.

**Comment by pragmaticpi** [comment]
I am doing manual commit on my consumer. Let's say I consumed 100 messages and paused the consumer without committing offset. After resuming, will it read those 100 messages again?
