### ISSUE TITLE
Support for ListConsumerGroupOffsets?

### ISSUE THREAD

**Issue by jeffwidman** [confluentinc/confluent-kafka-go#261]
The `AdminClient` is missing the [`ListConsumerGroupOffsets`](https://kafka.apache.org/20/javadoc/org/apache/kafka/clients/admin/AdminClient.html#listConsumerGroupOffsets-java.lang.String-org.apache.kafka.clients.admin.ListConsumerGroupOffsetsOptions-) call.

So this ticket is to track adding it.

This is blocked by `librdkafka` needing to implement it first--I filed https://github.com/edenhill/librdkafka/issues/2173 to track that.

See also my design notes there about allowing optional params specifying a known consumer group coordinator, partitions, etc.

**Comment by milindl** [comment]
Closing with #923
