### ISSUE TITLE
producer all connect are close_wait status and do not reconnect 

### ISSUE THREAD

**Issue by zhuxiufenghust** [confluentinc/confluent-kafka-go#262]
Description
===========
log-producer is module which receive log and push to kafka, but with some instances run some days, some connnections with broker may stay with close_wait status and can not recover and with much queue full error.  is it necessary to close the connection and reconnect mannual?

How to reproduce
================
hard to reproduce on live environment, may need to run some days to reproduce

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
    5e4d04e05fc319ce5996a867aafef29059f26862
 - [x] Apache Kafka broker version:
    1.0.0
 - [x] Client configuration: `ConfigMap{...}`
        	producer.raw, err = kafka.NewProducer(&kafka.ConfigMap{
		"queue.buffering.max.messages": bufferSize,
		"queue.buffering.max.ms":       bufferTime,
		"compression.codec":            "gzip",
		"message.max.bytes":            messageMaxBytes,
		"metadata.broker.list":         brokers,
		"go.delivery.reports":          false,
		"default.topic.config": kafka.ConfigMap{
			"produce.offset.report": false,
		},
	})
 - [x] Operating system:
    ubuntu 
 - [x] Provide client logs (with `"debug": ".."` as necessary)
![image](https://user-images.githubusercontent.com/13944001/50809648-e78aa000-133f-11e9-8528-c3f5bcb6e077.png)
![image](https://user-images.githubusercontent.com/13944001/50809682-23256a00-1340-11e9-8bb8-cb795e854eb1.png)

 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
what librdkafka version (LibraryVersion()) are you on?

**Comment by zhuxiufenghust** [comment]
how to get the LibraryVersion

**Comment by edenhill** [comment]
`_, verstr := kafka.LibraryVersion()`

**Comment by edenhill** [comment]
Can you reproduce this with `"debug": "broker,topic,msg"` config and provide the logs?

**Comment by zhuxiufenghust** [comment]
hard to reproduce it may run some days then ocurr and the librdkafka version may change, we compile and deploy with the master lastest version.

**Comment by zhuxiufenghust** [comment]
should we just ignore the send and  deliveryChan error  or should we close and reconnect mannual. hard to understand why the close_wait status last so long

**Comment by edenhill** [comment]
You should not reset/restart the producer when you get any error, the producer will automatically recover from all errors (short of configuratoin error)

**Comment by zhuxiufenghust** [comment]
got, we will deploy and open the debug log configuration.
