### ISSUE TITLE
Moving offset without commit

### ISSUE THREAD

**Issue by caevv** [confluentinc/confluent-kafka-go#264]
Description
===========

I found this when trying to create a retry strategy on my consumer. When I produce a message, consume and don't commit (with `"enable.auto.commit" = false`), and return to consume, it will reach EOF and change the offset, not try to re-process the same message. Basically the second time it starts from offset 1, instead of 0, even that the message was not committed.

I don't know if this is expected behaviour or a bug, if is expected, would very much appreciate some suggestion.

How to reproduce
================
```
go func() {
    attempt := 1

    // force error with consumer handler
    consumeHandler := func() error {
        defer wg.Done()
        calledTimes++
        log.Printf("called times: %v", calledTimes)
        return errors.New("something went wrong")
    }

    // attempt 1
    log.Printf("attempt: %v", attempt)
    err = consumer.consume(consumeHandler)
    if err != nil {
        log.Printf("failed to consume: %v", err)
        err = consumer.close()
        if err != nil {
            log.Printf("failed to close consumer: %v", err)
        }

        time.Sleep(backoffDuration)
        attempt++
        // attempt 2
        log.Printf("attempt: %v", attempt)

        consumer, err = newConsumer(broker, group, topic)
        err = consumer.consume(consumeHandler)
        if err != nil {
            log.Printf("failed to consume: %v", err)
            err = consumer.close()
            if err != nil {
                log.Printf("failed to close consumer: %v", err)
            }
        }
    }
}()
```

First time:
```%7|1548085813.162|FETCH|rdkafka#consumer-1| [thrd:main]: Partition test-topic [0] start fetching at offset 0```
Second time:
```%7|1548085825.348|FETCH|rdkafka#consumer-3| [thrd:main]: Partition test-topic [0] start fetching at offset 1```

All here:
https://github.com/nicovogelaar/kafka-consumer-fail-retry/blob/v0.1.0/kafka_test.go

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v0.11.4
 - [x] Apache Kafka broker version: https://github.com/nicovogelaar/kafka-consumer-fail-retry/blob/v0.1.0/docker-compose.yml#L25
 - [x] Client configuration: ```ConfigMap{
		"bootstrap.servers":    broker,
		"group.id":             group,
		"session.timeout.ms":   6000,
		"default.topic.config": confluentkafka.ConfigMap{"auto.offset.reset": "latest"},
		"enable.auto.commit":   false,
		"debug":                "consumer",
	}```
 - [x] Provide client logs (with `"debug": ".."` as necessary): https://travis-ci.org/nicovogelaar/kafka-consumer-fail-retry/jobs/477832325#L490

**Comment by rnpridgeon** [comment]
How are you confirming the offset has moved? If you haven't already done so try using the the consumer offset checker to ensure the offset has actually been committed to Kafka. 

https://cwiki.apache.org/confluence/display/KAFKA/System+Tools#SystemTools-ConsumerOffsetChecker

Based on the description alone I suspect you are reusing the same consumer instance which is likely pulling the offset from its own offset cache. Unless there was a rebalance there is no need for the consumer to query the broker for it's offset again.

**Comment by caevv** [comment]
We are confirming the offset by using `"debug": "consumer"`.
We don't commit the offset, and the new consumer starts from the (apparently) local cached offset.

https://github.com/nicovogelaar/kafka-consumer-fail-retry/blob/v0.1.1/kafka_test.go

> Based on the description alone I suspect you are reusing the same consumer instance which is likely pulling the offset from its own offset cache. Unless there was a rebalance there is no need for the consumer to query the broker for it's offset again.

On the new version v0.1.1, it'll close the old consumer and start a new one, here is a build with logs:
https://travis-ci.org/nicovogelaar/kafka-consumer-fail-retry/builds/479427388

**Comment by caevv** [comment]
@edenhill do you have any idea please?

**Comment by edenhill** [comment]
Can you run this with `"debug": "cgrp,topic,fetch"`, which will provide more information?

💯  on providing both the code and test run output!

**Comment by caevv** [comment]
The output is quite big, 1500 lines, so I run a test and it's on travis-ci here if that helps:
https://travis-ci.org/nicovogelaar/kafka-consumer-fail-retry/builds/482821556

**Comment by edenhill** [comment]
If I read the code correctly, consumer 1 is created before the first message is produced and consumer 2 is created after the first message is produced.
Since both consumers use auto.offset.reset=latest they'll start consuming from the end of the partition, for consumer 1 that is an empty partition where a message will soon be produced, thus seeing the message.
For consumer 2 the end of the partition is after the produced message, thus seeing the message.

**Comment by caevv** [comment]
That was it @edenhill, so simple, makes totally sense now, thanks for taking the time to look into it.
