### ISSUE TITLE
How to get the stats using go client

### ISSUE THREAD

**Issue by pradeepkusingh** [confluentinc/confluent-kafka-go#265]
Description
===========

I would like to get the Kafka stats using GO client. don't find any samples. Please help.

How to reproduce
================

NA

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): Latest versions
 - [ ] Apache Kafka broker version: 1.1.10
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: MAC
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue : Nope.

**Comment by edenhill** [comment]
Let me add an example for you.

**Comment by edenhill** [comment]
See this example:
https://github.com/confluentinc/confluent-kafka-go/blob/b25ea438a11e34459f71f626d16efbd053bb09a3/examples/stats_example/stats_example.go

**Comment by pradeepkusingh** [comment]
Thank you :)

**Comment by pradeepkusingh** [comment]
Sorry, but I don't see the consumer_lag value in MAP. I printed whole stats map and don't see the values.

**Comment by pradeepkusingh** [comment]
How to use this without consuming messages? I want to use this as a lag and different statistics monitor without consuming messages.

**Comment by pradeepkusingh** [comment]
Thanks, I found the details.
