### ISSUE TITLE
Wrong deprecation notices

### ISSUE THREAD

**Issue by Eitol** [confluentinc/confluent-kafka-go#268]
Description
===========
The notice "Deprecate" is used to mark that a variable structure, method, etc., is deprecated.
See this example: https://rakyll.org/deprecated/

The code is marked in some parts with this notice although it is not certain that the data type or variable is deprecated.
For example "ConfigMap" is marked by the IDE as a type of deprecated data although what is deprecated is the configuration property "default.topic.config" because this convention is missused.

My CI pipeline checks that deprecated things are not used and sends me alerts that do not let me go up to production.

![image](https://user-images.githubusercontent.com/1043061/51345106-ee6c8d80-1a78-11e9-9098-570c4749311a.png)
![image](https://user-images.githubusercontent.com/1043061/51345496-ec56fe80-1a79-11e9-8463-35eb59c20ce8.png)

I propose to change it from "Deprecated" to "Note"

**Comment by edenhill** [comment]
Fixed in v1.0.0
