### ISSUE TITLE
Message duplicated

### ISSUE THREAD

**Issue by sundy-li** [confluentinc/confluent-kafka-go#269]
Description
===========
I use this client, but found about 20% messages are dumplicated compared with other clients(sarama-cluster)

librdkafka v0.11.6
os: ubuntu 16.4

```
c, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers": k.Brokers,
		"group.id":          k.ConsumerGroup,
		"auto.offset.reset": "latest",

		"session.timeout.ms":       6000,
		"go.events.channel.enable": true,
		"auto.commit.interval.ms":  100,
	})
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [x ] Apache Kafka broker version:
 - [x ] Client configuration: `ConfigMap{...}`
 - [ x] Operating system:
 - [x ] Provide client logs (with `"debug": ".."` as necessary)
 - [x ] Provide broker log excerpts
 - [x ] Critical issue

**Comment by edenhill** [comment]
You will need to provide more information:
 * logs
 * relevant parts of your application that interact with the Kafka client
 * proof of messages being duplicated
 *  explain the setup and when the duplicated messages are seen

Also note the caveats of the channel based consumer:
https://github.com/confluentinc/confluent-kafka-go#api-strands

In particular that outdated/old messages or events may be returned from the channel after a rebalance, due to the queuing nature of channels.
Suggest you use the functional interface instead.

**Comment by sundy-li** [comment]
Hi, thanks for your reply

1. We have a monitor system that can figure out the number of the consumed and the produced records, it's true that messages are duplicated.

2. We have 120 partitons in this big topic. We started 48 consumer processors to read from the topic. Firstly, the consume messages are fine, after a while (around 90 minutes later), there are duplicated messages. But then we restarted the consumers , it came back to fine again.


We just saw rebalance log on the start time. The assign partitions will soon be stable cause we started 48 consumers,  no rebalance event any more.

The QPS(type=0) means the produce rate per second, and QPS(type=1) means the consume rate.


![image](https://user-images.githubusercontent.com/3325189/51392890-44246100-1b71-11e9-99fa-8c597e23c134.png)



I will try to use the functional interface instead.


3.  The detail code now is below

```
c, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers": k.Brokers,
		"group.id":          k.ConsumerGroup,
		"auto.offset.reset": "latest",

		"session.timeout.ms":       6000,
		"go.events.channel.enable": true,
		"auto.commit.interval.ms":  100,
		// "go.application.rebalance.enable": true,
	})

	if err != nil {
		return err
	}

	for run == true {
			select {
			case <-k.stopped:
				log.GetLogger().Debug("Caught signal, terminating")
				run = false

			case ev := <-c.Events():
				switch e := ev.(type) {
				case *kafka.Message:
                                          // we will pass k.msgs to another thread to read it
					k.msgs[int(e.TopicPartition.Partition)%len(k.msgs)] <- &KVMessage{e.Key, e.Value}
					nc := atomic.AddInt64(&(k.count), 1)
					atomic.AddInt64(&(k.size), int64(len(e.Key)+len(e.Value)))
					if nc%1000000 == 0 {
						cost := time.Now().Unix() - tx
						if cost != 0 {
							k.consumerRate = k.count / cost
							log.GetLogger().Debug("KAFKA consumer QPS => %d %d total : %d", k.count/cost, k.size/cost, nc)
						}
					}

				case kafka.Error:
					// Errors should generally be considered as informational, the client will try to automatically recover
					log.GetLogger().Debug("Error: %v\n", e)
				}
			}
		}

```

**Comment by sundy-li** [comment]
I tried functional interface, some messages are duplicated too.

Go version 1.11.
Kafka cluster version 2.0.
No other error logs.

**Comment by sundy-li** [comment]
I rebuilt the `librdkafka v0.11.6`,  and it's ok now. Maybe the previous lib and header file are not compatible
