### ISSUE TITLE
App crashes when confluent-kafka-go imported.

### ISSUE THREAD

**Issue by shreyasns** [confluentinc/confluent-kafka-go#270]
Description
===========
I have a golang webserver which produces to kafka. The webserver crashes without any error message with exit code of 137(`Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`). I recently upgraded my librdkafka and confluent-go-kafka. Can't provide logs as nothing gets printed on the stdout or stderr

Checklist
=========
Please provide the following information:
- golang version: 1.11.4
 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 0.11.6 both
 - [ ] Apache Kafka broker version: 1.0.0
 - [ ] Client configuration: `{ 
"lingerMS": 5, 
"compressionType": "gzip", 
"metaDataMaxAge": 300000, 
"requestTimeout": 30000, 
"maxInFlightRequestsPerConnection": 1, 
"retries": 3 
}`
 - [ ] Operating system: macOS 10.14.1
 - [ ] Provide client logs (with `"debug": ".."` as necessary) - not available
 - [ ] Provide broker log excerpts - not available
 - [ ] Critical issue

**Comment by shreyasns** [comment]
This is the output I got
```
/usr/local/opt/librdkafka/lib/librdkafka.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1560.12.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.220.15)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

**Comment by edenhill** [comment]
That looks good.
How did you install librdkafka?

**Comment by shreyasns** [comment]
installed it through brew

**Comment by edenhill** [comment]
Okay, good. Any log / stderr output from your application?

**Comment by shreyasns** [comment]
Nothing. not sure how I should proceed with the debugging.

**Comment by shreyasns** [comment]
And I think its happening only on my system.

**Comment by edenhill** [comment]
Try setting the "debug" config property to "all" and see if you get any output before it gets killed.
If there is nothing, try uninstalling librdkafka (all versions) and reinstalling it, then rebuilding confluent-kafka-go and your application.

**Comment by edenhill** [comment]
Set the "debug" config property to "all" in the ConfigMap

**Comment by shreyasns** [comment]
No luck.

**Comment by shreyasns** [comment]
can't even start the debugger. So it crashes even before the program starts to run I guess.

**Comment by edenhill** [comment]
It is not a debugger, it only makes the client output more debugging logging to stderr.
Did you try reinstalling librdkafka as instructed above?

**Comment by shreyasns** [comment]
Yeah, I tried reinstalling everything. I also tried to run the example from the repo. I suspect there is some problem with loading the program as it's not even printing the logs which are at the beginning.

**Comment by shreyasns** [comment]
I'm using macOS Mojave 10.14.1

**Comment by shreyasns** [comment]
Something is weird. The same binary for some reason works 1hr after building it.

**Comment by shreyasns** [comment]
Hey looks like my antivirus killing because it does not trust the signer of the code. So not a kafka-client issue. Closing this.
