### ISSUE TITLE
No such configuration property: "ssl.ca.location"

### ISSUE THREAD

**Issue by alifpay** [confluentinc/confluent-kafka-go#272]
Description
===========

ubuntu 16
Checked with 
apt list --installed

librdkafka++1/stable,now 0.11.6~1confluent5.1.0-1 amd64 [installed,automatic]
librdkafka-dev/stable,now 0.11.6~1confluent5.1.0-1 amd64 [installed]
librdkafka1/stable,now 0.11.6~1confluent5.1.0-1 amd64 [installed]

Get error 
No such configuration property: "ssl.ca.location"

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion( 0.11.6)`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That is weird, can you provide the output from `apt show librdkafka1` ?

**Comment by alifpay** [comment]
Package: librdkafka1
Version: 0.11.6~1confluent5.1.0-1
Priority: optional
Section: libs
Source: librdkafka
Maintainer: Faidon Liambotis <paravoid@debian.org>
Installed-Size: 1,112 kB
Depends: libc6 (>= 2.16), libsasl2-2 (>= 2.1.24), libssl1.0.0 (>= 1.0.0), zlib1g (>= 1:1.2.2)
Homepage: https://github.com/edenhill/librdkafka
Download-Size: 360 kB
APT-Manual-Installed: yes
APT-Sources: https://packages.confluent.io/deb/5.1 stable/main amd64 Packages
Description: library implementing the Apache Kafka protocol
 librdkafka is a C library implementation of the Apache Kafka protocol,
 containing both Producer and Consumer support. It was designed with message
 delivery reliability and high performance in mind, current figures exceed
 800000 msgs/second for the producer and 3 million msgs/second for the
 consumer. Supports broker version 0.8 and later.
 .
 More information about Apache Kafka can be found at http://kafka.apache.org/
 .
 This package contains the C shared library.

Package: librdkafka1
Version: 0.8.6-1.1
Priority: optional
Section: universe/libs
Source: librdkafka
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Faidon Liambotis <paravoid@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 226 kB
Depends: libc6 (>= 2.14), zlib1g (>= 1:1.2.2)
Homepage: https://github.com/edenhill/librdkafka
Download-Size: 87.7 kB
APT-Sources: http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Description: library implementing the Apache Kafka protocol
 librdkafka is a C implementation of the Apache Kafka protocol. It currently
 implements the 0.8 version of the protocol and can be used to develop both
 Producers and Consumers.
 .
 More information about Apache Kafka can be found at http://kafka.apache.org/

**Comment by alifpay** [comment]
remove all librdkafka's libs from /usr/local
and reinstalled now it is working.
Thank you

when will be in pure golang?

**Comment by edenhill** [comment]
Good thing you sorted it out!

As for a pure golang client; there are no such plans, we're looking at making the non-go dependency management easier though.
