### ISSUE TITLE
Generated Errors

### ISSUE THREAD

**Issue by abarrios1** [confluentinc/confluent-kafka-go#273]
Description
===========

Cannot use kafka lib without running into errors from current commit.

How to reproduce
================

go get -u github.com/confluentinc/confluent-kafka-go/kafka

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 0.11.5

 - [x] Operating system: centos 7

Debug
=======
kafka/generated_errors.go:258:65: could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_AUTHORIZATION_FAILED
kafka/generated_errors.go:250:58: could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_AUTH_DISABLED
kafka/generated_errors.go:260:53: could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_EXPIRED
kafka/generated_errors.go:252:54: could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_NOT_FOUND
kafka/generated_errors.go:254:59: could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_OWNER_MISMATCH
kafka/generated_errors.go:256:63: could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_REQUEST_NOT_ALLOWED
kafka/generated_errors.go:268:53: could not determine kind of name for C.RD_KAFKA_RESP_ERR_FETCH_SESSION_ID_NOT_FOUND
kafka/generated_errors.go:266:46: could not determine kind of name for C.RD_KAFKA_RESP_ERR_GROUP_ID_NOT_FOUND
kafka/generated_errors.go:270:55: could not determine kind of name for C.RD_KAFKA_RESP_ERR_INVALID_FETCH_SESSION_EPOCH
kafka/generated_errors.go:262:51: could not determine kind of name for C.RD_KAFKA_RESP_ERR_INVALID_PRINCIPAL_TYPE
kafka/generated_errors.go:240:48: could not determine kind of name for C.RD_KAFKA_RESP_ERR_KAFKA_STORAGE_ERROR
kafka/generated_errors.go:272:47: could not determine kind of name for C.RD_KAFKA_RESP_ERR_LISTENER_NOT_FOUND
kafka/generated_errors.go:242:45: could not determine kind of name for C.RD_KAFKA_RESP_ERR_LOG_DIR_NOT_FOUND
kafka/generated_errors.go:264:44: could not determine kind of name for C.RD_KAFKA_RESP_ERR_NON_EMPTY_GROUP
kafka/generated_errors.go:248:53: could not determine kind of name for C.RD_KAFKA_RESP_ERR_REASSIGNMENT_IN_PROGRESS
kafka/generated_errors.go:244:55: could not determine kind of name for C.RD_KAFKA_RESP_ERR_SASL_AUTHENTICATION_FAILED
kafka/generated_errors.go:274:52: could not determine kind of name for C.RD_KAFKA_RESP_ERR_TOPIC_DELETION_DISABLED
kafka/generated_errors.go:246:48: could not determine kind of name for C.RD_KAFKA_RESP_ERR_UNKNOWN_PRODUCER_ID
kafka/generated_errors.go:276:57: could not determine kind of name for C.RD_KAFKA_RESP_ERR_UNSUPPORTED_COMPRESSION_TYPE
kafka/generated_errors.go:118:36: could not determine kind of name for C.RD_KAFKA_RESP_ERR__FATAL
kafka/generated_errors.go:122:47: could not determine kind of name for C.RD_KAFKA_RESP_ERR__GAPLESS_GUARANTEE
kafka/generated_errors.go:120:43: could not determine kind of name for C.RD_KAFKA_RESP_ERR__INCONSISTENT
kafka/generated_errors.go:124:46: could not determine kind of name for C.RD_KAFKA_RESP_ERR__MAX_POLL_EXCEEDED
kafka/generated_errors.go:116:44: could not determine kind of name for C.RD_KAFKA_RESP_ERR__PURGE_INFLIGHT
kafka/generated_errors.go:114:41: could not determine kind of name for C.RD_KAFKA_RESP_ERR__PURGE_QUEUE
kafka/generated_errors.go:112:36: could not determine kind of name for C.RD_KAFKA_RESP_ERR__RETRY

**Comment by edenhill** [comment]
You should pin in at the latest version: v0.11.6.
Starting with the next version v1.0.0 (release due within a month), we'll keep the master branch pinned to the latest version.
Sorry for the inconvenience.

**Comment by edenhill** [comment]
Alternatively, you can install librdkafka by source from its master branch, but that should only be used for development work (and allow you to try out the idempotent producer!)

**Comment by pragmaticpi** [comment]
I am getting the above errors despite using librdkafka v0.11.6. I am using brew to install.

While trying building from source, I am getting following error on MacOS Mojave 10.14.3

install: mkdir /usr/include: Operation not permitted
make[1]: *** [lib-install] Error 71
make: *** [install] Error 2

**Comment by kjm789** [comment]
After building librdkafka from source at the location /usr/local, I can confirm that the issue illustrated by this ticket that I was seeing on my local macbook (version 10.13.6 High Sierra) was resolved.

It should be noted that I also initially installed librdkafka with homebrew and I was too seeing this issue illustrated by this ticket.

**Comment by daniesy** [comment]
> On osx you might need to install librdkafka to /usr/local (which is the default), so basically:
> 
> ```
> $ cd librdkafka
> $ ./configure --prefix=/usr/local # or just ./configure
> $ make
> $ sudo make install
> ```

Tried to remove librdkafka from brew and install it manually and still isn't working on Mojave 10.14.3.

**Comment by daniesy** [comment]
@edenhill i forgot the `local` from `--prefix=/usr/local` and got `mkdir /usr/include: Operation not permitted`.

Fixed it. Thanks.

**Comment by freeformz** [comment]
FWIW: The `kafka/generated_errors.go` file was generated off of `librdkafka 1.0.0-RC5-20-ga66502-devel-O0`. When I regenerated it using `go_rdkafka_generr/go_rdkafka_generr.go` against librdkafka 0.11.6 things went fine.

**Comment by edsonmedina** [comment]
I'm having the same issue with librdkafka 0.11.6 in alpine 3.8.

**Comment by kumarh1982** [comment]
same here, getting following errors in while running docker image with confluent kafka subscriber app.

vendor/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:258:65: could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_AUTHORIZATION_FAILED
vendor/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:250:58: could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_AUTH_DISABLED
vendor/github.com/confluentinc/confluent-kafka-go/kafka/generated_errors.go:260:53: could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_EXPIRED

and so on..

**Comment by vijaygurunanee** [comment]
I am getting same error on windows environment... windows-7 operating system... :(
I have librdkafka.redist.0.11.6 (already updated) and i have proper rdkafka.pc....


# github.com/confluentinc/confluent-kafka-go/kafka
could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_AUTHORIZATION_FAILED
could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_AUTH_DISABLED
could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_EXPIRED
could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_NOT_FOUND
could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_OWNER_MISMATCH
could not determine kind of name for C.RD_KAFKA_RESP_ERR_DELEGATION_TOKEN_REQUEST_NOT_ALLOWED
could not determine kind of name for C.RD_KAFKA_RESP_ERR_FETCH_SESSION_ID_NOT_FOUND
could not determine kind of name for C.RD_KAFKA_RESP_ERR_GROUP_ID_NOT_FOUND
could not determine kind of name for C.RD_KAFKA_RESP_ERR_INVALID_FETCH_SESSION_EPOCH
could not determine kind of name for C.RD_KAFKA_RESP_ERR_INVALID_PRINCIPAL_TYPE
could not determine kind of name for C.RD_KAFKA_RESP_ERR_KAFKA_STORAGE_ERROR
could not determine kind of name for C.RD_KAFKA_RESP_ERR_LISTENER_NOT_FOUND
could not determine kind of name for C.RD_KAFKA_RESP_ERR_LOG_DIR_NOT_FOUND
could not determine kind of name for C.RD_KAFKA_RESP_ERR_NON_EMPTY_GROUP
could not determine kind of name for C.RD_KAFKA_RESP_ERR_REASSIGNMENT_IN_PROGRESS
could not determine kind of name for C.RD_KAFKA_RESP_ERR_SASL_AUTHENTICATION_FAILED
could not determine kind of name for C.RD_KAFKA_RESP_ERR_TOPIC_DELETION_DISABLED
could not determine kind of name for C.RD_KAFKA_RESP_ERR_UNKNOWN_PRODUCER_ID
could not determine kind of name for C.RD_KAFKA_RESP_ERR_UNSUPPORTED_COMPRESSION_TYPE
could not determine kind of name for C.RD_KAFKA_RESP_ERR__FATAL
could not determine kind of name for C.RD_KAFKA_RESP_ERR__GAPLESS_GUARANTEE
could not determine kind of name for C.RD_KAFKA_RESP_ERR__INCONSISTENT
could not determine kind of name for C.RD_KAFKA_RESP_ERR__MAX_POLL_EXCEEDED
could not determine kind of name for C.RD_KAFKA_RESP_ERR__PURGE_INFLIGHT
could not determine kind of name for C.RD_KAFKA_RESP_ERR__PURGE_QUEUE
could not determine kind of name for C.RD_KAFKA_RESP_ERR__RETRY

**Comment by isapir** [comment]
Getting the same on Ubuntu 18.04 with librdkafka-dev 0.11.6

**Comment by abarrios1** [comment]
I am closing this issue that I opened. I have manually installed librdkafka and updated confluent kafka to the current version. Tested and verified it works on macos, centos, and ubuntu.
