### ISSUE TITLE
/usr/bin/ld: cannot find -lrdkafka

### ISSUE THREAD

**Issue by FU100** [confluentinc/confluent-kafka-go#274]
Description
===========
/usr/bin/ld: skipping incompatible /usr/local/lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: cannot find -lrdkafka

How to reproduce
================

1. 
librdkafka$ git reset --hard 4a7ed8ac7f6e6e63361b8705c0a768a31d28983b
HEAD is now at 4a7ed8a Bump ..VERSION to v1.0.0

librdkafka$ git make
librdkafka$ git sudo make install

2. 
confluent-kafka-go$ git reset --hard a82b13397c6bb17e9469c9bc28bad1e77e7f6211
HEAD is now at a82b133 Regenerate error codes

3.
confluent-kafka-go$ uname -a
Linux ubuntu123 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

confluent-kafka-go$ file -L /usr/local/lib/librdkafka.so
/usr/local/lib/librdkafka.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=db8a681e6c76ba31d73ce1bd989c78921b0cf6f1, not stripped

4.
after build my go program:
vendor/github.com/confluentinc/confluent-kafka-go/kafka
/usr/bin/ld: skipping incompatible /usr/local/lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/local/lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible //usr/local/lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible //usr/local/lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: cannot find -lrdkafka
/usr/bin/ld: skipping incompatible /usr/local/lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/local/lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible //usr/local/lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible //usr/local/lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: cannot find -lrdkafka
collect2: error: ld returned 1 exit status

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):confluent:latest,librdkafka:v1.0.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: ubuntu16.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you cross compiling your Go program for another arch?

**Comment by FU100** [comment]
no, I usually compile my go program on ubuntu 14.04.
after compiling on ubuntu 16.04, I got the error message.

**Comment by edenhill** [comment]
Can you provide the full build output with (`go build -x -v .....`) ?
