### ISSUE TITLE
Abstracted lib over confluent-kafka-go - thank you!

### ISSUE THREAD

**Issue by JoshKCarroll** [confluentinc/confluent-kafka-go#275]
Hi @edenhill,
We recently open sourced a [simplified message bus with a kafka implementation](https://github.com/qntfy/frafka) from the excellent confluent-kafka-go. Internally we are using it to share config for a number of processing/streaming services and simplifying support to deploy on both kafka and AWS kinesis.

This library is great and switching to it gave us a ~5x improvement in throughput over using the sarama client. Just wanted to bring to your attention and share our appreciation for all the work in guiding development of this client and all the great support shared here which helped us get to a working implementation. Thank you!

(feel free to close this issue)

**Comment by ijuma** [comment]
Thanks for taking the time to provide feedback!
