### ISSUE TITLE
librdkafka install fails in mac

### ISSUE THREAD

**Issue by Albinzr** [confluentinc/confluent-kafka-go#277]
Description
===========
When in perform this step in **MAC**
git clone https://github.com/edenhill/librdkafka.git
cd librdkafka
./configure --prefix /usr
make
**sudo make install** 

Error
==========
`install -d $DESTDIR/usr/include/librdkafka && \
	install -d $DESTDIR/usr/lib && \
	install rdkafka.h $DESTDIR/usr/include/librdkafka && \
	install librdkafka.a $DESTDIR/usr/lib && \
	install librdkafka.1.dylib $DESTDIR/usr/lib && \
	[ -f "rdkafka.pc" ] && ( \
		install -d $DESTDIR/usr/lib/pkgconfig && \
		install -m 0644 rdkafka.pc $DESTDIR/usr/lib/pkgconfig \
	) && \
	[ -f "rdkafka-static.pc" ] && ( \
		install -d $DESTDIR/usr/lib/pkgconfig && \
		install -m 0644 rdkafka-static.pc $DESTDIR/usr/lib/pkgconfig \
	) && \
	(cd $DESTDIR/usr/lib && ln -sf librdkafka.1.dylib librdkafka.dylib)
install: mkdir /usr/include: Operation not permitted
make[1]: *** [lib-install] Error 71
make: *** [install] Error 2`

How to reproduce
================
In **MAC**
git clone https://github.com/edenhill/librdkafka.git
cd librdkafka
./configure --prefix /usr
make
**sudo make install** 

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): Latest
 - [ ] Apache Kafka broker version: Lates
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: Mac
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
/usr is protected by [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection) (System Integrity Protection) - you can't install anything there even with root privileges.

**Comment by mhowlett** [comment]
(you can install to /usr/local, which is where librdkafka installs by default)

**Comment by Albinzr** [comment]
@mhowlett  how do i change the location
