### ISSUE TITLE
QueryWatermarkOffsets Requires Subscription

### ISSUE THREAD

**Issue by sachnk** [confluentinc/confluent-kafka-go#279]
Description
===========
We use `QueryWatermarkOffsets` to figure the number of messages in our topic. However, if we run `QueryWatermarkOffsets` before subscribing to anything, we get a leader not available error. 

How to reproduce
================

```
        cfg := kafka.ConfigMap{
		"enable.auto.commit":              true,
		"enable.auto.offset.store":        false,
		"auto.offset.reset":               "earliest",
		"go.events.channel.enable":        false,
		"go.application.rebalance.enable": false,
	}

	c, err := kafka.NewConsumer(&cfg)
	if err != nil {
		return err
	}
	
	_, hi, err := c.QueryWatermarkOffsets("foo", 0, 0)
	if err != nil {
		return err // this always get triggered with leader not available
	}
```

The workaround we're currently using is to do `c.SubscribeTopics()` then `poll()` for an EOF, and then do the QueryWatermarkOffsets. The topic we're querying exists long before we do the QueryWatermarkOffsets. 

Is this expected behavior? Shouldn't we be able to query for watermarks without subscribing?

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): confluent-kafka-go: 0.11.6; librdkafka 0.11.6
 - [x] Apache Kafka broker version: Docker image: confluentinc/cp-enterprise-kafka:5.1.0
 - [x] Client configuration: `ConfigMap{...}`provided above.
 - [x] Operating system: Mac OSX
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I believe there is a timing issue in QueryWatermarkOffsets() when there are no existing broker connections.
Either waiting a short while, or calling something like GetMetadata() to ensure a connection, is a workaround until we fix this.

**Comment by sachnk** [comment]
Actually, in my case.. I was passing a timeout of `0` to QueryWatermarkOffsets. When I changed this to 10000, it works without any problems.

**Comment by edenhill** [comment]
Oh, right, that makes sense. 0 is not enough time to get the results 👍
