### ISSUE TITLE
Consume messages in batch

### ISSUE THREAD

**Issue by mr-woot** [confluentinc/confluent-kafka-go#283]
Description
===========
How to consume messages in batches for every REST call?

I have a route handler that consumes messages. My use case is to consume messages at most 5. In the example provided, it is running an infinite loop to consume messages.
```
run := true

	for run == true {
		select {
		case sig := <-sigchan:
			fmt.Printf("Caught signal %v: terminating\n", sig)
			run = false

		case ev := <-c.Events():
			switch e := ev.(type) {
			case kafka.AssignedPartitions:
				fmt.Fprintf(os.Stderr, "%% %v\n", e)
				c.Assign(e.Partitions)
			case kafka.RevokedPartitions:
				fmt.Fprintf(os.Stderr, "%% %v\n", e)
				c.Unassign()
			case *kafka.Message:
				fmt.Printf("%% Message on %s:\n%s\n",
					e.TopicPartition, string(e.Value))
			case kafka.PartitionEOF:
				fmt.Printf("%% Reached %v\n", e)
			case kafka.Error:
				// Errors should generally be considered as informational, the client will try to automatically recover
				fmt.Fprintf(os.Stderr, "%% Error: %v\n", e)
			}
		}
	}
```
Also, I have multiple partitions.

**Comment by mr-woot** [comment]
@edenhill

**Comment by edenhill** [comment]
There is no batch consumer interface, so I suggest that you accumulate N number of messages yourself by  reading c.Events() >=N times (more than N to handle other event types), limited by an overall timeout.

**Comment by mr-woot** [comment]
> There is no batch consumer interface, so I suggest that you accumulate N number of messages yourself by reading c.Events() >=N times (more than N to handle other event types), limited by an overall timeout.

"limited by an overall timeout", can you elaborate on this. Also, can you explain the case if the message reaches the last batch and is of size 3 (example, 103 messages => 103 % 5 = 3), how it should be handled.
