### ISSUE TITLE
Consumer gets all messages every time

### ISSUE THREAD

**Issue by alifpay** [confluentinc/confluent-kafka-go#284]
Description
===========

Strange issue has been started 3 days ago, consumer gets all messages periodically(15-20 minutes).

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion(0.11.6~1confluent5.0.1-1)`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

`
func consumes(wg *sync.WaitGroup) {
	wg.Add(1)
	consMap := &kafka.ConfigMap{
		"bootstrap.servers":               "kafka1.tj:9093, kafka2.tj:9093, kafka3.tj:9093",
		"security.protocol":               "SASL_SSL",
		"sasl.mechanisms":                 "SCRAM-SHA-256",
		"sasl.username":                   "test",
		"sasl.password":                   "test234",
		"go.events.channel.enable":        true,
		"go.application.rebalance.enable": true,
		"group.id":                        "ko2",
		"session.timeout.ms":              30000,
		"auto.offset.reset":               "earliest",
		"debug":                           "generic,broker,security",
	}

	c, err := kafka.NewConsumer(consMap)
	if err != nil {
		log.Println("Failed to create consumer", err)
		return
	}
	log.Printf("Created balanceReq consumer %v\n", c)
	err = c.SubscribeTopics([]string{"providerReq"}, nil)
	if err != nil {
		log.Println("Failed to Subscribe", err)
		return
	}
	run := true
	for run == true {
		select {
		case <-runStop:
			log.Println("Caught signal to stop consumer")
			run = false
			wg.Done()
		case ev := <-c.Events():
			switch e := ev.(type) {
			case kafka.AssignedPartitions:
				fmt.Fprintf(os.Stderr, "%% %v\n", e)
				c.Assign(e.Partitions)
			case kafka.RevokedPartitions:
				fmt.Fprintf(os.Stderr, "%% %v\n", e)
				c.Unassign()
			case *kafka.Message:
				if *e.TopicPartition.Topic == "providerReq" {
					fmt.Println(string(e.Value))
				}
			case kafka.Error:

				log.Println("Error: ", e)
			}
		}
	}
	fmt.Printf("Closing consumer\n")
	c.Close()
}
`

**Comment by alifpay** [comment]
`func consumes(wg *sync.WaitGroup) {
	wg.Add(1)
	consMap := &kafka.ConfigMap{
		"bootstrap.servers":               "kafka1.tj:9093, kafka2.tj:9093, kafka3.tj:9093",
		"security.protocol":               "SASL_SSL",
		"sasl.mechanisms":                 "SCRAM-SHA-256",
		"sasl.username":                   "test",
		"sasl.password":                   "test1234",
		"go.events.channel.enable":        true,
		"go.application.rebalance.enable": true,
		"group.id":                        "ko2",
		"session.timeout.ms":              30000,
		"auto.offset.reset":               "earliest",
		"debug":                           "generic,broker,security",
	}
	c, err := kafka.NewConsumer(consMap)
	if err != nil {
		log.Println("Failed to create consumer", err)
		return
	}
	log.Printf("Created balanceReq consumer %v\n", c)
	err = c.SubscribeTopics([]string{"providerReq"}, nil)
	if err != nil {
		log.Println("Failed to Subscribe", err)
		return
	}
	run := true
	for run == true {
		select {
		case <-runStop:
			log.Println("Caught signal to stop consumer")
			run = false
			wg.Done()
		case ev := <-c.Events():
			switch e := ev.(type) {
			case kafka.AssignedPartitions:
				fmt.Fprintf(os.Stderr, "%% %v\n", e)
				c.Assign(e.Partitions)
			case kafka.RevokedPartitions:
				fmt.Fprintf(os.Stderr, "%% %v\n", e)
				c.Unassign()
			case *kafka.Message:
				if *e.TopicPartition.Topic == "providerReq" {
					fmt.Println(string(e.Value))
				}
			case kafka.Error:
				// Errors should generally be considered as informational, the client will try to automatically recover
				log.Println("Error: ", e)
			}
		}
	}
	fmt.Printf("Closing consumer\n")
	c.Close()
}`

**Comment by edenhill** [comment]
If the consumer replays all messages from the beginning it sounds like there are no committed offsets to continue from (possibly due to offset topic retention policy), which makes it employ auto.offset.reset that you have set to earliest, thus start from beginning.

**Comment by alifpay** [comment]
Changed kafka server configs 
log.retention.hours=168
offsets.retention.hours=168

another question how to ensure that producer has delivered message successfully to kafka server?

I did something like this. if  m.TopicPartition.Error  == nil then success?

`prodMap := &kafka.ConfigMap{
		"bootstrap.servers":        "kafka1.tj:9093, kafka2.tj:9093, kafka3.tj:9093",
		"security.protocol":        "SASL_SSL",
		"sasl.mechanisms":          "SCRAM-SHA-256",
		"sasl.username":            "test",
		"sasl.password":            "test234",
		"debug":                    "generic,broker,security",
	}
	b := payRequest{
		Txnid: "12346", Checkid: "000", Account: "254.01", Amount: 1520, Paytype: "wallet", Providerid: 9, Phone: "902453003",
	}

	valByte, err := json.Marshal(b)
	if err != nil {
		log.Println("BalanceResp json.Marshal", err)
		return
	}
	
	topic := "testReq2"
	p, err := kafka.NewProducer(prodMap)
	if err != nil {
		log.Println("producer", err)
		return
	}
	deliveryChan := make(chan kafka.Event)

	err = p.Produce(&kafka.Message{TopicPartition: kafka.TopicPartition{Topic: &topic,
		Partition: kafka.PartitionAny},
		Value: valByte},
		deliveryChan)
	e := <-deliveryChan
	m := e.(*kafka.Message)
	if m.TopicPartition.Error != nil {
		log.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
	}
	close(deliveryChan)`

**Comment by edenhill** [comment]
Yes, your delivery error checking is correct.
Please also consider setting the "acks" configuration property to "all" to make sure produced messages are written to replicas before a successful ack is returned.

**Comment by alifpay** [comment]
thank you!
`prodMap := &kafka.ConfigMap{
		"bootstrap.servers":        "kafka1.tj:9093, kafka2.tj:9093, kafka3.tj:9093",
		"security.protocol":        "SASL_SSL",
		"sasl.mechanisms":          "SCRAM-SHA-256",
		"sasl.username":            "test",
		"sasl.password":            "test234",
		"acks":                     "all",
		"debug":                    "generic,broker,security",
	}`

is it correct?
another question: Do I call every time NewProducer for produce message? what is best practice? 
`p, err := kafka.NewProducer(prodMap)
	if err != nil {
		log.Println("producer", err)
		return
	}`

I did like below, does it has any issues?
example

var (
	pub *kafka.Producer
)

//Connect to kafka
func Connect(adr, username, pass string) (err error) {
	pub, err = kafka.NewProducer(&kafka.ConfigMap{
		"bootstrap.servers":        adr,
		"security.protocol":        "SASL_SSL",
		"sasl.mechanisms":          "SCRAM-SHA-256",
		"sasl.username":            username,
		"sasl.password":            pass,
		"acks":                     "all",
		//"debug":                    "generic,broker,security",
	})
	return
}

//produce response message
func produce(topic string, prm interface{}) {
	vByte, err := json.Marshal(prm)
	if err != nil {
		log.Println("BalanceResp json.Marshal", err)
		return
	}
	dChan := make(chan kafka.Event)
	err = pub.Produce(&kafka.Message{TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny}, Value: vByte}, dChan)
	e := <-dChan
	m := e.(*kafka.Message)
	if m.TopicPartition.Error != nil {
		log.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
	}
	close(dChan)
}

**Comment by edenhill** [comment]
No, you should now instantiate a new producer for each message, that will be very slow and ineffective.
Producer and Consumers are supposed to be long-lived objects.
