### ISSUE TITLE
[ERROR] pkg-config: exec: "pkg-config": executable file not found in $PATH

### ISSUE THREAD

**Issue by vietwow** [confluentinc/confluent-kafka-go#291]
Description
===========

Hi,

I am trying to build my app with lib "confluent-kafka-go" in alpine image and then got the error :

> # pkg-config --cflags  -- rdkafka
> pkg-config: exec: "pkg-config": executable file not found in $PATH

How to reproduce
================

Try to build any golang code which is using lib "confluent-kafka-go" and then build with Dockerfile below :

```
FROM golang:alpine

# Install OS-level dependencies.
RUN apk update &&     apk add curl git &&     curl https://glide.sh/get | sh

# Copy our source code into the container.
WORKDIR /go/src/logging
ADD . /go/src/logging

# Install our golang dependencies and compile our binary.
RUN glide install
RUN go install logging

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=0 /go/bin/logging .

CMD ["./logging"]
```
also here is my glide.yaml :

```
package: logging
import:
- package: github.com/confluentinc/confluent-kafka-go/kafka
```

Hope to receive your help. Thank you so much.

Best Regards,
VietNC

**Comment by edenhill** [comment]
You'll need to install pkg-config: add `pkgconfig` to your `akp add ..` installation line:
`RUN apk update &&     apk add curl git pkgconfig &&     curl https://glide.sh/get | sh`

**Comment by yilufeng0** [comment]
confluent-kafka-go cant  run on windows ,right?
