### ISSUE TITLE
channelBatchProducer buggy

### ISSUE THREAD

**Issue by abergmeier** [confluentinc/confluent-kafka-go#294]
Description
===========

From looking at the code it seems like the checks for later `Message`s are missing from the directly fetched `Message`s.
Also I am not really sure whether there is a benefit in having a this complicated implementation of `channelBatchProducer`.

=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): master

**Comment by edenhill** [comment]
The batch producer was added as a way to circumvent the high per-C-call overhead of cgo, unless you need high thruput I suggest using the standard Produce() interface.

Can you point me to the code you think is suspect to an issue?
