### ISSUE TITLE
Get details of consumer group

### ISSUE THREAD

**Issue by neonlight1203** [confluentinc/confluent-kafka-go#296]
Is there a way to get details of a consumer group, like topics it's consuming from, it's offset on various partitions? I see admin modules only for topic metadata.

**Comment by mr-woot** [comment]
+1

**Comment by edenhill** [comment]
Not yet, group management API is on the backlog.

**Comment by simnotes** [comment]
I just opened a PR containing a new GetConsumerGroupsMetadata API for consumers, producers and adminClients. #301 

Using this you can get a list of all consumer groups or a specific consumer group by name. The return value contains consumer group member information with corresponding topic subscription status.

**Comment by gromas** [comment]
GetConsumerGroupsMetadata does not works while you don't call Pool() or subscribe(). Exists any method for get current static group subscription partitions list without call pool()?

**Comment by milindl** [comment]
I think the Admin API ListConsumerGroupOffsets can be used in the latest version for fetching these details. Similarly useful methods like ListConsumerGroups and DescribeConsumerGroups are also available.

Closing this with the new API, please reopen for any questions.
