### ISSUE TITLE
how to create consumer specific partition 

### ISSUE THREAD

**Issue by youcandoit95** [confluentinc/confluent-kafka-go#299]
Description
===========
hello i used kafka consumer channel , but i'm not get information for consumer config to specific partition ? 

can somebody help me ?

this is my config code 
---------

broker := os.Args[1]
	group := os.Args[2]
	topics := os.Args[3:]
	sigchan := make(chan os.Signal, 1)
	signal.Notify(sigchan, syscall.SIGINT, syscall.SIGTERM)

	c, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers":               broker,
		"group.id":                        group,
		"session.timeout.ms":              10000,
		"heartbeat.interval.ms":           8000,
		"go.events.channel.enable":        true,
		"enable.auto.commit":              true,
		"go.application.rebalance.enable": true,
		// Enable generation of PartitionEOF when the
		// end of a partition is reached.
		"enable.partition.eof": true,
		"auto.offset.reset":    "earliest"})

**Comment by edenhill** [comment]
Sorry, I dont quite understand what you are trying to do, what information is it that you want, and for what purpose?
