### ISSUE TITLE
Make it possible to create kafka.Error for better unit testing

### ISSUE THREAD

**Issue by artemyarulin** [confluentinc/confluent-kafka-go#302]
Description
===========

Working with confluent-kafka-go and have mocked kafka for unit testing, everything is fine, but minor inconvenience is that struct `kafka.Error{}` has fields `code` which is not exportable, so I cannot create it manually to check how my consumer handles timeouts or any other issues. Wonder if it’s possible to make `func newGoError(code ErrorCode) (err Error)` public https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/error.go#L38 or maybe making `code` field public?

Very minor issue and I can always wrap error with my own struct, define some interfaces, but fix is very small, I can create PR if you thinks it's OK

How to reproduce
================

Checklist
=========
Please provide the following information:

confluent-kafka-go v0.11.6
librdkafka 722687 - 0.11.6
kafka confluentinc/cp-kafka:5.1.0

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [x] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Sounds like a good idea, PRs welcome!

I think you should call it `NewError(code ErrorCode)`, rather than `NewGoError(..)`.
We can change the name of `newError(the_C_type...)` later, as it is private.
