### ISSUE TITLE
go build github.com/confluentinc/confluent-kafka-go/kafka: build constraints exclude all Go files in 

### ISSUE THREAD

**Issue by punithck** [confluentinc/confluent-kafka-go#303]
Description
===========

when i try to run file I get an error as fallows
go build github.com/confluentinc/confluent-kafka-go/kafka: build constraints exclude all Go files in /home/go/src/github.com/confluentinc/confluent-kafka-go/kafka

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):v0.11.5 
 - [ ] Apache Kafka broker version:2.1.0
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:ubuntu 16.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ankurjha7** [comment]
Can you share the complete build command? It appears that you are buiding with CGO_ENABLED=0 which is not supported by confluent Kafka due to dependency on librdkafka

**Comment by punithck** [comment]
Hi  ankurjha7,
Thanks for your concern to resolve my issue with librdkafka. Actually I am
facing issue when i run Application which use go-confluent-kafka-client.
Its was saying that librdkafka I have installed is not supported.
My issue has been resolved by doing the fallowing activity.

./configure --prefix /usr --install-deps
in ~/.bashrc file I have added below line
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export LD_LIBRARY_PATH=/usr/lib

**Comment by oswee** [comment]
Could this be explained better?
Having same issue when trying to build multi-stage scratch Docker container.
```sh
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main ./cmd/command-handler/main.go
```

**Comment by ahzamali** [comment]
I was facing problem with static compilation with librdkafka and confluent-kafka-go, I changed the library to confluent-kafka-go-dev, now the static compilation on my ubuntu 18 box goes through but while building inside docker container I get the following error
>> LDFLAGS -X main.version=v0.0.0 -X main.gitsha=fe2e364efa6f0087 -X main.buildTime=2019.09.30.09.40.54.964416705 -X main.builtBy=ahzam -X main.buildHost=devbox -extldflags '-static'
echo ">>-> Building event-publisher-build..."
>>-> Building event-publisher-build...
app=event-publisher && \
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
	go build -a -ldflags "-X main.version=v0.0.0 -X main.gitsha=fe2e364efa6f0087 -X main.buildTime=2019.09.30.09.40.54.964416705 -X main.builtBy=ahzam -X main.buildHost=devbox -extldflags '-static'" -o dist/${app} ./src/cmd/${app}
build lightning-event-publisher/src/cmd/event-publisher: cannot load github.com/confluentinc/confluent-kafka-go-dev/kafka/librdkafka: no Go source files

Strangely it fails to find the librdkafka library

**Comment by edenhill** [comment]
@oswee You must not disable CGO with confluent-kafka-go (or confluent-kafka-go-dev) since it is backed by a C client.

**Comment by av0899** [comment]
> @oswee You must not disable CGO with confluent-kafka-go (or confluent-kafka-go-dev) since it is backed by a C client.

Hi @edenhill , im getting this error:
go build github.com/confluentinc/confluent-kafka-go/kafka: build constraints exclude all Go files in /usr/local/goibibo/source/src/goibibo_thor/vendors/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.0.0/kafka

**Comment by edenhill** [comment]
v1.0.0 is really old, use the latest version v1.6.1
