### ISSUE TITLE
Delivery report for produce channel

### ISSUE THREAD

**Issue by bulls-i** [confluentinc/confluent-kafka-go#305]
In case the producer is not connected, is there any way to know (like delivery reports) if the messages sent to the `ProduceChannel` are not being produced. When I stop my kafka server during the production of large number of messages, it keeps enqueuing to the channel. However when the server is back online, it sends all those message successfully. But I am considering the downtime to be much higher so that I can do something with messages.

Secondly, I want to start a service when the server is back online. What is the most appropriate way to do that?

@edenhill

**Comment by mr-woot** [comment]
@edenhill

**Comment by edenhill** [comment]
You can limit the amount of time the messages are queued in the producer by adjusting the `message.timeout.ms` configuration property (default 5 minutes).
