### ISSUE TITLE
panic: librdkafka debian packages no longer available in confluent's debian package repository

### ISSUE THREAD

**Issue by livnoorbrar** [confluentinc/confluent-kafka-go#308]
Description
===========
while building our project on gitlab runner we install librdkafka using apt-get and then build the go project using `go build -o $(APP_EXECUTABLE) -tags static`. As of a week ago, fetching of librdkafka dependencies is failing from the confluent's debian package repository. The following error can be seen
```
$ add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main"
$ apt-get update
Hit:1 https://packages.confluent.io/deb/5.0 stable InRelease
Get:2 https://packages.confluent.io/deb/4.1 stable InRelease [5,116 B]
Get:3 https://packages.confluent.io/deb/4.1 stable/main amd64 Packages [22.1 kB]
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:6 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Fetched 27.2 kB in 1s (24.1 kB/s)
Reading package lists...
$ apt-get -y install librdkafka-dev=0.11.4~1confluent4.1.2-1 librdkafka1=0.11.4~1confluent4.1.2-1 librdkafka++1=0.11.4~1confluent4.1.2-1
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '0.11.4~1confluent4.1.2-1' for 'librdkafka-dev' was not found
E: Version '0.11.4~1confluent4.1.2-1' for 'librdkafka1' was not found
E: Version '0.11.4~1confluent4.1.2-1' for 'librdkafka++1' was not found
ERROR: Job failed: exit code 1 
```

librdkafka packages are no longer available. Is there an alternate solution to this?

How to reproduce
================

```
$ add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/4.1 stable main
$ apt-get update
$ apt-get -y install librdkafka-dev=0.11.4~1confluent4.1.2-1 librdkafka1=0.11.4~1confluent4.1.2-1 librdkafka++1=0.11.4~1confluent4.1.2-1
```

Checklist
=========
Please provide the following information:

 - [ -] confluent-kafka-go and librdkafka version (`LibraryVersion()`): confluent-kafka-go(
`0.11.4`)
 - [ -] Operating system: Ubuntu 16.04
 - [ -] Critical issue

**Comment by edenhill** [comment]
Confluent Platform 4.1.3 has been released, with the packages changing version to ..confluent.4.1.3-1.
So you will need to change your version pinning to `librdkafka-dev=0.11.4~1confluent4.1.3-1`

**Comment by livnoorbrar** [comment]
@edenhill What do you recommend to do to avoid the debian package download failures if the previous versions will be removed from the debian repo. Currently, version pinning assumes that the published package will not be removed.

**Comment by edenhill** [comment]
I think my suggestion at this point would be not to pin the package to a specific version but rely on the apt picking up the latest version. Since librdkafka is API/ABI stable, a later version is always better .
