### ISSUE TITLE
How delete consumer group

### ISSUE THREAD

**Issue by mimol91** [confluentinc/confluent-kafka-go#311]
Is there possibility to remove consumer group? 
I have been reading documentation, but I didn't found any info how to do it.

// Yes I have some reasons to remove it

**Comment by ankurjha7** [comment]
I don't think either confluent-kafka-go or librddkafka itself offers such an option . Normally  there's no need to delete group metadata for the new consumer as the group is deleted when the last committed offset for that group expires.

**Comment by mimol91** [comment]
is it possible to define expiration time for new consumer group?

**Comment by ankurjha7** [comment]
You can set  "offset.retention.minutes" at the server config. However I have to check if you can change it from client side too

**Comment by vanipolnedi** [comment]
how to create consumer group??
