### ISSUE TITLE
OffsetsForTimes

### ISSUE THREAD

**Issue by lougxing** [confluentinc/confluent-kafka-go#312]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by lougxing** [comment]
librdkafka : git commit:  f460729fda3916485508e63f491bba4bcae3a80d
confluent-kafka-go : git commit: 315c5615e1c7a2a96f6421cae1c4463bcf77e9c1
kafka broker: kafka_2.12-2.1.1.tgz
  func main() {
`    host, err := os.Hostname()

    c, err := kafka.NewConsumer(&kafka.ConfigMap{
        "sasl.mechanisms":   "SCRAM-SHA-256",
        "security.protocol": "SASL_PLAINTEXT",
        "message.max.bytes": "1000000",
        "bootstrap.servers": "127.0.0.1:9092",
        "group.id":          "tests-group",
        "auto.offset.reset": "earliest",
        "sasl.username":     "test",
        "sasl.password":     "test-secret",
        "client.id":         host,
    })  

    if err != nil {
        panic(err)
    }   
    topic := "test-topic"
    offsets, err := c.OffsetsForTimes([]kafka.TopicPartition{{Topic: &topic, Partition: 199, Offset: -1}}, 100000000)
    fmt.Println(offsets[0], err)  // return latest offset

    offsets, err = c.OffsetsForTimes([]kafka.TopicPartition{{Topic: &topic, Partition: 199, Offset: 1553000712}}, 100000000)  // return earliest offset  
 fmt.Println(offsets[0], err)
}
`

OffsetsForTimes didn't return the offset greater than 1553000712. 
1553000712 is (Mar 19 21:05:12 CST 2019).

**Comment by edenhill** [comment]
Timestamps are in milliseconds since the epoch, so try 1553000712000

**Comment by lougxing** [comment]
It's OK. Thanks.
