### ISSUE TITLE
Error : could not determine kind of name for C.RD_KAFKA_RESP_ERR__FATAL

### ISSUE THREAD

**Issue by alishan-ahmed** [confluentinc/confluent-kafka-go#313]
Description
===========
In librdkafka version 0.11.6 and confluent-kafka-go current master branch
librdkafka installed through brew and cloned confluent-kafka-go master branch

ERROR :
could not determine kind of name for C.RD_KAFKA_RESP_ERR__FATAL
could not determine kind of name for C.rd_kafka_fatal_error

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [macOS
<img width="980" alt="Screenshot 2019-03-23 at 12 23 02 PM" src="https://user-images.githubusercontent.com/22687830/54862835-75363300-4d66-11e9-91fd-0cc6b5ea75c4.png">
 ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by litao3rd** [comment]
https://github.com/confluentinc/confluent-kafka-go/issues/61#issuecomment-303746159

solved by this response.

**Comment by gbbr** [comment]
I have run into this problem too. Don't install through `brew`. Instead, remove your installation completely and do:
```sh
git clone --branch v1.0.0-RC9 https://github.com/edenhill/librdkafka.git /tmp/librdkafka-v1.0.0-RC9
cd /tmp/librdkafka-v1.0.0-RC9
make uninstall
./configure && make
make install
```
That should do it.

**Comment by alishan-ahmed** [comment]
That worked well. Thanks for the help @gbbr
