### ISSUE TITLE
Question - Permanent check of GetFatalError()

### ISSUE THREAD

**Issue by nsagnett** [confluentinc/confluent-kafka-go#318]
Description
===========
Simple question : Can permanent check of GetFatalError() status cause performance issue ?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The underlying call itself is very cheap, just a mutex lock and unlock, but cgo adds some per-call overhead so I wouldn't call GetFatalError() on each message if the message rate exceeds ~50k msgs/s.

But you really only need to check for fatal errors if Produce() fails, alternatively handle it using a kafka.Error event handler that checks for ErrFatal, as shown in the example: 
https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/idempotent_producer_example/idempotent_producer_example.go#L97
