### ISSUE TITLE
Question - determine current controller broker id

### ISSUE THREAD

**Issue by fritchie** [confluentinc/confluent-kafka-go#319]
I see that I can get a broker list with GetMetadata but is there a way to determine which broker is the current controller?

**Comment by edenhill** [comment]
There is a librdkafka API, [rd_kafka_controllerid](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2295), that can be used to acquire the controller id, but it is not (yet) exposed as a method in the Go client.

**Comment by edenhill** [comment]
Add ClusterId() and ControllerId()

**Comment by rigelbm** [comment]
Added the APIs for ClusterID and ControllerID. They should be available in v1.2.0.

**Comment by edenhill** [comment]
v1.2.2 :)
