### ISSUE TITLE
Expose the librdkafka stats callback in the go client?

### ISSUE THREAD

**Issue by jiminoc** [confluentinc/confluent-kafka-go#32]
I was reading through the librdkafka docs and noticed there's a stats_cb mentioned in those docs but grep'ing the golang client codebase doesn't yield any hits on this. Is it planned to expose that to the go client?

thanks

**Comment by edenhill** [comment]
You are right, it is not yet implemented in the Go client but it is on the backlog.
(Issues like these helps prioritizing the backlog)

**Comment by agis** [comment]
Probably done by https://github.com/confluentinc/confluent-kafka-go/commit/18b5a55f7ee663a3fc44a42ca937ed276de529d0.
