### ISSUE TITLE
confluent-kafka-go requires librdkafka v1.0.0 or later

### ISSUE THREAD

**Issue by yueyuan4** [confluentinc/confluent-kafka-go#321]
Description
===========
Step 6/13 : RUN CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -o application .
 ---> Running in fec7c5824a2c
g/x/c/vendor/github.com/confluentinc/confluent-kafka-go/kafka
../vendor/github.com/confluentinc/confluent-kafka-go/kafka/00version.go:44:2: error: #error "confluent-kafka-go requires librdkafka v1.0.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
 #error "confluent-kafka-go requires librdkafka v1.0.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
  ^~~~~
The command '/bin/sh -c CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -o application .' returned a non-zero code: 2
time="2019-04-10T04:57:29Z" level=fatal msg="exit status 2"

How to reproduce
================
```
FROM golang:1.10.3-alpine as builder
WORKDIR /go/src/g/x/c
RUN apk add librdkafka-dev build-base
COPY . .
WORKDIR /go/src/g/x/c/app
RUN CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -o application .

FROM alpine:edge
WORKDIR /root/
COPY --from=builder /go/src/g/x/c/app/application ./
RUN apk add --no-cache librdkafka

EXPOSE 80 8080
ENTRYPOINT ["./application"]
```

**Comment by edenhill** [comment]
The librdkafka version in alpine is too old, build librdkafka from source instead.
