### ISSUE TITLE
Allow access to other standard partitioners, such as murmur2.

### ISSUE THREAD

**Issue by the4thamigo-uk** [confluentinc/confluent-kafka-go#325]
Description
===========
Currently the default partitioner is `consistent_random`, but this is not compatible with the default partitioner of the standard confluent java-based eco-system, which is `murmur2`. This means that stream joins fail to work correctly out of the box. Furthermore, it also doesn't seem possible to set the partitioner to `murmur2`.

Relates to discussion in #16.

How to reproduce
================

Partition a stream using the java streams dsl, and also using confluent-kafka-go, then try to join them into a single output stream using the java streams dsl.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): any
 - [ ] Apache Kafka broker version: any
 - [ ] Client configuration: `ConfigMap{...}` : any
 - [ ] Operating system: any
 - [ ] Provide client logs (with `"debug": ".."` as necessary) : N/A
 - [ ] Provide broker log excerpts : N/A
 - [ ] Critical issue : N/A

**Comment by mhowlett** [comment]
the java compatible partitioner is `murmur2_random`, which you set using the `partitioner` config property. Are you saying you get an error when you try to set this? if so, what version of librdkafka are you using?

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by the4thamigo-uk** [comment]
Not an error, just that it didn't give me the results I was expecting from my stream join. I have now set the configuration value `{topic}.partitioner=murmur2_random`  using  `ConfigMap.SetKey()` and it seems to work. So I will close this issue. Thanks for your help.
