### ISSUE TITLE
Kafka producer do not work when one broker is down

### ISSUE THREAD

**Issue by wjzhangcsu** [confluentinc/confluent-kafka-go#327]
Description
===========
I have started two kafka broker , and set config["bootstrap.servers"] = "host1:port,host2:port"   . 
 But kafka producer do not work when one broker is killed. It just return "Delivery failed: Local: Message timed out" . 

How to reproduce
================
1. start two kafka broker.
2. set set config["bootstrap.servers"] = "host1:port,host2:port"
3. produce msg.
4. kill one broker.
5. produce msg

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):  v0.11.6
 - [x] Apache Kafka broker version: 2.12-2.2.0
 - [x] Client configuration: config = make(kafka.ConfigMap) config["bootstrap.servers"] =  "host1:port,host2:port"
 - [x] Operating system: centos7.5

I want the producer work well when one broker is down,what should I do.

**Comment by edenhill** [comment]
The client will automatically detect when a new leader is elected for a topic-partition.

Maybe you dont have an in-sync replica broker to take owner leadership of the partition?
Check your replication.factor for the topic, and what brokers are in the ISR (in-sync replica set)

**Comment by wjzhangcsu** [comment]
@edenhill ,thanks edenhill. I  use this command to create topic   : ./kafka-topics.sh --create --zookeeper 192.168.1.120:2181,192.168.1.15:2181,192.168.1.80:2181 --replication-factor 2 --partitions 3 --topic test-5  .  My producer work well when I kill a broker ,but my consumer cannot work .

**Comment by edenhill** [comment]
When the consumer stops working when brokers go down it is usually because the __consumer_offsets topic gets under-replicated, preventing the group coordinator role to function.
