### ISSUE TITLE
 kafka.LibraryVersion not equal  C.RD_KAFKA_VERSION

### ISSUE THREAD

**Issue by ckwillling** [confluentinc/confluent-kafka-go#328]
Description
===========

collectd/main.go

```
package main

//采集模块

import "fmt"

//import "time"

/*
#cgo CXXFLAGS: -I.

#include <stdlib.h>
#include <string.h>
#include <librdkafka/rdkafka.h>
*/
import "C"
import "github.com/confluentinc/confluent-kafka-go/kafka"

func main() {
    v, vs := kafka.LibraryVersion()
    fmt.Println(v, vs, C.RD_KAFKA_VERSION)
}
```
```sh
go build
./collectd
```
output 
```
525824 0.8.6 16777471
```

525824  not equal 16777471.
which  is v0.8.6 not equal v1.0.0

It's obvious the `LibraryVersion()` should equal `RD_KAFKA_VERSION`

but it's not, which confused me.

expect your help, thx

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:  
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: CentOS release 6.6
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ckwillling** [comment]
after hours work,   i got this `https://github.com/confluentinc/confluent-kafka-python/issues/65#issuecomment-269964346`

1. I remove librdkafka (delete or librdkafka* in /usr/lib/ directory) and reinstall it
```
./configure && make && make install && ldconfig
```
2. I  reinstall this kafka package 
3. go build and run `collectd`

finally,  it equas with each other.

But actually, i still confused.

**Comment by edenhill** [comment]
Due to Go toolchain constraints, we rely on librdkafka to be installed on the system prior to build the Go client.
It seems you had an outdated version of librdkafka installed, and the build error tries to point this out.
Upgrading to the latest librdkafka version should fix the issue.
