### ISSUE TITLE
Consumer.SubscribeTopics for more than one topic is not working

### ISSUE THREAD

**Issue by felipejfc** [confluentinc/confluent-kafka-go#33]
Hello, I'm trying to subscribe to 2 topics at once calling Consumer.SubscribeTopics using this code:
```
	err := q.Consumer.SubscribeTopics(q.Topics, nil)
	if err != nil {
		l.WithError(err).Error("error subscribing to topics")
		return err
	}

	l.Info("successfully subscribed to topics")

	for q.run == true {
		select {
		case ev := <-q.Consumer.Events():
			switch e := ev.(type) {
			case kafka.AssignedPartitions:
				err = q.assignPartitions(e.Partitions)
				if err != nil {
					l.WithError(err).Error("error assigning partitions")
				}
			case kafka.RevokedPartitions:
				err = q.unassignPartitions()
				if err != nil {
					l.WithError(err).Error("error revoking partitions")
				}
			case *kafka.Message:
				q.receiveMessage(e.TopicPartition, e.Value)
			case kafka.PartitionEOF:
				q.handlePartitionEOF(ev)
			case kafka.OffsetsCommitted:
				q.handleOffsetsCommitted(ev)
			case kafka.Error:
				q.handleError(ev)
				q.StopConsuming()
				return e
			default:
				q.handleUnrecognized(e)
			}
		}
	}
```

q.Topics contains two topics that are successfully printed in the log.

But I'm only receiving kafka.AssignedPartitions events of one of the topics, the last in the list, and I'm also only receiving messages sent to it... any hints? am I doing something wrong?

I'm configuring kafka as follows:

```
kafka.NewConsumer(&kafka.ConfigMap{
			"bootstrap.servers":               q.Brokers,
			"group.id":                        q.ConsumerGroup,
			"session.timeout.ms":              q.SessionTimeout,
			"go.events.channel.enable":        true,
			"go.application.rebalance.enable": true,
			"enable.auto.commit":              true,
			"default.topic.config": kafka.ConfigMap{
				"auto.offset.reset":  q.OffsetResetStrategy,
				"auto.commit.enable": true,
			},
		})
```

kafka version is 0.10.1.1

**Comment by edenhill** [comment]
Do both topics exist in the cluster?

**Comment by felipejfc** [comment]
yes, they do, I've also tested it and reproduced locally...

**Comment by edenhill** [comment]
I can't reproduce this:
```
$ ./consumer_example :9093 g1 xtest1 xtest2 xtest3
Created Consumer rdkafka#consumer-1
% Message on xtest1[0]@0:
msg1
% Reached EOF at xtest1[0]@1(Broker: No more messages)
% Message on xtest2[0]@0:
msg2
% Message on xtest3[0]@0:
msg3
% Reached EOF at xtest2[0]@1(Broker: No more messages)
% Reached EOF at xtest3[0]@1(Broker: No more messages)
Ignored OffsetsCommitted (<nil>, [xtest1[0]@1 xtest2[0]@1 xtest3[0]@1])
```

Is your q.assignPartitions() loosing the extra topics perhaps?

**Comment by edenhill** [comment]
Can you print `q.Topics` prior to calling SubscribeTopics?

**Comment by felipejfc** [comment]
@edenhill is it possible that my assignPartitions is overwriting assignments?

```
func (q *KafkaConsumer) assignPartitions(partitions []kafka.TopicPartition) error {
	l := q.Logger.WithFields(logrus.Fields{
		"method":     "assignPartitions",
		"partitions": fmt.Sprintf("%v", partitions),
	})

	l.Debug("Assigning partitions...")
	err := q.Consumer.Assign(partitions)
	if err != nil {
		l.WithError(err).Error("Failed to assign partitions.")
		return err
	}
	l.Info("Partitions assigned.")
	return nil
}
```

full code is here

https://github.com/topfreegames/pusher/blob/master/extensions/kafka_consumer.go

if you do not find something that may be causing this, I will investigate it further, for now I got it to work using regex anyway, so this is not critic for me anymore, but I'm willing to help if you need

**Comment by edenhill** [comment]
The code looks fine, can't see anything obvious.
Could you add some debugging and see where the topic lists gets lost?

**Comment by qrpike** [comment]
Did anyone solve this issue?

Thanks,

**Comment by edenhill** [comment]
@qrpike What is the exact issue you are seeing? And do you have some code to show?

**Comment by qrpike** [comment]
@edenhill https://github.com/confluentinc/confluent-kafka-go/issues/115 turned out to be my issue. Working fine now.

**Comment by antonin07130** [comment]
Unforutnately I seem to have this vrey same issue :
consuming multiple topics does not work. In the end I reach (a fake) EOF for one of the two topics and only one topic is effectively consumed.
