### ISSUE TITLE
rd_kafka_purge api

### ISSUE THREAD

**Issue by khorshuheng** [confluentinc/confluent-kafka-go#332]
Description
===========
rd_kafka_purge() api has been introduced in librdkafka v1.0.0, but this api is not exposed in confluent-kafka-go. Is there any plan of exposing this api in confluent-kafka-go, and if not, what would be the workaround to achieve similar result?

**Comment by edenhill** [comment]
We're adding additional methods when there's user demand, so your interest in the purge API is duly noted.

One way to speed up this process is submitting a PR with the change-

**Comment by jeffwidman** [comment]
Should this be closed as it appears it was fixed by https://github.com/confluentinc/confluent-kafka-go/pull/347?

**Comment by edenhill** [comment]
Yes! Thank's Jeff :+1:
