### ISSUE TITLE
No compression when topic compression.type set to producer

### ISSUE THREAD

**Issue by mpipet** [confluentinc/confluent-kafka-go#333]
Description
===========
Message content is not compressed at all if a **compression.type** is set on producer side and the topic **compression.type** is **producer**.

zlib-dev was installed at librdkafka compilation

When using the kafka-console-producer with **compression.type** to gzip, the message is correctly compressed in the log file.

How to reproduce
================
Produce to a topic with compression.type producer, from a producer with compression.type or compression.codec set to gzip.

The log file on broker side should contains the log content uncompressed

Checklist
=========
Please provide the following information:

 - confluent-kafka-go v1.0.0, librdkafka v1.0.0
 - Apache Kafka broker version: 2.1.1
 - Client configuration: `ConfigMap{"bootstrap.servers": broker,  "compression.type":  "gzip"}`
 - Operating system: Linux

**Comment by edenhill** [comment]
Content will only be sent compressed if the compressed size is smaller than the uncompressed size.
Try increasing the batch accumulation time with `linger.ms=N` on the producer.

**Comment by mpipet** [comment]
Thank you for the quick, I just tested with a bigger payload and it works, closing
