### ISSUE TITLE
C.RD_KAFKA_EVENT_OAUTHBEARER_TOKEN_REFRESH

### ISSUE THREAD

**Issue by dc-dos** [confluentinc/confluent-kafka-go#335]
Description
===========

Can't "go get" the lib. Breaks with:

../../../.gvm/pkgsets/go1.11/global/src/github.com/confluentinc/confluent-kafka-go/kafka/adminapi.go:930:82: could not determine kind of name for C.RD_KAFKA_EVENT_OAUTHBEARER_TOKEN_REFRESH

How to reproduce
================

 go get -u github.com/confluentinc/confluent-kafka-go/kafka

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
     librdkafka-1.0.0-RC9
 - [ ] Apache Kafka broker version

 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
       OSX
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Pin the import to v1:
`import "gopkg.in/confluentinc/confluent-kafka-go.v1/kafka"`
