### ISSUE TITLE
pkg-config - need install instructions (can we live without it)? 

### ISSUE THREAD

**Issue by jayunit100** [confluentinc/confluent-kafka-go#336]
Description
===========
Thanks for this great library ! My first issue so forgive me if any ignorance :) 

It seems like pkgconfig (maybe this is needed for `rdkafka` ?) makes the setup of this pretty clumsy:  I cant compile these into my app on OS x out of the box.

... I saw #291 but that seemed to depend on glide, so Im assuming docs for pkg-config and why we need it havent been updated in a while.  Can we live without it? 

The simplest way to close this issue i guess is to explain why pkg config is needed, and maybe if so why rdkafka is needed... and point to docs on how to set those up.

How to reproduce
================

```
➜  kafka-sim git:(master) ✗  go get github.com/rjeczalik/pkgconfig/cmd/pkg-config
➜  kafka-sim git:(master) ✗ go get -u gopkg.in/confluentinc/confluent-kafka-go.v1/kafka

# pkg-config --cflags  -- rdkafka
error <autogenerated>: no library found in $GOPATH: rdkafka
error $GOPATH: no library found in $GOPATH: rdkafka
error github.com: PKG_CONDIF_GITHUB not exported, skipping github.com lookup
error $PKG_CONFIG_PATH: open rdkafka.pc: no such file or directory
pkg-config: exit status 1
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): master 
 - [ ] Apache Kafka broker version: 
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by chuyeow** [comment]
I had a similar question as well and found the answer in the readme at https://github.com/confluentinc/confluent-kafka-go#installing-librdkafka.

If that works for you, please close this issue.
