### ISSUE TITLE
mklove: handle --disable-shared --silent

### ISSUE THREAD

**Issue by FU100** [confluentinc/confluent-kafka-go#339]
Description
===========

while compiling for linux/arm64 with xgo print the following message.
"Unknown option disable-shared"

How can I skip this?

How to reproduce
================

1.
/gopath/src/github.com/karalabe/xgo# ./xgo --deps=https://github.com/edenhill/librdkafka/archive/v1.0.1-RC1.tar.gz --targets=linux/arm64 /gopath/src/test.com/t12

Checking docker installation...
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:56:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Tue Feb 12 22:47:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Checking for required docker image karalabe/xgo-latest... found.
Dependency already cached: /root/.xgo-cache/v1.0.1-RC1.tar.gz.

Cross compiling test.com/t12...
Building locally test.com/t12...
Compiling for linux/arm64...
Configuring dependency librdkafka-1.0.1-RC1 for aarch64-linux-gnu...
**Unknown option disable-shared**
Usage: ./configure [OPTIONS...]

 mklove configure script - mklove, not autoconf
 Copyright (c) 2014-2019 Magnus Edenhill - https://github.com/edenhill/mklove

 librdkafka - The Apache Kafka C/C++ library
 Copyright (c) 2012-2015 Magnus Edenhill

Standard options:
   --prefix=PATH                        Install arch-independent files in PATH [/usr/local]
   --exec-prefix=PATH                   Install arch-dependent files in PATH [$prefix]

2. my test  main.go file
package main

import (
  "fmt"
  "gopkg.in/confluentinc/confluent-kafka-go.v1/kafka"
)

func main() {

  c, err := kafka.NewConsumer(&kafka.ConfigMap{
    "bootstrap.servers": "localhost",
    "group.id":          "myGroup",
    "auto.offset.reset": "earliest",
  })

  if err != nil {
    panic(err)
  }

  c.SubscribeTopics([]string{"myTopic", "^aRegex.*[Tt]opic"}, nil)

  for {
    msg, err := c.ReadMessage(-1)
    if err == nil {
      fmt.Printf("Message on %s: %s\n", msg.TopicPartition, string(msg.Value))
    } else {
      // The client will automatically try to recover from all errors.
      fmt.Printf("Consumer error: %v (%v)\n", err, msg)
    }
  }

  c.Close()
}

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): librdkafka:v1.0.1-RC1
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: ubuntu 16.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/karalabe/xgo/blob/d164e4e53dfdc4e25de90a762d213f8d397e24a1/docker/base/build_deps.sh#L20

xgo is passing some flags it probably doesn't need to, like --disable-shared, which is not supported by mklove in librdkafka.

**Comment by FU100** [comment]
Is there any steps that I can build this go program for arm?
