### ISSUE TITLE
Possible Producer Memory Leak?

### ISSUE THREAD

**Issue by abarrios1** [confluentinc/confluent-kafka-go#341]
Description
===========
I have been utilizing Confluent Kafka Go and creating docker images and containerizing them inside of kubernetes. I noticed when running a Kafka Producer without deliberately closing, that memory will increase and, depending on how much memory I limit on Kubernetes, will throw OOM error. 

- I am curious if this is a memory leak with the C wrapper library? 

- Maybe I am not using your library correctly? 

- Any suggestions on using Kafka Consumer and Producer cooperatively?

Any insights will be greatly appreciated!

How to reproduce
================
To reproduce, create a Kafka Consumer and Kafka Producer. Constantly have Kafka Consumer listen to a topic, when a message is consumed fire off a goroutine function passing a reference to the Kafka Producer. Inside that goroutine func, Kafka producer passed will produce data, but over time memory will increase significantly. The code has been Dockered and Containerized to deploy on Kubernetes.

Below I attached a pdf that shows the heap profile of our program. It shows that C wrapper func is the main cause for increasing memory. After further debugging inside your code, noticed that this is from producing messages, not consuming. I have created another program that brings up a kafka producer and tears it down, but that is really inconvenient and inefficient for sending millions of data in real time/near real time. 
[modem_rf_heap.pdf](https://github.com/confluentinc/confluent-kafka-go/files/3297299/modem_rf_heap.pdf)

Here is the setup with Kafka Consumer and Producer:

	// Producer Settings
	producer, err := kafka.NewProducer(&kafka.ConfigMap{
		"bootstrap.servers":      os.Getenv("KAFKA_PRODUCER_BROKERS"),
		"go.batch.producer":      true,
		"queue.buffering.max.ms": 10,
	})
	if err != nil {
		panic(err)
	}
	
	// Consumer Settings
	consumer, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers":     kf.Brokers,
		"broker.address.family": "v4",
		"group.id":              kf.Group,
		"session.timeout.ms":    6000,
		"auto.offset.reset":     "latest"})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create consumer: %s\n", err)
		os.Exit(1)
	}

	fmt.Printf("Created Consumer %v\n", consumer)

	err = consumer.SubscribeTopics(kf.Topics, nil)

	sigchan := make(chan os.Signal, 1)
	signal.Notify(sigchan, syscall.SIGINT, syscall.SIGTERM)

	// Start loop to consume messages
	run := true
	for run == true {
		select {
		case sig := <-sigchan:
			fmt.Printf("Caught signal %v: terminating\n", sig)
			run = false
		default:
			ev := consumer.Poll(100)
			if ev == nil {
				continue
			}
			switch e := ev.(type) {
			case *kafka.Message:
				lock.Lock()
				err := json.Unmarshal(e.Value, &modems)
				if err != nil {
					fmt.Printf("Unmarshal error: %v\n", err)
				}
				lock.Unlock()
				
				// Go thread that will collect stats, whenever a message is consumed. This 
				// will send a producer to the thread and then produce results to topic.
				go ModemRFStats(modems, &producer)
			case kafka.Error:
				if e.Code() == kafka.ErrAllBrokersDown {
					run = false
				}
			default:
			}

		}
	}
 
Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion(1.0.0)`):
 - [x] Apache Kafka broker version: `2.2.0`
 - [x] Client Producer configuration: `ConfigMap{
		"bootstrap.servers":      os.Getenv("KAFKA_PRODUCER_BROKERS"),
		"go.batch.producer":      true,
		"queue.buffering.max.ms": 10,
	}`
 - [x] Client Consumer configuration: `ConfigMap{
		"bootstrap.servers":     "Broker-IP-Address:9200",
		"broker.address.family": "v4",
		"group.id":              "ConsumerGroup",
		"session.timeout.ms":    6000,
		"auto.offset.reset":     "latest"})
	}`
 - [x] Operating system: Linux (Alpine) 
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The memory profiler suggests that it is memory for the delivery report messages that is taking up most of the space.
Are you reading from the `producer.Events()` channel? If not, you should (to know that your messages were actually delivered, or not), or disable it (which is a bad idea because you wont get any indication of error) with `go.delivery.reports=false`

**Comment by abarrios1** [comment]
I am not reading from the producer.Events() channel, but am using elasticsearch stack and can see the count of records in Kibana and know if messages are delivered. 
Does a Kafka Producer need to be closed in order to prevent a memory leak

**Comment by edenhill** [comment]
Then set `go.delivery.reports=false` and make sure to call Flush() before closing your producers, and you should be fine.
