### ISSUE TITLE
Consumer Connection The problem

### ISSUE THREAD

**Issue by xufei56789** [confluentinc/confluent-kafka-go#343]
Description
===========
I am using the kafka environment built by the docker container.
When the consumer connects to kafka, it gives an error：[
map[auto.offset.reset:earliest bootstrap.servers:kafka:9092 group.id:ReleasePosts]Consumer error: GroupCoordinator: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 5ms in state CONNECT) (<nil>)
]

Producer will not report an error when sending a message to the subject.

How to reproduce
================
### **Consumer**

package main

import (
	"github.com/confluentinc/confluent-kafka-go/kafka"
	"fmt"
	"os"
)
var (
	conf kafka.ConfigMap
	c    *kafka.Consumer
)

var topic = "ReleasePosts"

func main() {
	c.SubscribeTopics([]string{topic, "^aRegex.*[Tt]opic"}, nil)
	for {
		msg, err := c.ReadMessage(-1)
		if err == nil {
			fmt.Printf("Message on %s: %s\n", msg.TopicPartition, string(msg.Value))
		} else {
			// The client will automatically try to recover from all errors.
			fmt.Printf("Consumer error: %v (%v)\n", err, msg)
		}
	}

	c.Close()

}

func initConf()  {
	conf = kafka.ConfigMap{
		"bootstrap.servers": "kafka:9092",
		"group.id":          topic,
		"auto.offset.reset": "earliest",
	}
}
func initKafka()  {
	initConf()
	var err error
	fmt.Printf("%+v", conf)
	c, err = kafka.NewConsumer(&conf)
	if err != nil {
		fmt.Printf("Failed to create producer: %s\n", err)
		os.Exit(1)
	}
}

func init() {
	initKafka()
}

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by xufei56789** [comment]
@edenhill   Thank you for your guidance, it’s great.
