### ISSUE TITLE
error "Local: Queue full" when the producer is overwhelmed

### ISSUE THREAD

**Issue by XiaochenCui** [confluentinc/confluent-kafka-go#346]
Description
===========
In my benchmark test for confluent kafka, the test script write 200 million messages (each in size 30 - 1000 bytes) to kafka continuously.
After write 1 million messages, the error "Local: Queue full" will occurred.
I found this may be helpful, but it doesn't work:
https://github.com/confluentinc/confluent-kafka-go/issues/89#issuecomment-325098746

Here comes the test script:

```
func ConfluentKafkaNormalProduce() {
	var p *confluentKafka.Producer
	var err error

	if enableSSL {
		p, err = confluentKafka.NewProducer(&confluentKafka.ConfigMap{
			"bootstrap.servers":  viper.GetStringSlice("kafkaConfig.sslBrokerUrls")[0],
			"security.protocol":  "ssl",
			"ssl.ca.location":    "../ca-cert",
		})
	} else {
		p, err = confluentKafka.NewProducer(&confluentKafka.ConfigMap{
			"bootstrap.servers": viper.GetStringSlice("kafkaConfig.brokerUrls")[0],
		})
	}

	if err != nil {
		panic(err)
	}

	defer p.Close()

	doneChann := make(chan bool)

	go func() {
		defer close(doneChann)
		for e := range p.Events() {
			switch ev := e.(type) {
			case *confluentKafka.Message:
				if ev.TopicPartition.Error != nil {
					log.Printf("ev: %v", ev.TopicPartition.Error)
					errors++
				} else {
					successes++
				}
			}

			if successes+errors == count {
				return
			}
		}
	}()

	produceStart()

	topic := viper.GetString("kafkaConfig.topic")
	for n := 0; n < count; n++ {
		bs := getPkg()
		err = p.Produce(&confluentKafka.Message{
			TopicPartition: confluentKafka.TopicPartition{Topic: &topic, Partition: confluentKafka.PartitionAny},
			Value:          bs,
		}, nil)
		if err != nil {
			log.Printf("err: %v", err)
		}
		produce++
		produceWatch(n)
	}

	_ = <-doneChann

	// Wait for message deliveries before shutting down
	p.Flush(10 * 1000)

	produceEnd()
}
```

How to reproduce
================

The code snippet contains some other functions not involved.
If you want to run it yourself, try remove those code.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 confluent-kafka-go: confluent-kafka-go.v1 (gopkg.in/confluentinc/confluent-kafka-go.v1 v1.0.0)
 librdkafka: v1.1.0
 - [ ] Apache Kafka broker version: 2.12-2.2.0 (running via docker image wurstmeister/kafka:2.12-2.2.0)
 - [ ] Client configuration: 
 ```
 confluentKafka.ConfigMap{
			"bootstrap.servers":  viper.GetStringSlice("kafkaConfig.sslBrokerUrls")[0], # localhost:9093
			"security.protocol":  "ssl",
			"ssl.ca.location":    "../ca-cert",
		}
 ```
 - [ ] Operating system: docker for mac
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 ```
2019/06/28 08:19:06 err: Local: Queue full
2019/06/28 08:19:06 err: Local: Queue full
2019/06/28 08:19:06 err: Local: Queue full
2019/06/28 08:19:06 err: Local: Queue full
2019/06/28 08:19:06 err: Local: Queue full
...
 ```
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The queue will fill up if:
 1. messages can't be sent to the broker fast enough (slow network, slow brokers)
 2. the Event queue is not being served

**Comment by cedricve** [comment]
@edenhill  any way to recover from this (instead of upgrading hardware)?

**Comment by edenhill** [comment]
Increase linger.ms to improve throughput.
Increase the producer queue.buffering.max.messages (et.al) if necessary.

But at the end of the day, if the produce rate is higher than the cluster throughput there will be a backlog building up.

**Comment by denis-rusakov** [comment]
@edenhill  is there a way to see that it's actually the case? how can i be sure that it's my machine under performing around context switching? is there a way to see a "lag" on the producer side

**Comment by mhowlett** [comment]
@cedricve - you can just throttle at the application level by delaying for some amount of time when you get this error and then trying again (no risk of duplicates).

@denis-rusakov - statistics will tell you this
 - https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/stats_example/stats_example.go
 - https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

**Comment by denis-rusakov** [comment]
@mhowlett  how exactly does it work? i've created the statistics poller consumer, similar to the attached example,
but now when i'm looking at the exported statistics(exported only those i need)
"kafka-stats": {"metadata_cache_cnt": 1, "msg_cnt": 0, "msg_max": 0, "msg_size": 0, "msg_size_max": 0, "replyq": 0, "rx": 3192, "rx_bytes": 1812451, "rxmsg_bytes": 69974, "rxmsgs": 85, "simple_cnt": 0, "time": 1610906233, "ts": 4162595338592, "tx": 3195, "tx_bytes": 1322407, "txmsg_bytes": 0, "txmsgs": 0},
i wonder why msg_max msg_size_max is 0, this also made me wonder, does this code assumes that the producer client is running on the machine on which i run this consumer for statistics? how does it know of which producer client to get the stats for? for example it's stated
that msg_cnt("Current number of messages in producer queues") how does it know to which producer client to listen to?

**Comment by huantt** [comment]
Flush all pending messages then retry worked for me.
```golang
func (k *Producer) PublishMessage(ctx context.Context, key string, payload interface{}, topic string, headers map[string]string) error {
	value, err := json.Marshal(payload)
	if err != nil {
		return err
	}

	message := &confluentKafka.Message{
		Value: value,
		Key:   []byte(key),
		TopicPartition: confluentKafka.TopicPartition{
			Topic:     &topic,
			Partition: confluentKafka.PartitionAny,
		},
	}
	if len(headers) > 0 {
		var kafkaHeaders []confluentKafka.Header
		for key, value := range headers {
			kafkaHeaders = append(kafkaHeaders, confluentKafka.Header{
				Key:   key,
				Value: []byte(value),
			})
		}
		message.Headers = kafkaHeaders
	}
	err = k.kafkaProducer.Produce(message, k.deliveryChan)

	if kafkaError, ok := err.(confluentKafka.Error); ok && kafkaError.Code() == confluentKafka.ErrQueueFull {
		log.Error("Kafka local queue full error - Going to Flush then retry...")
		flushedMessages := k.kafkaProducer.Flush(30 * 1000)
		log.Infof("Flushed kafka messages. Outstanding events still un-flushed: %d", flushedMessages)
		return k.PublishMessage(ctx, key, payload, topic, headers)
	}

	return err
}
```

**Comment by yucehasan** [comment]
> the Event queue is not being served

This was the problem in my case. Adding a simple channel handler for `producer.Events` was the solution.
