### ISSUE TITLE
Question - How to do batching in producer client

### ISSUE THREAD

**Issue by pragmaticpi** [confluentinc/confluent-kafka-go#348]
Description
===========
Hi, I am trying to do batching in producer using the configuration <code>batch.num.messages</code>, since afaik <code>batch.size</code> doesn't work in librdkafka. I am using the producer channels code from examples directory with those extra configurations.

How to reproduce
================
```
        doneChan := make(chan struct{})

	go func() {
		defer close(doneChan)
		for e := range p.Events() {
			switch ev := e.(type) {
			case *kafka.Message:
				m := ev
				if m.TopicPartition.Error != nil {
					fmt.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
				} else {
					fmt.Printf("Delivered message to topic %s [%d] at offset %v\n",
						*m.TopicPartition.Topic, m.TopicPartition.Partition, 
                                                 m.TopicPartition.Offset)
				}
			default:
				fmt.Printf("Ignored event: %s\n", ev)
			}
		}
	}()

	for i := 0; i <= 1000; i++ {
		value := "Hello " + strconv.Itoa(i)
		p.ProduceChannel() <- &kafka.Message{TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny}, Value: []byte(value)}
	}
	<-doneChan

	p.Close()
```
Producer Configs

``` 
                 "enable.idempotence":  true,
		"delivery.timeout.ms": 60000,
		"batch.num.messages": 10, 
```

So, all 1000 messages in the for loop is being sent all together but it should happen in the batch of 10.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): both <code>1.0.0</code>
 - [x] Apache Kafka broker version: <code>2.2.1</code>
 - [x] Operating system: MacOS

**Comment by edenhill** [comment]
Batching of messages is done on the protocol level and is not exposed to the application (other than through linger.ms and batch.num.messages).
The application still produces messages one by one, and gets delivery reports one by one, regardless of the number of messages that were sent in a single batch.

**Comment by pragmaticpi** [comment]
Since I am using batch.num.messages for batching, you are saying that the batching is happening with batch size 5, I just can't see that in my application. Is there a way of verifying that?

**Comment by edenhill** [comment]
The easiest way is to set the `debug` config property to `msg`, and you should see log lines telling how many messages are in each produced MessageSet.
Otherwise look at the `batchcnt` metric in Statistics, https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md, but that requires more work.

**Comment by pragmaticpi** [comment]
I added <code>debug:msg</code> and <code>batch.num.messages:5</code> in configuration and got following logs, 

```
Delivered message to topic topicA [0] at offset 1465
%7|1561804852.317|PRODUCE|rdkafka#producer-1| [thrd:127.0.0.1:9092/0]: 127.0.0.1:9092/0: topicA [0]: Produce MessageSet with 1 message(s) (87 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1561804852.319|MSGSET|rdkafka#producer-1| [thrd:127.0.0.1:9092/0]: 127.0.0.1:9092/0: topicA [0]: MessageSet with 1 message(s) (MsgId 0, BaseSeq -1) delivered
Delivered message to topic topicA [0] at offset 1466
%7|1561804852.319|PRODUCE|rdkafka#producer-1| [thrd:127.0.0.1:9092/0]: 127.0.0.1:9092/0: topicA [0]: Produce MessageSet with 1 message(s) (87 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1561804852.321|MSGSET|rdkafka#producer-1| [thrd:127.0.0.1:9092/0]: 127.0.0.1:9092/0: topicA [0]: MessageSet with 1 message(s) (MsgId 0, BaseSeq -1) delivered
Delivered message to topic topicA [0] at offset 1467
```

Here you can see still Messages sets have only 1 message in it. So, batching is not working.
One more thing, I noticed after adding batching config, I am receiving each delivered messageSet report after some time, instead of immediately if I removed batching config.

**Comment by edenhill** [comment]
You will need to adjust linger.ms as well, see https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#performance

**Comment by pragmaticpi** [comment]
It didn't work.

I am pasting my actual code on which I am trying to do batching, maybe this will help you:

Main.go

```
package main

import (
	"test-kafka/prod"
)

func main() {
	prod.InitConsumer()

	for i := 0; i <= 100; i++ {
		prod.ProduceMessage(i)
	}
}
```

prod/producer.go

```
package prod

import (
	"fmt"
	"os"
	"os/signal"
	"strconv"
	"syscall"

	"gopkg.in/confluentinc/confluent-kafka-go.v1/kafka"
)

type Report struct {
	Isdelivered bool
}

var p *kafka.Producer
var done = make(chan *Report)
var topic = "topicA"

func InitConsumer() {
	broker := "localhost:9092"
	var err error
	p, err = kafka.NewProducer(&kafka.ConfigMap{
		"bootstrap.servers":   broker,
		"enable.idempotence":  true,
		"delivery.timeout.ms": 60000,
		"linger.ms":           10000,
		"batch.num.messages":  5,
		"debug":               "msg",
	})

	if err != nil {
		fmt.Println("Error creating producer", err)
		os.Exit(1)
	}

	fmt.Printf("Created Producer %v\n", p)

	go event()

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)

	go func() {
		select {
		case sig := <-c:
			fmt.Println("signal caught !!!", sig)
			os.Exit(1)
		}
	}()
}

func ProduceMessage(i int) *Report {
	value := "Hello " + strconv.Itoa(i)
	p.ProduceChannel() <- &kafka.Message{TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny}, Value: []byte(value)}
	return <-done
}

func event() {
	defer close(done)
	fmt.Println("p", p)
	for e := range p.Events() {
		switch ev := e.(type) {
		case *kafka.Message:
			m := ev
			if m.TopicPartition.Error != nil {
				fmt.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
				done <- &Report{
					Isdelivered: false,
				}
			} else {
				fmt.Printf("Delivered message to topic %s [%d] at offset %v\n",
					*m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
				done <- &Report{
					Isdelivered: true,
				}
			}
		default:
			fmt.Printf("Ignored event: %s\n", ev)
		}
	}
}
```

Logs are the same as before. Are there any errors on my code?

**Comment by edenhill** [comment]
Looks like you've implemented a sync producer, you produce one message and wait for its delivery report. By doing this you naturally can only have one message in a batch at the time since you only produce one message at the time.
Suggest you decouple the delivery reports from the producing.

**Comment by pragmaticpi** [comment]
But if I want the delivery report, how will I get that for the batching?

**Comment by edenhill** [comment]
No, the notion of batches is not exposed to the application, it is a protocol-level semantic, not a message-level semantic.

Batching is only used to improve performance, and that is all handled by the client implementation on the kafka protocol level.

You will get one delivery report for message, regardless of batching.

The level of batching can be *monitored* through Stats:
`batchcnt` see https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md,

**Comment by pragmaticpi** [comment]
As you said, waiting for the delivery report makes producer synchronous but as per my requirement, I have to run some processing once the batch is successful. Is there any workaround? I really need a successful/failure report.

Also, I am getting these logs:

```
%7|1562045521.246|PRODUCE|rdkafka#producer-1| [thrd:sasl_ssl://b3-pkc-438qm.us-east-1.aws.confluent.cloud:9092/3]: sasl_ssl://b3-pkc-438qm.us-east-1.aws.confluent.cloud:9092/3: small_customers_userprofiles [0]: No more space in current MessageSet (366 message(s), 998817 bytes)
%7|1562045521.246|PRODUCE|rdkafka#producer-1| [thrd:sasl_ssl://b3-pkc-438qm.us-east-1.aws.confluent.cloud:9092/3]: sasl_ssl://b3-pkc-438qm.us-east-1.aws.confluent.cloud:9092/3: small_customers_userprofiles [0]: Produce MessageSet with 366 message(s) (41760 bytes, ApiVersion 7, MsgVersion 2, MsgId 12079, BaseSeq 12078, PID{Id:30011,Epoch:0})
```
It is saying there is no more space in message set. What is the space size? Is it configurable?

**Comment by zzy0705** [comment]
I followed the example above to try the channel based producer, but not able to reach `p.Close()`, it hang before `<-doneChan` with last message show:
```
%7|1562061420.581|MSGSET|rdkafka#producer-3| [thrd:kafka:9092/bootstrap]: kafka:9092/1: raw-meter-data [0]: MessageSet with 1 message(s) (MsgId 1001, BaseSeq 1000) delivered
Delivered message to topic raw-meter-data [0] at offset 5209
```

```
for i := 0; i <= 1000; i++ {
		value := "Hello " + strconv.Itoa(i)
		p.ProduceChannel() <- &kafka.Message{TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny}, Value: []byte(value)}
	}
	<-doneChan

	p.Close()
```

any code that missing in the script?  As I want to reach p.Close() and return after 1000 messages been produced...

**Comment by edenhill** [comment]
A better approach might be to use producer transactions, which are coming in Q4.
