### ISSUE TITLE
How to set broker.address.family to v4

### ISSUE THREAD

**Issue by nitishnference** [confluentinc/confluent-kafka-go#354]
I am getting this error as my localhost points to v4 and v6 but the broker is running only on v4. GroupCoordinator: Connect to ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT) (<nil>) .  How can I set this property broker.address.family

**Comment by edenhill** [comment]
https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/consumer_example/consumer_example.go#L47
