### ISSUE TITLE
ProduceChannel() becomes blocked indefinitely on an otherwise healthy connection

### ISSUE THREAD

**Issue by jpiper** [confluentinc/confluent-kafka-go#356]
Description
===========

We are performing load testing and I seem to be having a critical issue similar to #251 where production locks up. It's pretty reproducible under high load (below ~60k messages/s everything is stable). As soon as we hit ~60k rps everything hangs, even though kafka is up and available (other producers are still working). We are reading the events off the event channel fine, so we're not blocking there. I would in the situation that the producer can't keep up that it drops messages, rather than lock up. There's nothing in the broker logs.

Really want to get to the bottom of this, so if you have any ideas on things I can do to help debug do let me know.

My config is

```
debug=broker,topic,msg
message.max.bytes=25165824 # matches broker config
metadata.request.timeout.ms=5000
message.timeout.ms=30000
socket.timeout.ms=10000
retry.backoff.ms=250
batch.num.messages=10000
queue.buffering.max.ms=10000
queue.buffering.max.messages=10000000
queue.buffering.max.kbytes=2097151
compression.type=snappy
acks=1
retries=2
security.protocol=ssl
<ssl_stuff>
```

At some point the `ProduceChannel()` just blocks indefinitely, - the librdkafka debug logs don't indicate anything is wrong, they just stop after some delivery confirmation, and later then print that the broker has disconnected them due to idle timeout.

```
%7|1563409867.622|PRODUCE|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.89:6443/89]: ssl://XXX.XXX.XXX.89:6443/89: blackhole [2]: Produce MessageSet with 2720 message(s) (320793 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1563409867.747|PRODUCE|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.25:6443/25]: ssl://XXX.XXX.XXX.25:6443/25: blackhole [15]: Produce MessageSet with 2532 message(s) (298652 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1563409867.821|PRODUCE|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.57:6443/57]: ssl://XXX.XXX.XXX.57:6443/57: blackhole [31]: Produce MessageSet with 2621 message(s) (309687 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1563409867.881|PRODUCE|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.89:6443/89]: ssl://XXX.XXX.XXX.89:6443/89: blackhole [11]: Produce MessageSet with 2466 message(s) (290497 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1563409867.996|PRODUCE|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.25:6443/25]: ssl://XXX.XXX.XXX.25:6443/25: blackhole [24]: Produce MessageSet with 2683 message(s) (316349 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1563409868.092|PRODUCE|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.89:6443/89]: ssl://XXX.XXX.XXX.89:6443/89: blackhole [17]: Produce MessageSet with 2402 message(s) (283891 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1563409868.092|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.89:6443/89]: ssl://XXX.XXX.XXX.89:6443/89: blackhole [2]: MessageSet with 10000 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409868.218|PRODUCE|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.25:6443/25]: ssl://XXX.XXX.XXX.25:6443/25: blackhole [30]: Produce MessageSet with 2801 message(s) (330229 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid})
%7|1563409868.270|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.57:6443/57]: ssl://XXX.XXX.XXX.57:6443/57: blackhole [31]: MessageSet with 10000 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409868.484|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.25:6443/25]: ssl://XXX.XXX.XXX.25:6443/25: blackhole [15]: MessageSet with 10000 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409868.950|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.89:6443/89]: ssl://XXX.XXX.XXX.89:6443/89: blackhole [17]: MessageSet with 10000 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409869.195|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.57:6443/57]: ssl://XXX.XXX.XXX.57:6443/57: blackhole [31]: MessageSet with 10000 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409869.198|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.89:6443/89]: ssl://XXX.XXX.XXX.89:6443/89: blackhole [2]: MessageSet with 2720 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409869.371|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.57:6443/57]: ssl://XXX.XXX.XXX.57:6443/57: blackhole [31]: MessageSet with 2621 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409869.386|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.25:6443/25]: ssl://XXX.XXX.XXX.25:6443/25: blackhole [30]: MessageSet with 10000 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409869.407|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.89:6443/89]: ssl://XXX.XXX.XXX.89:6443/89: blackhole [11]: MessageSet with 2466 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409869.638|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.25:6443/25]: ssl://XXX.XXX.XXX.25:6443/25: blackhole [15]: MessageSet with 2532 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409869.748|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.89:6443/89]: ssl://XXX.XXX.XXX.89:6443/89: blackhole [17]: MessageSet with 2402 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409869.851|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.25:6443/25]: ssl://XXX.XXX.XXX.25:6443/25: blackhole [24]: MessageSet with 2683 message(s) (MsgId 0, BaseSeq -1) delivered
%7|1563409870.178|MSGSET|rdkafka#producer-1| [thrd:ssl://XXX.XXX.XXX.25:6443/25]: ssl://XXX.XXX.XXX.25:6443/25: blackhole [30]: MessageSet with 2801 message(s) (MsgId 0, BaseSeq -1) delivered
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.1.0 and 1.1.0
 - [x] Apache Kafka broker version: 2.1.0
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Alpine 3.10
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by jpiper** [comment]
So I've found that if rather than using the `ProduceChan`, I use `Produce` and pass in my own events channel that everything works much better.

Rather than hanging, `Produce` now throws `Local: Queue full` errors (but doesn't stall indefinitely), which is of course because we're reaching a throughput limit, but that's fine and I can deal with this :)

I guess another question is, can we increase the limit for `queue.buffering.max.kbytes`? Modern servers have hundreds of GB of memory, so I'm wondering why the 2GB cap here?

**Comment by edenhill** [comment]
@jpiper The upper limit is to avoid an internal int overflow, which we should obviously fix if there's demand for larger queue sizes.

**Comment by jpiper** [comment]
@edenhill My use case is that I'm doing a _lot_ of throughput, bytes wise (each broker has a 40Gb NICs and lots of disks) per librdkafka deployment, so even a small broker error/flap can quickly cause the 2GB to fill up and produces to fail. I can deploy more librdkafka instances to spread the load to get around this, but then I have have more producers (and all the overheads associated with it)

**Comment by jpiper** [comment]
I suppose I could also just put a huge buffered channel in front of the Produce method

**Comment by edenhill** [comment]
I'll increase the maximum to INT_MAX, roughly 2TB

**Comment by edenhill** [comment]
Fixed on librdkafka master.

**Comment by jpiper** [comment]
@edenhill amazing! Any idea about the other half of this bug, i.e. why when this channel fills up `ProduceChannel` stays in a blocked state forever?

**Comment by lizthegrey** [comment]
I wonder if it's https://github.com/edenhill/librdkafka/issues/2464
