### ISSUE TITLE
Ubuntu - #pkg-config --cflags  -- rdkafka Package rdkafka was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by QuanVan95** [confluentinc/confluent-kafka-go#358]
Description
===========
Hi Mr. Edenhill, I'm using Ubuntu 14.04.3 LTS to install confluent-kafka-go. Following your instruction: "For Debian and Ubuntu based distros, install librdkafka-dev from the standard repositories or using Confluent's Deb repository." I installed  librdkafka-dev, but it shows me the error:

# pkg-config --cflags  -- rdkafka
Package rdkafka was not found in the pkg-config search path.
Perhaps you should add the directory containing `rdkafka.pc'
to the PKG_CONFIG_PATH environment variable
Package 'rdkafka', required by 'world', not found
pkg-config: exit status 1

I also tried to install pkg-config or pkgconfig as well, but it doesn't work.
Btw, I checked the folder, Inside folder lib/pkgconfig/ there are 2 files:
drwxr-xr-x  2 root root 4096 Jul 14  2013 ./
drwxr-xr-x 65 root root 4096 Jul 22 08:59 ../
Cannot find any rdkafka.pc file and there also doesn't has folder pkg-config.

Could you please help me to resolve this problem. Thanks so much.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Install librdkafka-dev from the confluent deb repository:
https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#systemd-ubuntu-debian-install

**Comment by QuanVan95** [comment]
Thank for your support Mr. @edenhill 
I resolved this problem by running the command apt-get install -y pkg-config lxc-dev 
It worked for me (y)
