### ISSUE TITLE
Auto offset reset policy not working

### ISSUE THREAD

**Issue by cw-rajanchauhan** [confluentinc/confluent-kafka-go#359]
Description
===========
`auto.offset.reset` config set to `"earliest"` not working

How to reproduce
================

	func NewKafkaConsumer(brokerServers string, consumerGroupName string, customConfig map[string]interface{}, logger *gologger.CustomLogger) *KafkaConsumer {
		kc := &KafkaConsumer{
			CloseChannel : make(chan os.Signal, 1),
		}
		signal.Notify(kc.CloseChannel, syscall.SIGINT, syscall.SIGTERM)
		kc.logger = logger
		kc.config = &kafka.ConfigMap{
			"bootstrap.servers": brokerServers,
			"broker.address.family": "v4",
			"group.id":              "My-group3",
			"session.timeout.ms":    6000,
			"enable.auto.commit": 	false,
			"debug": "consumer",
			"auto.offset.reset":		"earliest",
		}
		
		fmt.Printf("%v", kc.config)
		c, err := kafka.NewConsumer(kc.config)
		if err != nil {
			kc.logger.LogError("Failed to create consumer: %s\n", err)
			os.Exit(1)
		}
		kc.Consumer = c
		kc.logger.LogInfo(fmt.Sprintf("Created Consumer %v\n", c))
		return kc
	}
	kc.Consumer.SubscribeTopics(kc.Topics, nil) // Here I am providing two topics MyEVENTDATA and MyNOTIFICATIONDATA
       And polling events in a loop as in the consumer example  

**Librdkafka Debug Logs**
Logs on starting up the consumer  
Here you can see consumer is fetching the recent offset of topics instead of fetching records from offset 0.

	&map[bootstrap.servers:x.x.x.x:9092,y.y.y.y:9092 broker.address.family:v4 group.id:My-group3 session.timeout.ms:6000 enable.auto.commit:false debug:consumer auto.offset.reset:earliest]%7|1564065665.199|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v1.1.0 (0x10100ff) rdkafka#consumer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,sasl_oauthbearer, GCC GXX PKGCONFIG INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL SASL_CYRUS HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x2000)
	{"log_level": "INFO", "log_timestamp": "2019-07-25 20:11:05.199178011 +0530 IST m=+0.096387060", "log_facility": "My Consumer","log_message": "Created Consumer rdkafka#consumer-1\n"}
	%7|1564065665.200|SUBSCRIBE|rdkafka#consumer-1| [thrd:main]: Group "My-group3": subscribe to new subscription of 2 topics (join state init)
	%7|1564065665.200|REBALANCE|rdkafka#consumer-1| [thrd:main]: Group "My-group3" is rebalancing in state init (join-state init) without assignment: unsubscribe
	%7|1564065666.221|JOIN|rdkafka#consumer-1| [thrd:main]: Group "My-group3": postponing join until up-to-date metadata is available
	%7|1564065666.226|REJOIN|rdkafka#consumer-1| [thrd:main]: Group "My-group3": subscription updated from metadata change: rejoining group
	%7|1564065666.226|REBALANCE|rdkafka#consumer-1| [thrd:main]: Group "My-group3" is rebalancing in state up (join-state init) without assignment: group rejoin
	%7|1564065668.199|JOIN|rdkafka#consumer-1| [thrd:main]: localnosql1:9092/0: Joining group "My-group3" with 2 subscribed topic(s)
	%7|1564065668.211|ASSIGNOR|rdkafka#consumer-1| [thrd:main]: Group "My-group3": "range" assignor run for 1 member(s)
	%7|1564065668.218|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "My-group3": new assignment of 20 partition(s) in join state wait-assign-rebalance_cb
	%7|1564065668.218|OFFSET|rdkafka#consumer-1| [thrd:main]: GroupCoordinator/0: Fetch committed offsets for 20/20 partition(s)
	%7|1564065668.234|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [1] start fetching at offset 240
	%7|1564065668.234|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [0] start fetching at offset 53106
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [3] start fetching at offset 2204
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [2] start fetching at offset 76
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [4] start fetching at offset 9644
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [5] start fetching at offset 0
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [6] start fetching at offset 17608
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [7] start fetching at offset 9785
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [8] start fetching at offset 0
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyEVENTDATA [9] start fetching at offset 69238
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [0] start fetching at offset 0
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [1] start fetching at offset 23
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [2] start fetching at offset 64
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [3] start fetching at offset 0
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [5] start fetching at offset 0
	%7|1564065668.240|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [4] start fetching at offset 0
	%7|1564065668.241|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [7] start fetching at offset 19
	%7|1564065668.241|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [6] start fetching at offset 0
	%7|1564065668.241|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [8] start fetching at offset 0
	%7|1564065668.241|FETCH|rdkafka#consumer-1| [thrd:main]: Partition MyNOTIFICATIONDATA [9] start fetching at offset 0

**Kafka Consumer Group Description**
On Checking offset in kafka for particular consumer group. As you can see in below logs there is no offset committed for the consumer group in the broker even after providing the `auto offset reset` policy set to `earliest` it is not consuming old records in the kafka topic.
```
GROUP           TOPIC                  PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
My-group3   MyEVENTDATA        6          -               17608           -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 7          -               19              -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 2          -               64              -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyEVENTDATA        9          -               69238           -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyEVENTDATA        7          -               9785            -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyEVENTDATA        1          -               240             -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 8          -               0               -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyEVENTDATA        0          -               53106           -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyEVENTDATA        2          -               76              -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 3          -               0               -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 9          -               0               -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyEVENTDATA        4          -               9644            -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 5          -               0               -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyEVENTDATA        3          -               2204            -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 4          -               0               -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 1          -               23              -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 6          -               0               -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyEVENTDATA        5          -               0               -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyEVENTDATA        8          -               0               -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
My-group3   MyNOTIFICATIONDATA 0          -               0               -               rdkafka-1bc96135-0fab-4de9-978f-591e1871ee2d /10.10.40.254   rdkafka
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [x] Apache Kafka broker version: 2.3.0
 - [x] Client configuration: `ConfigMap{"bootstrap.servers": brokerServers,
			"broker.address.family": "v4",
			"group.id":              "My-group3",
			"session.timeout.ms":    6000,
			"enable.auto.commit": 	false,
			"debug": "consumer",
			"auto.offset.reset":		"earliest",}`
 - [x] Operating system: ubuntu 16.04
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [x] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
the debug=consumer logs don't provide any clues as to what's up. can you set debug to 'all'?

**Comment by cw-rajanchauhan** [comment]
@mhowlett Here is the full [logs](https://github.com/cw-rajanchauhan/img-benchmarking/blob/master/log.txt) with `debug:all`

**Comment by mhowlett** [comment]
In response to a request for the beginning offset (which is used as the offset to start fetching from), the broker is returning what you have tabulated as the log end offset. are you able to successfully consume earlier messages in this topic using another client (e.g. kafkacat)? 

> %7|1564074180.335|OFFSET|rdkafka#consumer-1| [thrd:main]: Offset BEGINNING request for MyEVENTDATA [2] returned offset 76 (76)

**Comment by cw-rajanchauhan** [comment]
The older message in the topics got purged due to `retention.ms` settings. So consumer was bound to start from the respective partition offset but not 0.
Thanks @mhowlett for you response.
