### ISSUE TITLE
Question regarding processing messages concurrently and how to handle committing  processed message offset while some prior messages are not processed yet? 

### ISSUE THREAD

**Issue by taalhach** [confluentinc/confluent-kafka-go#362]
Description
===========

hi...
i have a quick question
lets say on my topic x total messages are 10 and i am processing messages concurrently and every go routine of message handlers commits messages manually
message at offset: 3 gets all resources and completes the processing
message at offset:1 doesn't gets resources and fails to complete process and system crashes
lets say message at offset:3 handler committed its offset then my question is how can i assure that i will read the message at offset: 1 while i have committed message offset to 3 ?

`package main

import (
	"github.com/confluentinc/confluent-kafka-go/kafka"
	"fmt"
	"os"
	"time"
)

type myConsumer struct {
	con *kafka.Consumer
}
func main()  {
	cc, err := kafka.NewConsumer(&kafka.ConfigMap{
		//"bootstrap.servers": "127.0.0.1:9092",
		//"bootstrap.servers": "18.234.224.231:9092",
		"bootstrap.servers": "localhost:9092",
		"group.id":          "id",
		"session.timeout.ms":   6000,
		"enable.auto.commit":   false,
		"default.topic.config": kafka.ConfigMap{"auto.offset.reset": "earliest"},
	})
	c:=myConsumer{
		con:cc,
	}
	if err != nil {
		panic(err)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create consumer: %s\n", err)
		os.Exit(1)
	}
	err = c.con.SubscribeTopics([]string{"x"}, nil)
	for {
		//i:=0
		x:=time.Now()

		msg, _ := c.con.ReadMessage(-1)
		c.handler(msg.TopicPartition.Offset,msg )

		fmt.Println("time: ",time.Since(x))
	}

}
func (c *myConsumer)handler(offset kafka.Offset,message *kafka.Message)  {
	// get resources
	// do some task

	c.con.CommitOffsets([]kafka.TopicPartition{kafka.TopicPartition{Offset:offset}})
}
`
How to reproduce
================
Nothing really to reproduce

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion(v1.1.0)`):
 - [ ] Operating system: linux ubuntu 16.04

**Comment by mhowlett** [comment]
you'll need to maintain a collection of outstanding processing operations (sorted set seems appropriate), and commit offsets based on the state of this. your processing needs to be idempotent too, of course.

**Comment by SnugglyCoder** [comment]
I don't know how you would handle it, but I think you should avoid processing multiple messages off of the queue out of order and instead increase the number of partitions to increase your ability to process messages faster.
