### ISSUE TITLE
[Question] Automatic rebalancing in consumer

### ISSUE THREAD

**Issue by pragmaticpi** [confluentinc/confluent-kafka-go#364]
Description
===========
Setup:- One golang application with two goroutines, each goroutine will create a consumer instance in a consumer group and will subscribe to one topic each. The consumer is responsible for sending the messages to elasticsearch after some processing. I am doing manual commits after the indexing into elasticsearch is successful.

Problem:- There was a rebalance event out of nowhere and at the time of re-assignment only one of the goroutine got assigned.

Logs:-

rdkafka#consumer-1: topic-1
rdkafka#consumer-2: topic-2

```
{"consumer":"rdkafka#consumer-2", "level":"info","msg":"message consumed","offset":357310,"partition":0,"state":"consumed","time":"2019-07-30T11:16:34Z","topic":"topic-2","version":"1.0.0"}

{"consumer":"rdkafka#consumer-1","level":"debug","msg":"no message received in time frame","time":"2019-07-30T11:16:50Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-2","elastic-region":"Dev1","host":"pdp-kafka-oplog-consumer","ip":"10.10.189.188","kafka-region":"Dev1","level":"info","msg":"batch indexing into ES successful","state":"processed","time":"2019-07-30T11:16:56Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-2","level":"info","msg":"Commit successful for [topic-2[0]@357311]","time":"2019-07-30T11:16:56Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-2","level":"info","msg":"message consumed","offset":357311,"partition":0,"state":"consumed","time":"2019-07-30T11:17:15Z","topic":"topic-2","version":"1.0.0"}

{"consumer":"rdkafka#consumer-1","level":"debug","msg":"no message received in time frame","time":"2019-07-30T11:17:20Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-2", "level":"info","msg":"batch indexing into ES successful","state":"processed","time":"2019-07-30T11:17:26Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-1", "level":"info","msg":"Event: RevokedPartitions: [topic-1[0]@unset]","time":"2019-07-30T11:17:38Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-2", "level":"info","msg":"Event: RevokedPartitions: [topic-2[0]@unset]","time":"2019-07-30T11:17:38Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-1", "error":"GroupCoordinator: 1 request(s) timed out: disconnect (after 516424898ms in state UP)", "level":"warning","msg":"error received, error code: -185","time":"2019-07-30T11:17:38Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-1", "level":"info","msg":"Event: AssignedPartitions: [topic-1[0]@unset]","time":"2019-07-30T11:17:38Z","version":"1.0.0"}
```

I have the following questions:

1. In what cases, rebalancing can occur other than adding/removing the consumer from a consumer group?

2. If the consumer didn't receive any message in last 30 seconds, I am logging <code>no message received in time frame</code>. <code>rdkafka#consumer-1</code> was not receiving any message for last 8 minutes or so. Is there any logic like if the consumer didn't receive any messages for a particular period of time, the consumer got disconnected and rebalancing will occur?

3. As you can see from <code>time</code> field in logs, <code>rdkafka#consumer-2</code> consumed a message at <code>2019-07-30T11:17:15Z</code> but at <code>2019-07-30T11:17:38Z</code>, 13 seconds later, its partitions got revoked at the same time <code>rdkafka#consumer-1</code> got revoked. How it is possible? Is this related to the fact that both are separate goroutines and not separate application altogether?

4. <code>GroupCoordinator: 1 request(s) timed out: disconnect (after 516424898ms in state UP)</code>, I am not able to understand the meaning of this error and what causes it?

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): <code>1.0.0</code>
 - [x] Apache Kafka broker version: <code>2.1.0</code>
 - [x] Client configuration: 
               `"bootstrap.servers":     localhost:9092,
		"session.timeout.ms":    10000,
		"enable.auto.commit":    "false",
		"auto.offset.reset":     "latest",`
 - [x] Operating system: MacOS

**Comment by mhowlett** [comment]
> 1. In what cases, rebalancing can occur other than adding/removing the consumer from a consumer group?

1. If the group coordinator doesn't receive a heartbeat from a consumer within `session.timeout.ms` of the last.

2. If the application hasn't called poll (`ReadMessage`) within `max.poll.interval.ms` of the last call to poll.

> 2. ... Is there any logic like if the consumer didn't receive any messages for a particular period of time, the consumer got disconnected and rebalancing will occur?

your application cannot spend too long outside of a call to `ReadMessage` (`max.poll.interval.ms`) or it will be assumed to have failed.

> 3. ... How it is possible? 

Seems to be about in line with the default value of `session.timeout.ms` which is 10 seconds. if your application was disconnected from the group coordinator for this amount of time, all it's consumers will be kicked out of the group.

> 4. GroupCoordinator: 1 request(s) timed out: disconnect (after 516424898ms in state UP), I am not able to understand the meaning of this error and what causes it?

an API level request to the group coordinator broker timed out due to a disconnect. network or broker problem.


you might like to increase the value of `session.timeout.ms` which will prevent a rebalance from happening so quickly in the event of a network issue. the downside is a rebalance will take longer in the case of a genuine problem. note: this is all irrelevant in the case of a clean shutdown (close called) - in that case, a rebalance will happen immediately.

**Comment by pragmaticpi** [comment]
Thanks for the answer. 

1. What you said about <code>max.poll.interval.ms</code>, according to librdkafka configurations, the default value is <code>300000</code> which is 5 mins and my poll() is <code>poll(100)</code>. So, I have to make sure I poll every 100ms otherwise it will wait for max 5 mins and the consumer will fail?

2. But why after revoked partition, only one consumer got reassigned? Is it related to the fact that I am pausing the consumer during processing and committing offset time and resuming it afterward? So, if the consumer is in a paused state and re-balance occurs, that consumer will not get re-assigned? 

3. I want to block poll() so that I don't consume messages basically during the time of processing the messages. What would be the optimal way to do that other than pausing consumers?

4. Sometimes, I got messages <code>"error":"GroupCoordinator response error: Local: Broker transport failure"</code>, how it is different from the above message?

5. Lastly, yesterday I received the following logs:

```
{"consumer":"rdkafka#consumer-2", "level":"info","msg":"Event: RevokedPartitions: [small_customers_userprofiles[0]@unset]","time":"2019-08-08T10:35:47Z","version":"1.0.0"}

{"error":"GroupCoordinator: 1 request(s) timed out: disconnect (after 167073131ms in state UP)", "level":"warning","msg":"error received, error code: -185","time":"2019-08-08T10:35:47Z

{"consumer":"rdkafka#consumer-1","elastic-region":"Dev1","host":"pdp-kafka-oplog-consumer","ip":"10.10.189.188","kafka-region":"Dev1","level":"info","msg":"Event: RevokedPartitions: [topic-1[0]@unset]","time":"2019-08-08T10:35:49Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-1","level":"info","msg":"Event: AssignedPartitions: [topic-1[0]@unset]","time":"2019-08-08T10:35:49Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-1","level":"info","msg":"Event: RevokedPartitions: [topic-1[0]@unset]","time":"2019-08-08T10:35:52Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-1","level":"info","msg":"Event: AssignedPartitions: [topic-2[0]@unset]","time":"2019-08-08T10:35:52Z","version":"1.0.0"}

{"consumer":"rdkafka#consumer-2","level":"info","msg":"Event: AssignedPartitions: [topic-2[0]@unset]","time":"2019-08-08T10:35:52Z","version":"1.0.0"}
```
Same consumer <code>rdkafka#consumer-1</code> got revoked two times in a duration of 3 secs. What could be the reason here?

**Comment by pragmaticpi** [comment]
@mhowlett Can you please look into the questions?

**Comment by edenhill** [comment]
You seem to be having connectivity issues with the cluster, I would sort that out before investigating consumer rebalances.
