### ISSUE TITLE
[question]make failed

### ISSUE THREAD

**Issue by lazytooo** [confluentinc/confluent-kafka-go#367]
/go/src/librdkafka # ./configure --prefix /usr

checking for OS or distribution... ok (alpine)
checking for C compiler from CC env... failed
checking for gcc (by command)... failed
checking for clang (by command)... failed
checking for cc (by command)... failed (fail)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... failed
checking for C++ compiler (clang++)... failed
checking for C++ compiler (c++)... failed (fail)
checking executable ld... failed (disable)
checking executable nm... failed (disable)
checking executable objdump... failed (disable)
checking executable strip... failed (disable)
checking for pkgconfig (by command)... ok
checking for install (by command)... failed
checking for PIC (by compile)... failed (disable)
checking for GNU-compatible linker options... failed
checking for OSX linker options... failed
checking for GNU linker-script ld flag... failed
checking for Solaris linker-script ld flag... failed (ignore)
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... failed (disable)
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
checking for __sync_64 (by compile)... failed (disable)
checking for socket (by compile)... failed
checking for socket_nsl (by compile)... failed (fail)
parsing version '0x010200ff'... ok (1.2.0)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... failed
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... failed (fail)
checking for c11threads (by pkg-config)... failed
checking for c11threads (by compile)... failed (disable)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... failed (disable)
checking for zlib (by pkg-config)... failed
checking for zlib (by compile)... failed (disable)
checking for libcrypto (by pkg-config)... failed
checking for libcrypto (by compile)... failed (disable)
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by pkg-config)... failed
checking for libsasl (by compile)... failed (disable)
checking for libzstd (by pkg-config)... failed
checking for libzstd (by compile)... failed (disable)
checking for libm (by pkg-config)... failed
checking for libm (by compile)... failed (disable)
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for rapidjson (by compile)... failed (disable)
checking for crc32chw (by compile)... failed (disable)
checking for regex (by compile)... failed (disable)
checking for strndup (by compile)... failed (disable)
checking for strerror_r (by compile)... failed (disable)
checking for pthread_setname_gnu (by compile)... failed (disable)
checking for pthread_setname_darwin (by compile)... failed (disable)
checking for nm (by env NM)... failed

###########################################################
###########################################################
###########################################################
 cc (WITH_CC) 
    module: cc
    action: fail
    reason:
command 'cc --version' failed:
mklove/modules/configure.base: line 1711: cc: command not found

 cxx (WITH_CXX) C++ compiler (c++)
    module: cc
    action: fail
    reason:
command 'c++ --version' failed:
mklove/modules/configure.base: line 1711: c++: command not found

 socket_nsl () 
    module: socket
    action: fail
    reason:
compile check failed:
CC: CC
flags: 
  -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpeaFINb.c -o _mkltmpeaFINb.c.o -lsocket -lnsl  :
mklove/modules/configure.base: line 1336: -g: command not found
source: 
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
void foo (void) {
   int s = socket(0, 0, 0);
   close(s);
}

 libpthread () 
    module: self
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lpthread
  -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpJnADIl.c -o _mkltmpJnADIl.c.o   -lpthread:
mklove/modules/configure.base: line 1336: -g: command not found
source: #include <pthread.h>

/go/src/librdkafka # make
./Makefile.config missing: please run ./configure
make: *** [mklove/Makefile.base:73: mklove-check] Error 1
/go/src/librdkafka # make install
make[1]: Entering directory '/go/src/librdkafka/src'
Install librdkafka to /usr/local
install -d $DESTDIR/usr/local/include/librdkafka && \
install -d $DESTDIR/usr/local/lib && \
install rdkafka.h $DESTDIR/usr/local/include/librdkafka && \
install librdkafka.a $DESTDIR/usr/local/lib && \
install librdkafka.1 $DESTDIR/usr/local/lib && \
[ -f "rdkafka.pc" ] && ( \
	install -d $DESTDIR/usr/local/lib/pkgconfig && \
	install -m 0644 rdkafka.pc $DESTDIR/usr/local/lib/pkgconfig \
) && \
[ -f "rdkafka-static.pc" ] && ( \
	install -d $DESTDIR/usr/local/lib/pkgconfig && \
	install -m 0644 rdkafka-static.pc $DESTDIR/usr/local/lib/pkgconfig \
) && \
(cd $DESTDIR/usr/local/lib && ln -sf librdkafka.1 librdkafka)
install: can't stat 'librdkafka.a': No such file or directory
make[1]: *** [../mklove/Makefile.base:187: lib-install] Error 1
make[1]: Leaving directory '/go/src/librdkafka/src'
make: *** [Makefile:41: install] Error 2
/go/src/librdkafka # 

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You're lacking a compiler, among other things.

See librdkafka build requirements here:
https://github.com/edenhill/librdkafka#requirements

Or use a pre-built librdkafka package from here https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#systemd-ubuntu-debian-install
