### ISSUE TITLE
[Question] A publish (on a producer) succeeds: is it guaranteed Kafka has the message?

### ISSUE THREAD

**Issue by rodgarrison** [confluentinc/confluent-kafka-go#369]
What is the post-condition when a producer succeeds in publishing a message? In particular is it guaranteed Kafka got the message ... or could it be lost if the code crashes immediately following the return from `Producer.Publish`? Based on the API it's reasonable the lib doesn't guarantee Kafka got the message. But `Producer.Flush` should if it returns without error, correct?

**Comment by mhowlett** [comment]
the result of the produce request is not known until the corresponding delivery report event. see for example: https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/idempotent_producer_example/idempotent_producer_example.go#L74

**Comment by rodgarrison** [comment]
Thank you. That's clear
