### ISSUE TITLE
Storing Offset Issue

### ISSUE THREAD

**Issue by mayankbargali** [confluentinc/confluent-kafka-go#370]
Description
===========
Getting below error running multiple instances of consumer  

6218.561539900:7f567bfff700: imkafka.c: imkafka: msgConsume Loop on socdap-eh-cef-zscaler/^test-cg$/socdap-ehns-siem-002.servicebus.windows.net:9093: [0], offset 19281053479, 942 bytes):
6218.926410000:7f569293b700: imkafka.c: imkafka: kafka log message [7,OFFSET]: [thrd:main]: Topic socdap-eh-cef-zscaler [0]: stored offset 19281053480, committed offset 19281051544
6218.926463800:7f569293b700: imkafka.c: imkafka: kafka log message [7,OFFSET]: [thrd:main]: Topic socdap-eh-cef-zscaler [0]: setting stored offset 19281053480 for commit
6218.926475000:7f569293b700: imkafka.c: imkafka: kafka log message [7,OFFSET]: [thrd:main]: Topic socdap-eh-cef-zscaler [1]: stored offset -1001, committed offset -1001
6218.926486000:7f569293b700: imkafka.c: imkafka: kafka log message [7,OFFSET]: [thrd:main]: Topic socdap-eh-cef-zscaler [1]: setting offset INVALID for commit
6218.926495400:7f569293b700: imkafka.c: imkafka: kafka log message [7,OFFSET]: [thrd:main]: Topic socdap-eh-cef-zscaler [2]: stored offset -1001, committed offset -1001
6218.926505300:7f569293b700: imkafka.c: imkafka: kafka log message [7,OFFSET]: [thrd:main]: Topic socdap-eh-cef-zscaler [2]: setting offset INVALID for commit
6218.926554600:7f569293b700: imkafka.c: imkafka: kafka log message [7,OFFSET]: [thrd:main]: Topic socdap-eh-cef-zscaler [3]: stored offset -1001, committed offset -1001
6218.926568600:7f569293b700: imkafka.c: imkafka: kafka log message [7,OFFSET]: [thrd:main]: Topic socdap-eh-cef-zscaler [3]: setting offset INVALID for commit

Used below Configuration:
"security.protocol=SASL_SSL",
                "sasl.mechanisms=PLAIN",
                "sasl.username=$ConnectionString",
                "sasl.password=<key>",
                "ssl.ca.location=/opt/certs/microsoft_eh_cacert.pem",
                "group.id=test-cg",
                "offset.store.method=broker",
                "broker.version.fallback=1.0.0",
                "compression.codec=none",
                "session.timeout.ms=60000",
                "socket.timeout.ms=240000",
                "socket.keepalive.enable=true",
                "topic.metadata.refresh.interval.ms=-1",
                "debug=cgrp,metadata,topic",
                "enable.partition.eof=false"

Do I need to set any other configuration property to resolve it. How the offset are stored and in which location. Is there any configuration for the same.
https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management

**Comment by edenhill** [comment]
Those are not errors, it simply says that there is no offset to store for partitions 1..3
