### ISSUE TITLE
Question: how does a producer indicate retries? Did it succeed

### ISSUE THREAD

**Issue by rodgarrison** [confluentinc/confluent-kafka-go#372]
Kafka guarantees per partition ordering. However it needs to qualify that by adding if inflight>1 and published message(s) need retrying then succeeds ordering can change from what the publisher intended. Default inflight is 5.

Question: where in this api are we notified of any of the following ... Not from the event channel afaik:

* Message publish retried 
* Message publish failed
* Offset/handle/message ptr for dropped message

Thank you!

**Comment by edenhill** [comment]
For guaranteed ordering I suggest you look into the idempotent producer (`enable.idempotence=true`) which provides exactly-once and in-order **producer** guarantees.

As for propagation of message delivery status, that's done by `*kafka.Message` events (also called Delivery reports) on producer `Events()` channel, or the user-specific per-message delivery channel passed to `Produce()`.

See the librdkafka manual for more info:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability

**Comment by rodgarrison** [comment]
Thank you for that information. Now one last clarification: I did check the Event() method and think I already log everything that comes there. Can you tip me to what type or text string indicates retry and or dropped message? Or is it buried in a general error message? Then I'll close this.

**Comment by edenhill** [comment]
Retries are performed internally by the client and does not really have relevance to the application/user;  you give the client constraints, the message timeout and the number of retries, and it will do its best to produce the messages under those constraints. On failure it will either give you the broker-side error code (e.g., invalid message size), or the local error code (typically message timed out).

**Comment by rodgarrison** [comment]
Thank you.

**Comment by Digl** [comment]
Hi!
Is there any way to notice failed publishes without waiting for the retries to be exhausted?
The delivery report is only called after the retries have been exhausted, right?
Thanks
