### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by zhs077** [confluentinc/confluent-kafka-go#373]
Description
===========

/tmp/go-build/github.com/confluentinc/confluent-kafka-go/kafka/_obj/cgo-gcc-prolog:43: undefined reference to `rd_kafka_fatal_error'
/tmp/go-build241262187/github.com/confluentinc/confluent-kafka-go/kafka/_obj/error.cgo2.o: In function `_cgo_2b37cfc26b28_Cfunc_rd_kafka_test_fatal_error':
/tmp/go-build/github.com/confluentinc/confluent-kafka-go/kafka/_obj/cgo-gcc-prolog:64: undefined reference to `rd_kafka_test_fatal_error'
/tmp/go-build241262187/github.com/confluentinc/confluent-kafka-go/kafka/_obj/event.cgo2.o: In function `_cgo_2b37cfc26b28_Cfunc_rd_kafka_event_config_string':
/tmp/go-build/github.com/confluentinc/confluent-kafka-go/kafka/_obj/cgo-gcc-prolog:62: undefined reference to `rd_kafka_event_config_string'
/tmp/go-build241262187/github.com/confluentinc/confluent-kafka-go/kafka/_obj/event.cgo2.o: In function `_cgo_2b37cfc26b28_Cfunc_rd_kafka_event_error_is_fatal':
/tmp/go-build/github.com/confluentinc/confluent-kafka-go/kafka/_obj/cgo-gcc-prolog:80: undefined reference to `rd_kafka_event_error_is_fatal'
/tmp/go-build241262187/github.com/confluentinc/confluent-kafka-go/kafka/_obj/handle.cgo2.o: In function `_cgo_2b37cfc26b28_Cfunc_rd_kafka_oauthbearer_set_token':
/tmp/go-build/github.com/confluentinc/confluent-kafka-go/kafka/_obj/cgo-gcc-prolog:82: undefined reference to `rd_kafka_oauthbearer_set_token'
/tmp/go-build241262187/github.com/confluentinc/confluent-kafka-go/kafka/_obj/handle.cgo2.o: In function `_cgo_2b37cfc26b28_Cfunc_rd_kafka_oauthbearer_set_token_failure':
/tmp/go-build/github.com/confluentinc/confluent-kafka-go/kafka/_obj/cgo-gcc-prolog:101: undefined reference to `rd_kafka_oauthbearer_set_token_failure'

How to reproduce
================

librdkafka-1.1.0

./configure --prefix /usr
make 
make install

[root@hn-chenzhousjzx-sx-dgk-0001 ~]# cat .bashrc 
# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
export PKG_CONFIG_PATH=/usr/lib/pkgconfig
go get -u github.com/confluentinc/confluent-kafka-go/kafka

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You have an older librdkafka somewhere on your system, make sure to remove all install librdkafka versions and then install v1.1.0

**Comment by Kishan-Padmashali** [comment]
@edenhill can you please share the link for  librdkafka v1.1.0

**Comment by edenhill** [comment]
You should be using librdkafka v1.3.0 now.
See installation instructions in the README:
https://github.com/confluentinc/confluent-kafka-go#installing-librdkafka
