### ISSUE TITLE
How to config more than one producer?

### ISSUE THREAD

**Issue by thangld322** [confluentinc/confluent-kafka-go#376]
Description
===========
I use this lib to send events to kafka. But everytime the EPS pass 100.000, it gives out this error: `2019-10-01T08:25:13.330883661Z time="2019-10-01T08:25:13Z" level=error msg="output module &{{\"kafka\"} \"rdkafka#producer-1\" '\\x01' 'ꀀ' \"siem-raw-input\" \"kafka01:9092,kafka02:9093,kafka03:9094\" map[\"type\":\"json\"] \"none\" '\\x05' 'ᎉ' '\\x03' '✐' '\\U00100000' %!q(int=10000000)} failed: Local: Queue full\n" func="CyM-Log-Agent/config.(*Config).startOutputs.func1.1.1" file="/go/src/CyM-Log-Agent/config/output.go:81"
`. 
As far as I know, `failed: Local: Queue full` error occurred when events are sent to lib rdkafka faster than lib rdkafka can handle so that local queue of lib rdkafka is full.

My question: Are there any ways to make rdkafka faster? Like config more than one producer?
Thanks.

My config:
================
```
        bootstrapServers: kafka01:9092,kafka02:9093,kafka03:9094
        topic: raw-input
        batchSize: 40960
        acks: 1
        compressionType: none
        lingerMs: 5
        requestTimeoutMs: 5001
        retries: 3
        bufferMaxMessages: 10001
        bufferMaxKbytes: 1048576
        maxRequestSize: 1000000
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by cw-rajanchauhan** [comment]
You haven't mentioned the kind of producer you are using is it batch producer or function based producer.
Are you reading messages out from the `Events` channel because delivery reports are enabled by default in kafka client? 
If not go through the [docs](https://github.com/confluentinc/confluent-kafka-go/blame/master/README.md#L91)
The error local queue filled is pointing out to that issue.

I have used batch produce with the following configuration
```
                 "bootstrap.servers": brokerServers,
		"go.batch.producer": true,
		"go.events.channel.size": 100000,
		"go.produce.channel.size": 100000,
		"linger.ms": 100,
		"queue.buffering.max.messages":   100000,
		"batch.num.messages": 5000,
		"acks": 1,
``` 
I myself have tested it for more than 10k EPS with batch produce API.
See if you missing out anything

**Comment by edenhill** [comment]
With a maximum queue size of 10001 it is not surprising that the queue becomes full if your produce-rate starts reaching this number.
I strongly suggest starting off with default settings (which allows far more messages on the producer queue than 10001).
