### ISSUE TITLE
Producer stops publishing messages after a few hours

### ISSUE THREAD

**Issue by natemurthy** [confluentinc/confluent-kafka-go#377]
Description
===========
I have a Kafka client using the confluent-kafka-go library. The client streams batches of messages from another I/O library and sends them to a Kafka topic on a separate goroutine. After several hours, the Kafka producer appears to stop publishing even though the client observes the messages as sent.

The screenshot below is what the client sees. We increment a gauge for each time `(*kafka.Producer).Produce()` is called to generate a 1-minute moving average of message publication attempts per second:

![image](https://user-images.githubusercontent.com/1788878/65999125-9c766700-e451-11e9-820a-73538d02cabb.png)

You can see this client is producing at a steady-state of roughly 24 msg/sec. Now this screenshot is from the JMX metrics exported from the Kafka broker for the topic to which the above message should be written:

![image](https://user-images.githubusercontent.com/1788878/65999133-a4360b80-e451-11e9-9dee-ae0aba116468.png)

You can observe the messages in per second begin to taper off around 17:15 and eventually goes completely to zero after 17:45 even though the client continues to publish at a steady rate.

What's strange is that if I pass in a non-nil delivery channel to `(*kafka.Producer).Produce()` to and block on it, then I can get my messages through, but this comes at a huge throughput penalty as these producer calls need to be asynchronous.

How to reproduce
================
Implement a loop that calls `kp` (of type `kafka.Producer`) on a separate goroutine like so:
```go
func handler(stream xyz.Stream) {
    for  {
        batch, _ := stream.Recv()
        go publish(batch)
    }
}

func publish(batch []kafka.Message) {
    for _, msg := range batch {
        metric.KafkaProduceAttemps.Inc()
        kp.Produce(msg, nil)
    }
}
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version: `1.1.0`
 - [x] Apache Kafka broker version: `2.1.1`
 - [x] Client configuration:`ConfiMap{"go.events.channel.size":0, "go.produce.channel.size":0}`
 - [x] Operating system: `Linux Debian Stretch (slim)`
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by natemurthy** [comment]
Related past reported issues:

* https://github.com/confluentinc/confluent-kafka-go/issues/251
* https://github.com/confluentinc/confluent-kafka-go/issues/356

**Comment by edenhill** [comment]
Thanks for a great report!

How are you handling the delivery reports? The Events() channel needs to be served at all times to avoid filling up and blocking further produces.

Your code snippet does not handle Produce() errors, is your real code doing that, and if so, are you seeing any errors when the produce rate drops?

**Comment by natemurthy** [comment]
@edenhill you bet :) just want to make your job easy

The current code does not handle delivery reports (i think there's a way of disabling this, correct?), just needs to support fire-and-forget.

And good observation: the snippet above does not handle Produce() errors, but we are checking for `err != nil` and logging them in our actual production code. Mysteriously enough, we do not see any errors when the produce rate drops.

**Comment by edenhill** [comment]
Yes, delivery reports may be disabled, but it is not recommended, an application should care if messages are produced, if nothing else just to catch config errors.

**Comment by edenhill** [comment]
To troubleshoot this issue I recommend doing two things:
 * enable delivery reports and serve the Events() channel continously, propagate any delivery errors appropriately (log or whatever)
 * check produce() for errors.

**Comment by natemurthy** [comment]
Is selecting over the `Events()` channel equivalent to selecting over the `deliveryChan` if passed into `Produce()`?

**Comment by edenhill** [comment]
Right, you will need to wait for all outstanding messages delivery reports on the deliveryChan before closing it since there is no way for the Go client to know if your channel was closed or not.

**Comment by edenhill** [comment]
If you don't pass a deliveryChan to Produce() the delivery reports will be emitted on the Events() channel instead. The Events() channel may also return other event types, such as Error.

**Comment by natemurthy** [comment]
> Right, you will need to wait for all outstanding messages delivery reports on the deliveryChan before closing it since there is no way for the Go client to know if your channel was closed or not.

Is there a goroutine-safe way to know whether all outstanding messages on the deliveryChan have been sent (I could check `len(delveryChan)`) OR block any goroutines from writing to it before calling `close()`?

**Comment by edenhill** [comment]
We generally do not recommend disabling delivery reports since you will have no indication if messagses are produced or not, a simple configuration error could mean all your messages are lost.

**Comment by natemurthy** [comment]
Will add some logic to make sure Produce() and deliveryChan are properly synchronize based on that 1:1 relation.

For this application, we're using `acks = 0` so we can tolerate some data loss as these are non-critical events, just need high-throughput. 

Thanks for your help walking through this with me :) Closing this out.

**Comment by edenhill** [comment]
nit: 'acks=0' means you will tolerate complete data loss without any indication of error. You will always want at least acks=1 (but preferably acks=all).
