### ISSUE TITLE
No such configuration property: "max.poll.records"

### ISSUE THREAD

**Issue by hanluner** [confluentinc/confluent-kafka-go#380]
Description
===========
I got an error `No such configuration property: "max.poll.records"` when I wanted to use property `max.poll.records`.

Would you tell me how I can use `max.poll.records` ?

**Comment by edenhill** [comment]
There is no such property, messages are fetched in batches from the broker and queued locally, but the application may only receive one message at the time.
We believe this is the best approach to stream processing.

**Comment by hanluner** [comment]
@edenhill Hi, Where is the config property list I can set in the repo? I want to know what properties I can configure. Thank u.

**Comment by edenhill** [comment]
The list of available configuration properties is here:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by Black-Sirius69** [comment]
> There is no such property, messages are fetched in batches from the broker and queued locally, but the application may only receive one message at the time. We believe this is the best approach to stream processing.

How may I do that ?
I am writing a backend where if by mistake 2 messages are consumed together there will consistency problem with my data and I don't want to do that

**Comment by Murtagy** [comment]
> The list of available configuration properties is here: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#max-poll-records
Seems out of sync
