### ISSUE TITLE
lose messages when consumer reconnect

### ISSUE THREAD

**Issue by fuchen90** [confluentinc/confluent-kafka-go#381]
Description
===========
Recently, we found that when consumer disconnect and reconnect, there will be a lot of message loss, and the offset will have a fault. What is the reason?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
    0.11.4 and 1.2.0
 - [x] Apache Kafka broker version: 1.0
 - [x] Client configuration: `ConfigMap{...}`
     kafka.ConfigMap{
		"enable.auto.commit":              false,
		"session.timeout.ms":              120000,
		"go.events.channel.enable":        true,
		"go.application.rebalance.enable": true,
		"default.topic.config":            kafka.ConfigMap{"auto.offset.reset": "earliest"}
     }
 - [x] Operating system:
    Ubuntu 7.4.0
 - [x] Provide client logs (with `"debug": ".."` as necessary)
```
 | October 11th 2019, 00:54:11.509 | content:2019-10-11 00:54:11.509796\|INFO\|0x182_0\|framework.go:404\|framework.GetMessage\|mq message on [order_payment_id_live[9]@26698644] ip:*.*.*.87 @timestamp:October 11th 2019, 00:54:11.509 collect_time:October 11th 2019, 00:54:18.352 project:error env:live _id:AW22l7Qd8pWnzcX5jOLp _type:default _index:error-19100923 _score: -

  | October 11th 2019, 00:54:09.092 | content:2019-10-11 00:54:09.092440\|INFO\|0x182_0\|framework.go:404\|framework.GetMessage\|mq message on [**order_payment_id_live[9]@26698643**] ip:*.*.*.87 @timestamp:October 11th 2019, 00:54:09.092 collect_time:October 11th 2019, 00:54:13.611 project:error env:live _id:AW22l6GftHf6aI_M-DRI _type:default _index:error-19100923 _score: -

  | October 11th 2019, 00:51:18.725 | content:2019-10-11 00:51:18.725003\|INFO\|0x166_0\|framework.go:546\|framework.PutMessage\|delivered message to topic order_payment_id_live [9] at offset 26698642 ip:*.*.*.167 @timestamp:October 11th 2019, 00:51:18.725 collect_time:October 11th 2019, 00:51:20.463 project:error env:live _id:AW22lTZrDDcIscVH2zeN _type:default _index:error-19100923 _score: -

  | October 11th 2019, 00:51:18.593 | content:2019-10-11 00:51:18.593582\|INFO\|0x166_0\|framework.go:404\|framework.GetMessage\|mq message on [**order_payment_id_live[9]@26698612**] ip:*.*.*.167 @timestamp:October 11th 2019, 00:51:18.593 collect_time:October 11th 2019, 00:51:20.463 project:error env:live _id:AW22lTZryqxvG5OCm_Bd _type:default _index:error-19100923 _score: -

  | October 11th 2019, 00:51:18.589 | content:2019-10-11 00:51:18.589451\|INFO\|0x166_0\|framework.go:546\|framework.PutMessage\|delivered message to topic order_payment_id_live [9] at offset 26698641 ip:*.*.*.167 @timestamp:October 11th 2019, 00:51:18.589 collect_time:October 11th 2019, 00:51:20.463 project:error env:live _id:AW22lTjiMonh1Bi36tEj _type:default _index:error-19100923 _score: -

  | October 11th 2019, 00:51:18.455 | content:2019-10-11 00:51:18.455780\|INFO\|0x166_0\|framework.go:404\|framework.GetMessage\|mq message on [**order_payment_id_live[9]@26698611**] ip:*.*.*.167 @timestamp:October 11th 2019, 00:51:18.455 collect_time:October 11th 2019, 00:51:20.463 project:error env:live _id:AW22lQ1zEcnApZAqXvY9 _type:default _index:error-19100923 _score:
```

 

> This is a continuous log of reading and writing kafka messages on kibana. It can be seen that when the consumer reconnects, the offset under the read partition[9] is discontinuous, and many messages are skipped directly. And during the period I did not see any commit logs

_'order_payment_id_live[9]@26698612' Explanation：
'order_payment_id_live': topic
'9': partition number
'26698612': current offset_

 
```
| October 11th 2019, 00:51:19.729 | content:2019-10-11 00:51:19.729337\|INFO\|0x166_0\|framework.go:314\|framework.ConsumerFramework\|restart consumer success:rdkafka#consumer-320 ip:*.*.*.167 @timestamp:October 11th 2019, 00:51:19.729 collect_time:October 11th 2019, 00:51:22.338 project:error env:live _id:AW22lQyeVMgeu3UoJboe _type:default _index:id-error-19100923 _score: -

  | October 11th 2019, 00:51:18.728 | content:2019-10-11 00:51:18.728562\|INFO\|0x166_0\|framework.go:331\|framework.ConsumerFramework\|handle mq msg return: needCommit(1), error(<nil>) ip:*.*.*.167 @timestamp:October 11th 2019, 00:51:18.728 collect_time:October 11th 2019, 00:51:20.463 project:error env:live _id:AW22lRJTVAB3RyVle0Ug _type:default _index:error-19100923 _score: -

  | October 11th 2019, 00:51:18.728 | content:2019-10-11 00:51:18.728573\|ERROR\|0x166_0\|framework.go:409\|framework.GetMessage\|mq error: *.*.*.100:9092/100: Disconnected (after 1501663ms in state UP) ip:*.*.*.167 @timestamp:October 11th 2019, 00:51:18.728 collect_time:October 11th 2019, 00:51:20.463 project:error env:live _id:AW22lT9aT8DcbEbm-VCX _type:default _index:error-19100923 _score: -

  | October 11th 2019, 00:51:18.728 | content:2019-10-11 00:51:18.728577\|INFO\|0x166_0\|framework.go:256\|framework.ConsumerFramework\|mq::GetMessage, topic:hub_order_payment_id_live, partition:-1, status:0, data:null, error:kafka read error:*.*.*.100:9092/100: Disconnected (after 1501663ms in state UP) ip:*.*.*.167 @timestamp:October 11th 2019, 00:51:18.728 collect_time:October 11th 2019, 00:51:20.463 project:error env:live _id:AW22lTU2OWt5E3FvIDTO _type:default _index:19100923 _score: -
```

 

> This is the reconnection log, and the time point coincides with the consumption abnormal time point.
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the full issue template, including any relevant client and broker logs, consumer group offset printouts, etc.

**Comment by fuchen90** [comment]
![image](https://user-images.githubusercontent.com/22956024/66726377-9a59d280-ee6b-11e9-8f82-fec3c272385c.png)
![image](https://user-images.githubusercontent.com/22956024/66726503-5a471f80-ee6c-11e9-84d0-c759357e6ff2.png)

This is a continuous log of read and write kafka messages on kibana. It can be seen that when the consumer reconnects, the offset under the read zone is not continuous, and many messages are skipped directly. And during the period I did not see any commit logs

**Comment by edenhill** [comment]
Please fill out the full issue template by editing the first comment.

**Comment by fuchen90** [comment]
ok, already filled

**Comment by edenhill** [comment]
> 0.11.4 and 1.2.0

Is that confluent-kafka-go 0.11.4 and librdkafka 1.2.0?
I strongly suggest you upgrade the Go client to the latest version, v1.1.0.

> "enable.auto.commit": false,

How and when are you manually committing messages?

If you want to know what is going on under the hood I recommend you configure `"debug": "consumer"` (on go client v1.1.0).

**Comment by fuchen90** [comment]
`Is that confluent-kafka-go 0.11.4 and librdkafka 1.2.0?`
 Yes
`How and when are you manually committing messages?`
  when the consumption function ends
`If you want to know what is going on under the hood I recommend you configure "debug": "consumer" (on go client v1.1.0).`
 ok， I will try again

**Comment by fuchen90** [comment]
@edenhill Hi,  I found that I get the message in the way of consumer_channel_example and commit it using the Commit() method. The first commit will commit the largest offset, but we haven't finished the batch yet. At this time, restarting the consumer service will appear. Lost message。
What is the cause of this and how should it be solved?

**Comment by edenhill** [comment]
Commit() will only allow you to commit an offset that is higher than the last committed offset.
So if you process a number of messages from the same partition, you should process them in order, or make sure that you at least commit them in order.

**Comment by fuchen90** [comment]
So I need to use this method 'CommitMessage()' or 'CommitOffsets()' to avoid losing messages?

**Comment by edenhill** [comment]
Depends on your processing model, if you consume a bunch of messages, process them and then commit you can just call Commit().
If you want to commit per-message you can use CommitMessage(), but note that committing an offset tells the consumer where to start consuming on restart, i.e., for a given group.id, topic and partition there is only one committed offset.
On top of that librdkafka ignores any Commit*()s for offsets that are less than the last committed offset.

Also note that per-message commits are slow and will reduce your throughput, it is better to use autocommit but set `enable.auto.offset.store` to false and then call `StoreOffsets()` as you would call CommitMessage().

**Comment by fuchen90** [comment]
Ok，got it,  thank you very much
