### ISSUE TITLE
Runtime error: Symbol not found: _timespec_get 

### ISSUE THREAD

**Issue by yokawasa** [confluentinc/confluent-kafka-go#383]
Description
===========
I got the following error message when I run `confluent-kafka-go/examples/confluent_cloud_example/confluent_cloud_example.go`. 

```txt
go run confluent_cloud_example.go
dyld: lazy symbol binding failed: Symbol not found: _timespec_get
  Referenced from: /usr/local/opt/librdkafka/lib/librdkafka.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _timespec_get
  Referenced from: /usr/local/opt/librdkafka/lib/librdkafka.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

signal: abort trap
```

How to reproduce
================

Here is how i producde

```bash
# install librdkafka from Homebrew.
brew install librdkafka pkg-config

# Run the program
export GO111MODULE=on
cd confluent-kafka-go/examples/confluent_cloud_example
go run confluent_cloud_example.go
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):

[confluent-kafka-go]( https://github.com/confluentinc/confluent-kafka-go/releases/tag/v1.1.0): v1.1.0

```
$ brew info librdkafka
l
ibrdkafka: stable 1.2.1 (bottled), HEAD
The Apache Kafka C/C++ library
https://github.com/edenhill/librdkafka
/usr/local/Cellar/librdkafka/1.2.1 (16 files, 3.0MB) *
  Poured from bottle on 2019-10-18 at 19:33:46
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/librdkafka.rb
==> Dependencies
Build: pkg-config ✔
Required: lz4 ✔, lzlib ✔, openssl@1.1 ✔, zstd ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 8,843 (30 days), 18,112 (90 days), 51,593 (365 days)
install_on_request: 3,877 (30 days), 8,263 (90 days), 24,338 (365 days)
build_error: 0 (30 days)
```
 - Apache Kafka broker version: I am using Confluent Cloud on GCP 
 - Client configuration: `ConfigMap{...}`
 - Operating system:  `macOS 10.14.6 (18G103)`
 - Go version: 
```
$ go version
go version go1.13.1 darwin/amd64

```

**Comment by edenhill** [comment]
XCode decided to remove this symbol.

Fixed on librdkafka master:
https://github.com/edenhill/librdkafka/issues/2461

**Comment by yokawasa** [comment]
@edenhill  thank you so much for your help! I confirmed the issue was resolved with the librdkafka built from [master source](https://github.com/edenhill/librdkafka).

**Comment by klesgidis** [comment]
Hey guys, do you know when this is going to be released?

**Comment by edenhill** [comment]
librdkafka v1.2.2 will be released later this week.
