### ISSUE TITLE
SSL ConfigMap as String?

### ISSUE THREAD

**Issue by esinek** [confluentinc/confluent-kafka-go#392]
Description
===========
In our deployment, we are unable to mount files/folders for our kafka certs (I know - that would be a simple solution). As a result, we need a way to configure the SSL certs and keys using strings (we are allowed a single yaml file to be mounted). I was hoping I could base64 encode the key, cert, and ca and put into the yaml file and then programmatically base64 decode and set in the kafka configmap prior to calling NewConsumer(). Are there any string alternatives to the following:
- ssl.key.location
- ssl.certificate.location
- ssl.ca.location

How to reproduce
================
Disable the ability to mount kafka cert/keys/ca and try to figure out how to set using string values of these files

Checklist
=========
Please provide the following information:

 - [v1.1.0 v1.1.0] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yes, see `ssl.key.pem` and `ssl.certificate.pem`.
As for the CA, it can't be specified via pem at this point.

**Comment by esinek** [comment]
Thanks @edenhill - a couple follow-ups
- Do you have a timeline on when you will support CA via pem?
- For the `ssl.key.pem` and `ssl.certificate.pem`, once I decode the base64, do I need to `pem.Decode` it and then cast the bytes to a string when assigning it to the configMap? Or can I just pass in the string casted base64 value?

**Comment by esinek** [comment]
@edenhill , with this addition (addition of `ssl.ca.pem`), is it fair to say we no longer need to mount the cert, key, ca files?
https://github.com/edenhill/librdkafka/issues/2380

**Comment by edenhill** [comment]
@esinek Yep 👍

**Comment by edenhill** [comment]
And to answer your previous question, you should pass the textual PEM format to those config properties.
