### ISSUE TITLE
Running in docker and waiting for kafka

### ISSUE THREAD

**Issue by Agihi** [confluentinc/confluent-kafka-go#398]
Description
===========

When running the provided consumer and producer in Docker together with the confluent-image for kafka I run into problems regarding waiting. The producer and consumer won't check if kafka is ready. For creating topics I could do the following as a simple command replacement for the docker image:
`bash -c 'echo Waiting for Kafka to be ready... && \
      cub kafka-ready -b kafka:19092 1 20 && \
      kafka-topics --create --topic taxi --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181 && \
      sleep infinity'`

But I wan't to use Go to access Kafka and therefore I need an equivalent for this line: ` cub kafka-ready -b kafka:19092 1 20 && `

How to reproduce
================

Just start everything in docker via docker-compose and then the Consumer/Producer would error out because they can't connect to Kafka, because it is not ready yet. (Happens most of the time, but not always)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [x] Apache Kafka broker version: 5.1.2
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Alpine in Docker
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by bcashier** [comment]
Did you found a solution for this problem ? Any alternative to cub kafka-ready ?

Thank you

**Comment by edenhill** [comment]
You could call GetMetadata() to check if the client is connected to the cluster.
