### ISSUE TITLE
While closing consumer how to get out of infinite stuck loop so that further processing is not done

### ISSUE THREAD

**Issue by taalhach** [confluentinc/confluent-kafka-go#399]
Description
===========

Hi all
in following code my loop is stuck at c.ReadMessage line for an indefinite time and it will go further if any message is returned but that time is not known let say termination signal comes but loop is stuck at that c.readMessage for indefinite time then how should i terminate the loop which is not moving further

 ```
	for {
		select {
		case <-sign:
                     break
		default:
			//i:=0
			msg, _ := c.ReadMessage(-1)

		}

	}
```

**Comment by mhowlett** [comment]
use a timeout that isn't infinite. ideally we would provide a cooperative cancellation mechanism, but don't yet to my knowledge.

**Comment by taalhach** [comment]
thank you i used timeout

**Comment by taalhach** [comment]
context package can give us cancellation functionality and currently it isn't available here so i used timeout interval to poll the kafka and topped consumer when needed to

**Comment by taalhach** [comment]
context package can give us cancellation functionality and currently it isn't available here so i used timeout interval to poll the kafka and stopped consumer when needed, closing this issue further
