### ISSUE TITLE
auto_offset_reset doesn't change much

### ISSUE THREAD

**Issue by groyee** [confluentinc/confluent-kafka-go#40]
I am trying to consume latest messages using:

kafka.ConfigMap{"auto.offset.reset": "latest"}

It seems that it doesn't' affect anything and still reads from the last available offset.

What I need it that it will always start consuming **NEW** message and ignore the previous offset.

**Comment by edenhill** [comment]
auto.offset.reset is only used when there is no previously committed offset to continue from, or the committed offset is wrong (doesnt exist).

If you always want to start at a fixed offset (be it absolute or logical (beginning, end)) you can provide the starting .Offset per-partition in the TopicPartition you provide to Assign() from the AssignedPartitions event.

**Comment by groyee** [comment]
Thank You!
