### ISSUE TITLE
Memory leak in setting configuration properties?

### ISSUE THREAD

**Issue by gabeysunda** [confluentinc/confluent-kafka-go#402]
Hi,

In the function `anyconfSet()` in `kafka/config.go`, two CString's are allocated for the property key and value before being sent to the `rd_kafka_*_conf_set` library function. I don't think this library takes ownership of the string pointers passed in and the CString's are never free'd. The key is used in a comparison against the set of supported Kafka properties and if valid, new memory is allocated for the value. I believe `defer C.free(unsafe.Pointer(..))` needs to be called for each allocation so they are free'd when the function exits.

```
func anyconfSet(anyconf rdkAnyconf, key string, val ConfigValue) (err error) {
	value, errstr := value2string(val)
	if errstr != "" {
		return newErrorFromString(ErrInvalidArg, fmt.Sprintf("%s for key %s (expected string,bool,int,ConfigMap)", errstr, key))
	}
	cKey := C.CString(key)
	cVal := C.CString(value)
	cErrstr := (*C.char)(C.malloc(C.size_t(128)))
	defer C.free(unsafe.Pointer(cErrstr))

	if anyconf.set(cKey, cVal, cErrstr, 128) != C.RD_KAFKA_CONF_OK {
		C.free(unsafe.Pointer(cKey))
		C.free(unsafe.Pointer(cVal))
		return newErrorFromCString(C.RD_KAFKA_RESP_ERR__INVALID_ARG, cErrstr)
	}

	return nil
}
```

I see memory usage increase while repeatedly calling `NewAdminClient()` and `Close()` in `kafka/adminapi.go`. After free'ing the C strings in the above function memory is stable.

**Comment by rigelbm** [comment]
Thanks for catching this up and reporting!
