### ISSUE TITLE
Compatibility librdkafka v1.3.0

### ISSUE THREAD

**Issue by nsagnett** [confluentinc/confluent-kafka-go#404]
Hi there,

Just a question to know the release date of a compatible version with librdkafka v1.3.0

Thanks

**Comment by edenhill** [comment]
The Go client is compatible with future versions of librdkafka, meaning that the current release of confluent-kafka-go (v1.1.0) is compatible with the newly released librdkafka v1.3.0.

The opposite is not true though, the Go client version must not be higher than the librdkafka version.

We're aiming to release confluent-kafka-go v1.3.0 this week.

**Comment by nsagnett** [comment]
Is it possible to tag, even if the same commit has multiples tags, with the librdkakfa compatible version ?

**Comment by edenhill** [comment]
Not sure what you mean, can you elaborate?

**Comment by nsagnett** [comment]
Yes, sure.
The idea is just to keep a strict release equivalence between librdkafka and Go client to simplify upgrade librairies in our projets

**Comment by edenhill** [comment]
That scheme would break if a new Go client release is needed without a corresponding librdkafka version bump.

What we will do very soon is start bundling librdkafka with the Go client which voids any need for the user to maintain a separate librdkafka install.
You can try it out in this repo: 
https://github.com/confluentinc/confluent-kafka-go-dev

**Comment by nsagnett** [comment]
OK I see, it will be a very enjoyable bundle, that's right ! 

Thanks for your precisions !
