### ISSUE TITLE
/bin/sh: export: line 1: pkg-config: bad variable name

### ISSUE THREAD

**Issue by lazytooo** [confluentinc/confluent-kafka-go#408]
FROM golang:1.13.4-alpine

WORKDIR /project

RUN apk update && apk add curl git pkgconfig && curl https://glide.sh/get | sh

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
	&& apk add --no-cache --update git gcc libc-dev librdkafka

RUN export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig/:/usr/local/Cellar/librdkafka/0.11.6/lib/pkgconfig/ pkg-config --libs rdkafka

COPY go.mod go.sum ./
    && GO111MODULE="on" \
    && GOPRIVATE="xxxxx" \
    && GOSUMDB=off \
    && GOPROXY="https://goproxy.cn,direct" \
    && env \
    && time go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    && go build -o main \
    && go test --cover  $(go list ./...)

=======
/bin/sh: export: line 1: pkg-config: bad variable name

Error: ResponseItem.ErrorDetail[code=2,message=The command '/bin/sh -c export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig/:/usr/local/Cellar/librdkafka/0.11.6/lib/pkgconfig/ pkg-config --libs rdkafka' returned a non-zero code: 2]
Failed to deploy '<unknown> Dockerfile: infrastructure/analytics/Dockerfile': The command '/bin/sh -c export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig/:/usr/local/Cellar/librdkafka/0.11.6/lib/pkgconfig/ pkg-config --libs rdkafka' returned a non-zero code: 2

**Comment by edenhill** [comment]
> PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig/:/usr/local/Cellar/librdkafka/0.11.6/lib/pkgconfig/ pkg-config --libs rdkafka

That line looks suspect:
 * it is probably missing backticks around the pkg-config ..
 * it has a hard reference to what looks to be a macos brew path (usr/local/Cellar)
 * it references librdkafka 0.11.6 which is too old and not compatible with the current version of the Go client
 * it is not needed, the Go client build script already has pkg-config specified.

**Comment by edenhill** [comment]
The Go client now comes with librdkafka bundled.
