### ISSUE TITLE
OSX: unable to build kafkacat

### ISSUE THREAD

**Issue by bluebob** [confluentinc/confluent-kafka-go#41]
Followed install instructions, ("brew install pkg-config git librdkafka") and got:
```
$ go get gopkg.in/confluentinc/confluent-kafka-go.v0/kafka
$ go get gopkg.in/confluentinc/confluent-kafka-go.v0/examples/go-kafkacat
# github.com/confluentinc/confluent-kafka-go/kafka
github.com/confluentinc/confluent-kafka-go/kafka/producer.go:46:9: error: use of undeclared identifier 'RD_KAFKA_V_END'
        RD_KAFKA_V_END);
        ^
1 error generated.
$
```

Build system is El-Capitan Mac, running "go version go1.7.5 darwin/amd64"

Was going to wonder if there was a header file that it's not picked up, but if that's the cause then it's a bit weird that it's only one id that's failing. Any suggestions?

**Comment by edenhill** [comment]
What is your installed version of librdkafka?

**Comment by bluebob** [comment]
`$ brew list librdkafka
/usr/local/Cellar/librdkafka/0.9.3/include/librdkafka/ (2 files)
/usr/local/Cellar/librdkafka/0.9.3/lib/librdkafka++.1.dylib
/usr/local/Cellar/librdkafka/0.9.3/lib/librdkafka.1.dylib
/usr/local/Cellar/librdkafka/0.9.3/lib/pkgconfig/ (2 files)
/usr/local/Cellar/librdkafka/0.9.3/lib/ (4 other files)`

**Comment by bluebob** [comment]
Followed the equivalent setup for Centos7 and that works fine. :)

**Comment by edenhill** [comment]
I dont have access to a mac right now so could you do this for me:

`$ grep VERSION /usr/local/Cellar/librdkafka/0.9.3/include/librdkafka/rdkafka.h`
and 
`$ grep _V_ /usr/local/Cellar/librdkafka/0.9.3/include/librdkafka/rdkafka.h`

?

**Comment by bluebob** [comment]
```
$ grep VERSION /usr/local/Cellar/librdkafka/0.9.3/include/librdkafka/rdkafka.h
#define RD_KAFKA_VERSION  0x000903ff
 * @sa See RD_KAFKA_VERSION for how to parse the integer format.
	RD_KAFKA_RESP_ERR_UNSUPPORTED_VERSION = 35,
```
the other grep doesn't come back with anything

**Comment by edenhill** [comment]
Thank you.
The version check is wrong in the Go client, will fix.

**Comment by bluebob** [comment]
Thanks. That was quick work to diagnose. :)

**Comment by edenhill** [comment]
This is fixed on Go client master now, can you update and try agian?

**Comment by bluebob** [comment]
Yes, that sorted it. _Thanks!_
