### ISSUE TITLE
How to use uncommit function

### ISSUE THREAD

**Issue by hanluner** [confluentinc/confluent-kafka-go#410]
Description
===========
I want to control commit offset manually, through commit logic and uncommit logic. Now I got consumer commit method by the repo, but I couldn't find how to use uncommit function.  Equal
 to leave the current message to go and to do next one.  The current message can be assign to other consumer client.

**Comment by taalhach** [comment]
as far as i know if higher offset of "a partition" is committed then lower offsets' messages can't be consumed again its like marking the index till you have consumed not the individual index marking . If you want to have more than one consumers with same group id then you need to use consumer group and more than one partitions of same topic. while you will be producing messages you will be giving the desired partitions to desired messages.

**Comment by milindl** [comment]
There is no uncommit function and no plan to add something like that.
If you want to consume the same message with different consumers, you can consider using separate consumer groups for the two consumers as mentioned in the above answer.
Closing this issue, please reopen for any further issues.
