### ISSUE TITLE
compile error on mac mojave

### ISSUE THREAD

**Issue by ShmSeeker** [confluentinc/confluent-kafka-go#413]
Description
===========
build failed.
librdkafka has something wrong

How to reproduce
================
i use go build -gcflags "-N -L" main.go to compile,it is all right. but when i use the blow command,it's wrong.
 CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -gcflags "-N -L" main.go 
# command-line-arguments
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: ignoring file /var/folders/0l/w50x4mcx2cv3qm9fr2wsyy1w0000gn/T/go-link-946911388/go.o, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /var/folders/0l/w50x4mcx2cv3qm9fr2wsyy1w0000gn/T/go-link-946911388/go.o
Undefined symbols for architecture x86_64:
  "__cgo_topofstack", referenced from:
      __cgo_eb5afb1728b5_Cfunc_ConfigEntry_by_idx in 000002.o
      __cgo_eb5afb1728b5_Cfunc_ConfigResource_by_idx in 000002.o
      __cgo_eb5afb1728b5_Cfunc_rd_kafka_AlterConfigs_result_resources in 000002.o
      __cgo_eb5afb1728b5_Cfunc_rd_kafka_ConfigEntry_is_read_only in 000002.o
      __cgo_eb5afb1728b5_Cfunc_rd_kafka_ConfigEntry_is_sensitive in 000002.o
      __cgo_eb5afb1728b5_Cfunc_rd_kafka_ConfigEntry_is_synonym in 000002.o
      __cgo_eb5afb1728b5_Cfunc_rd_kafka_ConfigEntry_name in 000002.o
      ...
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: __cgo_eb5afb1728b5_Cfunc_rd_kafka_queue_get_main)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
librdkafka-1.3.0.mojave.bottle.tar.gz
pkg-config-0.29.2.mojave.bottle.1.tar.gz
 - [x] Operating system:
mojave 10.14.6
 - [x] Critical issue
      yes

**Comment by edenhill** [comment]
The Go client now comes with librdkafka bundled.
