### ISSUE TITLE
The latest pre-built version of librdkafka is 1.1.0?

### ISSUE THREAD

**Issue by zhuwh1118** [confluentinc/confluent-kafka-go#419]
Description
===========
Like title, is 1.3.0 pre-built package available?
I can only get librdkafka-devel-1.1.0_confluent5.3.2-1.el7.x86_64.rpm from Confluent repository

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka v1.3.0 deb and rpm packages will be released very soon, stay tuned.

In the meantime I suggest building librdkafka from source.

**Comment by anukul-mohil** [comment]
@edenhill Eagerly waiting for this

**Comment by phemmer** [comment]
Well, it seems 1.3.0 RPMs are out, but now the golang package requires 1.4.0, of which there are no releases, and we're back in the same boat again :-(

**Comment by anukul-mohil** [comment]
@edenhill Do you have something on the roadmap for future golang package requirement matching with the released RPMs or there is no commitment on that and its on a best effort basis. Want to know so that we can plan accordingly.

**Comment by edenhill** [comment]
The next version of confluent-kafka-go will be shipped with librdkafka included, voiding the need to install librdkafka separately.
It is due in less than a month.
