### ISSUE TITLE
Confluent Rust Client?

### ISSUE THREAD

**Issue by nathanawmk** [confluentinc/confluent-kafka-go#424]
I have experimented with C/C++ Client, Go Client, Java Client, .NET Client and Python Client.

By far, ceteris paribus, Go Client is the fastest. However, Rust will be faster. 

Are there plans to develop a Rust-Based Client? Can I start?

**Comment by edenhill** [comment]
Did you see this Rust client that is based on librdkafka?
https://github.com/fede1024/rust-rdkafka
