### ISSUE TITLE
consumer channel, Events() has a race condition

### ISSUE THREAD

**Issue by evgeniyasti** [confluentinc/confluent-kafka-go#428]
Description
===========
When I'm reading your [example for the consumer channel](https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/consumer_channel_example/consumer_channel_example.go), I can't help to notice that there's a race condition in it.
Consider the following [fact](https://github.com/confluentinc/confluent-kafka-go/blob/0.9.4.x/kafka/event.go#L126-L138): 			

```
// Since librdkafka requires the rebalance event to be "acked" by
// the application to synchronize state we keep track of if the
// application performed Assign() or Unassign(), but this only works for
// the non-channel case. For the channel case we assume the application
// calls Assign() / Unassign().

// Failure to do so will "hang" the consumer, e.g., it wont start consuming
// and it wont close cleanly, so this error case should be visible
// immediately to the application developer.
```

Does this mean that if a termination signal occurs on [line 67](https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/consumer_channel_example/consumer_channel_example.go#L67), and then right before calling `c.Close()` there's a rebalancing event sent to the application, the `c.Close()` will hang indefinitely? 

How to reproduce
================

Checklist
=========
Please provide the following information:

I'm trying to understand better how to use the `Events()` consumer channel.

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
Thanks for filing this issue. I'm closing this as the channel based consumer is now deprecated (since v2.0.2) and there won't be any changes to it.
