### ISSUE TITLE
Error: Disconnected (after XYZms in state UP)

### ISSUE THREAD

**Issue by fnuneztw** [confluentinc/confluent-kafka-go#436]
Description
===========
When trying to connect to our Kafka brokers the following error is thrown:

`127.0.0.1:10004/bootstrap: Disconnected (after 7011ms in state UP)`

I am using that address since I am using HAProxy.

I can't seem to find any information related to this error and I am unsure how to fix it.

Under which circumstances is this error thrown, and what does it mean to be in state UP?

How to reproduce
================
Unsure. In my case I am unable to connect, so just running the application produces the error.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion(1.3.0)`):
 - [x] Apache Kafka broker version: 
 - [x] Client configuration:
   ```
	"bootstrap.servers":  "127.0.0.1:10004",
	"group.id":           "some.group.id",
	"auto.offset.reset":  "earliest",
	"enable.auto.commit": "false",
    ```
 - [x] Operating system: **Amazon Linux AMI**
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Set `"debug": "protocol,broker"` to see what is being sent.
Also make sure that you are using the correct security.protocol, sasl.mechanism, etc, for connecting to your broker.

**Comment by fnuneztw** [comment]
> "debug": "protocol,broker"

Where is the generated output dumped?

**Comment by edenhill** [comment]
stderr by default

**Comment by fnuneztw** [comment]
Sample of the output generated in stderr (ips masked, hope that isn't a problem): [gist](https://gist.github.com/fnuneztw/883aef5bd486e3ce3990add17eff271b)

**Comment by edenhill** [comment]
It looks like you are explicitly closing the consumer:
> 2020-03-06T08:05:35-08:00 %7|1583510735.796|DESTROY|rdkafka#consumer-43| [thrd:app]: Terminating instance (destroy flags none (0x0))

Do you have some error handling logic that closes the consumer?

Most errors are just informative, the client will try to automatically recover from all errors and an application does not need to perform any special action in case an error is raised, given the client is correctly configured.

**Comment by fnuneztw** [comment]
> Do you have some error handling logic that closes the consumer?

Yes. After I receive an error in `ReadMessage`, I close the consumer and recreate it.

When I test the application locally (it is containerized) it works without problems, but when deployed to AWS is when it fails. I have an utility tool that verified that I can correctly read topic messages from inside the deployed container in AWS.

Furthermore, when using [Segment's client](https://github.com/segmentio/kafka-go) I have no problems neither locally nor when deployed in AWS :/

**Comment by edenhill** [comment]
> Yes. After I receive an error in ReadMessage, I close the consumer and recreate it. 

Don't do that and you should be fine.

**Comment by edenhill** [comment]
There is a fix in the upcoming v1.4.0 release that should silence the Node update error, but you still need to fix your code not to exit on consumer error.

**Comment by fnuneztw** [comment]
Ok... Let me try that 👍

**Comment by fnuneztw** [comment]
By the way, in which case would one have to close the consumer?

**Comment by edenhill** [comment]
Given that the consumer and cluster is correctly configured: never, all errors should be considered temporary.

But we're improving the error type to be able to indicate if an error is retriable, ignorable, or fatal. It'll take some time for that to hit all APIs though.

**Comment by fnuneztw** [comment]
That did the trick! Thank you.

> But we're improving the error type to be able to indicate if an error is retriable, ignorable, or fatal. It'll take some time for that to hit all APIs though.

👍
