### ISSUE TITLE
consume kicked from group unexpectedly

### ISSUE THREAD

**Issue by solarhell** [confluentinc/confluent-kafka-go#438]
Description
===========
err log
`%4|1584354682.571|MAXPOLL|rdkafka#consumer-1| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 149ms (adjust max.poll.interval.ms for long-running message processing): leaving group`

I am working on a program that consume from kafka and upload to aws s3.
From the log, i can see that the consumer was kicked from group after exactly **2** minutes.
```
{"L":"INFO","T":"2020-03-16T18:24:22.394+0800","M":"start polling..."
..........................................
{"L":"DEBUG","T":"2020-03-16T18:26:22.421+0800","M":"nil event"
%4|1584354682.571|MAXPOLL|rdkafka#consumer-1| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 149ms (adjust max.poll.interval.ms for long-running message processing): leaving group
```
And i also checked the java client, i can see that after half hour that the client is still polling from topic.
But i don't have the **"2 minutes (120000 ms)"**  in my config.

After kicked from the group, i can't see the log "start polling..." nor "nil evnet".

How to reproduce
================
```golang
	config := &kafka.ConfigMap{
		"bootstrap.servers":    strings.Join(conf.Kafka.Brokers, ","),
		"group.id":             job.meta,
		"auto.offset.reset":    "earliest",
		"enable.auto.commit":   false,
		"session.timeout.ms":   10000,
		"max.poll.interval.ms": 300000,
		//"enable.auto.offset.store": false,
		//"go.application.rebalance.enable": true,
		//"enable.partition.eof":            true,
	}
```
main func
```
for {
			select {
			.......
                         deafult:
				job.logger.Info("start polling...")
				ev := job.consumer.Poll(100)
				if ev == nil {
					logger.Debug("nil event")
					continue
				}
				switch e := ev.(type) {
				//case kafka.AssignedPartitions:
				//	panic(e)
				//case kafka.RevokedPartitions:
				//	panic(e)
				case *kafka.Message:
}}
```
newConsumer
```
c, err := kafka.NewConsumer(config)
err = c.Subscribe(job.topicName, job.newConsumerRebalanceCb())

func (job *Job) newConsumerRebalanceCb() kafka.RebalanceCb {
	return func(consumer *kafka.Consumer, ev kafka.Event) error {
		job.mu.Lock()
		defer job.mu.Unlock()
		job.logger.Info("start rebalance", zap.String("consumer", consumer.String()))
		switch e := ev.(type) {
		case kafka.AssignedPartitions:
			job.logger.Info("AssignedPartitions", zap.Any("event", e))
			if err := consumer.Assign(e.Partitions); err != nil {
				job.logger.Error("Error Assign Partition", zap.Error(err))
				panic(err)
			}
			job.partitions.Clear()
			for _, p := range e.Partitions {
				job.partitions.Add(p.Partition)
			}
			job.logger.Info("current partition status", zap.String("partitions", job.partitions.String()))
		case kafka.RevokedPartitions:
			job.logger.Info("RevokedPartitions", zap.Any("event", e))
			if err := consumer.Unassign(); err != nil {
				job.logger.Error("Error Revoke Partition", zap.Error(err))
				panic(err)
			}
			job.partitions.Clear()
			// some clean stuff
			job.msg = map[int32][]string{}
			job.offsets = map[int32]kafka.TopicPartition{}
		}
		return nil
	}
}
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.3.0
 - [x] Apache Kafka broker version: 1.0.0
 - [x] Client configuration: `	config := &kafka.ConfigMap{
		"bootstrap.servers":    strings.Join(conf.Kafka.Brokers, ","),
		"group.id":             job.meta,
		"auto.offset.reset":    "earliest",
		"enable.auto.commit":   false,
		"session.timeout.ms":   10000,
		"max.poll.interval.ms": 300000,
		//"enable.auto.offset.store": false,
		//"go.application.rebalance.enable": true,
		//"enable.partition.eof":            true,
	}`
 - [x] Operating system: macOS
 - [x] Provide client logs (with `"debug": ".."` as necessary) %4|1584354682.571|MAXPOLL|rdkafka#consumer-1| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 149ms (adjust max.poll.interval.ms for long-running message processing): leaving group`
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you make a printout (with timestamp) for the non-nil case as well?

Are you calling Poll() in a loop?

Looking at the timestamps of the nil printout and the librdkafka log it is exactly 5 minutes or 300s, which suggests that Poll() was not called again after the nil printout.

**Comment by solarhell** [comment]
For Q1: I have already consumed all of the msgs in topic and committed the offsets of them, so there is no msg left to consume. You can  treat it as an emtpy topic.
For Q2: Yes. I will upload every 10 mintues or when i have gathered enouth msgs (BatchSize) and will commit offsets if the upload is success.
For Q3: This is what made my confused. I call Poll() in a infinite loop. But i can't see the log.

Cause i am using the PC at home, i can append some more useful log you mentioned tomorrow when in the company.

Thanks for your attention. I’m looking forward to your reply.

**Comment by solarhell** [comment]
Sorry, it's my code's mistake. I have tested again and it works now.
BTW, i can see the config 'go.application.rebalance.enable', now i didn't set it, but i can also handle reBalance event. Can you explain for this config?

Thanks for your attention. I’m looking forward to your reply.

**Comment by solarhell** [comment]
![image](https://user-images.githubusercontent.com/10279583/79295000-2f688180-7f0a-11ea-9e62-778d92d9af0d.png)
Now i know that the config is for consumer to specific offsets to consume from.
