### ISSUE TITLE
Kafka Producer Concurrent Usage and Events Channel

### ISSUE THREAD

**Issue by jenu9417** [confluentinc/confluent-kafka-go#442]
Description
===========
In a previous [issue](https://github.com/confluentinc/confluent-kafka-go/issues/67), it was mentioned that, the kafka.Producer struct is safe for concurrent usage. But what happens when we are listening to the events channel for acknowledgement after calling `producer.Produce()`
In this case, ideally two routines are waiting for the output from `producer.Events()` channel, and the first output can be received by either of the go routines. In this case, 
a) How can we say that, producer API is thread safe?
b) How to handle the scenario properly?

How to reproduce
================

Sample Code:

`events := producer.Events()`
` err := producer.Produce(message, nil)`
` ev := <-events`
` switch event := ev.(type) {`
` case *kafka.Message:`
  `   .....`
` case *kafka.Error:`
  `   .....`
`  default:`
  `   .....`
`}`

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
       `confluent-kafka-go v1.3.0`
      ` librdkafka v1.3.0`
 - [ ] Apache Kafka broker version:
       `Kafka v2.11-0.10.1.1`
 - [ ] Client configuration: `ConfigMap{...}`
      `kafka.ConfigMap{`
      `    "bootstrap.servers":     "localhost:9092",`
      `	  "request.required.acks": "all",`
     ` }`
 - [ ] Operating system:
       `centos7`
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Go channels are thread safe.
An event written to a Go channel will be read by at most one Go channel reader, there is no guarantee on which reader will see the event.
You can't use a single channel to broadcast events to all readers.
