### ISSUE TITLE
go build     undefined: kafka.NewConsumer

### ISSUE THREAD

**Issue by liukelin** [confluentinc/confluent-kafka-go#445]
Description
===========
os: redhat centos
go build     
undefined: kafka.NewConsumer

librdkafka-dev (0.8.6-1.1)。

How to reproduce
================

**Comment by edenhill** [comment]
confluent-kafka-go v1 requires librdkafka v1.3.0 or later, see https://github.com/confluentinc/confluent-kafka-go/blob/master/README.md#getting-started

and make sure to import the client with v1:
```golang
import (
	"fmt"
	"gopkg.in/confluentinc/confluent-kafka-go.v1/kafka"
)

**Comment by mostafatalebi** [comment]
I do this but still get error/ I import: "gopkg.in/confluentinc/confluent-kafka-go.v1/kafka" but when I run `go mod tidy & go mod vendor` it throws the following error:
`
go: finding module for package gopkg.in/confluentinc/confluent-kafka-go.v1/kafka
inventory/pkg/service/adapters imports
        gopkg.in/confluentinc/confluent-kafka-go.v1/kafka: cannot find module providing package gopkg.in/confluentinc/confluent-kafka-go.v1/kafka: gopkg.in/confluentinc/confluent-kafka-go.v1@v1.3.0: invalid version: go.mod has non-....v1 module path "github.com/confluentinc/confluent-kafka-go" at revision v1.3.0
`

**Comment by edenhill** [comment]
If you are using go mod you should import without the v1 suffix and instead specify the version in your go.mod file.
gopkg.....v1 is for people that can't use go mods.

**Comment by mostafatalebi** [comment]
Solved my issue.
Thanks

**Comment by liukelin** [comment]
Thanks.
