### ISSUE TITLE
How to suspend Consumer ？ and Do not close the connection. 

### ISSUE THREAD

**Issue by liukelin** [confluentinc/confluent-kafka-go#452]
Description
===========

    c, err := kafka.NewConsumer(&kafka.ConfigMap{
	"bootstrap.servers":     strings.Join(broker, ","),
	"broker.address.family": "v4",
	"group.id":              group,
	"session.timeout.ms":    6000,
	"auto.offset.reset":     "earliest",
	"enable.auto.commit":    false,
    })

...
 
     if suspended == false {
		offsets, err := c.Commit()
		if err == nil {
			c.CommitOffsets(offsets)
		}
	} else {
		var metadata string
		metadata = "" // *e.TopicPartition.Metadata
		offits, _ := strconv.Atoi(e.TopicPartition.Offset.String())
		partition := int(e.TopicPartition.Partition)
		commitOffset(c, *e.TopicPartition.Topic, partition, offits, metadata)
	}

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you pause the message fetcher by calling Pause() on your Assignment(), but you will need to call Poll(), ReadMessage() or read from the Events channel regular intervals (< max.poll.interval.ms) to avoid getting kicked out of the group.

**Comment by liukelin** [comment]
call Poll(),   suspended commit offset-1;   other normal  commit offset;   ?
and 
suspended-> normal   goto again SubscribeTopics()

**Comment by edenhill** [comment]
I'm sorry but I don't understand your question, please elaborate.

**Comment by liukelin** [comment]
I'm so sorry . my english is poor.
Thanks .  my problem seems to be solved according to your suggestion.   Resume()/Pause()

**Comment by milindl** [comment]
Closing as the problem was solved.
