### ISSUE TITLE
consumer stops after read some messages.

### ISSUE THREAD

**Issue by ankitpatelce** [confluentinc/confluent-kafka-go#459]
Description
===========
I have get sample code of consumer and connect it with my kafka server.
when I run sample code every time it tkaes 900 Messages (each message is approx 1200 Bytes) in second and then it stops or get error for 4 to 5 second and get 900 Messages again.

means it stops 4 to 5 min after reading 900 messages. is there any limitation?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What error are you seeing when it stops?

**Comment by ankitpatelce** [comment]
for {
		msg, err := c.ReadMessage(-1)
		if err == nil {
			dt := time.Now()
			//fmt.Printf("Message on %s: %s\n",msg.TopicPartition, string(msg.Value))
			fmt.Printf("<%s> %s\n", dt.Format("15:04:05"), string(msg.Value))
		} else {
			// The client will automatically try to recover from all errors.
			fmt.Printf("Consumer error: %v (%v)\n", err, msg)
		}
	}

Not geeting error but after reading 900 message, it stops at c.ReadMessage

**Comment by edenhill** [comment]
And you're sure there are more messages in the topic/partitions to consume?
Perhaps the producer is only producing new messages every 4-5 seconds?

**Comment by ankitpatelce** [comment]
Yes I am sure.

I have already produced 10000 message in that topic.
So all the messages are there.

**Comment by edenhill** [comment]
Interesting, can you enable `"debug": "cgrp,fetch,topic,broker"` and provide the output from where you see a pause in consumption?

**Comment by ankitpatelce** [comment]
Not understand your point. How to enable it and debug it. Please guid me.

**Comment by edenhill** [comment]
Set this in your consumer's ConfigMap:
```golang
 "debug": "cgrp,fetch,topic,broker",
```

**Comment by pundliksarafdar** [comment]
I am facing same issue, Mostly partition with larger offset stops sending message to consumer after some time. I will try adding "debug": "cgrp,fetch,topic,broker" and will update on this once again

**Comment by deanMdreon** [comment]
Was there any resolution to this issue? I am seeing the same behavior, where  17 of my 40 partitions stop receiving messages at the same offset every time it is run, while there are many more messages in the topic.

**Comment by ankitpatelce** [comment]
Dear Sir,

I have tried many ways . But I did not get a solution to it.

Ankit Patel
Sr. Software Engineer

**Comment by edenhill** [comment]
Please reproduce this with `"debug": "cgrp,fetch,topic,broker"` and provide the full log, as well as information on what topic+partitions you are not seeing messages for, and when.

**Comment by milindl** [comment]
Closing this as it's been awaiting the logs for a while.
Please reopen this if this still persists, with the logs generated by adding the debug key in the configmap.
