### ISSUE TITLE
Is Transaction supported across kafka cluster

### ISSUE THREAD

**Issue by Knight-Wu** [confluentinc/confluent-kafka-go#465]
Description
===========
Hi, i want to know if consume from A kafka cluster -> process -> produce to B kafka cluster, is supported by the latest version (confluent-kafka-go) . 
Both kafka cluster support transaction. 
Thanks first .

**Comment by edenhill** [comment]
Transactions can't span multiple Kafka clusters since input-offsets and output-messages are committed atomically.

**Comment by Knight-Wu** [comment]
hi, @edenhill  what do you mean atomically ? Can you explain more details ? Offset commited in line 64, is that right ? 
![image](https://user-images.githubusercontent.com/20329409/81674187-5cfc0880-947f-11ea-9f71-1d266e6072fc.png)

**Comment by Knight-Wu** [comment]
https://github.com/eugenp/tutorials/blob/master/libraries-6/src/main/java/com/baeldung/kafka/TransactionalWordCount.java, i take java api for example , it is almost the same with confluent-kafka-go
