### ISSUE TITLE
Stats Events are not getting delivered

### ISSUE THREAD

**Issue by dearchap** [confluentinc/confluent-kafka-go#467]
Description
===========
The statistics.interval.ms is set to 1000ms but we dont see the StatsEvent every 1. Its more likely that the StatsEvents are falling through default in GetMessage() loop since both Events and Messages use the same c.Poll() call. 

How to reproduce
================
Enable stats events and make sure messages are being sent on that topic. See that stats are not delivered periodically

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1, latest from git
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`  
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
As stated in the API docs, ReadMessage is a convenience function that discards everything but Message events:
https://docs.confluent.io/current/clients/confluent-kafka-go/index.html#Consumer.ReadMessage

Its purpose is to quickly get up and running with the client, for more advanced uses, like when stats are desired, you need to use the Poll API.
