### ISSUE TITLE
Is there a way to setup primary/secondary kafka

### ISSUE THREAD

**Issue by evgeniyasti** [confluentinc/confluent-kafka-go#468]
Hello.

Is there a way to specify a primary and a backup Kafka cluster for the Kafka client?

Thanks

**Comment by edenhill** [comment]
A Kafka client must only be connected to one cluster at the time.
You can use DNS records with short TTLs to allow redirecting clients to a different cluster (by changing the DNS records), but it is imperative that a client must not be able to have simultaneous connections to brokers in different clusters.
