### ISSUE TITLE
Unexpected delay when poll messages

### ISSUE THREAD

**Issue by hoobean1996** [confluentinc/confluent-kafka-go#473]
Description
===========

Currently, I don't get more information or logs, the situation is described as below:

1 I have a producer write a message to Kafka at time t, assume the topic is T

2 there is a consumer subscribing to this topic T, but I found after `t+3` hours, the consumer polled this message, no errors/ bad things happened.

How to reproduce
================
Still investigating.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
latest
 - [ ] Apache Kafka broker version:
2.10
 - [ ] Client configuration: `ConfigMap{...}`
```
	"bootstrap.servers":    strings.Join(brokers, ","),
			"session.timeout.ms":   120000,
			"enable.auto.commit":   false,
			"group.id":             groupID,
			"auto.offset.reset":    "earliest",
			"max.poll.interval.ms": 600000,
```
 - [ ] Operating system:
Ubuntu 16.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
Current no.
 - [ ] Provide broker log excerpts
Current no
 - [ ] Critical issue

Do you ever encounter such a situation, I don't know how to reproduce it now, can you please share some ideas for me then I can check it.
Thanks so much!!

**Comment by edenhill** [comment]
You need to specify the exact confluent-kafka-go and librdkafka versions (use Version() and LibVersion()) for us to know if you're hitting a known issue or not.

**Comment by hoobean1996** [comment]
resolved already

**Comment by dangquocdat97** [comment]
> resolved already

Hi, can you share your solution ? It seems I get the same problem. Thanks
