### ISSUE TITLE
Golang kafka producer is not hashing when key is specified

### ISSUE THREAD

**Issue by GMac2890** [confluentinc/confluent-kafka-go#474]
Description
===========
From the confluent kafka docs: https://docs.confluent.io/current/clients/producer.html
It is specified:
`If the key is provided, the partitioner will hash the key with murmur2 algorithm and divide it by the number of partitions. The result is that the same key is always assigned to the same partition. If a key is not provided, behavior is Confluent Platform version-dependent`

I'm using confluent kafka golang library but even though I specify a key, my messages are always written to partition 0. Looking at the producer.go, I see that the TopicPartition.Partition is picked and couldn't find any hash functions.

Are the writers expected to compute the hash by themselves and specify the partition number?

How to reproduce
================
Any writer writing to a topic with multiple partitions

Checklist
=========
Please provide the following information:

 - [ v1.4.2 ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [0.11.0.2 ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [CentOS] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
When constructing the `Message` you need to set the partition to `PartitionAny` for the partitioner to be used, if you leave it to the default initialization value of 0 it will use partition 0.
See the example here:
https://github.com/edenhill/confluent-kafka-go/blob/master/examples/producer_example/producer_example.go#L52

**Comment by GMac2890** [comment]
Hi, I saw the PartitionAny but it looks like that will cause the writer to use a random partition for a set of messages with the same key. Is my understanding incorrect? I need ordering guarantees for messages, so I am looking for a hash function on the message key.

**Comment by edenhill** [comment]
It will use the partitioner to when PartitionAny, resulting in same key going to the same partition.
