### ISSUE TITLE
can't consumer msg from confluent cloud but cli work normally

### ISSUE THREAD

**Issue by somnus0x** [confluentinc/confluent-kafka-go#477]
Description
===========
can't connect to consumer. but when i try to consume msg on the cli it worked normally.

How to reproduce
================

here are my source code for consumer initialization

`consumer, err := kafka.NewConsumer(
		&kafka.ConfigMap{
			// Avoid connecting to IPv6 brokers:
			// This is needed for the ErrAllBrokersDown show-case below
			// when using localhost brokers on OSX, since the OSX resolver
			// will return the IPv6 addresses first.
			// You typically don't need to specify this configuration property.
			// "bootstrap.servers":     <BOOTSTRAP_SERVER>,
			"sasl.username":         <API_KEY>,
			"sasl.password":        <API_SECRET>,
			"broker.address.family": "v4",
			"group.id":              "test-group",
			"session.timeout.ms":      6000,
			"auto.offset.reset":       "earliest",
			"sasl.mechanisms":         "PLAIN",
			"broker.version.fallback": "0.10.0.0",
			"api.version.fallback.ms": 0,
			"security.protocol":     "SASL_SSL",
			// "enable.auto.commit":    false,
		})`

here are my source code for consuming msg

`err := s.consumer.SubscribeTopics(topic, nil)
	if err != nil {
		panic(err.Error())
	}
	sigchan := make(chan os.Signal, 1)
	run := true
	for run == true {
		fmt.Println("polling in progress .....")
		select {
		case sig := <-sigchan:
			fmt.Printf("Caught signal %v: terminating\n", sig)
			run = false
		default:
			ev := s.consumer.Poll(100)
			if ev == nil {
				fmt.Println("s ")
				continue
			}

			switch e := ev.(type) {
			case *kafka.Message:
				fmt.Printf("%% Message on %s:\n%s\n",
					e.TopicPartition, string(e.Value))
				if e.Headers != nil {
					fmt.Printf("%% Headers: %v\n", e.Headers)
				}
			case kafka.Error:
				// Errors should generally be considered
				// informational, the client will try to
				// automatically recover.
				// But in this example we choose to terminate
				// the application if all brokers are down.
				fmt.Fprintf(os.Stderr, "%% Error: %v: %v\n", e.Code(), e)
				if e.Code() == kafka.ErrAllBrokersDown {
					run = false
				}
			default:
				fmt.Printf("Ignored %v\n", e)
			}
		}
	}

	fmt.Printf("Closing consumer\n")
	s.consumer.Close()`

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): gopkg.in/confluentinc/confluent-kafka-go.v1 v1.4.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `&kafka.ConfigMap{
			// Avoid connecting to IPv6 brokers:
			// This is needed for the ErrAllBrokersDown show-case below
			// when using localhost brokers on OSX, since the OSX resolver
			// will return the IPv6 addresses first.
			// You typically don't need to specify this configuration property.
			// "bootstrap.servers":     <BOOTSTRAP_SERVER>,
			"sasl.username":         <API_KEY>,
			"sasl.password":        <API_SECRET>,
			"broker.address.family": "v4",
			"group.id":              "test-group",
			"session.timeout.ms":      6000,
			"auto.offset.reset":       "earliest",
			"sasl.mechanisms":         "PLAIN",
			"broker.version.fallback": "0.10.0.0",
			"api.version.fallback.ms": 0,
			"security.protocol":     "SASL_SSL",
			// "enable.auto.commit":    false,
		})`
 - [ ] Operating system: macOS Catalina 10.15.5 
 - [ ] Provide client logs (with `"debug": ".."` as necessary): No error just no msg
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
if you provide debug logs, we can see what's going on.

if you're not adding messages to the topic as you're trying to consume from it, perhaps try changing the group name in case you've committed the last offset.

**Comment by milindl** [comment]
Closing this as it's been a while since Matt asked for the debug logs.
Please reopen with debug logs if this persists.
