### ISSUE TITLE
Mock consumer.Events() for unit tests

### ISSUE THREAD

**Issue by Rahul7794** [confluentinc/confluent-kafka-go#486]
My consumer listens to Events() and receives a chan event and processes it further. I am trying to write unit tests for my consumer functions which basically looks like this:
```
func consume(c *kafka.Consumer) {
run := true
for run {
		select {
		case sig := <-sigchan:
			log.Fatalf("caught signal %v: terminating ", sig)
			run = false
		case ev := <-c.Events():
			switch e := ev.(type) {
			case *kafka.Message:
				 // do something
				}
}
}
}
```
Any suggestions to mock c.Events() or how to produce chan of `events` for testing purposes?

**Comment by edenhill** [comment]
@Rahul7794 Did you find a solution?

**Comment by Rahul7794** [comment]
Oh Yes! I did not see earlier the implementation of Kafka.Event which is similar to Stringify. So I can just pass the custom Kafka message that I can create for the test to function expecting Kafka.Event

func HandleEvent(event Kafka.Event) {
// Do something
}
so in the test, I directly passed Kafka.Message{} and it worked.
