### ISSUE TITLE
sasl.kerberos.min.time.before.relogin = 3600000

### ISSUE THREAD

**Issue by yzpnet** [confluentinc/confluent-kafka-go#488]
confluent-kafka-go.v1

set sasl.kerberos.min.time.before.relogin = 3600000

Consumption is reduced greatly.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the checklist.
