### ISSUE TITLE
Connect to Kafka broker with JAAS enabled

### ISSUE THREAD

**Issue by cedricve** [confluentinc/confluent-kafka-go#489]
Description
===========

How do you specify the JAAS configuration files with the Go Library. How do you create and configure the Kafka client?

**Comment by edenhill** [comment]
JAAS is a Java-specific format.
The Go library makes use of OpenSSL and standard PEM (et.al) files for SSL.

See https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/confluent_cloud_example/confluent_cloud_example.go#L74 for an example how to connect with SSL and SASL PLAIN.

**Comment by cedricve** [comment]
boom... thanks so much.
