### ISSUE TITLE
Unable to build application for linux on windows machine

### ISSUE THREAD

**Issue by rakeshrvce** [confluentinc/confluent-kafka-go#491]
Description
===========
On windows mingw-w64 is installed for gcc and CGO_ENABLED is set to 1 which is needed for confluent-kafka-go library.
I am trying to build the application which internally uses this library but I am getting following errors:

Logs:
$ go build -o packet-handler myapp/main.go
runtime/cgo
gcc_linux_amd64.c: In function '_cgo_sys_thread_start':
gcc_linux_amd64.c:61:2: error: unknown type name 'sigset_t'; did you mean '_sigset_t'?
  sigset_t ign, oset;
  ^~~~~~~~
  _sigset_t
gcc_linux_amd64.c:66:2: error: implicit declaration of function 'sigfillset' [-Werror=implicit-function-declaration]
  sigfillset(&ign);
  ^~~~~~~~~~
gcc_linux_amd64.c:61:16: error: unused variable 'oset' [-Werror=unused-variable]
  sigset_t ign, oset;
                ^~~~
cc1.exe: all warnings being treated as errors

How to reproduce
================
export GO111MODULE="on"
export GOOS="linux"
export GOEXE=""
export GOARCH="amd64"
export CGO_ENABLED=1

Build any application on windows which is using confluent-kafka-go library

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): gopkg.in/confluentinc/confluent-kafka-go.v1 v1.4.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: Windows 10
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The failing source is not part of confluent-kafka-go, but the cgo toolchain, so that falls outside the scope of this project.
