### ISSUE TITLE
How do we manage transactional IDs on an application running multiple processes?

### ISSUE THREAD

**Issue by shridharvarun** [confluentinc/confluent-kafka-go#492]
Description
===========
Overview of the application:
An ingestion service which accepts logs from clients. The logs are processed and are then pushed into Kafka. Since these logs are critical and I cannot afford a loss in the same, I decided to adopt transactions for the same.

The docs state:
> A producer instance is configured for transactions by setting the `transactional.id` to an identifier unique for the application. This id will be used to fence stale transactions from previous instances of the application, typically following an outage or crash.

I'm generating a static transaction ID at the start of the application. This will imply that on multiple calls to the API the same transaction ID will be used. Won't this lead to multiple processes Producing data sequentially?

Is this the correct way of doing this? And if not, how do I improve this?

How to reproduce
================
NA

Checklist
=========
Please provide the following information:

 - [v1.1.0 ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ kafka_2.12-2.5.0] Apache Kafka broker version:
 - [NA] Client configuration: `ConfigMap{...}`
 - [NA] Operating system:
 - [NA] Provide client logs (with `"debug": ".."` as necessary)
 - [NA] Provide broker log excerpts
 - [NA] Critical issue

**Comment by mhowlett** [comment]
each producer instance needs to have a unique `transactional.id` which doesn't change across restarts of the producing process. "I'm generating a static transaction ID at the start of the application" doesn't sound right - sounds like you're generating a different id on restart. 

this blog post might be useful: https://www.confluent.io/blog/transactions-apache-kafka/

**Comment by shridharvarun** [comment]
Closing this now since I found a clear explanation for the same [here](https://stackoverflow.com/questions/50335227/how-to-pick-a-kafka-transaction-id)
