### ISSUE TITLE
How to implement redundant kafka logic

### ISSUE THREAD

**Issue by evgeniyasti** [confluentinc/confluent-kafka-go#493]
Hello.

My team is implementing Kafka redundancy. I need to be able to switch between instances if one instance goes down.

Is there a feature in the library for this or I need to handle it programmatically? 

Thanks

**Comment by mhowlett** [comment]
If you just mean failover between broker instances within a single cluster, that is standard behavior - recommend reading up on Kafka fundamentals. There's no real reason to have redundant clusters in the same data center. If you are looking for cross-dc redundancy, here's the current state of affairs: https://www.confluent.io/blog/multi-region-data-replication/ . The confluent go client supports fetch-from-follower.

**Comment by milindl** [comment]
Closing this with Matt's answer. Please reopen if needed.
