### ISSUE TITLE
Read messages without consumer group - Assign to any partition

### ISSUE THREAD

**Issue by mimol91** [confluentinc/confluent-kafka-go#497]
Description
===========
Hello, I am trying to read all 'new' messages on specific topics. 
I don't need to commit offsets, neither consumer-groups (it should always read latest messages - and I have multiple processes running at this same time)

I thought that I can just use `Assign` and pass set partition as `kafka.PartitionAny`. However it seems that it's not consuming any messages.

Explicitly setting all possible partitions seems to work, but I would rather avoid that. (I believe `kafka.PartitionAny` can be only used in producer)

**Is there any way to read all incoming messages from specific topic (without using consumer group)** (and handle case when number of partitions increase)

How to reproduce (Ignoring error for visibility)
================
```go
consumer, _ := kafka.NewConsumer(&config)
topics := []string{"myTopic"}
assignedTopics := make([]kafka.TopicPartition, len(topics))
for i, topic := range topics {
	assignedTopics[i] = kafka.TopicPartition{Topic: &topic, Offset: kafka.OffsetEnd, Partition: kafka.PartitionAny}
}
consumer.Assign(assignedTopics)
for {
		msg, _ := consumer.ReadMessage(-1)
		log("msg")
}

```

Checklist
=========
**ConfigMap**:
```
    config["enable.auto.offset.store"] = false
	config["enable.auto.commit"] = false
	config["socket.keepalive.enable"] = true
	config["api.version.request"] = true
	config["broker.version.fallback"] = "2.1.1"
	config["api.version.fallback.ms"] = 0
	config["auto.offset.reset"] = "latest"
```
**confluent-kafka-go**: v1.4.2
**librdkafka**: 1.2.2-r0

**Comment by mhowlett** [comment]
you could use `GetMetadata` to find out how many partitions a topic has, then use that to subscribe to all of them. that won't work if you dynamically add partitions though without restarting the process (that should be rare however).

I think it's best to just use subscribe and use a different group.id per process so they don't operate in a group - just use a randomly generated guid or something. kafka will clean up these consumer groups automatically as required.

**Comment by mimol91** [comment]
This is what I'am using now (random consumer groups)

I was wondering if there is maybe some not so known trick with assign so you can consume all partitions (even when new one is created),but it seems there is nothing.

**Comment by raghu11111** [comment]
Do you have written any java code without using consumer groups.
Can  someone help me out . Thanks.

**Comment by raghu11111** [comment]
Is there any way to read all incoming messages from specific topic (without using consumer group) by using java code.
Can someone help me out . Thanks.
