### ISSUE TITLE
"fetch.min.bytes" not respected

### ISSUE THREAD

**Issue by alvatar** [confluentinc/confluent-kafka-go#500]
Description
===========

EDIT: this was _No such configuration property: \"fetch.wait.max.ms\"\_ but after further trying to reproduce I no longer can, however, the end behavior has not changed.

I'm trying to reduce Kafka latency. Particularly for testing I want these settings:
```
&kafka.ConfigMap{
                 ...
		"fetch.wait.max.ms":        50,
		"fetch.min.bytes":          256,
}
```

although for production I'd like to keep a low max wait as well, but perhaps allow more room for batching.

In first place, I'd like to ask if these configurations are supposed to do what I'm trying to: restrict the delay to consume the events so they are processed in the Kafka consumer. Then my next question is about the following error:

`No such configuration property: \"fetch.wait.max.ms\"\`

I've also tried with linger.ms, but it produced no effect.
I'm taking config parameters from here: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

The current delay is around 2-3 seconds to consume the message. In contrast, the kafka shell consumer script consumes in under 1s. In the past I've been able to reduce this delay considerably, using a different library like sarama, and configuring the Kafka server differently (but I don't recall which particular options did I change for that).

How to reproduce
================

Just create a consumer with the ConfigMap with the parameters:
```
kafka.ConfigMap{
		"group.id":                 "kafka_test",
		"bootstrap.servers":        broker,
		"go.events.channel.enable": true,
		"broker.address.family":    "v4",
		"session.timeout.ms":       6000,
		"auto.offset.reset":        "earliest",
		"fetch.wait.max.ms":        50,
		"fetch.min.bytes":          256,
	}
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):1.4.2 / version int: 17040127 version string: 1.4.2-dirty
 - [x] Apache Kafka broker version: 2.4.0
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Linux
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
`fetch.wait.max.ms` is a valid consumer configuration property, i'm not sure why you would see that error (providing the full code would probably help). if your goal is to ensure good consumer latency, i wouldn't bother changing `fetch.wait.max.ms` - just set `fetch.min.bytes` to 1, which will cause the long-poll fetch requests the consumer does to the broker to return as soon as there are any messages. note that end-to-end latency is typically milliseconds (to my localhost with moderate load, I see ~3ms).

**Comment by alvatar** [comment]
Thanks for your answer @mhowlett 

 It turns out that I probably was doing something wrong, because now it's accepting it. I'm sure I didn't write the config wrong, so perhaps I was passing it to a producer as well and that's where the issue was happening.

In any case, I've made this test case. It illustrates that the config is nevertheless ignored: on my machine the first message is consumed around 3 seconds after it's produced, while in the console kafka consumer its displayed in <1s.


```go

func kafkaTestConsumer(logger *logrus.Logger, broker, topic string, outputCh chan *kafka.Message) (c *kafka.Consumer, stop chan struct{}) {
	var err error
	c, err = kafka.NewConsumer(&kafka.ConfigMap{
		"group.id":                 "kafka_test",
		"bootstrap.servers":        broker,
		"go.events.channel.enable": true,
		"broker.address.family":    "v4",
		"session.timeout.ms":       6000,
		"auto.offset.reset":        "earliest",
		"fetch.min.bytes":          1,
		"fetch.wait.max.ms":        10,
	})
	if err != nil {
		logger.Fatalf("Failed to create consumer: %s", err)
	}
	logger.Infof("Created Consumer %v", c)

	err = c.SubscribeTopics([]string{topic}, nil)
	if err != nil {
		logger.Fatal(err)
	}

	stop = make(chan struct{})
	go func() {
		for {
			select {
			case <-stop:
				return
			case ev := <-c.Events():
				switch e := ev.(type) {
				case *kafka.Message:
					outputCh <- e
				case kafka.Error:
					logger.Fatal(e)
				default:
					fmt.Printf("Ignored %v\n", e)
				}
			}
		}
	}()

	return c, stop
}

func kafkaTestProducer(logger *logrus.Logger, broker, topic string) (p *kafka.Producer, done chan struct{}) {
	p, err := kafka.NewProducer(&kafka.ConfigMap{
		"bootstrap.servers":     broker,
		"broker.address.family": "v4",
		"session.timeout.ms":    6000,
	})
	if err != nil {
		logger.Fatalf("new producer: %v", err)
	}

	done = make(chan struct{})
	go func() {
		defer close(done)
		for e := range p.Events() {
			switch ev := e.(type) {
			case *kafka.Message:
				m := ev
				if m.TopicPartition.Error != nil {
					logger.Infof("Delivery failed: %v", m.TopicPartition.Error)
				} else {
					logger.Infof("Delivered message to topic %s [%d] at offset %v",
						*m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
				}
				return

			default:
				fmt.Printf("Ignored event: %s\n", ev)
			}
		}
	}()
	return
}

func TestKafka(t *testing.T) {
	t.SkipNow()

	topic := "kafka_test"
	outputCh := make(chan *kafka.Message)
	kafkaTestConsumer(logrus.New(), "localhost:9092", topic, outputCh)
	p, _ := kafkaTestProducer(logrus.New(), "localhost:9092", topic)

	p.ProduceChannel() <- &kafka.Message{
		TopicPartition: kafka.TopicPartition{
			Topic:     &topic,
			Partition: kafka.PartitionAny,
		},
		Value: []byte("HELLO"),
	}

	for msg := range outputCh {
		fmt.Println("Message received: ", string(msg.Value))
	}
}

```

**Comment by mhowlett** [comment]
it seems your time measurement includes time to create the clients and subscribe to the topic? those will dominate, and the fetch config properties don't have any impact.

I think v1.5 includes some improvements here to the consumer (i recall a related discussion, pretty sure the changes made it in). That should be out soon.

**Comment by alvatar** [comment]
I've tried giving 4 seconds for the consumer and producer to be created. Then looping.
It's an interesting behavior, because I get a very long delay at the beginning +5 seconds sometimes. Then it consumes then fast.

It seems that it takes long then to subscribe, so that might be it. I find it kinda strange, since I have a single replica, so there might be something going on that I'm missing.

BTW the only changes that seem to have happened since 1.4.2 are doc tweaks. Is there a branch where this development is happening (is not `dev`)

Thanks for your response!
I think we can close this if you want

**Comment by mhowlett** [comment]
try using librdkafka v1.5, as described here: https://github.com/confluentinc/confluent-kafka-go#installing-librdkafka - there won't be any related changes to the go client itself in v1.5

**Comment by alvatar** [comment]
Awesome, thank you @mhowlett
