### ISSUE TITLE
[Question] When is the excepted update to librdkafka 1.5.0?

### ISSUE THREAD

**Issue by MikeSchlosser16** [confluentinc/confluent-kafka-go#504]
Description
===========
I'm currently running into an issue where the producer is not returning an error if it tries to produce to a topic that does not exist, with auto topic creation false. Per https://github.com/confluentinc/confluent-kafka-dotnet/issues/1144, it appears this was fixed in librdkafka 1.5.0. Is there a target data to pull this into `confluent-kafka-go` and tag a release? 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.4.2
 - [ ] Apache Kafka broker version: 
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by tkdrahn** [comment]
@edenhill do you know if pulling in librdkafka 1.5.x to confluent-go is planned?  we would like to take advantage of some of the AKS networking fixes available in 1.5

**Comment by edenhill** [comment]
The plan is to release confluent-kafka-go v1.5.2 with librdkafka v1.5.2 early next week.

**Comment by tkdrahn** [comment]
thank you!

**Comment by tkdrahn** [comment]
@edenhill do you still think this release is coming this week?

**Comment by tkdrahn** [comment]
@edenhill sorry to bother. Any update on this? Azure networking is causing us tons of headaches

**Comment by MikeSchlosser16** [comment]
closing this since 1.5.2 has been released. Thanks @edenhill !
