### ISSUE TITLE
[Help] does confluent-kafka-go support specify partition.assignment.strategy

### ISSUE THREAD

**Issue by csrgxtu** [confluentinc/confluent-kafka-go#505]
according to kip 54: https://cwiki.apache.org/confluence/display/KAFKA/KIP-54+-+Sticky+Partition+Assignment+Strategy  and https://docs.confluent.io/current/installation/configuration/consumer-configs.html#, there is an way to specify partition.assignment.strategy, dose confluent-kafka-go support it?

**Comment by edenhill** [comment]
`partition.assignment.strategy` is supported, see https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

The Sticky partition assignment strategy is not supported yet.
