### ISSUE TITLE
Kafka stream

### ISSUE THREAD

**Issue by lenimartin** [confluentinc/confluent-kafka-go#512]
Hello,

I know it has already been mentioned, but that was 2 years ago and maybe you changed your mind :) 
Is there a project to bring in Kafka streams and Kafka state store into the go implementation of the library ?

I know you don't and probably have not planned to, but I thought it would be good to put a little reminder that the community would love it :) 

Have a good day

previous request: https://github.com/confluentinc/confluent-kafka-go/issues/181

**Comment by edenhill** [comment]
Thank you for the reminder, but this is still unlikely to happen :)
We recommend a combination of KSQL and standard (Go) producers and consumers to construct your streaming pipelines.

**Comment by Larleyt** [comment]
It's been 4 more years. No Kafka Streams in the roadmap?
