### ISSUE TITLE
Why kafka._Cfunc_GoBytes (inline) Take up such a high memory ？

### ISSUE THREAD

**Issue by yew1eb** [confluentinc/confluent-kafka-go#513]
go tool pprof -inuse_space http://10.66.160.225:6060/debug/pprof/heap

github.com/confluentinc/confluent-kafka-go/kafka._Cfunc_GoBytes (inline)

![image](https://user-images.githubusercontent.com/4133864/91130811-d2ae7c00-e6de-11ea-9439-b86b5b9940fa.png)

**Comment by edenhill** [comment]
@yew1eb Did you find the reason?
