### ISSUE TITLE
Build with dynamic tag finds bundled librdkafka header instead of system one

### ISSUE THREAD

**Issue by KJTsanaktsidis** [confluentinc/confluent-kafka-go#514]
Description
===========
I'm trying to build confluent-kafka-go against a patched librdkafka, where I've added a function to the public interface. I've installed my patched librdkafka with the makefile into `/usr/local`, and pkg-config correctly figures out where it is and prints relevant include flags.

However, when I try and build my patched copy confluent-kafka-go that calls one of the new functions I added to librdkafka, I get the following error from cgo:

```
WORK=/tmp/go-build059416622
can't load package: package ./confluent/kafka: cannot find package "." in:
	/root/go/src/github.com/zendesk/zendesk_kafka_go/v2/confluent/kafka/confluent/kafka
root@eb416f2a9872:~/go/src/github.com/zendesk/zendesk_kafka_go/v2/confluent/kafka# cd ../..
root@eb416f2a9872:~/go/src/github.com/zendesk/zendesk_kafka_go/v2# go build -x -tags=dynamic ./confluent/kafka
WORK=/tmp/go-build552844409
mkdir -p $WORK/b001/
cd /root/go/src/github.com/zendesk/zendesk_kafka_go/v2/confluent/kafka
pkg-config --cflags -- rdkafka
pkg-config --libs -- rdkafka
CGO_LDFLAGS='"-g" "-O2" "-L/usr/local/lib" "-lrdkafka"' /usr/local/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b001/ -importpath github.com/zendesk/zendesk_kafka_go/v2/confluent/kafka -- -I/usr/local/include -I $WORK/b001/ -g -O2 ./00version.go ./adminapi.go ./adminoptions.go ./build_dynamic.go ./config.go ./consumer.go ./error.go ./error_gen.go ./event.go ./generated_errors.go ./handle.go ./header.go ./kafka.go ./log.go ./message.go ./metadata.go ./misc.go ./offset.go ./producer.go ./testhelpers.go ./time.go
# github.com/zendesk/zendesk_kafka_go/v2/confluent/kafka
confluent/kafka/consumer.go:883:10: could not determine kind of name for C.rd_kafka_ssl_refresh
```

This is happening because cgo is using `librdkafka/rdkafka.h` from the confluent-kafka-go directory to figure out the types, _not_ the system copy in /usr/local/include/librdkafka/rdkafka.h (where this new function `rd_kafka_ssl_refresh` is defined). If I rename `rdkafka.h` in the source tree to `not_rdkafka.h`, everything works great.

I'm _pretty_ sure this is a cgo bug - it's not using different search paths for "" vs <> imports - although it could probably be worked around in confluent-kafka-go by nesting the `librdkafka` directory inside something else. I just wanted to check here first to make sure I'm not missing something obvious before I try and file a golang bug report.

How to reproduce
================
* Install a system librdkafka
* Write some garbage garbage that won't compile into the bundled librdkafka/rdkafka.h
* Run `go build -x -tags=dynamic ./kafka`
* Observe that the build fails because the bundled header doesn't parse. It shouldn't even be being used in the first place.

Checklist
=========
Please provide the following information:

(Most of this isn't relevant):

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: Ubuntu 18.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The system (and `-I`) libraries should indeed take preference over relative paths, I don't see an easy way to fix this in the client itself since each CGo-using .go file will need to make the import we can't use -tags or similar.

Your best bet at this point is probably to simply overwrite the bundled rdkafka.h with your version.

**Comment by KJTsanaktsidis** [comment]
Well, I "fixed" it by nesting `librdkafka/` inside another directory `cgovendor`, and changing the bundle-import.sh script to emit

```
#cgo CFLAGS: -I\${SRCDIR}/cgovendor
#cgo LDFLAGS: \${SRCDIR}/cgovendor/librdkafka/${dpath} $dynlibs
```

instead of

```
#cgo CFLAGS: -I\${SRCDIR}
#cgo LDFLAGS: \${SRCDIR}/librdkafka/${dpath} $dynlibs
```

but you're right, this shouldn't really be needed, and I don't really think it should be merged despite making my life easier :). 

I'll try and narrow this down into a reproduction I can take to the Go bug tracker.

**Comment by edenhill** [comment]
Good luck! (and I mean that :) )

**Comment by KJTsanaktsidis** [comment]
OK, FYI I filed this issue with golang: https://github.com/golang/go/issues/41059

**Comment by KJTsanaktsidis** [comment]
@edenhill it seems that this behaviour from cgo is something that we're stuck with - it was actually "fixed" before (by accident) and then reverted because it caused breakage in the wild.

The cgo maintainer suggested an alternative approach where a preprocessor macro is used to switch between bundled/dynamic builds - I've gone ahead and implemented this in https://github.com/confluentinc/confluent-kafka-go/pull/520
