### ISSUE TITLE
Consume a partition on a given topic/partition with given offset using kafka.Consumer or kafka.AdminClient

### ISSUE THREAD

**Issue by apabla** [confluentinc/confluent-kafka-go#517]
Description
===========
I am attempting to retrieve a list of "kafka.TopicPartition" associated to a particular topic.  I need the list to create individual consumers for each partition(_1 consumer per topic partition rule_).  In review of the following two components namely,  _kafka.consumer_ and _kafka.AdminClient_ I am unable to access the list of topic partitions.  I was able to access "Partitions []PartitionMetadata" via the adminclient.GetMetadata but this is not an instance of "kafka.TopicPartition" from which I can consume data.

I did review the consumer.Assignment() but this requires subscribing/polling and returns only current assignments to a active partition.  

In contrast sarama.Consumer(https://sourcegraph.com/github.com/Shopify/sarama/-/blob/consumer.go) exposes topic partitions and allows a consumer to consume from a single partition.

Could you please advise on how I can consume/access individual topic partitions using the confluent consumer or admin client?  Is there another approach I should consider?

**Comment by hsawhney09** [comment]
I came here looking for an answer myself.

**Comment by edenhill** [comment]
Simply construct a list of TopicPartition from the TopicMetadata and PartitionMetadata, and then past that to consumer.Assign() to start consuming.

**Comment by milindl** [comment]
Closing this with Magnus' answer above.
