### ISSUE TITLE
installation error on Ubuntu

### ISSUE THREAD

**Issue by abuvaneswari** [confluentinc/confluent-kafka-go#52]
Hello,

Installed librdkafka on my Ubuntu 14.04 machine.

$ldconfig -p | grep librdkafka
librdkafka.so.1 (libc6,x86-64) => /usr/local/lib/librdkafka.so.1
librdkafka++.so.1 (libc6,x86-64) => /usr/local/lib/librdkafka++.so.1

Tried to do 'go get' of confluent-kafka-go, but getting the following error. Please help resolve.
If you need librdkafka version number, please let me know the command to find that out.

thanks,
Buvana

$go get gopkg.in/confluentinc/confluent-kafka-go.v0/kafka

# gopkg.in/confluentinc/confluent-kafka-go.v0/kafka
37: error: 'rd_kafka_conf_set_events' undeclared (first use in this function)
37: error: 'rd_kafka_event_destroy' undeclared (first use in this function)
38: error: 'rd_kafka_queue_get_main' undeclared (first use in this function)
38: error: 'rd_kafka_event_error_string' undeclared (first use in this function)
38: error: 'rd_kafka_event_type' undeclared (first use in this function)
38: error: 'RD_KAFKA_EVENT_OFFSET_COMMIT' undeclared (first use in this function)
38: error: 'rd_kafka_event_error' undeclared (first use in this function)
38: error: 'rd_kafka_event_name' undeclared (first use in this function)
38: error: 'rd_kafka_commit_queue' undeclared (first use in this function)
38: error: 'rd_kafka_queue_get_consumer' undeclared (first use in this function)
38: error: 'rd_kafka_event_topic_partition_list' undeclared (first use in this function)
38: error: 'rd_kafka_queue_poll' undeclared (first use in this function)
38: error: 'RD_KAFKA_EVENT_REBALANCE' undeclared (first use in this function)

**Comment by edenhill** [comment]
You need to upgrade librdkafka to v0.9.4
Debian/Ubuntu packages available here:
http://docs.confluent.io/3.2.0/installation.html#installation-apt

**Comment by abuvaneswari** [comment]
Upgraded to 0.9.4; yet, getting the error message. please scroll down & check below the separator line. Should any environment variable be set? 

Also tried to query for multiple installations, fyi:

$ ldconfig -p | grep librdkafka	librdkafka.so.1 (libc6,x86-64) => /usr/local/lib/librdkafka.so.1
	librdkafka.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/librdkafka.so.1
	librdkafka.so (libc6,x86-64) => /usr/local/lib/librdkafka.so
	librdkafka.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/librdkafka.so
	librdkafka++.so.1 (libc6,x86-64) => /usr/local/lib/librdkafka++.so.1
	librdkafka++.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/librdkafka++.so.1
	librdkafka++.so (libc6,x86-64) => /usr/local/lib/librdkafka++.so
	librdkafka++.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/librdkafka++.so

$ ls -al /usr/local/lib/librdkafka.so.1
-rwxr-xr-x 1 root root 2776826 Jun 20  2016 /usr/local/lib/librdkafka.so.1
$ ls -al /usr/lib/x86_64-linux-gnu/librdkafka.so.1
-rw-r--r-- 1 root root 649928 Feb 28 22:15 /usr/lib/x86_64-linux-gnu/librdkafka.so.1

Not sure if /usr/local/lib/librdkafka.so.1 the correct version i.e 0.9.4?

=========================================================
$sudo apt-get install librdkafka-devReading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gyp javascript-common libc-ares-dev libc-ares2 libjs-node-uuid libssl-dev
  libssl-doc libv8-3.14-dev libv8-3.14.5
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  librdkafka++1 librdkafka1
The following NEW packages will be installed:
  librdkafka++1
The following packages will be upgraded:
  librdkafka-dev librdkafka1
2 upgraded, 1 newly installed, 0 to remove and 278 not upgraded.
Need to get 585 kB of archives.
After this operation, 679 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://packages.confluent.io/deb/3.2/ stable/main librdkafka-dev amd64 0.9.4~1confluent3.2.0-1 [319 kB]
Get:2 http://packages.confluent.io/deb/3.2/ stable/main librdkafka1 amd64 0.9.4~1confluent3.2.0-1 [233 kB]
Get:3 http://packages.confluent.io/deb/3.2/ stable/main librdkafka++1 amd64 0.9.4~1confluent3.2.0-1 [33.2 kB]
Fetched 585 kB in 2s (260 kB/s)          
(Reading database ... 252400 files and directories currently installed.)
Preparing to unpack .../librdkafka-dev_0.9.4~1confluent3.2.0-1_amd64.deb ...
Unpacking librdkafka-dev:amd64 (0.9.4~1confluent3.2.0-1) over (0.9.0~1confluent2.0.1-1) ...
Preparing to unpack .../librdkafka1_0.9.4~1confluent3.2.0-1_amd64.deb ...
Unpacking librdkafka1:amd64 (0.9.4~1confluent3.2.0-1) over (0.9.0~1confluent2.0.1-1) ...
Selecting previously unselected package librdkafka++1:amd64.
Preparing to unpack .../librdkafka++1_0.9.4~1confluent3.2.0-1_amd64.deb ...
Unpacking librdkafka++1:amd64 (0.9.4~1confluent3.2.0-1) ...
Setting up librdkafka1:amd64 (0.9.4~1confluent3.2.0-1) ...
Setting up librdkafka++1:amd64 (0.9.4~1confluent3.2.0-1) ...
Setting up librdkafka-dev:amd64 (0.9.4~1confluent3.2.0-1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...

$ go get -tags static gopkg.in/confluentinc/confluent-kafka-go.v0/kafka
# gopkg.in/confluentinc/confluent-kafka-go.v0/kafka
37: error: 'rd_kafka_conf_set_events' undeclared (first use in this function)
37: error: 'rd_kafka_event_destroy' undeclared (first use in this function)
38: error: 'rd_kafka_queue_get_main' undeclared (first use in this function)
38: error: 'rd_kafka_event_error_string' undeclared (first use in this function)
38: error: 'rd_kafka_event_type' undeclared (first use in this function)
38: error: 'RD_KAFKA_EVENT_OFFSET_COMMIT' undeclared (first use in this function)
38: error: 'rd_kafka_event_error' undeclared (first use in this function)
38: error: 'rd_kafka_event_name' undeclared (first use in this function)
38: error: 'rd_kafka_commit_queue' undeclared (first use in this function)
38: error: 'rd_kafka_queue_get_consumer' undeclared (first use in this function)
38: error: 'rd_kafka_event_topic_partition_list' undeclared (first use in this function)
38: error: 'rd_kafka_queue_poll' undeclared (first use in this function)
38: error: 'RD_KAFKA_EVENT_REBALANCE' undeclared (first use in this function)

**Comment by edenhill** [comment]
Looks like it finds an older rdkafka.h somewhere, can you do a `find / -name rdkafka.h 2>/dev/null | grep RD_KAFKA_VERSION`?
It should only find the one in /usr/include/librdkafka/rdkafka.h with version 0x000904ff

**Comment by edenhill** [comment]
Any luck?

**Comment by abuvaneswari** [comment]
Sorry for the long delay. Here you go:
/usr/local/include/librdkafka/rdkafka.h
#define RD_KAFKA_VERSION  0x000901ff
* @sa See RD_KAFKA_VERSION for how to parse the integer format.
/usr/include/librdkafka/rdkafka.h
#define RD_KAFKA_VERSION  0x000904ff
* @sa See RD_KAFKA_VERSION for how to parse the integer format.

**Comment by edenhill** [comment]
@abuvaneswari Thanks, as I thought, you have two versions of librdkafka installed, an old unsupported (by go client) version in /usr/local and a brand new v0.9.4 (supported!) in /usr.
There is no generic way of telling which one your compiler will choose (and it seems to prefer /usr/local) so I suggest you remove that one by doing something like:
`rm -r /usr/local/include/librdkafka /usr/local/lib/librdkafka* /usr/local/lib/pkgconfig/rdkafka*pc`

(prefix that command with `sudo` when you are sure it does the right thing)

Then rebuild the go client

**Comment by edenhill** [comment]
@abuvaneswari Did you resolve this issue?

**Comment by abuvaneswari** [comment]
Still not resolved. I get new errors… trying to chase the problem.
For the time being, I have a clean installation in a different server, which I am using for my development purposes.

**Comment by edenhill** [comment]
Okay, let me know if we can help

**Comment by abuvaneswari** [comment]
Hi Magnus,

Finally, I am able to fix the issues! Thanks a lot for the help all along.

Regards,
Buvana
