### ISSUE TITLE
Two Consumer in one Consumer Group got assigned same partition at the same time

### ISSUE THREAD

**Issue by hoobean1996** [confluentinc/confluent-kafka-go#522]
Description
===========

How to reproduce
================

Hi master, we have encountered a strange issue.
For a topic T, we have two consumers with the same group id. Noted as c1, and c2.

at first, the c1 got a partition assigned 13, and started to consume it,

later on, the c2 got a partition assigned, and it got partition 13 as well, so it starts to consume it. 

as we all know, different consumers in one consumer group should not consume the same partition at the same time, so it is a little wried.

confluent-kafka-go: github.com/confluentinc/confluent-kafka-go-dev/kafka
confluent-kafka-2.12/stable,now 5.4.0-1 all [installed,upgradable to: 5.4.2-1]
kafkacat/xenial,now 1.2.0-2 amd64 [installed]
librdkafka1/stable,now 1.3.0~1confluent5.4.2-1 amd64 [installed,automatic]

ConfigMap =  &kafka.ConfigMap{
			"bootstrap.servers":    strings.Join(brokers, ","),
			"session.timeout.ms":   120000,
			"enable.auto.commit":   true,
			"group.id":             groupID,
			"auto.offset.reset":    "earliest",
			"request.timeout.ms":   900000,
			"max.poll.interval.ms": 7200000,
		}

OS: Ubuntu 16.04
Client Logs: we did not open debug here,  

Critial Cases: Two consumers both receive messages from the same partition(13) at the same time.

But I remember it is impossible for Kafka to happen such case, can you give me any advices? thanks so much

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That should not be possible indeed, can you provide more of your code to help us understand how you are using the client?
In particular code around Subscribe() and the message consume loop.

**Comment by hoobean1996** [comment]
Hope this can make sense, I remove some sensitive information without changing the code logic, thanks master

```Go
func start() {
  sch.consumer.Subscribe(Topics)
  
  go consumeLoop()
}

// Message Consume Loop

func consumeLoop() {

	for {
		select {
		case <-sch.ctx.Done():
			{
				sch.l.Info("end_poll_tasks")
				return
			}
		default:
		}

		msg, err := sch.consumer.Poll(sch.cfg.PollTimeout) // here is 3000 ms

		if err != nil {
			sch.l.WithField("error_message", err.Error()).WithError(err).Debug("poll_message_failed")
			continue
		}

		task := UnmarshalFrom(msg.Value)

		ctxLogger.
			Info("pulled_message_success")

		var (
			topic     = msg.TopicPartition.Topic
			partition = msg.TopicPartition.Partition
			offset    = int64(msg.TopicPartition.Offset)
		)

		task.Topic = topic
		task.Partition = &partition
		task.Offset = &offset

		sch.initialConsumeStatus(ctxLogger, *topic, partition, offset)
		PutTaskToAContainer(task)
		ctxLogger.Info("push_task_to_task_queue")
	}

}
```

**Comment by edenhill** [comment]
Thank you, that looks correct.

Can you reproduce this issue with `"debug": "cgrp"` set in the ConfigMap and provide the logs?

**Comment by hoobean1996** [comment]
okay, let me try, if I can reproduce it, I'll get it back to you. 
thanks.

**Comment by milindl** [comment]
Closing this for now. Please reopen if reproduced in the latest version with the logs. Thanks
