### ISSUE TITLE
Option to Reduce Allocations for Producer Delivery Report Events

### ISSUE THREAD

**Issue by kevinconaway** [confluentinc/confluent-kafka-go#524]
Description
===========
@edenhill When using the producer with delivery reports enabled (as is the default), the message body will get re-allocated when the delivery report event is created.

In high volume systems, this ends up being a non trivial amount of memory usage.  Our use case revolves around using the `opaque` field for tracking delivery reports so we don't really need the message key/value at all.

Are you open to some kind of configuration option that would allow omitting the key/value from the delivery report events to avoid these allocations?

How to reproduce
================
N/A

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I think this makes sense and we do something similar in the .NET client:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/ConfigPropertyNames.cs#L50

**Comment by kevinconaway** [comment]
If you're open to it, I'm happy to submit a PR that is similar in behavior.

**Comment by edenhill** [comment]
That'd be great!

**Comment by kevinconaway** [comment]
Closing this out since #530 is merged
