### ISSUE TITLE
Seeing Local: Message Timed Out After broker restarts

### ISSUE THREAD

**Issue by abhinavsolan** [confluentinc/confluent-kafka-go#528]
Description
===========
We restart our Brokers every month to move to the latest and greatest version of Kafka, but every time this restart happens the Producers (both in Go and Python) start seeing this error
`topic_name[35]@unset(Local: Message timed out)` this does not happen on for all the messages out of 50 kubernetes pods we see this happening just on one pod.
And the error remains persistent for hours, to fix it we would need to kill that pod. 

How to reproduce
================
We have tried it on smaller (staging) cluster but we are unable to reproduce it, but it always happens in our production cluster and both Produces (Go and Python) face the same issue.

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.4.0
 - [X] Apache Kafka broker version: 2.5
 - [X] Client configuration: `ConfigMap{
request.timeout.ms: 2000,
security.protocol: "SASL_SSL",
retry.backoff.ms: 500,
socket.nagle.disable: true,
queue.buffering.max.messages: 100000,
queue.buffering.backpressure.threshold: 1,
queue.buffering.max.ms: 0.5,
retries: 10,
}`
 - [X] Operating system: Linux
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I think you might be seeing this:
> Fix produce/consume hang after partition goes away and comes back, such as when a topic is deleted and re-created (regression in v1.3.0).

https://github.com/edenhill/librdkafka/releases/tag/v1.4.2

**Comment by abhinavsolan** [comment]
Thanks, we will try with the new version then
