### ISSUE TITLE
How to get topics created using api? 

### ISSUE THREAD

**Issue by xidongc-wish** [confluentinc/confluent-kafka-go#529]
Description:

If there any api to get all topics created in kafka cluster , or get topics by parsing a prefix? Thanks  

How to reproduce

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version: latest
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: 
 - [ ] Operating system:
 - [ ] Provide client logs 
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Look at AdminClient.CreateTopics().
