### ISSUE TITLE
[Question]Kafka: check if brokers are reachable and SASL credentials are valid

### ISSUE THREAD

**Issue by tushardas** [confluentinc/confluent-kafka-go#531]
Description
===========
How do I check if the brokers provided in config are reachable?

   I have the below use cases

   Usecase1: Return error if kafka instance is not running

   Usecase2: Return error if the SASL credentials provided are invalid

Currently NewProducer() and NewConsumer() doesn't produce error if brokers are down or sasl credentials are invalid

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You could call GetMetadata() after initializing the client to verify that it can connect successfully.
Preferably something like:
```go
 md, err := c.GetMetadata(nil, false, 10000)
 if err != nil {
      /* Get the generic connection error (if any) by polling for Error events */
      ev, ok =: <- c.Events()
      if ok {
          handle the event..
      }
  }
```
