### ISSUE TITLE
got Not coordinator for group when commit offset

### ISSUE THREAD

**Issue by Shonminh** [confluentinc/confluent-kafka-go#533]
Description
===========
confluent-kafka-go version: v0.11.6
we created 4 machine to consume in a same group.
For machine A, in time t1, consumed a message M1 and then commit successfully,
but for machine B, in time t2 (t2> t1), also consumed message M1, but when it commit, got a error:
```
Broker: Not coordinator for group
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.0.0-RC2-6-g194121-dirty
 - [x] Apache Kafka broker version: 1.0
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by cuongtl1992** [comment]
Same issue

**Comment by hoobean1996** [comment]
same issue, and could not recover.

**Comment by edenhill** [comment]
What confluent-kafka-go and librdkafka versions are you on? (LibraryVersion())

**Comment by hoobean1996** [comment]
> same issue, and could not recover.

after upgrade to latest version, the issue was resolved automatically
