### ISSUE TITLE
Questions Regarding ReadMessage()

### ISSUE THREAD

**Issue by iYooooooona** [confluentinc/confluent-kafka-go#536]
Description
===========
For this method, https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/consumer.go#L289, in case of errors, there will be 3 situations,
1. (nil, err) -> err is a Kafka timeout error;
2. (nil, err) -> err is general error;
3. (msg, err) -> err is partition-specific error.

When I was browsing the javadocs https://kafka.apache.org/26/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html, I noticed the concept of `Offsets and Consumer Position`, 
```
The position of the consumer gives the offset of the next record that will be given out. It will be one larger than the highest offset the consumer has seen in that partition. It automatically advances every time the consumer receives messages in a call to poll(Duration).

The committed position is the last offset that has been stored securely. Should the process fail and restart, this is the offset that the consumer will recover to. The consumer can either automatically commit offsets periodically; or it can choose to control this committed position manually by calling one of the commit APIs (e.g. commitSync and commitAsync).
```

Questions:
1. I am wondering that in the event of the situations, will the `position` still increment by 1 even if what I get from `ReadMessage()` is an error? Or to put in another way, if our consumer calls `ReadMessage()` and it returns an error, will we get the next message or the same message when we call this method one more time?
2. For the above errors mentioned, can I get a list indicating if an error is retriable, ignorable, or fatal?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
1. No, that won't happen, because in case of errors there's no message, and so the position is not changed.
2. There are IsFatal and IsRetriable methods on the Error type. The second one is only relevant for the Transactional producer. For the rest of the errors, it's up to the user how to handle them, because there might be different requirements. As a general principal, the library retries/reconnects on its own, so logging the error and carrying on is sufficient action.
