### ISSUE TITLE
When I execute this order “go get gopkg.in/confluentinc/confluent-kafka-go.v1/kafka” ，following errors！

### ISSUE THREAD

**Issue by smart33690** [confluentinc/confluent-kafka-go#537]
Description
===========
Ok！
When I execute this order “go get gopkg.in/confluentinc/confluent-kafka-go.v1/kafka” ，following errors！

=========
C:\Users\Documents\Smart33690\kuiper\plugins\sinks>go get gopkg.in/confluentinc/confluent-kafka-go.v1/kafka
go: found gopkg.in/confluentinc/confluent-kafka-go.v1/kafka in gopkg.in/confluentinc/confluent-kafka-go.v1 v1.4.2
 gopkg.in/confluentinc/confluent-kafka-go.v1/kafka
In file included from C:\goProject\pkg\mod\gopkg.in\confluentinc\confluent-kafka-go.v1@v1.4.2\kafka\00version.go:24:
./librdkafka/rdkafka.h:83:10: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h> /* for sockaddr, .. */
          ^~~~~~~~~~~~~~
compilation terminated.
What should I do?
Thank you！

**Comment by edenhill** [comment]
Please fill out the issue checklist when filing a new issue.

Windows is not a supported platform.
