### ISSUE TITLE
Hard code for the timeoutMs and maxEvents when eventsChanEnable=true

### ISSUE THREAD

**Issue by sbookworm** [confluentinc/confluent-kafka-go#539]
Description
===========

https://github.com/confluentinc/confluent-kafka-go/blob/d4b1fadc0776d02e9b74a1815f1e02dbb124fccd/kafka/consumer.go#L482

This will not flexible for poor networking environment

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The networking handling is taken care of by the underlying librdkafka client, these timeouts are just how long to block on the internal message queue and is a balance between quicker termination and infrequent wakeups.

**Comment by sbookworm** [comment]
@edenhill got that, thanks very much for explain. I will close the issue, thanks
