### ISSUE TITLE
Local:Message timed out

### ISSUE THREAD

**Issue by Prasannagud** [confluentinc/confluent-kafka-go#541]
Description
===========
When do we get Local:Message timed out in kafka producer and what does the offset Unset mean ?

Error occurred when publishing to a topic :
                   Error :cdrin-3[4]@unset ","error":"Local: Message timed out

Producer Configurations used
================

        "socket.keepalive.enable": "true",
        "metadata.max.age.ms": "900000",
        "metadata.request.timeout.ms": "30000",
        "retries": "1000000",
        "message.timeout.ms": "300000",
        "socket.timeout.ms": "30000",
        "max.in.flight.requests.per.connection": "5",
        "heartbeat.interval.ms": "3000",
        "enable.idempotence": "true"

gopkg.in/confluentinc/confluent-kafka-go.v1 v1.4.2

Debug logs 
================
Attaching debug logs file for producer until the error occured.
[Publish failures for producer-2 VIL.xlsx](https://github.com/confluentinc/confluent-kafka-go/files/5310452/Publish.failures.for.producer-2.VIL.xlsx)

**Comment by eran-levy** [comment]
It might related to network issues or that broker cant handle the requests in a timely manner. How many messages you publish per sec and whats their size?
The best way to check further is to add a debug property maybe with the broker,topic,queue arguments

**Comment by Prasannagud** [comment]
Hi @eran-levy,

Message size was around 400 bytes and the publish rate was 100 per sec. And i have attached the debug property enabled in the logs earlier. Can you please have a look into it.

**Comment by eran-levy** [comment]
It looks like the client is losing its connection to the broker alot "...but broker not up" and  "Broker changed state UP -> DOWN" and many retries to connect
are you sure that the cluster is up and running? also check whats the replication factor that currently
