### ISSUE TITLE
when i NewConsumer How can i config 4 bokers,can give me an explame!!

### ISSUE THREAD

**Issue by lavendder** [confluentinc/confluent-kafka-go#543]
Description
===========

my kafka cluster have 4 boker addrs,how can i send bokers parmas?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Pass the list of brokers with a comma-separated string, like so:
```go
 config := kafka.ConfigMap{"bootstrap.servers": "broker1,broker3,broker4,broker2"}
    
```

**Comment by lavendder** [comment]
thanks，edenhill ！！! 
can you tell me in code where you parse the  "bootstrap.servers", i can not find out it.
thanks again！！！

**Comment by edenhill** [comment]
It is parsed by librdkafka:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L5859

**Comment by lavendder** [comment]
thanks，edenhill ！！!
