### ISSUE TITLE
Broker: Policy violation error while publishing

### ISSUE THREAD

**Issue by vanipolnedi** [confluentinc/confluent-kafka-go#544]
Description
===========
Hi,
Getting **Broker: Policy violation** error while publishing data.
When we will get this error and how to fix ?

**Producer Configuration:**
                "socket.keepalive.enable": "true",
		"metadata.max.age.ms": "180000",
		"retries": "1000000",
		"message.timeout.ms": "300000",
		"socket.timeout.ms": "30000",
		"max.in.flight.requests.per.connection": "1",
		"enable.idempotence": "true"

**Pkg:**    gopkg.in/confluentinc/confluent-kafka-go.v1 v1.4.2

Thanks in advance

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Can you please fill up the above checklist. And also do you still met this error with the latest version?

**Comment by milindl** [comment]
Closing this for now. Please reopen with the checklist and debug logs if this still persists.
