### ISSUE TITLE
Migrate to go modules

### ISSUE THREAD

**Issue by eran-levy** [confluentinc/confluent-kafka-go#551]
Description
===========
Following the 1.9 deprecation in #548 a step forward to be better compatible is to migrate to go modules:
1. Migrate to go modules including examples + kafkatest
2. Some code us gopkg.in and some use another, deprecate all usages of gopkg.in  
3. Update documentation

**Comment by eran-levy** [comment]
@edenhill I can create create a PR for it, just before doing so I've seen that some of the places that we had go.mod they have been removed - what was the reason for that?

**Comment by eran-levy** [comment]
following the 1.9 deprecation in #548 a step forward to be better compatible is to migrate to go modules

**Comment by robsonpeixoto** [comment]
@edenhill are there plans to migrate to go modules?
