### ISSUE TITLE
How get HighWatermark ？

### ISSUE THREAD

**Issue by liukelin** [confluentinc/confluent-kafka-go#557]
Description
===========

Hi.   I want to get   partition LAG （LAG = HighWatermark - ConsumerOffset ），
How get HighWatermark ？

Thinks.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by esinek** [comment]
```
func getLag(consumer *kafka.Consumer, topicPartition kafka.TopicPartition) (int64, error) {
	// lowOffset: The offset of the earliest message in the topic/partition. If no messages have been written to the topic, the low
	//  watermark offset is set to 0. The low watermark will also be 0 if one message has been written to the partition (with offset 0).
	// highOffset: The high watermark offset, which is the offset of the latest message in the topic/partition available for consumption + 1.
	_, highOffset, err := consumer.QueryWatermarkOffsets(*topicPartition.Topic, topicPartition.Partition, kafkaTimeout)
	if err != nil {
		return -1, err
	}
	offset := int64(topicPartition.Offset)
	return highOffset - offset, nil
}

```

**Comment by liukelin** [comment]
Thank you very much.
