### ISSUE TITLE
Linux builds fail

### ISSUE THREAD

**Issue by ilbambino** [confluentinc/confluent-kafka-go#56]
I can succesfully use the library in Mac, but if I try to use it in Linux I get the following error when bulding:

<detail>

```
~/go/src/github.com/confluentinc/confluent-kafka-go/examples/go-kafkacat# go build
# github.com/confluentinc/confluent-kafka-go/kafka
could not determine kind of name for C.RD_KAFKA_RESP_ERR_INVALID_CONFIG
could not determine kind of name for C.RD_KAFKA_RESP_ERR_INVALID_PARTITIONS
could not determine kind of name for C.RD_KAFKA_RESP_ERR_INVALID_REPLICATION_FACTOR
could not determine kind of name for C.RD_KAFKA_RESP_ERR_INVALID_REPLICA_ASSIGNMENT
could not determine kind of name for C.RD_KAFKA_RESP_ERR_INVALID_REQUEST
could not determine kind of name for C.RD_KAFKA_RESP_ERR_NOT_CONTROLLER
could not determine kind of name for C.RD_KAFKA_RESP_ERR_TOPIC_ALREADY_EXISTS
could not determine kind of name for C.RD_KAFKA_RESP_ERR_UNSUPPORTED_FOR_MESSAGE_FORMAT
could not determine kind of name for C.RD_KAFKA_RESP_ERR__UNSUPPORTED_FEATURE
could not determine kind of name for C.RD_KAFKA_RESP_ERR__WAIT_CACHE
```

</detail>

I have tried in two linux machines one debian and one latest ubuntu 17.04
Go version 1.8
Gcc 6.3.0

Also tried in a clean docker based on ubuntu 17.04 and Go1.8 and exactly the same results.

**Comment by edenhill** [comment]
You need to install librdkafka v0.9.4
See here for RPM  (librdkafka-devel) and Debian packages  (librdkafka-dev):
http://docs.confluent.io/3.2.0/installation.html

**Comment by ilbambino** [comment]
And you are right. I checked the versions of go, gcc, this package. But forgot to check that one. And that cgo error was confusing, so started to look in the wrong place.
Sorry for the noise, and thank you for the help 👍
