### ISSUE TITLE
Is `deliveryChan` actually optional?

### ISSUE THREAD

**Issue by roppa** [confluentinc/confluent-kafka-go#560]
According to this:

https://github.com/confluentinc/confluent-kafka-go/blob/7d2340912ba4a7a3437b775f304cba425d85ecd0/examples/producer_example/producer_example.go#L46

`deliveryChan` is optional, but I'm pretty sure it is not?

**Comment by edenhill** [comment]
If you pass nil to Produce() it will send delivery reports on the producer `Events()` channel.

**Comment by roppa** [comment]
Ahhh of course! Sorry noob Golang here!
