### ISSUE TITLE
Failed to create consumer: Unsupported partition.assignment.strategy: cooperative-sticky error

### ISSUE THREAD

**Issue by ilyamor** [confluentinc/confluent-kafka-go#573]
Description
===========
using v1.5.2 trying to init consumer with the new rebalance protocol and getting this error:
**Failed to create consumer: Unsupported partition.assignment.strategy: cooperative-sticky** 

How to reproduce
================
	consumer, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers":               kf.broker,
		"group.id":                        kf.group,
		"session.timeout.ms":              sessionTimeout,
		"go.events.channel.enable":        true,
		"log.connection.close":            false,
		"max.partition.fetch.bytes":       2097152,
		"compression.codec":               "lz4",
		"go.application.rebalance.enable": true,
		"partition.assignment.strategy":   "cooperative-sticky",
		"default.topic.config":            kafka.ConfigMap{"auto.offset.reset": kf.auto_offset_reset}})

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [x] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
cooperative-sticky has not been released for the Go (or librdkafka) client yet, will be available in the upcoming v1.6.0 release due in December.
