### ISSUE TITLE
Cannot resolve hostname:port error

### ISSUE THREAD

**Issue by gwuah** [confluentinc/confluent-kafka-go#574]
Description
===========

I'm trying to setup a simple producer and consumer for my app and I keep getting the error below. (see screenshot)<br/>
<img width="1439" alt="Screen Shot 2020-12-03 at 12 00 19 PM" src="https://user-images.githubusercontent.com/24861123/101015387-39a1c380-355f-11eb-9a84-88a5c1d7e7d2.png">

The hostname of my computer is "gwuah", but i don't understand why that's overwriting `bootstrap.servers` in ConfigMap.

Here's my producer
```
func Producer() {

	p, err := kafka.NewProducer(&kafka.ConfigMap{
		"bootstrap.servers": "localhost",
	})
	if err != nil {
		panic(err)
	}

	defer p.Close()

	// Delivery report handler for produced messages
	go func() {
		for e := range p.Events() {
			switch ev := e.(type) {
			case *kafka.Message:
				if ev.TopicPartition.Error != nil {
					fmt.Printf("Delivery failed: %v\n", ev.TopicPartition)
				} else {
					fmt.Printf("Delivered message to %v\n", ev.TopicPartition)
				}
			}
		}
	}()

	// Produce messages to topic (asynchronously)
	topic := "myTopic"
	for _, word := range []string{"Welcome", "to", "the", "Confluent", "Kafka", "Golang", "client"} {
		p.Produce(&kafka.Message{
			TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny},
			Value:          []byte(word),
		}, nil)
	}

	// Wait for message deliveries before shutting down
	p.Flush(15 * 1000)

}
```

Here's my consumer 
```
func Consumer() {

	c, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers": "localhost",
		"group.id":             "myGroup",
		"auto.offset.reset":    "earliest",
	})

	if err != nil {
		panic(err)
	}

	c.SubscribeTopics([]string{"myTopic"}, nil)

	for {
		msg, err := c.ReadMessage(-1)
		if err == nil {
			fmt.Printf("Message on %s: %s\n", msg.TopicPartition, string(msg.Value))
		} else {
			// The client will automatically try to recover from all errors.
			fmt.Printf("Consumer error: %v (%v)\n", err, msg)
		}
	}

}
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: MacOS
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That's the advertised listener learned from the bootstrap brokers, see https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by gwuah** [comment]
In case anyone also faces this same issue, the fix is to go to the config file for kafka (`/usr/local/etc/kafka/server.properties`) and set `advertised.listeners=PLAINTEXT://localhost:9092`

once you're done, run `brew services restart kafka` and run your application. everything would work fine!
