### ISSUE TITLE
Memory leak? Or doing something wrong?

### ISSUE THREAD

**Issue by craigching** [confluentinc/confluent-kafka-go#575]
Description
===========

We were seeing what appeared to be a small memory leak in 1.1.0 and so upgraded to 1.5.2 to see if we are seeing the same thing.  We are seeing a much more dramatic usage of memory in 1.5.2 compared to 1.1.0 which leads me to believe we're missing something. The line before the blue annotation is memory usage for 1.1.0 and after the blue annotation line is for 1.5.2. The only change we made was to upgrade.

![null-test-memory-usage](https://user-images.githubusercontent.com/109843/101057719-fab94100-3551-11eb-86b9-5fa81a64224a.png)

After these instances hit the top of the graph, they will be OOM killed and restarted. Here is a memory profile as well, it almost appears that we need to deallocate something per message, is that right?

![image](https://user-images.githubusercontent.com/109843/101058897-4c160000-3553-11eb-8d13-053c43a69e7d.png)

How to reproduce
================

I don't have a simple test case, I'm hoping I'm missing something obvious, but I can try and write a test if I am not missing something obvious. Basically we have 12 application instances with 2 consumers each consuming a single topic that has 24 partitions. Each consumer is doing about 15k messages/sec. We are using Poll, not the channel-based consumer. We are using the KafkaStats reports to report per partition lag from our consumers if that matters.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

We are using confluent-kafka-go version 1.5.2 with embedded librdkafka

Kafka version: 2.2.1

Client configuration:
```
{
 Topics:[metrics]
 BootStrapServers:<kafka-host>:9092
 ClientID:null-test
 GroupID:null-test-20201130
 AutoOffsetReset:latest
 StatisticsInterval:30s
}
```

Operating system: I'm not 100% sure we have a deployment platform that abstracts this from us.

I can't provide any logs at this time unfortunately, but I don't see anything reported in them that I'd think would be useful.

**Comment by gscteam** [comment]
I am trying to debug something very similar, kind of a slow creep while idle and processing no message.

**Comment by craigching** [comment]
I am closing this as user error, sorry for the noise. The explanation for the growth in memory was because we were inadvertently holding onto the TopicPartition from every message in an attempt to track which partitions were assigned to our consumers so we could report lag only for the partitions that were assigned to each instance. The upgrade must have improved performance over the older version and the resulting faster memory exhaustion was due to each instance processing more volume through them. So kudos to the team, we're getting great performance!
