### ISSUE TITLE
Possibility to build/bind go-kafka to librdkafka arm64 binaries

### ISSUE THREAD

**Issue by m-lyashenko** [confluentinc/confluent-kafka-go#576]
Description
===========

Hello here.

We use linux aarch64 OS and have an issue with 1.5.2 confluent-kafka-go version.

- librdkafka 1.5.2 installed
- confluent-kafka-go before v1.4.0 has no any issues

Is there a way to bind confluent-kafka-go v1.4.0+ to the system installed librdkafka?

Could you provide some info of "how to" or am I doing something wrong?

Thanks in advance!

How to reproduce
================

Try to build or test some go-project with confluent-kafka-go v1.4.0+ on arm64 OS architecture

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
v1.5.2/1.5.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: linux/aarch64
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by awcjack** [comment]
I have built confluent-kafka-go with arm64 librdkafka (build from source) successfully in arm Mac (Darwin/arm64) by `go build -tags dynamic *.go`  
Please try

**Comment by awcjack** [comment]
> I have built confluent-kafka-go with arm64 librdkafka (build from source) successfully in arm Mac (Darwin/arm64) by `go build -tags dynamic *.go`
> Please try

tried in rpi (5.4.0-1015-raspi/aarch64)
after go build & test, producer show `runtime error: invalid memory address or nil pointer dereference`
Not sure is lib problem or go problem in my code 😂

**Comment by awcjack** [comment]
> > I have built confluent-kafka-go with arm64 librdkafka (build from source) successfully in arm Mac (Darwin/arm64) by `go build -tags dynamic *.go`
> > Please try
> 
> tried in rpi (5.4.0-1015-raspi/aarch64)
> after go build & test, producer show `runtime error: invalid memory address or nil pointer dereference`
> Not sure is lib problem or go problem in my code 😂

tried again lol
Before installing librakafka, **remember to remove librdkafka-dev from apt/librdkafka-devel from yum**  

Check /usr/lib/* (`find "/usr/lib/" -name librdkafka.so.1`) & remove/move librdkafka from other source
git clone librdkafka source code
Remember to install lib of librakafka mentioned in [README](https://github.com/edenhill/librdkafka#requirements) or run ./configure --install-deps to install dependencies (For me is installed some libs via apt and some libs installed by configure)
Build librdkafka from source (follow https://github.com/confluentinc/confluent-kafka-go#installing-librdkafka),
the compiled libs will be put to `/usr/local` (check stdout after sudo make install)
cp or ln lib (librdkafka.so.1) to `/usr/lib`
Run `go build -tags dynamic *.go` & run the binary to test the kafka!

**Comment by m-lyashenko** [comment]
@awcjack Thank you very much! It works! I missed that info in the README.

**Comment by kkHAIKE** [comment]
make a fork for it
https://github.com/kkHAIKE/confluent-kafka-go/releases/tag/v1.7.1

**Comment by dsandor** [comment]
I do realize there is a way to build this from source however it is convenient to have a platform version bundled. Is there any way we can get a darwin_arm64 variant bundled as Apple Silicon Macs are becoming more prevalent for developers. I understand that you do not want to bundle every variant possible but this seems to be a logical inclusion.

Thanks

**Comment by edenhill** [comment]
We will transition to another CI provider soon, which will allow us to provide arm64 builds.

**Comment by bothra90** [comment]
@edenhill: Are you tracking the transition to the new CI provider in a different issue that we can subscribe to?

**Comment by jatinkapoor1313** [comment]
> dynamic

then how we will debug it if we are not using command line

**Comment by alicerum** [comment]
@edenhill any news on that? it would be nice to be *finally* able to build multiarch docker images for my apps without heavy workarounds.
