### ISSUE TITLE
Recent change breaks vendoring confluent-kafka-go

### ISSUE THREAD

**Issue by KJTsanaktsidis** [confluentinc/confluent-kafka-go#581]
Description
===========
A recent change https://github.com/confluentinc/confluent-kafka-go/commit/d2e0d83bd58738501f8c98a6785e2e0de07b5f3d tries to provide better error messages for building without cgo by using a bad import in a file with `!cgo`. Unfortunately, this also breaks vendoring the package with `go mod vendor`.

How to reproduce
================
Get a project using go modules and confluent-kafka-go, and point it at current master:

```
replace github.com/confluentinc/confluent-kafka-go => github.com/confluentinc/confluent-kafka-go master
```

Then run `go mod vendor`:

```
% go mod vendor
github.com/zendesk/zendesk_kafka_go/v2/kafka imports
	github.com/confluentinc/confluent-kafka-go/kafka imports
	ConfluentKafkaGo_CANT_BE_CROSS_COMPILED: package ConfluentKafkaGo_CANT_BE_CROSS_COMPILED is not in GOROOT (/usr/local/Cellar/go/1.15.6/libexec/src/ConfluentKafkaGo_CANT_BE_CROSS_COMPILED)
github.com/zendesk/zendesk_kafka_go/v2/kafka imports
	github.com/confluentinc/confluent-kafka-go/kafka imports
	ConfluentKafkaGo_REQUIRES_CGO_ENABLED: package ConfluentKafkaGo_REQUIRES_CGO_ENABLED is not in GOROOT (/usr/local/Cellar/go/1.15.6/libexec/src/ConfluentKafkaGo_REQUIRES_CGO_ENABLED)
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): current master
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: `ConfigMap{...}` N/A
 - [x] Operating system: OSX
 - [ ] Provide client logs (with `"debug": ".."` as necessary):  N/A
 - [ ] Provide broker log excerpts: N/A
 - [ ] Critical issue

**Comment by edenhill** [comment]
Huhm, okay, that's not good.

**Comment by edenhill** [comment]
I guess we'll have to revert this change
