### ISSUE TITLE
How can I get the full clientID list under the same consumer group?

### ISSUE THREAD

**Issue by wrfly** [confluentinc/confluent-kafka-go#584]
Description
===========

When run multiple consumers consume multiple topics with one partition each, only one consumer can get messages, with all the topics provided. Actually, we ran multiple consumers to split the topics into different consumers.

This library provides a function to `Assign()` topic and partitions manually, but one question is how to get the full client ID list
to balance the topics and partitions.

How to reproduce
================

Consume multiple topics (one partition each) with multiple consumers.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): `17105663 1.5.2-dirty`
 - [x] Apache Kafka broker version:  with https://github.com/confluentinc/cp-all-in-one/tree/6.0.1-post/cp-all-in-one
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: `Ubuntu 16.04`
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You should use `"partition.assignment.strategy": "roundrobin"` for when you have multiple consumers subscribing to single-partition topics.
