### ISSUE TITLE
Question: ok to use confluent-kafka-go v1.5.2 w/ librdkafka 1.6.0 ?

### ISSUE THREAD

**Issue by rogaha** [confluentinc/confluent-kafka-go#594]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yes, that's perfectly fine.
