### ISSUE TITLE
Messages are not always Flushed when using ProduceChannel.

### ISSUE THREAD

**Issue by fwilkerson** [confluentinc/confluent-kafka-go#596]
Description
===========
When using ProduceChannel, calling Flush does not guarantee messages are actually flushed. This will not happen every time, but it is a frequent failure. While stepping through with the debugger, when Flush calls `p.Len()`, it returns 0.

<img width="1373" alt="Screen Shot 2021-02-19 at 5 21 10 PM" src="https://user-images.githubusercontent.com/14129965/108567957-3654e300-72d7-11eb-9d04-fc57c439de89.png">

I have not been able to reproduce this issue using the function based Produce. The only difference between Produce and ProduceChannel that I saw was the flag being passed. ProducedChannel uses `RD_KAFKA_MSG_F_BLOCK`. I understand that I must await deliveries on the Events channel (and I am), but I don't see how I can safely shut down a server if I cannot rely on Flush, unless I maintain my own count of outstanding messages.

Notably [the example for produce channel](https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/producer_channel_example/producer_channel_example.go) does not use Flush.

How to reproduce
================

Produce messages with ProduceChannel and wait on Flush when shutting down the program.

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.5.2
 - [X] Apache Kafka broker version: 2.7 (confluent cloud)
 - [X] Client configuration: `kafka.ConfigMap{"sasl.mechanisms":   "PLAIN", "security.protocol": "SASL_SSL"}`
 - [X] Operating system: darwin
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [X] Critical issue

**Comment by fwilkerson** [comment]
```go
package main

import (
	"fmt"
	"os"

	"github.com/confluentinc/confluent-kafka-go/kafka"
)

func main() {

	if len(os.Args) != 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <broker> <topic>\n",
			os.Args[0])
		os.Exit(1)
	}

	broker := os.Args[1]
	topic := os.Args[2]

	p, err := kafka.NewProducer(&kafka.ConfigMap{"bootstrap.servers": broker})

	if err != nil {
		fmt.Printf("Failed to create producer: %s\n", err)
		os.Exit(1)
	}

	fmt.Printf("Created Producer %v\n", p)

	go func() {
		for e := range p.Events() {
			switch ev := e.(type) {
			case *kafka.Message:
				m := ev
				if m.TopicPartition.Error != nil {
					fmt.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
				} else {
					fmt.Printf("Delivered message to topic %s [%d] at offset %v\n",
						*m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
				}
				return

			default:
				fmt.Printf("Ignored event: %s\n", ev)
			}
		}
	}()

	value := "Hello Go!"
	p.ProduceChannel() <- &kafka.Message{TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny}, Value: []byte(value)}

	p.Flush(10e3)

	p.Close()
}
```

The issue can be reproduced with this modification to the producer channel example.

**Comment by jliunyu** [comment]
Let's close this one to use the https://github.com/confluentinc/confluent-kafka-go/issues/601 to track the status.
