### ISSUE TITLE
Not consuming

### ISSUE THREAD

**Issue by Prasannagud** [confluentinc/confluent-kafka-go#599]
1)Created an eventhub in azure and connected using confluent kafka go client <librdkafka go-client :1.5.2">.
Started producer and produced a message yet the consumer wasn't started. After the delivery of produce then started the consumer but the message wasn't consumed .
 
Is that a normal behaviour for starting message not to  be consumed or any reason for it?

2)Created an eventhub in azure and left idle for some hours then Pushed traffic.We  observed latency in publish with the error

%3|1613536501.674|FAIL|rdkafka#producer-3| [thrd:sasl_ssl://SI-egress-Tel-AIR700071.servicebus.windows.net:9093/]: sasl_ssl://SI-egress-Tel-AIR700071.servicebus.windows.net:9093/0: 1 request(s) timed out: disconnect (after 42161139ms in state UP, 1 identical error(s) suppressed)

%5|1613536501.674|REQTMOUT|rdkafka#producer-3| [thrd:sasl_ssl://SI-egress-Tel-AIR700071.servicebus.windows.net:9093/]: sasl_ssl://SI-egress-Tel-AIR700071.servicebus.windows.net:9093/0: Timed out ProduceRequest in flight (after 435ms, timeout #0) e

Thanks in advance.

**Comment by jliunyu** [comment]
The v1.8.0 release added support for the client to kill idle connections before the LB or broker does, improved things on Azure. Please upgrade your go client to the latest version.

**Comment by milindl** [comment]
Closing this with @jliunyu 's comment, please reopen this if the issue persists with v2.3.0.
