### ISSUE TITLE
race condition with channel based producer when calling flush

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-go#601]
I think there's a race condition when producing a message to `p.ProduceChannel()`, then immediately calling Flush. I think the following sequence is possible:

message take from `produceChannel` here: https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/producer.go#L556

length of channel is queried here and found to be zero, hence flush skipped: https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/producer.go#L328

`p.produce(m, C.RD_KAFKA_MSG_F_BLOCK, nil)` called here: https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/producer.go#L557

**Comment by fwilkerson** [comment]
Indeed -> https://github.com/confluentinc/confluent-kafka-go/issues/596

**Comment by danielMensah** [comment]
@jliunyu Hi is there any update on this bug?

**Comment by milindl** [comment]
Closed due to #894
