### ISSUE TITLE
How to get the lag for a given topic and partition without consuming the partition?

### ISSUE THREAD

**Issue by shaobovaltix** [confluentinc/confluent-kafka-go#602]
Description
===========
This is more a question. We would like to programmatically check the lags for our topic partitions. But look like we can only do so by creating a consumer in a consumer group and let it subscribe to the give topics. But that will affect the current consumers which are consuming the topics. Is there any way in Golang or any REST APIs we can use to check the lags for topic partitions without consuming messages from them?

One API we checked was consumer.QueryWatermarkOffsets() which returns the first and last message offsets. It would be good if lag can be fetched from somewhere else.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.4.2
 - [x] Apache Kafka broker version: 1.1.1
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You also need to get the currently committed offsets with Committed(), you can then subtract the committed offsets from the High watermark to get the consumer lag.

**Comment by shaobovaltix** [comment]
> You also need to get the currently committed offsets with Committed(), you can then subtract the committed offsets from the High watermark to get the consumer lag.

Hi @edenhill, thanks for your reply. Actually if I create a consumer without subscribing to any topics, consumer.Committed() will return an empty list. Does that mean the consumer needs to subscribe to a topic if I want to get the offsets of the partitions of that topic?

**Comment by shaobovaltix** [comment]
Basically we want to have a programmatic implementation of Kafka-consumer-group CLI:
`kafka-consumer-groups --bootstrap-server <server-list> --describe --group <group-name>`
This returns a list of topic partitions the consumer group is reading messages from with current offsets and lags.

**Comment by rlanhellas** [comment]
@edenhill  I have the same requirements, is there a way to do it?

**Comment by milindl** [comment]
The AdminAPIs ListOffsets and ListConsumerGroupOffsets can be used for this in the latest version of the client, so that a consumer does not need to be created.
