### ISSUE TITLE
Required property group.id not set

### ISSUE THREAD

**Issue by maeglindeveloper** [confluentinc/confluent-kafka-go#603]
Description
===========

Hi everyone, 

I'm actually facing an issue when instanciating a consumer with the following configmap

```go
// Define Kafka settings to deal with the cluster
consumerConfig := &kafka.ConfigMap{
    "bootstrap.servers": brokerAddr,
    "auto.offset.reset": "earliest",
    "enable.auto.commit": false,
}
```

I always have this error 

```
Required property group.id not set
```

Which seems strange IMO since I don't want to create that consumer with a group ID.
I wrote somewhere in my codes as a comment that it is `necessary` for **librdkafka** to have it, but I can't explain it to myself.

@edenhill Is there a reason for this ?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`1.5.2`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: Linux
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The group.id is required (for various technical reasons), but if you're not planning to subscribe() or commit offsets (neither manual or auto) you can set it to any string, it won't really be used for anything.
