### ISSUE TITLE
Unable to catch kafka.Event of type transaction marker

### ISSUE THREAD

**Issue by maeglindeveloper** [confluentinc/confluent-kafka-go#604]
Description
===========
Hi everyone, 

I have a topic that contains messages produced using a transactional producer.

I saw that the offsets are incrementing not by one on each messages produced. I noticed that it is probably due to marker messages, that also take an offset inside the topic partition.

**_Question:_**

Lets say I want to know if my consumer is **"ready"**, meaning that it has consumed the last offset of my partition, how can I handle that using confluent-kafka-go lib since it seems that the `Poll` method from the `kafka.Consumer` is not abble to catch them ?

I found that issue because I tried to compare my "current offset" from the last commited kafka.Event message, and the high offset of my topic partition using `QueryWatermarksOffsets`.

Another library seems to handle that job to retrieve that information [here](https://github.com/twmb/franz-go/blob/2bea568f9d240493e0700e0f34926799dc008ed2/pkg/kgo/record_and_fetch.go#L52-L61)
Any advice ? @edenhill 

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`1.5.2`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The client automatically filters out the txn ctrl messages and updates the application's consume position accordingly, so you can simply call Position() and compare that to QueryWatermarkOffsets().

**Comment by maeglindeveloper** [comment]
Ok ! thanks @edenhill I will give it a try :+1:
