### ISSUE TITLE
migrating to coopartive-sticky rebalance protocol

### ISSUE THREAD

**Issue by ilyamor** [confluentinc/confluent-kafka-go#605]
Description
===========
after upgrading to 1.6.1, i am trying to migrate the rebalance protocol to cooperative-sticky, using rolling update.
when starting the app  I get "Inconsistent group protocol".

when trying to pass multiple strategies 
`"partition.assignment.strategy": "range,cooperative-sticky",
`I get 
`All partition.assignment.strategy (range,cooperative-sticky) assignors must have the same protocol type, online migration between assignors with different protocol types is not supported `

How to reproduce
================
"partition.assignment.strategy": "cooperative-sticky"

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.6.1
 - [x] Apache Kafka broker version: 2.7.0
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yeah, we don't support rolling upgrades between eager and cooperative partition assignment strategies, you will need to close all range consumers and then start all cooperative ones.
