### ISSUE TITLE
How pre-build librdkafka works? When I create golang binary using go build will it contain librdkafka lib? Can I run this binary in other machine?

### ISSUE THREAD

**Issue by punithck** [confluentinc/confluent-kafka-go#608]
Description
===========
Actually I have question related to usage of pre-built librdkafka. In the doc mentioned librdkafka is need not to be installed for certain OS's. I am using following OS. I build my code with `go build -mod vendor`. I get binary of service. If i want to run this binary in following OS. I have to install librdkafka here otherwise it throws following error.
```
error while loading shared libraries: librdkafka.so.1: cannot open shared object file: No such file or directory
```
Do we need to install librdkafka if we want to use this service?
librdkafka installation has been taking 2 to 3 min of time in ec2 machine. My intention is to avoid it by using pre-built librdkafka in client. Can you guys suggest me am I missing something here?
**OS version:**
_NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"_

**GLIBC version:**
_ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper._

How to reproduce
================
Create  a sample example code using this lib. build the code. run binary

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.5.2
 - [x] Apache Kafka broker version: 1.1.1
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If you want to use your own version of librdkafka you need to build your program with `-tags dynamic` to make the Go client link librdkafka dynamically.

**Comment by punithck** [comment]
Hi Edenhill,
  Thanks for the reply. Actually I want to use pre-built librdkafka that is present in go client. So that I no need to install librdkafka in my machine. May I know how to use pre-build librdkafka that is present in go-client?

**Comment by edenhill** [comment]
The prebuilt bundled librdkafka is used by default on supported platforms (glibc linux, osx). For Alpine linux you need to pass `-tags musl`.

**Comment by punithck** [comment]
Thanks. I got it.
