### ISSUE TITLE
librdkafka-cpp build failure on rpm generation

### ISSUE THREAD

**Issue by dharmarajat** [confluentinc/confluent-kafka-go#612]
Description
===========

i am trying to create librdkafka rpm on linux for C++.. and i see below error

error: File not found: /builddir/build/BUILDROOT/librdkafka-1.6.1-1.el7.x86_64/usr/lib64/librdkafka-static.a

Build environment:

[build@298708359c21 librdkafka]$ uname -a
Linux 298708359c21 4.4.0-203-generic #235-Ubuntu SMP Tue Feb 2 02:49:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

How to reproduce
================

1) git clone
2) ./configure --enable-static
3) make rpm

LOG: 
[kafka-buildlog.txt.txt](https://github.com/confluentinc/confluent-kafka-go/files/6170455/kafka-buildlog.txt.txt)

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I don't think you can build rpms on ubuntu directly, you will need mock or docker.
Try `packaging/tools/distro-build.sh centos` and then look in artifacts/
