### ISSUE TITLE
[Question] SIGSEGV when doing a flush that reads p.Len()

### ISSUE THREAD

**Issue by sneko** [confluentinc/confluent-kafka-go#613]
Description
===========

Hi,

When pushing just 1 message I sometimes used the `Flush()` to make it immediate when necessary.

For a new producer I mix pushing 1 event, and some time after I push a transaction of 3 messages and I had the "reflex" to flush, doing like:
`push(event1)`
`push(event2)`
`...`
`pushTx(event3, event4, event5)`
`flush()`

But I got a panic:
```
goroutine 1341 [syscall]:
runtime.cgocall(0x1043cb0, 0xc0003bee18, 0x0)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0003bede8 sp=0xc0003bedb0 pc=0x46b2fb
github.com/confluentinc/confluent-kafka-go/kafka._Cfunc_rd_kafka_outq_len(0x2774e20, 0x0)
	_cgo_gotypes.go:2173 +0x49 fp=0xc0003bee18 sp=0xc0003bede8 pc=0xaf2ec9
github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).Len.func1(0xc000385550, 0x4f78e0)
	/xxxxxxxxxx/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:328 +0x56 fp=0xc0003bee50 sp=0xc0003bee18 pc=0xb13356
github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).Len(0xc000385550, 0x407f8052a2)
	/xxxxxxxxxx/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:328 +0x4c fp=0xc0003bee80 sp=0xc0003bee50 pc=0xb06a4c
github.com/confluentinc/confluent-kafka-go/kafka.(*Producer).Flush(0xc000385550, 0x3a98, 0x1582700)
	/xxxxxxxxxx/vendor/github.com/confluentinc/confluent-kafka-go/kafka/producer.go:340 +0x173 fp=0xc0003bef08 sp=0xc0003bee80 pc=0xb06bf3
```

This does not seem to happen every time and I would like to better understand what could be the cause. When looking at https://github.com/confluentinc/confluent-kafka-go/blob/972d1084fd2907305fb52962199c632dc4607ae8/kafka/producer.go#L328 it seems indeed it calls C layer to call producer `outq_len()` but was a mutex missing on my end? I can't get the reason for this.

Note that the transaction didn't return an error, and that I fully understand the `commitTransaction` will on its own flush messages. Putting the `p.Flush()` was useless due to transaction behavior, I removed it, but I want to clarify what could have made this happening.

Thank you,

cc @edenhill  

How to reproduce
================

That's a "random" (race condition?) issue it seems.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.6.1
 - [ ] Operating system: linux

**Comment by edenhill** [comment]
Are you calling Flush() or Len() from multiple Go-routines or is all this from a single "thread"?
Can you share some code that reproduces the issue?

**Comment by sneko** [comment]
@edenhill I have 2 threads:
* 1 doing readiness: calling `.Position(...)`
* 1 dealing with 1 producer pushing events and flushing with `.Flush()`

Is it possible that underlying C code access shared memory between the `Position()` and `Flush()`?

_I don't have right now a simple example to reproduce the issue, I will try to set up a sample for this_

**Comment by edenhill** [comment]
> Is it possible that underlying C code access shared memory between the Position() (consumer) and Flush() (producer) ?

No, each client instance is separate, and each instance is thread safe.

**Comment by sneko** [comment]
Hmmm ok, I will keep investigating.

It makes me think: I want to be sure a message is produced and replicated across Kafka brokers. Is just checking `err := p.Produce(...)` is fine if no error? Or does this instruction just mean "I successfully set it into the buffer to be sent"?

Because if that's the first case, what's the advantage to call `Flush()` after a `.Produce()` since the `Flush()` won't return an error, the buffer could never be sent? Or did I misunderstand something 🤔 ?

Thank you,

**Comment by edenhill** [comment]
Produce() is asynchronous and only returns an error if the message was refused for even attempting delivery, e.g., too big or queue is full.

You need to monitor the p.Events() channel for delivery report events (`*kafka.Message`) which will eventually give you the per-message delivery status: if the message does not have an error the message was successfully written to the cluster, if it has an error it was not. See the producer examples.

**Comment by sneko** [comment]
Oh indeed! Thanks for clarification @edenhill , by luck it seems I didn't encounter a huge issue with this missing check (but I will implement it).

Considering just `p.Events()` as you said: what would you recommend to make sure I check right messages from this channel? For example:
* I have already in my queue: `messageA, messageB, messageC`
* I produce messages `message1, message2, message3` that go in my queue
* The queue is not yet flushed so I have into it: `messageA, messageB, messageC,message1, message2, message3`
* Once flushed, the "manager" will communicate through the channel to say to me that `messageA, messageB, messageC,message1, message2, message3` have been written to Kafka and that's a success (or not)
* I want to make sure of the delivery of `message1, message2, message3` but how to distinguish them since I'm just receiving a `*kafka.Message`?

I could imagine:
1. Comparing `key+value` and with a little chance I don't have duplicates?
2. Otherwise I saw headers but it seems they are not spread through delivery channel and they would be stored into Kafka?
3. Otherwise I misunderstood and the object has the same address than the original one when producing (but while looking at the code I think it's going through the C layer and looses the memory address?)

**Or a simpler solution, dedicate a specific channel related to this `p.Produce()` much simpler (but I tried to understand why you advised about `p.Events()` over the specific one inside `p.Produce(...)`:
![image](https://user-images.githubusercontent.com/8195958/112371869-641ab680-8cdf-11eb-91c6-d4edb8277052.png)

Thank again, as always pretty helpful to get your feedback!

**Comment by edenhill** [comment]
You can pass a per-message Opaque value (Message.Opaque) in your Produce() call that will be available in the delivery report event message.

**Comment by sneko** [comment]
As you advised we are filling now the Opaque value to make sure it has been deliver (or not).

About the original issue of `panic`, it seems we have no longer this (we did some modifications), I close the issue.

Thanks again for your help @edenhill 😃
