### ISSUE TITLE
How to specify private channel in Channel-Based producer?

### ISSUE THREAD

**Issue by iAziz786** [confluentinc/confluent-kafka-go#627]
Description
===========
In the README it's mentioned that we can use private channel with `producer.ProducerChannel()` I'm not able to find how to do so since the example which is given is using the `producer.Events()` function.

My use case is that I wanted to inform the caller of the `ProducerChannel` by a call back function if any error occurs therefore I need the private channel for that. I know I can do it with `producer.Produce()` but wanted to know how it is possible with producer channel.

![image](https://user-images.githubusercontent.com/17024120/114263580-1488fa00-9a04-11eb-9b96-72c0c0dc5f9d.png)

**Comment by iAziz786** [comment]
Here is what I'm doing right now with the `Produce()` method.

```go
type KafkaProducer struct {
	producer *kafka.Producer
}

func (kp *KafkaProducer) Produce(msg *kafka.Message, fn func(error)) error {
	deliveryChan := make(chan kafka.Event)
	go func() {
		e := <-deliveryChan
		if m, ok := e.(*kafka.Message); ok {
			fn(m.TopicPartition.Error)
		}
	}()

	return kp.producer.Produce(msg, deliveryChan)
}
```

**Comment by edenhill** [comment]
Yep, your deliveryChan is the private (or rather user-specified) delivery channel, as opposed to the default p.Events() channel.

**Comment by iAziz786** [comment]
Yes, but how can I pass the private channel to producer.ProducerChannel()?
