### ISSUE TITLE
Reasons for removing go.mod?

### ISSUE THREAD

**Issue by BurkovBA** [confluentinc/confluent-kafka-go#628]
Hi, I see that this project used to have `go.mod` files at some point, but later on they were removed: https://github.com/confluentinc/confluent-kafka-go/commit/1f6f5ba66fd2a6729be5553990c0053b36a076d3.

Could you explain the reasons for doing that?

**Comment by edenhill** [comment]
I think they were removed in a time when gopkg.in was still the way to go, but now we're ready to sunset gopkgin support in favour of go modules, so they should be added back.

**Comment by BurkovBA** [comment]
@edenhill Thank you for the response and provided information. Should I close the issue?
