### ISSUE TITLE
Consistent OOM in the Consumer

### ISSUE THREAD

**Issue by shivsantham** [confluentinc/confluent-kafka-go#631]
Description
===========
One of our consumers is running consistently OOM, and the heap dump points to kafka. 
Any idea what could be causing this?

![image](https://user-images.githubusercontent.com/8406152/114757839-312d7680-9d11-11eb-9ea8-2c4dacf3eebb.png)

How to reproduce
================

NA, memory keeps growing when starting the consumers

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): Confluent-kafka-go 1.6.1
 - [ ] Apache Kafka broker version: Confluent Kafka version 5.5.1 
 - [ ] Client configuration: 
 `"socket.keepalive.enable": true,
"socket.timeout.ms": 150000,
"session.timeout.ms": 15000,
"max.poll.interval.ms": 900000,
"message.max.bytes": 104857600,
"receive.message.max.bytes": 104858112,
"go.application.rebalance.enable": true,
"enable.auto.commit": true,
"enable.auto.offset.store": true,
"allow.auto.create.topics": true,
"auto.offset.reset": earliest,`
 
- [ ] Operating system: Consumers Run (Linux (Alpine))
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
``%7|1618423184.731|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423185.700|CGRPQUERY|rdkafka#consumer-5| [thrd:main]: sasl_plaintext://kafka-1.kafka.infra.svc.cluster.local:9071/1: Group "consumer.groupXX": querying for coordinator: intervaled in state up
%7|1618423185.705|CGRPCOORD|rdkafka#consumer-5| [thrd:main]: sasl_plaintext://kafka-1.kafka.infra.svc.cluster.local:9071/1: Group "consumer.groupXX" coordinator is kafka-1.kafka.infra.svc.cluster.local:9071 id 1
%7|1618423186.588|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423186.604|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423189.588|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423189.604|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423189.724|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423189.724|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423189.724|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423189.724|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423189.724|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423189.724|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423189.731|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423189.731|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423189.731|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423189.731|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423189.731|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423189.731|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423189.731|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423189.731|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423189.731|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423189.731|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423192.588|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423192.608|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423194.724|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423194.724|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423194.724|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423194.724|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423194.724|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423194.724|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423194.731|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423194.731|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423194.731|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423194.732|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423194.732|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423194.732|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423194.732|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423194.732|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423194.732|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423194.732|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423195.595|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423195.612|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423198.596|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423198.616|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423199.724|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423199.724|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423199.724|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423199.724|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423199.724|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423199.724|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423199.732|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423199.732|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423199.732|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423199.732|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423199.732|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423199.732|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423199.732|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423199.732|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423199.732|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423199.732|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423201.602|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423201.620|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423204.604|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423204.621|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423204.725|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423204.725|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423204.725|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423204.725|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423204.725|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423204.725|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423204.732|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423204.732|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423204.732|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423204.732|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423204.732|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423204.732|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423204.732|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423204.732|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423204.732|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423204.732|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423207.604|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423207.621|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423209.725|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423209.725|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423209.725|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423209.725|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423209.725|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423209.725|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423209.733|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423209.733|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423209.733|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423209.733|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423209.733|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423209.733|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423209.733|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423209.733|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423209.733|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423209.733|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423210.604|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423210.622|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423213.612|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423213.624|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423214.725|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423214.725|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423214.725|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423214.725|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423214.725|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423214.725|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423214.733|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423214.733|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423214.733|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423214.733|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423214.733|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423214.733|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423214.733|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423214.733|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423214.733|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423214.733|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423216.615|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423216.628|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423219.616|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423219.632|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423219.728|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423219.729|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423219.729|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423219.729|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423219.729|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423219.729|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423219.733|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423219.733|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423219.733|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423219.733|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423219.733|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423219.733|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423219.733|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423219.733|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423219.733|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423219.733|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423222.618|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423222.634|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423224.729|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423224.729|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423224.729|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423224.729|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423224.729|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423224.729|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423224.734|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423224.734|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423224.734|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423224.734|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423224.734|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423224.735|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423224.735|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423224.735|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423224.735|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423224.735|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423225.624|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423225.642|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423228.626|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423228.648|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423229.729|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423229.729|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423229.729|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423229.729|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423229.730|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423229.730|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423229.734|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423229.735|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423229.735|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423229.735|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423229.735|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423229.735|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423229.735|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423229.735|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423229.735|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423229.735|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423231.628|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423231.649|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423234.628|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423234.651|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423234.729|DUMP|rdkafka#consumer-6| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1618423234.729|DUMP_ALL|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423234.729|DUMP_PND|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423234.730|DUMP_QRY|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423234.730|DUMP_REM|rdkafka#consumer-6| [thrd:main]: List with 0 partition(s):
%7|1618423234.730|ASSIGNDONE|rdkafka#consumer-6| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423234.735|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [18]: stored offset 18886831, committed offset 18886831: not including in commit
%7|1618423234.735|OFFSET|rdkafka#consumer-5| [thrd:main]: Topic topic.XX.ABC [19]: stored offset 19060650, committed offset 19060650: not including in commit
%7|1618423234.735|DUMP|rdkafka#consumer-5| [thrd:main]: Assignment dump (started_cnt=2, wait_stop_cnt=0)
%7|1618423234.735|DUMP_ALL|rdkafka#consumer-5| [thrd:main]: List with 2 partition(s):
%7|1618423234.735|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [18] offset STORED
%7|1618423234.735|DUMP_ALL|rdkafka#consumer-5| [thrd:main]:  topic.XX.ABC [19] offset STORED
%7|1618423234.735|DUMP_PND|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423234.735|DUMP_QRY|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423234.735|DUMP_REM|rdkafka#consumer-5| [thrd:main]: List with 0 partition(s):
%7|1618423234.735|ASSIGNDONE|rdkafka#consumer-5| [thrd:main]: Group "consumer.groupXX": assignment operations done in join-state steady (rebalance rejoin=false)
%7|1618423237.628|HEARTBEAT|rdkafka#consumer-5| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015
%7|1618423237.651|HEARTBEAT|rdkafka#consumer-6| [thrd:main]: GroupCoordinator/1: Heartbeat for group "consumer.groupXX" generation id 4015``
 - [ ] Provide broker log excerpts
 - [X] Critical issue

**Comment by shivsantham** [comment]
Found that the issue, its due to the way we were committing offsets.

**Comment by krvajal** [comment]
In which version is it fixed?

**Comment by krvajal** [comment]
I am having the same issue, can you elaborate on what was the problem?

**Comment by aakash9290** [comment]
@shivsantham @krvajal 

Can you provide more details?
We are disabling enable.auto.offset.store and using StoreOffset to commit manually and autoCommitIntervalMs is set to 1000.
Go Consumer is going OOM whenever its slow.
