### ISSUE TITLE
Consumer fails to commit offset with cooperative-sticky assignment strategy

### ISSUE THREAD

**Issue by dvachaiev** [confluentinc/confluent-kafka-go#633]
Description
===========
Consumer fails with the error:
```
failed to commit offset: Broker: Group rebalance in progress
%4|1617810820.630|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "processor": application *assign() call failed: Changes to the current assignment must be made using incremental_assign() or incremental_unassign() when rebalance protocol type is COOPERATIVE
```

How to reproduce
================
1. Start consumer that explicitly commits offset after receiving each message
2. During active consuming by first consumer start another one in the same consumer group
3. First consumer fails with the error

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`17170943 1.6.1`):
 - [x] Apache Kafka broker version: 2.12-2.2.0
 - [x] Client configuration: `ConfigMap{"partition.assignment.strategy": "cooperative-sticky"}`
 - [x] Operating system: `MacOS`
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Try to reproduce this on v1.7.0, and please provide some code from your consumer app.

**Comment by JonathanMeyerCS** [comment]
This issue is closed, has the problem been resolved ? 
If so, in which version of `librdkafka` / `confluent-kafka-go` ?

Thanks !
