### ISSUE TITLE
consumer: Async offset commits

### ISSUE THREAD

**Issue by agis** [confluentinc/confluent-kafka-go#64]
Hi @edenhill.

Async commits are supported by librdkafka and the [Python](http://docs.confluent.io/current/clients/confluent-kafka-python/index.html#confluent_kafka.Consumer.commit) driver built on top of it, but not by confluent-kafka-go.

This would be useful in our case: we manually commit the offsets, but don't want to do this synchronously since this would cause performance issues with a big number of very fast jobs. So we have to implement our own batching logic to step around this issue. It would be nice if this was implemented right in the driver instead.

Are there any plans to support such a use case?

Thanks!

**Comment by edenhill** [comment]
We started off implementing async commits, but then concluded that a simple go-routine wrapper around the sync commit gives the same flexibility without the expense of a larger API surface area.
