### ISSUE TITLE
Produce stopped on a few Kubernetes pods 1:30 hours after network glitch

### ISSUE THREAD

**Issue by abhinavsolan** [confluentinc/confluent-kafka-go#642]
Description===========
We are using Channel Producer.
Around 3:30 AM in the morning we saw a network glitch on Kafka Brokers which spiked produce latencies from Client -> Server, all produce and consume recovered after that without any issue.
The only issue we started to see after the glitch was memory usage on 8/100 pods started increasing.
![Screen Shot 2021-05-12 at 6 54 25 AM](https://user-images.githubusercontent.com/52720556/117987177-17bb2280-b2ef-11eb-8a3d-e4780a45c432.png)
we didn't see any drop in `produce` on the Broker Side, but the rate of `success` dropped on the `Events()` channel in Producer.

Actual Produce and Consume didn't get impacted until 5:00 AM where we start seeing a drop on Consume side, and then degradation on our services. 
The degradation was for 10% of the data, the rest was working fine.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.4.2 librdkafka 1.5.0
 - [X] Apache Kafka broker version: 2.5.1
 - [X] Client configuration: 
 ```
ConfigMap{
security.protocol : SASL_SSL
retry.backoff.ms : 500
socket.nagle.disable : true
queue.buffering.max.ms : 25
statistics.interval.ms : 10000
broker.version.fallback : 10.0.0
api.version.fallback.ms : 0
reconnect.backoff.ms : 5000
sasl.password : test
bootstrap.servers : kafka-staging-iadfast-1.lyft.net:9093
request.timeout.ms : 2000
queue.buffering.backpressure.threshold : 1
api.version.request : true
ssl.ca.location : /etc/ssl/lyft-private-cas/lyft-kafka.pem
queue.buffering.max.messages : 1000
retries : 10
sasl.mechanism : SCRAM-SHA-256
}
 ```
 - [X] Operating system: Linux
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [X] Critical issue

**Comment by mhowlett** [comment]
we'd need to have more information to investigate. I think looking into this further is out of scope in the community support context.
