### ISSUE TITLE
Memory leaks in producer

### ISSUE THREAD

**Issue by stgleb** [confluentinc/confluent-kafka-go#643]
Description
===========

When producer is working for a while it has heavy memory pressure.

How to reproduce
================

Start kafka producer that writes messages to kafka for a long time.

Heap profile:

![profile](https://user-images.githubusercontent.com/5112367/118130737-660f1500-b406-11eb-908d-d7c5c26a97e8.png)

[pprof.webserver.alloc_objects.alloc_space.inuse_objects.inuse_space.013.pb.gz](https://github.com/confluentinc/confluent-kafka-go/files/6472641/pprof.webserver.alloc_objects.alloc_space.inuse_objects.inuse_space.013.pb.gz)

According to that profile I can conclude that memory leaks comes from:

https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/producer.go#L434
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/producer.go#L533
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/producer.go#L627
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/event.go#L230
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/message.go#L171
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/message.go#L146

it looks like CGO code allocates memory per each message sent and does not free it. 
Or maybe I am do something wrong configuring producer.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.6.1
 - [x] Apache Kafka broker version: 12.9.5
 - [x] Client configuration: `ConfigMap{...}` 
       ```
                "bootstrap.servers": p.bootstrapServers,
		"log_level":         7,
       ```
 - [x] Operating system: ubuntu 20.04

**Comment by mhowlett** [comment]
looks like you might not be handling delivery reports? see for example https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/producer_example/producer_example.go . if you are doing that, please provide a complete program so we can take a look.

**Comment by stgleb** [comment]
@mhowlett No, I don't. I actually provide a nil for delivery channel, AFAIK in that case reports are written to Events channel of producer. Should they still be received? Is there any option to discard them by default?

**Comment by edenhill** [comment]
You will need to read from the Events() channel to know if messages were successfully sent, and free any per-message state the client keeps for the application.

**Comment by stgleb** [comment]
@edenhill Thank you, it helped!

**Comment by rkr-rakesh** [comment]
@edenhill I have turned off delivery reports "go.delivery.reports = false" and passing nil deliver channel to produce function. Do I still need to read? Golang is GC language so what you mean by "free any per-message state the client keeps for the application"
