### ISSUE TITLE
Scratch base image in Dockerfile doesn't work after 1.5.2

### ISSUE THREAD

**Issue by emretanriverdi** [confluentinc/confluent-kafka-go#644]
Description
===========

Hi,

Dockerfile with Scratch base image works up until v1.4.2.
Doesn't work starting from versions 1.5.2 and above and writes this error:

Failed to resolve 'kafka-cluster.local:9092': Bad address (after 0ms in state CONNECT, 4 identical error(s) suppressed)

This error is not seen in debian:stretch-slim

How to reproduce
================

Just use this Dockerfile:

```
FROM golang:1.15 as prod-build

WORKDIR /app
COPY . .

RUN go mod download
RUN go build -ldflags="-w -s -extldflags -static" -o /app/my-app

# runtime container setup
FROM scratch

WORKDIR /app
COPY --from=prod-build /app/my-app /app/my-app
COPY --from=prod-build /app/resources/ /app/resources

EXPOSE 7575
ENTRYPOINT ["/app/my-app"]
```

Works flawlessly with debian:

```
FROM golang:1.15 as prod-build

WORKDIR /app
COPY . .

RUN go mod download
RUN go build -ldflags="-w -s" -o /app/my-app

# runtime container setup
FROM debian:stretch-slim
USER root

WORKDIR /app
COPY --from=prod-build /app/my-app /app/my-app
COPY --from=prod-build /app/resources/ /app/resources

EXPOSE 7575
ENTRYPOINT ["/app/my-app"]

```

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`v.1.5.2 and above`): go 1.15
 - [X] Apache Kafka broker version: 2.2 and 2.4 both does not work
 - [X] Client configuration: `ConfigMap{...}`
 - [X] Operating system: MacOS Big Sur
 - [X] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by emretanriverdi** [comment]
I decided to use distroless. Works flawlessly.

```
FROM golang:1.15 as prod-build

WORKDIR /app
COPY . .

RUN go mod download
RUN go build -ldflags="-w -s" -o /app/my-app

# runtime container setup
FROM gcr.io/distroless/base

WORKDIR /app
COPY --from=prod-build /app/my-app /app/my-app
COPY --from=prod-build /app/resources/ /app/resources

EXPOSE 7575
ENTRYPOINT ["/app/my-app"]
```

I am not closing the issue since it's still not working with scratch.

**Comment by respondcreate** [comment]
> I decided to use distroless. Works flawlessly.

Thanks so much for sharing this fix, @emretanriverdi !

**Comment by emretanriverdi** [comment]
You're welcome, @respondcreate :)
