### ISSUE TITLE
Effect of number of partitions per consumer on latency

### ISSUE THREAD

**Issue by csdenboer** [confluentinc/confluent-kafka-go#652]

**Comment by mhowlett** [comment]
not enough information (how many brokers? rtt? message size? etc) to comment. debug logs (set debug config to all) will most likely expose the reason.

**Comment by csdenboer** [comment]
Number of brokers: 3
RTT: max 1ms
Message size: max 1kb
Debug logs: https://pastebin.com/Cpq5ZqUq
