### ISSUE TITLE
How often should GetConsumerGroupMetadata be called?

### ISSUE THREAD

**Issue by csdenboer** [confluentinc/confluent-kafka-go#653]
Description
===========
I'm currently implementing Kafka transactions. In the example I see that GetConsumerGroupMetadata is called before every commit. GetConsumerGroupMetadata queries the broker for consumer groups metadata, which obviously increases e2e latency. Is it possible to cache the metadata? If yes, how long can it be cached safely? Thanks!

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.7.0
 - [x] Apache Kafka broker version: 2.8.0
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Amazon Linux
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue: no

**Comment by edenhill** [comment]
GetConsumerGroupMetadata does not query the broker, it simply returns some internal consumer group state from the consumer instance and is thus a cheap call, and it must not be cached.
The only time you need to call it is to pass the metadata to the SendOffsetsToTransaction() API, which is typically once per transaction.
