### ISSUE TITLE
Kafka Consumer Group Timeout error

### ISSUE THREAD

**Issue by sudeepigntion** [confluentinc/confluent-kafka-go#654]
Description
===========

%4|1623843447.348|SESSTMOUT|EXCH_OMS_rslinmnmeftlotvpha_1#consumer-27| [thrd:main]: Consumer group session timed out (in join-state steady) after 30000 ms without a successful response from the group coordinator (broker 1, last error was Success): revoking assignment and rejoining group
%4|1623843448.177|SESSTMOUT|AE_RES_rslinmnmeftlotvpha_1#consumer-13| [thrd:main]: Consumer group session timed out (in join-state steady) after 30000 ms without a successful response from the group coordinator (broker 5, last error was Success): revoking assignment and rejoining group
%4|1623843449.305|SESSTMOUT|NSE_FOrslinmnmeftlotvpha_1#consumer-11| [thrd:main]: Consumer group session timed out (in join-state steady) after 30001 ms without a successful response from the group coordinator (broker 4, last error was Success): revoking assignment and rejoining group
%4|1623843449.305|SESSTMOUT|NSE_FOrslinmnmeftlotvpha_2#consumer-2| [thrd:main]: Consumer group session timed out (in join-state steady) after 30002 ms without a successful response from the group coordinator (broker 4, last error was Success): revoking assignment and rejoining group
%4|1623843449.306|SESSTMOUT|NSE_FOrslinmnmeftlotvpha_3#consumer-12| [thrd:main]: Consumer group session timed out (in join-state steady) after 30002 ms without a successful response from the group coordinator (broker 4, last error was Success): revoking assignment and rejoining group
%4|1623843453.927|SESSTMOUT|BSE_FOrslinmnmeftlotvpha_1#consumer-5| [thrd:main]: Consumer group session timed out (in join-state steady) after 30001 ms without a successful response from the group coordinator (broker 4, last error was Success): revoking assignment and rejoining group
%4|1623843453.928|SESSTMOUT|BSE_FOrslinmnmeftlotvpha_3#consumer-1| [thrd:main]: Consumer group session timed out (in join-state steady) after 30001 ms without a successful response from the group coordinator (broker 4, last error was Success): revoking assignment and rejoining group
%4|1623843453.929|SESSTMOUT|BSE_FOrslinmnmeftlotvpha_2#consumer-22| [thrd:main]: Consumer group session timed out (in join-state steady) after 30002 ms without a successful response from the group coordinator (broker 4, last error was Success): revoking assignment and rejoining group

Suddenly facing this issue in kafka I am using confluent for 1 year but now from 3-4 days I am facing this issue.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the checklist

**Comment by mhowlett** [comment]
the consumer(s) were unable to successfully send heartbeats. if the group is still alive they will have been kicked out, so they are attempting to re-join.

this is likely indicative of a network or broker issue.
