### ISSUE TITLE
How To Create a Window Service Using Confluent-Kafka-Go

### ISSUE THREAD

**Issue by Orlandoiii** [confluentinc/confluent-kafka-go#655]
Description
===========
I have a service when I use golang.org/x/sys/windows/svc to create my api as window service. This works perfect.
I was able to follow this How to use Golang client on Windows #128 and thats work to. I can consume, produce my api work as I want. I can use both librerys and when I run the service in debug mode everything is fine. But when the api is a window service the service dont start I got a 1053 error message. I was running several test and I can say the service dont work when I use the confluent librery. I know that because this librery dont support window something is missing when .exe run as service but I can figure out what it is. 

How to reproduce
================
I make a little program apart from my main project. Justo copy and paste the example from here golang.org/x/sys/windows/svc and add a consumer from confluent. 
This what i have in the Excute function 
	const cmdsAccepted = svc.AcceptStop | svc.AcceptShutdown | svc.AcceptPauseAndContinue
	changes <- svc.Status{State: svc.StartPending}
	fmt.Println("AQUI LLEGO")
	if _, err := os.Stat(".\\LOGSmsPrueba\\"); os.IsNotExist(err) {
		os.MkdirAll(".\\LOGSmsPrueba\\", 0700)
	}
	filelogs, _ := os.OpenFile(".\\LOGSmsPrueba\\LOGS.log", os.O_APPEND|os.O_CREATE|os.O_RDWR, 0644)
	//writerLog := zerolog.MultiLevelWriter(filelogs)
	defer filelogs.Close()

	log := zerolog.New(filelogs).With().Logger()
	log.Debug().Msg("Before The Thread Of Consumer")
	go func() {

		log := zerolog.New(filelogs).With().Logger()

		kafkaservice.ConsumidorKafka(&log)
	}()

	changes <- svc.Status{State: svc.Running, Accepts: cmdsAccepted}
loop:
	for {
		select {

		case c := <-r:
			switch c.Cmd {
			case svc.Interrogate:
				changes <- c.CurrentStatus
				// Testing deadlock from https://code.google.com/p/winsvc/issues/detail?id=4
				time.Sleep(100 * time.Millisecond)
				changes <- c.CurrentStatus
			case svc.Stop, svc.Shutdown:
				// golang.org/x/sys/windows/svc.TestExample is verifying this output.
				testOutput := strings.Join(args, "-")
				testOutput += fmt.Sprintf("-%d", c.Context)
				elog.Info(1, testOutput)
				break loop
			case svc.Pause:
				changes <- svc.Status{State: svc.Paused, Accepts: cmdsAccepted}

			case svc.Continue:
				changes <- svc.Status{State: svc.Running, Accepts: cmdsAccepted}

			default:
				elog.Error(1, fmt.Sprintf("unexpected control request #%d", c))
			}
		}
	}
	changes <- svc.Status{State: svc.StopPending}
	return

Checklist

librdkafka Version: 1.7.0
confluent-kafka-go Version:1.7.0
&kafka.ConfigMap{
		"bootstrap.servers": "localhost:9092",
		
		"broker.address.family": "v4",
		"group.id":              "grp.banco_emisor.credt_transf_inmdt",
		"session.timeout.ms":    6000,
		"auto.offset.reset":     "earliest"}

golang.org/x/sys v0.0.0-20210615035016

**Comment by edenhill** [comment]
Have no experience with windows services, maybe file an issue with the Go module that provides the windows service interface?

**Comment by Orlandoiii** [comment]
> Have no experience with windows services, maybe file an issue with the Go module that provides the windows service interface?

Thanks I will do it. I ask for help here, because the librery for window service works. Is really not complicated is just an interface when you have to listen to SWM, and it work. And the confluent librery also work after doing all the steps in the guide with cygwin and librkafka. The problem arise when I run the .exe as window service using confluent. I assume is because is not standart supported on window. Something broke or is missing that is not allowed the project to run as window service it has to be a component for the confluent librery.

**Comment by Orlandoiii** [comment]
Finally I made it work. The only part that was missing was compile in a static way like this => go build -ldflags '-extldflags "-static"'. This fixed the issue with a missing dll, the problem was that on console everything works fine. I never see the missing dll. But when I work on a window server 2016 the console did not run. The specific error was "Run bin file Systerm Error "libwinpthread-1.dll was not found". I fix thats with static compile and came back to prove the window service with this compilation too. And finally i have my go service running as window service and using confluent kafka librery.

**Comment by edenhill** [comment]
Thanks for the update, I'm sure it will be useful for other people aswell!

**Comment by neptoess** [comment]
For anyone else who encounters this issue, I would recommend examining your binary's dependencies (with a tool like https://github.com/lucasg/Dependencies/), and deciding between the approach suggested by @Orlandoiii and copying the dependencies to the target machine along with the binary. For the most part, `libwinpthread-1.dll` and `libgcc_s_seh-1.dll` seem to be the only MinGW dependencies that need copied along with the binary (if the target machine doesn't already have MinGW installed).

If confluent-kafka-go is your only cgo dependency, the static build flag will work fine, but if you need to use both statically-linked and dynamically-linked cgo dependencies, it may cause issues. Just food for thought.
