### ISSUE TITLE
Set enable.auto.offset.store=false and manual call StoreOffsets, but can't been auto committed

### ISSUE THREAD

**Issue by zhangxin0623** [confluentinc/confluent-kafka-go#656]
Description
===========
Hallo, 
there is a kafka consumer in my programm and the process for the message cost long time(10s e.g.). I want to make sure that, the commit is done after the process end. According[ Note: It is recommended to set enable.auto.offset.store=false for long-time processing applications and then explicitly store offsets (using offsets_store()) after message processing, to make sure offsets are not auto-committed prior to processing has finished. ](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)  i set "enable.auto.offset.store": false in ConfigMap of the consumer and manual call StoreOffsets after processing. The function StoreOffsets returned right but this offset is not been auto commited.
Thanks.

How to reproduce
================
Here is my programm:
```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/confluentinc/confluent-kafka-go/kafka"
)

func main() {

	if len(os.Args) < 4 {
		fmt.Fprintf(os.Stderr, "Usage: %s <broker> <group> <topics..>\n",
			os.Args[0])
		os.Exit(1)
	}

	broker := os.Args[1]
	group := os.Args[2]
	topics := os.Args[3:]
	sigchan := make(chan os.Signal, 1)
	signal.Notify(sigchan, syscall.SIGINT, syscall.SIGTERM)

	c, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers":        broker,
		"group.id":                 group,
		"enable.auto.offset.store": false,
		"auto.commit.interval.ms":  5000,
		"auto.offset.reset":        "earliest"})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create consumer: %s\n", err)
		os.Exit(1)
	}

	fmt.Printf("Created Consumer %v\n", c)

	err = c.SubscribeTopics(topics, nil)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to subscribe topics: %s\n", err)
		os.Exit(1)
	}
	run := true

	var cnt int = 0

	for run == true {
		select {
		case sig := <-sigchan:
			fmt.Printf("Caught signal %v: terminating\n", sig)
			run = false
		default:
			ev := c.Poll(1)
			if ev == nil {
				continue
			}

			switch e := ev.(type) {
			case *kafka.Message:
				str := string(e.Value)
				if len(str) > 256 {
					str = str[0:255]
				}
				if e.Headers != nil {
					fmt.Printf("%% Headers: %v\n", e.Headers)
				}
				cnt++
				fmt.Printf("now offset[%d] in partition[%d],total recv msg[%v]\n", e.TopicPartition.Offset, e.TopicPartition.Partition, cnt)
				storedoffsets, err := c.StoreOffsets([]kafka.TopicPartition{e.TopicPartition})
				if err != nil {
					fmt.Printf("offset[%v] store err: %v\n", e.TopicPartition, err)
				} else {
					fmt.Printf("offset[%v] store success\n", storedoffsets)
				}
			case kafka.Error:
				fmt.Fprintf(os.Stderr, "%% Error: %v: %v\n", e.Code(), e)
				if e.Code() == kafka.ErrAllBrokersDown {
					run = false
				}
			default:
				fmt.Printf("Ignored %v\n", e)
			}
		}
	}

	fmt.Printf("Closing consumer\n")
	c.Close()
}
```

I have test times and follow list two cases:

Case 1: there is only one not commited msg in kafka: 
What expected print out msg is:

>Created Consumer rdkafka#consumer-1
>now offset[1] in partition[0],total recv msg[1]
>offset[[TOPIC-NAME[0]@1]] store success
>Ignored OffsetsCommitted (<nil>, [TOPIC-NAME[0]@2 TOPIC-NAME[1]@unset TOPIC-NAME[2]@unset TOPIC-NAME[3]@unset TOPIC-NAME[4]@unset TOPIC-NAME[5]@unset TOPIC-NAME[6]@unset TOPIC-NAME[7]@unset TOPIC-NAME[8]@unset])

But the actual result is:

>Created Consumer rdkafka#consumer-1
>now offset[1] in partition[0],total recv msg[1]
>offset[[TOPIC-NAME[0]@1]] store success

As you can see, the offset 1 is stored but not auto commited. If I restart the program the offset 1 in partition 0 will be consumed again.

Case 2: there is two not commited msg in kafka:
What expected print out msg is:
>Created Consumer rdkafka#consumer-1
>now offset[1] in partition[0],total recv msg[1]
>offset[[XMC-BASE-LESSON2[0]@1]] store success
>Ignored OffsetsCommitted (<nil>, [TOPIC-NAME[0]@2 TOPIC-NAME[1]@unset TOPIC-NAME[2]@unset TOPIC-NAME[3]@unset TOPIC-NAME[4]@unset TOPIC-NAME[5]@unset TOPIC-NAME[6]@unset TOPIC-NAME[7]@unset TOPIC-NAME[8]@unset])
>now offset[2] in partition[0],total recv msg[2]
>offset[[XMC-BASE-LESSON2[0]@2]] store success
>Ignored OffsetsCommitted (<nil>, [TOPIC-NAME[0]@3 TOPIC-NAME[1]@unset TOPIC-NAME[2]@unset TOPIC-NAME[3]@unset TOPIC-NAME[4]@unset TOPIC-NAME[5]@unset TOPIC-NAME[6]@unset TOPIC-NAME[7]@unset TOPIC-NAME[8]@unset])

The actual output is:
>Created Consumer rdkafka#consumer-1
>now offset[1] in partition[0],total recv msg[1]
>offset[[XMC-BASE-LESSON2[0]@1]] store success
>now offset[2] in partition[0],total recv msg[2]
>offset[[XMC-BASE-LESSON2[0]@2]] store success
>Ignored OffsetsCommitted (<nil>, [TOPIC-NAME[0]@2 TOPIC-NAME[1]@unset TOPIC-NAME[2]@unset TOPIC-NAME[3]@unset TOPIC-NAME[4]@unset TOPIC-NAME[5]@unset TOPIC-NAME[6]@unset TOPIC-NAME[7]@unset TOPIC-NAME[8]@unset])

Now you can see: the offset 1 is commited, but offset 2 is not. When i restart the programm, offset 2 will be consumed again.

Checklist
=========
golang Version: 1.6.0
librdkafka Version: 1.7.0
confluent-kafka-go Version:1.7.0
`ConfigMap{"bootstrap.servers":        broker,
		"group.id":                 group,
		"enable.auto.offset.store": false,
		"auto.commit.interval.ms":  5000,
		"auto.offset.reset":        "earliest"}`

**Comment by mhowlett** [comment]
By convention, a committed offset represents the next message to be consumed. You need to commit the offset of the last consumed message + 1, not the offset of the last consumed message.
