### ISSUE TITLE
Question: transactional producer

### ISSUE THREAD

**Issue by kuronyago** [confluentinc/confluent-kafka-go#657]
Do I understand correctly that transactions within a single "transactional.id" must be strictly linearized?

**Comment by kuronyago** [comment]
from [docs](https://docs.confluent.io/5.5.0/clients/confluent-kafka-go/index.html)
"A producer instance may only have one single on-going transaction."

**Comment by mhowlett** [comment]
yes, Kafka transactions are designed for streaming use cases - you can only have one transaction per transactional.id (i.e. producer instance) open at any given time.
