### ISSUE TITLE
How to create pre-built librdkafka for my os?

### ISSUE THREAD

**Issue by punithck** [confluentinc/confluent-kafka-go#659]
Description
===========
My service is running in amazon-linux. Pre-built librdkafka exist in librdkafka repo that doesnt support my OS
When I deploy the service, first I install librdkafka with source code and then deploy my service. Installing of librdkafka taking more time around 2 - 5 min.

 Is there a way that I can build my service (using confluent-kafka-go) with librdkafka in it, So that I no need to install librdkafka in target machine? 
Or
 Is there way that I can create binary of librdkafka and put that in target machine so that I no need to build the source code and install librdkafka each time when I want to run my service in new machine?
 Or 
 How to create pre-built librdkafka for my OS and how to install it in my target machine?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.5.2
 - [x] Apache Kafka broker version: 1.1.1
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system:Amazon Linux AMI 2018.03
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Latest version of confluent-kafka-go comes with librdkafka prebuilt and bundled, so you should not need to install it separately.

So please try the latest version.

**Comment by punithck** [comment]
Using of latest version confluent-kafka-go worked. Thanks @edenhill
