### ISSUE TITLE
Question - guarantees of the delivery channel

### ISSUE THREAD

**Issue by Zach-Johnson** [confluentinc/confluent-kafka-go#660]
Hello -
I have a use case for producing ordered messages within a Kafka transaction and I am curious about the mechanics of the delivery channel here. In order for me to ensure messages are written in order and received successfully, I want to read the delivery channel after each message is produced to check for errors and abort the transaction if necessary. I'm concerned about blocking on this channel though. What are the guarantees of this channel? Is there a guarantee that _something_ will be sent on this delivery channel for each message produced? Or are there edge cases where a call to produce can fail and nothing will be sent on the delivery channel (causing my app to block indefinitely)? Or will something always be sent on the delivery channel as long as the initial `Produce` call didn't itself throw an error?

**Comment by edenhill** [comment]
A nice thing with transactions is that you don't need to care for individual message delivery reports: commit_transaction(), and the transaction itself, will fail if any of the messages since begin_transaction() failed.

But if you do have delivery reports enabled you will get one delivery report per message, either during the lifetime of the transaction, or when calling commit_transaction() or abort_transaction() since they both do a flush() internally.

**Comment by Zach-Johnson** [comment]
@edenhill thank you this is very helpful, I was not aware that commit_transaction() would fail if any message in the transaction failed. 

I was also concerned about message ordering within the transaction, as I don't want things written to Kafka out of order. Do the internal queues in this library maintain message ordering across retries? I'm configuring the producer with `enable.idempotence`, `max.in.flight.requests.per.connection=1`, and `acks=all`, so I'm assuming that should enforce ordering within this library, is that correct?

**Comment by edenhill** [comment]
The per-partition ordering guarantees are provided by the idempotent producer, which the transactional producer is using.

You do not need to, and should not, configure any of the listed properties as the defaults for a transactional producer are properly set already (acks=all, in.flight=5, enable.idempotence=true).

**Comment by Zach-Johnson** [comment]
Ah, okay got it - my understanding is I should still set in.flight=1 though, setting it to 5 indicates that re-ordering can occur if a message batch is re-tried. Or is that not the case for transactions, since they are sent to the partition in a single batch?

**Comment by edenhill** [comment]
The idempotent producer takes care of ordering, and it does so up to max.in.flight=5. But there's work to remove this limit as well.
There is no need to decrease max.in.flight.

**Comment by Zach-Johnson** [comment]
@edenhill okay that makes sense. If I don't actually care about the delivery reports, can I just disable them entirely and check for an error on the commit? Do I still need to drain the producer events channel in this case in a separate routine?

**Comment by edenhill** [comment]
I think that would work, disabling delivery reports and just checking commit error. At least in librdkafka, need to double check with the Go bindings, but give it a shot in the meantime.
