### ISSUE TITLE
Transactional Producer Offset multiplied by 2 

### ISSUE THREAD

**Issue by g-freire** [confluentinc/confluent-kafka-go#665]
Description
===========
When I use transactions the offsets seems to be multiplied by 2. Can I change it ?

<img width="729" alt="transKowl" src="https://user-images.githubusercontent.com/25310481/126261998-45e67afe-cffa-44a9-8fbf-bb72767e2480.png">

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
this is caused by the transaction control records (begin/end/abort) which are for internal use and not exposed to the application. you can't change this.

**Comment by g-freire** [comment]
Okay, thanks for the quick response @mhowlett 👍
