### ISSUE TITLE
Producer timing out 

### ISSUE THREAD

**Issue by g-freire** [confluentinc/confluent-kafka-go#666]
Description
===========
Hi, I'm having an issue on some of the microservices pods running the library. I'm receiving many timeouts, which I don't receive using other libs(eg. sarama). Does someone now if this is something expected, like a warning  ? We are concerned, because we can't lose data and there is timeouts all over the logs. I've already increased the client timeout related configs, downgraded the version and test in different clusters.  Any help on it will be very welcomed as we really like this lib and want to use in prod.

How to reproduce
================
 If I publish every second I can't reproduce the error. If I start sleeping between the iteration, I always trigger the timeout when sleeping more than 5-7 min.  I'm running it on a Azure cluster (AKS). When we test it locally pointing to the qa cluster on azure we receive the timeouts but we don't lose data. I don't know about the qa system now, because we have many clients and is harder to track the data flow. Same problem with transactional or non-transactional block

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.7 (latest)
 - [x] Apache Kafka broker version: 2.7
 - [x] Client configuration: `ConfigMap{...}` 
 - [x] Operating system: golang image build executing on debian image
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [x] Provide broker log excerpts
 - [ ] Critical issue

![image](https://user-images.githubusercontent.com/25310481/126669952-84a95c7e-ba4b-41ee-ae38-748cd7515d19.png)

Configs used on tests
![image](https://user-images.githubusercontent.com/25310481/126670890-8f19b02b-6127-4b71-836f-64981cf4166a.png)
![image](https://user-images.githubusercontent.com/25310481/126670840-cfc3878e-5892-45c4-a3c1-fea0b03d9056.png)
No configs at all

**Comment by jliunyu** [comment]
Thanks @g-freire for reporting this. Looks this is related to https://github.com/edenhill/librdkafka/issues/2845#issuecomment-625433415. 

But I saw there is a fix related to this https://github.com/edenhill/librdkafka/commit/052745727ce86c2c36c7cc3c4aefc181c5da88d8. 

@edenhill , can you please take a look at this one?

**Comment by jliunyu** [comment]
Hi @g-freire, sorry for the late response. I conformed with @edenhill , the coming 1.8.0 release will improve things on Azure.
https://github.com/edenhill/librdkafka/issues/3109
