### ISSUE TITLE
Application stalls when calling Consumer.Close() with a rebalance callback set to nil

### ISSUE THREAD

**Issue by ThreadedStream** [confluentinc/confluent-kafka-go#670]
Description
===========
Execution of a program stalls when calling Close() on a consumer initialized with a rebalance callback set to nil.
However, issue suddenly disappears once i pass a dummy callback. I dug into source code of librdkafka and stumbled upon the 
following remark right above rd_kafka_destroy's definition
```
rd_kafka_consumer_close() will be called from this function
 *         if the instance type is RD_KAFKA_CONSUMER, a \c group.id was
 *         configured, and the rd_kafka_consumer_close() was not
 *         explicitly called by the application. This in turn may
 *         trigger consumer callbacks, such as rebalance_cb.
 *         Use rd_kafka_destroy_flags() with
 *         RD_KAFKA_DESTROY_F_NO_CONSUMER_CLOSE to avoid this behaviour
 ```
I wonder whether it's possible to call rd_kafka_destroy_flags() with a mentioned flag specified. On the other hand, I have no doubt that a library handles the case with a nil callback, replacing the latter with a default one.  

How to reproduce
================

Just call Consumer.Subscribe() with a rebalanceCb set to nil, subsequently calling a Close() method.   

Checklist
=========

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.7.0 (latest at the moment)
 - [x] Apache Kafka broker version: ```2.7.0```
 - [x] Client configuration: 
 ```go
	consumer, err = confkafka.NewConsumer(&confkafka.ConfigMap{
		"bootstrap.servers":     Config().KafkaBrokerIp,
		"broker.address.family": "v4",
		"group.id":              Config().CompanyGroupId + "-" + Config().KafkaClientId + "_group",
		"auto.offset.reset":     "latest",
		"enable.auto.commit":    false,
	})
```
 - [x] Operating system: Ubuntu 20.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Hi @ThreadedStream, thanks for reporting this.

This looks the same issue with https://github.com/confluentinc/confluent-kafka-go/issues/661, we are going to provide a fix soon.
