### ISSUE TITLE
AdminClient] How to determine whether a topic exists[

### ISSUE THREAD

**Issue by SeanFarrow** [confluentinc/confluent-kafka-go#672]
Is it possible using the admin client to determine whether a particular topic exists?
I can't seem to find anything so wondered whether a PR to add this would be accepted as it's something I need.

Thanks,
Sean.

**Comment by jliunyu** [comment]
Hi @SeanFarrow thanks for mention this, I added this to our backlog.

**Comment by edenhill** [comment]
You can use GetMetadata() to get the metadata for a topic, and thus find out if it exists or not.
