### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by mrosenc** [confluentinc/confluent-kafka-go#673]
Description
===========

Sorry this is more of a question, the docs weren't clear enough for me.  It says that the client is safe for concurrent use, but can I use a consumer concurrently?  That is can I Poll in one goroutine while calling Commit in another?

Also is there any way to cancel a Poll?  I tried calling Close concurrently, but that produced a crash.

Thanks!

**Comment by jliunyu** [comment]
Hi @mrosenc, thanks for asking. 

"can I use a consumer concurrently? That is can I Poll in one goroutine while calling Commit in another?" Unfortunately, the answer is no. 

```You can’t have multiple consumers that belong to the same group in one thread and you can’t have multiple threads safely use the same consumer. **_One consumer per thread is the rule_**. To run multiple consumers in the same group in one application, you will need to run each in its own thread. It is useful to wrap the consumer logic in its own object and then use Java’s ExecutorService to start multiple threads each with its own consumer. The Confluent blog has a tutorial that shows how to do just that.```

Refer to : https://www.oreilly.com/library/view/kafka-the-definitive/9781491936153/ch04.html
