### ISSUE TITLE
FusionInsight HD 6.5.1 kafka 对接失败

### ISSUE THREAD

**Issue by 297242448** [confluentinc/confluent-kafka-go#674]
Description
===========
vide more information (Server kafka/fsnh-ioc-hd-dn01@HADOOP.COM not found in Kerberos database)
%3|1628342061.129|FAIL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.209:21007/bootstrap]: sasl_plaintext://10.170.204.209:21007/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn01@HADOOP.COM not found in Kerberos database) (after 31ms in state AUTH_REQ)
%2|1628342061.440|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.209:21007/bootstrap]: sasl_plaintext://10.170.204.209:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn01@HADOOP.COM not found in Kerberos database)
%3|1628342061.440|FAIL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.209:21007/bootstrap]: sasl_plaintext://10.170.204.209:21007/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn01@HADOOP.COM not found in Kerberos database) (after 34ms in state AUTH_REQ, 1 identical error(s) suppressed)
%2|1628342061.475|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.211:21007/bootstrap]: sasl_plaintext://10.170.204.211:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn03@HADOOP.COM not found in Kerberos database)
%3|1628342061.476|FAIL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.211:21007/bootstrap]: sasl_plaintext://10.170.204.211:21007/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn03@HADOOP.COM not found in Kerberos database) (after 33ms in state AUTH_REQ)
%2|1628342061.737|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.211:21007/bootstrap]: sasl_plaintext://10.170.204.211:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn03@HADOOP.COM not found in Kerberos database)
%3|1628342061.737|FAIL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.211:21007/bootstrap]: sasl_plaintext://10.170.204.211:21007/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn03@HADOOP.COM not found in Kerberos database) (after 32ms in state AUTH_REQ, 1 identical error(s) suppressed)
%2|1628342062.128|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.210:21007/bootstrap]: sasl_plaintext://10.170.204.210:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn02@HADOOP.COM not found in Kerberos database)
%2|1628342062.553|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.209:21007/bootstrap]: sasl_plaintext://10.170.204.209:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn01@HADOOP.COM not found in Kerberos database)
%2|1628342062.968|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.211:21007/bootstrap]: sasl_plaintext://10.170.204.211:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn03@HADOOP.COM not found in Kerberos database)
%2|1628342064.583|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.210:21007/bootstrap]: sasl_plaintext://10.170.204.210:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn02@HADOOP.COM not found in Kerberos database)
%2|1628342065.689|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.209:21007/bootstrap]: sasl_plaintext://10.170.204.209:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn01@HADOOP.COM not found in Kerberos database)
%2|1628342066.717|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.211:21007/bootstrap]: sasl_plaintext://10.170.204.211:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn03@HADOOP.COM not found in Kerberos database)
%2|1628342074.616|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.210:21007/bootstrap]: sasl_plaintext://10.170.204.210:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn02@HADOOP.COM not found in Kerberos database)
%2|1628342075.724|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://10.170.204.209:21007/bootstrap]: sasl_plaintext://10.170.204.209:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/fsnh-ioc-hd-dn01@HADOOP.COM not found in Kerberos database)
%4|1628342075.891|TERMINATE|rdkafka#producer-1| [thrd:app]: Producer terminating with 7 messages (38 bytes) still in queue or transit: use flush() to wait for outstanding message delivery

How to reproduce
================
package main

import (
	"fmt"
	"github.com/confluentinc/confluent-kafka-go/kafka"
)

func main() {

	p, err := kafka.NewProducer(&kafka.ConfigMap{
		"bootstrap.servers": "10.170.204.209:21007,10.170.204.210:21007,10.170.204.211:21007",
		//"kerberos.domain.name": "hadoop.hadoop.com",
		"security.protocol": "SASL_PLAINTEXT",
		"sasl.mechanism":"GSSAPI",
		"sasl.kerberos.service.name": "kafka",
		"sasl.kerberos.principal": "HADOOP.COM",
		"sasl.username":"hids_svr",
		"sasl.password":"Huawei@123",
		"sasl.kerberos.keytab": "/opt/Elkeid/server/agent_center/conf/user.keytab",
	})
	if err != nil {
		panic(err)
	}

	defer p.Close()

	// Delivery report handler for produced messages
	go func() {
		for e := range p.Events() {
			switch ev := e.(type) {
			case *kafka.Message:
				if ev.TopicPartition.Error != nil {
					fmt.Printf("Delivery failed: %v\n", ev.TopicPartition)
				} else {
					fmt.Printf("Delivered message to %v\n", ev.TopicPartition)
				}
			}
		}
	}()

	// Produce messages to topic (asynchronously)
	topic := "hids_test"
	for _, word := range []string{"Welcome", "to", "the", "Confluent", "Kafka", "Golang", "client"} {
		p.Produce(&kafka.Message{
			TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny},
			Value:          []byte(word),
		}, nil)
	}

	// Wait for message deliveries before shutting down
	p.Flush(15 * 1000)
}

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Hi @297242448 , thanks for asking, can you please provide which go clients version and librdkafka version are you using?

**Comment by 297242448** [comment]
> 嗨@297242448，感谢提问，你能提供你使用的是哪个go客户端版本和librdkafka版本吗？

go version go1.16.3 linux/amd64
librdkafka 1.8.0

**Comment by jliunyu** [comment]
Thanks @297242448 , librdkafka 1.8.0 is not released yet, please use our latest released version v1.7.0. And for go clients, our latest released version v1.7.0 is also a good choice.
