### ISSUE TITLE
Apple M1 Chip : Unable to build the project

### ISSUE THREAD

**Issue by georgejpadayatti** [confluentinc/confluent-kafka-go#675]
Description
===========

The same build works if the host operating system is Linux based (Past operating system being Ubuntu 64bit)

Unable to build the project. Throws an error and exits. Terminal stack trace is provided below.

```
/usr/bin/ld: /go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.4.2/kafka/librdkafka/librdkafka_glibc_linux.a(rdkafka_error.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: /go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.4.2/kafka/librdkafka/librdkafka_glibc_linux.a(rdkafka_error.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: /go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.4.2/kafka/librdkafka/librdkafka_glibc_linux.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

How to reproduce
================

The docker file of the builder container used to build the golang project is provided below:

```
FROM golang:1.16


WORKDIR /go/src/github.com/myproject/api
COPY go.mod .
COPY go.sum .

# Install go dependencies
RUN go mod download

ENV TERM xterm-256color
RUN echo 'export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "' >> ~/.bashrc
# Cleanup
RUN apt-get clean && \
    rm -rf /tmp/* /var/tmp/* && \
    rm -rf /var/lib/apt/lists/*

```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.4.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Mac OS Big Sur (Apple M1 chip)
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by georgejpadayatti** [comment]
The above issue was due to docker by default building containers in `arm64` architecture. Once the container architecture was changed to `amd64` by using `docker buildx` tool, the above issue got resolved.

**Comment by kurennoy16** [comment]
Hey @georgejpadayatti 
I don't get how you resolve this. Could anyone point to what I'm doing wrong?

I'm trying to build the app inside the Docker container like that: `docker build -f ./docker/Dockerfile --no-cache -t $(IMAGE_NAME):latest`
It fails with the error:
                                                                                                                                                                                                                                                        
 > [builder 6/7] RUN CGO_ENABLED=1 go build -o build/bin/masterdata/masterdata ./masterdata/cmd:                                                                                                                                                                   
#10 14.89 # github.com/confluentinc/confluent-kafka-go/kafka                                                                                                                                                                                                       
#10 14.89 /usr/bin/ld: vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_error.o): Relocations in generic ELF (EM: 62)                                                                                    
#10 14.89 /usr/bin/ld: vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_error.o): Relocations in generic ELF (EM: 62)                                                                                    
#10 14.89 /usr/bin/ld: vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a: error adding symbols: file in wrong format
#10 14.89 collect2: error: ld returned 1 exit status
------


Dockerfile:
```
FROM golang as builder

COPY . my-service/
WORKDIR my-service/

ARG BUILD_PATH

RUN go mod download 
RUN CGO_ENABLED=1 go build -o ${BUILD_PATH}/service ./service/cmd
```

I've tried to run `docker buildx build --platform linux/amd64 -f ./docker/Dockerfile --no-cache -t $(IMAGE_NAME):latest`. But it failes with the error: 

> [builder 5/7] RUN go mod download:
#9 0.314 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#9 0.317 Segmentation fault
------
error: failed to solve: executor failed running [/bin/sh -c go mod download]: exit code: 139

Running `docker buildx build --platform linux/arm64 -f ./docker/Dockerfile --no-cache -t $(IMAGE_NAME):latest` fails with the main err:                                                                                                                                                                                                                                                   
 > [builder 6/7] RUN CGO_ENABLED=1 go build -o build/bin/masterdata/masterdata ./masterdata/cmd:                                                                                                                                                                   
#10 14.89 # github.com/confluentinc/confluent-kafka-go/kafka                                                                                                                                                                                                       
#10 14.89 /usr/bin/ld: vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_error.o): Relocations in generic ELF (EM: 62)                                                                                    
#10 14.89 /usr/bin/ld: vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_error.o): Relocations in generic ELF (EM: 62)                                                                                    
#10 14.89 /usr/bin/ld: vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a: error adding symbols: file in wrong format
#10 14.89 collect2: error: ld returned 1 exit status
------

**Comment by kkHAIKE** [comment]
make a fork for it
https://github.com/kkHAIKE/confluent-kafka-go/releases/tag/v1.7.1

**Comment by viktor-minko** [comment]
@kurennoy16 
this worked for me 
export DOCKER_DEFAULT_PLATFORM=linux/amd64
