### ISSUE TITLE
Kafka successful connect or not

### ISSUE THREAD

**Issue by cedricve** [confluentinc/confluent-kafka-go#679]
What is the best way to verify if Kafka was successful to connect?
I know the `kafka.NewConsumer` can return an error, but it looks like returning async.

Kind regards

**Comment by edenhill** [comment]
You can enable statistics and extract the per-broker states to check that at least one broker is UP.
https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

**Comment by cedricve** [comment]
Thank you so much Magnus!
