### ISSUE TITLE
Static membership doesn't respect session.timeout.ms

### ISSUE THREAD

**Issue by shang-wang** [confluentinc/confluent-kafka-go#682]
Description
===========
Hi all! I recently encountered a weird behavior that might be a bug. I'm currently experimenting with static membership feature by setting `group.instance.id` for my service. It works well for our current version 1.3.0, when a consumer is restarted, no rebalance happens, from broker logs I see:

```
[GroupCoordinator 10000]: Static member Some(process-discovery-test-2) of group test with unknown member id rejoins, assigning new member id test-2-aee026cc-0742-48bc-8722-8c4e07474b7d, while old member id test-2-a1414d95-2458-4fda-9658-26f153d84037 will be removed.
[GroupCoordinator 10000]: Static member which joins during Stable stage and doesn't affect selectProtocol will not trigger rebalance.
```

However, with no code change and merely bumping the dependency to 1.6.1, restarting a consumer would immediately trigger rebalance. From the broker log:

```
[GroupCoordinator 10000]: Member[group.instance.id Some(process-discovery-test-2), member.id test-2-8d66f5c8-3a59-40ec-959b-25f457e08f90] in group test has left, removing it from the group
[GroupCoordinator 10000]: Preparing to rebalance group test in state PreparingRebalance with old generation 263 (__consumer_offsets-29) (reason: removing member test-2-8d66f5c8-3a59-40ec-959b-25f457e08f90 on LeaveGroup)
```

To me this looks like `session.timeout.ms` is not respected, but I could be wrong. I tested all versions prior to 1.6.1 and they all seem to be working. Can someone let me know if there's any change that's needed to make it work for 1.6.1, or this could simply be a bug?

How to reproduce
================
I was able to reproduce this by just upgrading confluent-kafka-go from v1.5.2 or earlier to v1.6.1.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): problematic version found `1.6.1`
 - [x] Apache Kafka broker version: `2.7.1`
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: ubuntu 18.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Let's use https://github.com/confluentinc/confluent-kafka-go/issues/649 to track the status.
