### ISSUE TITLE
Bundle arm64 librdkafka

### ISSUE THREAD

**Issue by alol** [confluentinc/confluent-kafka-go#684]
Hello! We're running confluent-kafka-go in an environment which uses both arm64 and amd64 machines (as well as M1 and Intel Macs).

We note that we're able to build with `go build -tags dynamic`, but it would be ideal if librdkafka for arm64 (both for Linux and ideally Darwin) was bundled as it is for amd64, so that we can have a consistent build step between platforms (and don't have to manage the librdkafka dependency ourselves). 

I think this would also result in fewer issues such as https://github.com/confluentinc/confluent-kafka-go/issues/591 https://github.com/confluentinc/confluent-kafka-go/issues/675 https://github.com/confluentinc/confluent-kafka-go/issues/576

Thank you!

**Comment by kkHAIKE** [comment]
make a fork for it
https://github.com/kkHAIKE/confluent-kafka-go/releases/tag/v1.7.1

**Comment by jliunyu** [comment]
Since there are more discussion and comments at https://github.com/confluentinc/confluent-kafka-go/issues/591, let's close this one and use https://github.com/confluentinc/confluent-kafka-go/issues/591 to track the status.
