### ISSUE TITLE
dose golang supoort DescribeGroups api?

### ISSUE THREAD

**Issue by jcs12311** [confluentinc/confluent-kafka-go#685]
Description
===========
i want to get the consumer group's consumer client id like:  kafka_2.11-2.3.1/bin/kafka-consumer-groups.sh --describe --group xx  --bootstrap-server= xx do
dose any api can do this?

**Comment by jliunyu** [comment]
Hi @jcs12311 , thanks for asking.

From librdkafka, https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L4826 is the function contains the information you need. Unfortunately, this API is not exposed to go client yet.
