### ISSUE TITLE
prebuild librdkafka throwing error for ubuntu 12.04(virtual machine)

### ISSUE THREAD

**Issue by punithck** [confluentinc/confluent-kafka-go#688]
Description
===========
I am getting below error while building the service with prebuild librdkafka. command: go build -mod vendor -tags static

>  #github.com/confluentinc/confluent-kafka-go/kafka
> vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_queue.o): In function `rd_kafka_q_pop_serve':
> (.text+0xb59): undefined reference to `timespec_get'
> vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_queue.o): In function `rd_kafka_q_serve':
> (.text+0xeb5): undefined reference to `timespec_get'
> vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_queue.o): In function `rd_kafka_q_serve_rkmessages':
> (.text+0x148e): undefined reference to `timespec_get'
> vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka.o): In function `rd_kafka_new':
> (.text+0x2511): undefined reference to `timespec_get'
> vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka.o): In function `rd_kafka_flush':
> (.text+0x6f34): undefined reference to `timespec_get'
> vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(getenv.o): In function `ossl_safe_getenv':
> (.text+0x1): undefined reference to `secure_getenv'
> collect2: ld returned 1 exit status
> 

OS version:

> Distributor ID: Ubuntu
> Description:    Ubuntu 12.04 LTS
> Release:        12.04
> Codename:       precise

Adding glibc version: It might help

> ldd (Ubuntu EGLIBC 2.15-0ubuntu10) 2.15
> Copyright (C) 2012 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.
> 

How to reproduce
================
go build -mod vendor -tags static

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):v1.7.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: ubuntu
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your glibc version is too old and not supported by the prebuilt librdkafka libraries.
You will need to install librdkafka separately and then build your Go application with `-tags dynamic`.

**Comment by punithck** [comment]
Thanks @edenhill  for quick reply.
