### ISSUE TITLE
Need a way to extract bootstrap servers after mock servers are created

### ISSUE THREAD

**Issue by CodechCFA** [confluentinc/confluent-kafka-go#689]
Description
===========
librdkafka allows creating mock brokers for testing purposes by passing `test.mock.num.brokers` as a configuration parameter. The problem is we need the bootstrap server addresses it creates in order to produce to them or consume from them but this library provides no way to extract them.

How to reproduce
================
```go
kafkaProducer, err := kafka.NewProducer(&kafka.ConfigMap{"test.mock.num.brokers": 3})

consumer, err := kafka.NewConsumer(&kafka.ConfigMap{"bootstrap.servers":   ?})
```

**Comment by edenhill** [comment]
Right, we would need to add a Go function for `rd_kafka_mock_cluster_bootstraps()`.

**Comment by SourceFellows** [comment]
I created a "fix"/pull request for something like that: https://github.com/confluentinc/confluent-kafka-go/pull/729

We use the implementation to do "isolated integration testing" for our application.
