### ISSUE TITLE
some notes on my experience

### ISSUE THREAD

**Issue by alexec** [confluentinc/confluent-kafka-go#691]
This isn't a bug, just some commentary.

## General

My code performed poorly before I tuned it based on Confluent's recommendation](https://docs.confluent.io/cloud/current/client-apps/optimizing/throughput.html). The examples were very helpful and straight forward, as was configuration. I like that I could get re-balance event (Sarama cannot do that ).

## Consumer

The way my app works is that it uses `Poll()` and then puts the messages onto a channel, there is a one channel per partition. There is a Goroutine reading from each channel (i.e. concurrently) and each routine will use a ticker to commit offset every 1s, and on exit.

[The source code](https://github.com/argoproj-labs/argo-dataflow/blob/main/runner/sidecar/source/kafka/kafka.go).

* `Events()` vs `Poll`: I did not find any performance difference between the two mechanisms. 
* `Events()` seems to leave 1 un-consumed message in the buffer. Could be a bug, but won't affect many people.
* I set `fetch.min.bytes" as per Confluent's recommendation, but it did not seem to have any effect. 
* I seem to get some looping of assign and revoke. Still not sure why this happened.

## Producer

* I wanted both sync and async producer options. For sync I used a channel of size 1 which I could read from straight after `Produce()`. It was important to sent `linger.ms=0` for that to be performant.

[The source code](https://github.com/argoproj-labs/argo-dataflow/blob/main/runner/sidecar/sink/kafka/kafka.go)

**Comment by mhowlett** [comment]
thanks!
