### ISSUE TITLE
Kafka consumer only reading from one partition

### ISSUE THREAD

**Issue by cedricve** [confluentinc/confluent-kafka-go#694]
Hey amazing work!

I recently encountered some "strange" behaviour with confluent-kafka-go. I have setup Kafka with 3 partitions for a specific topic. I noticed that with a deployment I have a single consumer reading from the topic, but it is only receiving messages from a specific partition; and not the others.

I have, another, but with the same configuration Kafka broker, where a single consumer is reading from multiple partitions. Any ideas?

**Comment by edenhill** [comment]
You can get some insight into the fetcher workings by setting `"debug": "fetch"` in your consumer config.
