### ISSUE TITLE
Is specifying ReplicaAssignment compulsory when using the CreatePartitions API?

### ISSUE THREAD

**Issue by Mayuresh-Gharat** [confluentinc/confluent-kafka-go#695]
Description
===========
When using the kafka-topics.sh commandline script, specifying the `--partitions <NumParitions>` suffices to increase the partitions for the topic. We don't need to specify replica assignment. 
Whereas it seems like the `CreatePartitions ` API for the GO client makes it compulsory to specify the replica assignment. I wanted to understand why that is the case and correct me if I am wrong in my understanding.

**Comment by jliunyu** [comment]
Hi @Mayuresh-Gharat, thanks for asking. For the `CreatePartitions` API https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/adminapi.go#L663, `ReplicaAssignment` is optional: https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/adminapi.go#L109

**Comment by milindl** [comment]
Closing this as @jliunyu has answered the question, please reopen for further issues.
