### ISSUE TITLE
Possibility of linking librdkafka statically on MacOS arm64 machine (M1 macbook)

### ISSUE THREAD

**Issue by MuweiHe** [confluentinc/confluent-kafka-go#696]
Description
===========
I'm able to build from a darwin_amd64 machine for darwin_arm64, using the librdkafka copied from a M1 macbook and `-tags=dynamic`. But when I try replacing the librdkafka_darwin.a file in librdkafka_vendor with what I copied from M1 macbook and build without the dynamic tag, I got the following errors:
```
⨯ release failed after 8.84s error=failed to build for darwin_arm64: exit status 2: # github.com/confluentinc/confluent-kafka-go/kafka
Undefined symbols for architecture arm64:
  "_BIO_ctrl", referenced from:
      _rd_kafka_conf_set_ssl_cert in librdkafka_darwin.a(rdkafka_cert.o)
  "_BIO_free", referenced from:
      _rd_kafka_conf_set_ssl_cert in librdkafka_darwin.a(rdkafka_cert.o)
      _rd_kafka_ssl_ctx_init in librdkafka_darwin.a(rdkafka_ssl.o)
  "_BIO_new_mem_buf", referenced from:
      _rd_kafka_conf_set_ssl_cert in librdkafka_darwin.a(rdkafka_cert.o)
      _rd_kafka_ssl_ctx_init in librdkafka_darwin.a(rdkafka_ssl.o)
  "_CRYPTO_free", referenced from:
      _rd_kafka_transport_ssl_cert_verify_cb in librdkafka_darwin.a(rdkafka_ssl.o)
```
Not replacing the .a file (directly use the .a file for amd64) got different errors like
```
ld: warning: ignoring file ../../../go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.7.0/kafka/librdkafka_vendor/librdkafka_darwin.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_rd_kafka_AdminOptions_destroy", referenced from:
      __cgo_497ae96c6da8_Cfunc_rd_kafka_AdminOptions_destroy in _x003.o
     (maybe you meant: __cgo_497ae96c6da8_Cfunc_rd_kafka_AdminOptions_destroy)
```
I'm guessing that even replacing the .a file with the arm64 version, it's still calling underlying amd64 version of other packages (like crypto in openssl). Is there a way we can get librdkafka statically linked to ckgo on a arm64 machine?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Hi @MuweiHe , thanks for asking. We are looking into a fix for M1 support. If you have a workaround, I think it's better to use it for now.

**Comment by jliunyu** [comment]
Let's use https://github.com/confluentinc/confluent-kafka-go/issues/727 to track the status.
