### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by silverpark** [confluentinc/confluent-kafka-go#70]
I have a problem when I try to connect with broker kafka with localhost on port 9092 :
```
Failed to resolve '9c95dafd9323:9092': Name or service not known
```

I not understand why `localhost` is translated by `9c95dafd9323`, it not work but it's normal,

Can you help me please ?

Thank in advance

**Comment by edenhill** [comment]
The client will first connect using the brokers in `bootstrap.servers` and then query those brokers for the full list of brokers in the cluster, these are reported according to the broker's `advertised.listener` (which defaults to the hostname) and it is imperative that these hostnames are resolvable and reachable.

**Comment by kevinburke** [comment]
(FWIW, if anyone else is wondering why they are setting a different host in their configuration, but kafka is connecting to localhost, this was the answer for us - we weren't configuring advertised.listener)
