### ISSUE TITLE
关于 "confluent-kafka-go is not supported on Windows."

### ISSUE THREAD

**Issue by ZongzhiCui** [confluentinc/confluent-kafka-go#701]
Description
===========
关于confluent-kafka-go不支持Windows的讲法, 好像加入2个文件就可以支持了,希望确认下

How to reproduce
================
在对应位置增加文件
github.com/confluentinc/confluent-kafka-go/kafka/文件夹下 添加 build_windows.go 文件
github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/文件夹下 添加 librdkafka_window.a 文件
就可以在Windows系统下运行

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): confluent-kafka-go v1.7.0, librdkafka:代码库里对应的版本
 - [ ] Apache Kafka broker version: 未知
 - [ ] Client configuration: `ConfigMap{...}`
var kafkaconf = &kafka.ConfigMap{
		"api.version.request":       "true",
		"auto.offset.reset":         "latest",
		"heartbeat.interval.ms":     3000,
		"session.timeout.ms":        30000,
		"max.poll.interval.ms":      120000,
		"fetch.max.bytes":           1024000,
		"max.partition.fetch.bytes": 256000}
 - [ ] Operating system: Windows10
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by MuweiHe** [comment]
建议更新你的clone。repo里的librdkafka_vendor自带windows版本的库文件了。

**Comment by jliunyu** [comment]
Confluent-kafka-go supports windows from v1.7.0.
