### ISSUE TITLE
Invalid value "read_commited" for configuration property "isolation.level"

### ISSUE THREAD

**Issue by guotie** [confluentinc/confluent-kafka-go#707]
Description
===========

create consumer with `isolation.level` of `read_commited` failed:
```
error new kafka consumer: Invalid value \"read_commited\" for configuration property \"isolation.level\"
```

How to reproduce
================

```
	consumer, err := ka.NewConsumer(&ka.ConfigMap{
		"bootstrap.servers":          c.Addr,
		"group.id":                   c.Group,
		"enable.auto.commit":         c.AutoCommit,
		"queued.min.messages":        1000,
		"queued.max.messages.kbytes": 5120,
		"isolation.level":            "read_commited",
	})
	if err != nil {
		log.Error("error new kafka consumer: %v", err)
		return
	}
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
kafka: 3.0.0 (Commit:8cb0a5e9d3441962)

confluent-kafka-go: 1.5.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 Mac Os 12
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Check your spelling, it should be   read_committed

Den mån 15 nov. 2021 kl 10:20 skrev 铁哥 ***@***.***>:

**Comment by guotie** [comment]
Ok, thanks.
