### ISSUE TITLE
How to use StoreOffsets()? I should store the lasted message offset or the lasted message offset+1?

### ISSUE THREAD

**Issue by intfish123** [confluentinc/confluent-kafka-go#717]
Description
===========

How to use StoreOffsets()? I should store the lasted message offset or the lasted message offset+1?

**Comment by edenhill** [comment]
There's a StoreMessage() now that should use instead.

**Comment by intfish123** [comment]
There is not the StoreMessage() function in release v1.7.0.

**Comment by jliunyu** [comment]
Hi @intfish123 , it's released at v1.8.2: https://github.com/confluentinc/confluent-kafka-go/blob/master/CHANGELOG.md

**Comment by jliunyu** [comment]
Since this issue is resolved with v1.8.2, close this issue.
