### ISSUE TITLE
Hi, our kafka applications got disconnection errors during broker maintenance.

### ISSUE THREAD

**Issue by xin-au** [confluentinc/confluent-kafka-go#718]
Description
===========

Hi, we got a disconnections error during broker maintenance. The maintenance seems added brokers or bounce brokers one at a time. It seems other java apps looked fine. But Kafka go client apps started to throw disconnection errors and tried to reconnect, but it got refusing connection errors. Wondering is there any way to mitigate the issue? Could Kafka go client to connect multi brokers to switch a broker that is available?

**Comment by edenhill** [comment]
The Go client (or rather the underlying librdkafka client) will log unexpected disconnects, but will reconnect automatically, so you don't need to act on these logs.
You can disable them by setting `"log.connection.close": False` (but it is good keep them enabled for troubleshooting purposes).

**Comment by xin-au** [comment]
@edenhill , thanks for the info and details! Agreed that I should keep the log enabled.
Wondering is there any config for the client to switch to a different broker when a connection broke? 
We have a topic with 3 replicas, (I assume those replicas are distributed to different brokers (we have more than 3 brokers).)
So, if a broker is not available, will the client connect to another broker with replica data inside? Or is it something on the broker side?

**Comment by edenhill** [comment]
The client will automatically reconnect to other brokers as necessary. The application doesn't need to do anything.

**Comment by xin-au** [comment]
@edenhill , thanks for the info!

**Comment by VictorDenisov** [comment]
@edenhill Could you please clarify. When you say it logs this error message. What does it mean?
Where is this error logged? Does the operation succeed even if I receive an error from Produce operation?

**Comment by VictorDenisov** [comment]
This code reports errors when broker disappear. It reports connection close.
```
	consumer, err := ck.NewConsumer(&ck.ConfigMap{
		"bootstrap.servers":        "localhost:9092",
		"group.id":                 "test-confluent-consumer",
		"enable.auto.commit":       "false",
		"auto.offset.reset":        "earliest",
		"reconnect.backoff.ms":     50,
		"reconnect.backoff.max.ms": 60000,
		"log.connection.close":     false,
	})
	if err != nil {
		fmt.Printf("Failed to construct consumer: %v\n", err)
		return
	}
	consumer.Subscribe("test_topic", nil)
	for {
		msg, err := consumer.ReadMessage(5 * time.Second)
		if err != nil {
			fmt.Printf("Failed to read message: %v\n", err)
		} else {
			fmt.Printf("%v\n", string(msg.Value))
		}
	}
```
