### ISSUE TITLE
I deliberately wrote  the topic or groupId incorrectly, but no error is returned

### ISSUE THREAD

**Issue by intfish123** [confluentinc/confluent-kafka-go#719]
Description
===========
I deliberately wrote the topic or groupId wrong, but no error is returned, which is not expected

How to reproduce
================

PLEASE FILL THIS OUT

Checklist
=========

PLEASE FILL THIS OUT

Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
Hi @intfish123 , thanks for asking. Can you please share your code and the error logs?

**Comment by edenhill** [comment]
Please fill out the checklist; please provide config and try to reproduce this with `"debug": "cgrp,topic"` set in the configuration and provide us with the logs.

Thanks
