### ISSUE TITLE
Documentation server references invalid style sheet

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [confluentinc/confluent-kafka-go#723]
Description
===========

The documentation server at https://docs.confluent.io/platform/current/clients/confluent-kafka-go/index.html references style sheet
```
<link href="//golang.org/lib/godoc/style.css" rel="stylesheet" type="text/css"/>
```
which no longer seems to exist.

How to reproduce
================

1. Go to GitHub page at https://github.com/confluentinc/confluent-kafka-go
2. Click the hyperlink in the "See the API documentation for more information." sentence from the README.md file.
3. Observe the unstyled page.
4. View the page source.  Click the link to the above stylesheet and note that it is no longer valid.

**Comment by jliunyu** [comment]
Thanks for reporting this, I added it to your backlock.
