### ISSUE TITLE
log forwarding from AdminClient

### ISSUE THREAD

**Issue by nkostoulas** [confluentinc/confluent-kafka-go#725]
Would it make sense to allow log forwarding, similar to how it's done for Producer/Consumer APIs? 

What would be the impact of having multiple handles in the same client and both attempt to forward logs? It seems that now if an application creates both an `AdminClient` and a `Producer` and use the `Producer` to forward logs from `rdkafka` then logs from both handles will be accessible via `Logs()` on the client side.

**Comment by edenhill** [comment]
Yeah I think for this use-case you should instantiate a Producer instance with log forwarding and then create an AdminClient instance from that producer using NewAdminClientFromProducer().
