### ISSUE TITLE
GetMetadata incorrectly creates a topic when it doesn't exist, then causing CreateTopics to fail

### ISSUE THREAD

**Issue by marshmallory** [confluentinc/confluent-kafka-go#726]
Issues
===========
1. GetMetadata returns what appears to be a valid topic, but is not.
2. GetMetadata will eventually create the invalid topic, making it a real but still faulty topic.
3. Creation by way of GetMetadata never allows the appropriate specifications to be passed into the creation, further solidifying the faulty topic in the actual cluster.

Description
===========
GetMetadata returns a topic object, even if the topic does not exist, by creating an empty `TopicSpecification` with only a name [according to this workaround/issue.](https://github.com/confluentinc/confluent-kafka-go/issues/672#issuecomment-954036668)

GetMetadata function eventually calls `getRkt0` [in handle.go](https://github.com/confluentinc/confluent-kafka-go/blob/1d5067b0f4f88f4167cb66a78ab4c4f3ec3b5786/kafka/handle.go#L182), which creates an empty topic.

Since the topic eventually gets created, it makes the use of CreateTopics pointless.  Kafka cannot have more than one topic by a single name, and so we arrive at a conflict.

This is our current code:
[Kafka Shim Client](https://github.com/libertymutual/provider-kafka/blob/refactor/internal/clients/kafka/topic/topic.go)
[Kubernetes Provider](https://github.com/libertymutual/provider-kafka/blob/main/internal/clients/kafka/client.go)

How to reproduce
================
Running the following code where &name == "sample-topic"

```go
	_, err := client.GetMetadata(&name, false, 1000)
	if err != nil {
		return nil, errors.Wrap(err, "cannot get the topic")
	}
	return nil, nil
```
[Pulled from Kafka Shim Client](https://github.com/libertymutual/provider-kafka/blob/refactor/internal/clients/kafka/topic/topic.go)

Expected Behavior: 
`if topic exists by name`
Returns metadata about given topic (would be a variable, not a _)
`if topic does not exist by name`
Returns nil or an error

Actual Behavior:
1. `client.GetMetadata` request creates the topic with `ErrLeaderNotAvailable` error
2. `client.GetMetadata` request returns topic with no error because it creates a metadata object that is set to defaults except for the provided name (making it appear as though the topic has been created).
3. Creates the topic after a while with the default values.  This occurs when `client.Metadata` calls `getRkt0`, creating the non-existent topic with bad values.
4. Can only be determined to be "not created" if the [workaround](https://github.com/confluentinc/confluent-kafka-go/issues/672#issuecomment-954036668) is followed, but it will create the bad topic regardless so the workaround isn't effective.

Secondary Issue Created By GetMetadata Functionality
=========
The above behavior is problematic because when CreateTopics is called, it is not working because the topic is already created, without the values we expect.  If this is expected behavior, CreateTopics is not a useable function having called the Metadata first.  Instead, we would need to use an update function, and disregard the creation entirely.  That's not excellent.

The entire flow is as follows ->

Setup:
1. Provide a yaml file to K8s. 
2. Convert K8s yaml into `TopicSpecification` [Reference](https://pkg.go.dev/github.com/confluentinc/confluent-kafka-go/kafka@v1.7.0#TopicSpecification) in [this file](https://github.com/libertymutual/provider-kafka/blob/main/internal/clients/kafka/topic/topic.go)

Expected Behavior:
3. Check if topic exists via `GetMetadata`
4. If topic exists, do nothing.  Provide info back to Kubernetes stating that we're in sync.
5. If the topic does not exist, create it via `CreateTopics` by providing given `TopicSpecification`

Actual Behavior:
3. Check if topic exists via `GetMetadata` (causes the GetMetadata issue)
4. If the topic does not exist, create it (it "exists" because GetMetadata returns a faulty topic).
5. Creation fails.  Topic is created via the GetMetadata function instead, with out any of the given values aside from `name`

Further Notes
=========
There are potential workarounds here.  Two options:
1. Get all metadata for all topics, and iterate over it.
2. Try to create a topic to determine if the topic exists.

We're looking at using this on a minimum of 500 topics per cluster, so we're concerned performance would be a problem.  Additionally, since we're writing a K8s provider the functionality is that we're syncing K8s regularly with what exists on the Kafka cluster.  This happens on a reconciliation/observation loop, and so the calls need to be made on a regular interval (~2s, with timeouts.)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.7.0
 - [x] Apache Kafka broker version: 3.0.0 https://bitnami.com/stack/kafka/helm
 - [x] Client configuration: Default
 - [x] Operating system: K8s via MacOS
 - [x] Provide client logs: Logs show no errors.  Using Kaf cli to verify that the topic creation is valid.
 - [x] Provide broker log excerpts: Unable to retrieve
 - [x] Critical issue: Yes

**Comment by marshmallory** [comment]
Update: This issue on `GetMetadata` ONLY occurs when a name is included.  If a name is not included, we are able to pass through.  However, this breaks the GetMetadata functionality, since the GetMetadata is forcing creation of a topic without the TopicSpecification we have to give it.

**Comment by edenhill** [comment]
This is a bit weird because auto topic creation is disabled by default on the client for newer broker versions.
Can you reproduce this with `"debug": "feature,protocol,metadata,topic"` and provide the logs?

**Comment by marshmallory** [comment]
> This is a bit weird because auto topic creation is disabled by default on the client for newer broker versions. Can you reproduce this with `"debug": "conf,feature,protocol,metadata,topic"` and provide the logs?

I can, but I also think we found the issue.  The auto.create.topics.enable is set to true by default, at least when installing via helm.  Below is the command we're running for the install, which defaults to true:

`helm upgrade --install kafka-dev -n kafka-cluster bitnami/kafka --set auth.clientProtocol=sasl --set deleteTopicEnable=true --set autoCreateTopicsEnable=false --wait`

Now that it is disabled and I reran  the functionality works as expected. :)

I would like to discuss this issue further regardless.  It seems rough that you cannot create a topic with the data you expect due to it being created after calling GetMetadata() when this setting is involved.  Also, in terms of Kubernetes/Crossplane, this will absolutely not work with this setting set to true, unfortunately.  It would break the functionality 100%, and isn't something we can really code around.   We will have to state explicitly that if this setting is enabled, you can't use our provider.

Instead, GetMetadata creates this empty topic.  Did you want me to loop through that and provide logs?  I'll have to redo my cluster, so it may take me a bit.

**Comment by edenhill** [comment]
Even with enable.auto.create.topics=true on the broker the client shouldn't auto create topics unless configured with allow.auto.create.topics=true.
But.. and I think here lies the issue..  the default is false for the consumer and true for the producer..

**Comment by marshmallory** [comment]
Oh, maybe that's the case.  I am not well versed in Kafka, just using the libraries to write a K8s provider.

**Comment by edenhill** [comment]
The workaround should be to set `allow.auto.create.topics=false` on the producer.

**Comment by marshmallory** [comment]
For my purposes, would this affect the AdminClient?

**Comment by edenhill** [comment]
NewAdminClient() instantiates a producer underneath, so you need to pass `allow.auto.create.topics=false` as part of the ConfigMap.

**Comment by amanjain08** [comment]
Disable auto creation of topics while getting the metadata 

`adminClient, err = kafka.NewAdminClient(&kafka.ConfigMap{"bootstrap.servers": kafkaBootstrapServers, "allow.auto.create.topics": "false"})`
