### ISSUE TITLE
"consumer.Close()" gets stuck for 10 seconds with manually assigned partitions (due to "Unsubscribe()/Poll()")

### ISSUE THREAD

**Issue by sneko** [confluentinc/confluent-kafka-go#728]
Hi @edenhill ,

There are 2 ways I use a Kafka consumer:
1. with static partitions (I set them at init)
2. or dynamically thanks to `subscribeTopics()`

If for (2) I close the consumer (`consumer.Close()`), it returns almost instantly whereas with the (1) it gets stuck for 10 seconds.

I see that it comes from there:
https://github.com/confluentinc/confluent-kafka-go/blame/194896a278506e9ac36e48d54abd123f0dcb3800/kafka/consumer.go#L438

but I don't understand why the "Poll()" is so long since in a infinite loop. In major cases it will be done in a few ms and forcing waiting 10s seems overkilled.

After looking at other issues mentioning some "Close()" issue, I tried first to do:
```
.Unassign()
.Poll(1000)
.Close()
```

But unfortunately it's still the same.

Is there a way to reduce this duration? I may be doing something wrong hmmm?

Thank you,

**Comment by jliunyu** [comment]
This looks same issue with https://github.com/confluentinc/confluent-kafka-go/issues/661

**Comment by jliunyu** [comment]
Thank for reporting this @sneko , please tracking this issue with https://github.com/confluentinc/confluent-kafka-go/issues/661
