### ISSUE TITLE
Build fails on raspberry pi

### ISSUE THREAD

**Issue by kostrahb** [confluentinc/confluent-kafka-go#73]
I have raspberry pi with raspbian, installed go version 1.8.3 and librdkafka installed according to instructions (latest version from repository). After downloading this project I have tried to compile the producer channel example, but go complained about kafka/message.go file -- there are two errors on line 213.
kafka/message.go:213 constant 2147483648 overflows int
kafka/message.go:213 array bound is too large
Is it possible to be a bug?

**Comment by edenhill** [comment]
This looks like a 32-bit porting problem, you can try to decrease the shifts by one on line 212 and 213 like so and see if it fixes the problem:

```
copy((*[1 << 29]byte)(payload)[valueLen:allocLen], msg.Key)
keyp = unsafe.Pointer(&((*[1 << 30]byte)(payload)[valueLen]))
```

**Comment by kostrahb** [comment]
Probably, in any case, this update solved the compilation issue. Thank you very much.

**Comment by kunickiaj** [comment]
Is there any plan to actually patch the client to build OOTB on 32-bit ARM?

**Comment by edenhill** [comment]
We could use doozer.io for armhf builds.
