### ISSUE TITLE
Consumer error: Decompression (codec 0x2) of message at 75475171 of 2725 bytes failed: Local: Not implemented (<nil>)

### ISSUE THREAD

**Issue by natureLanguageQing** [confluentinc/confluent-kafka-go#730]
Description
===========

Consumer error: Decompression (codec 0x2) of message at 75475171 of 2725 bytes failed: Local: Not implemented (<nil>)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the checklist

**Comment by edenhill** [comment]
It seems like your version of librdkafka was not build with snappy support.
Please update to the latest version of librdkafka and rebuild it, it comes with snappy included.
Or use the prebuilt binaries for Go, make sure to use the latest version of the Go client for that.
If you still see a problem, please provide the confluent-kafka-go and librdkafka versions.
