### ISSUE TITLE
Feature Request: consumer custom partition assigner

### ISSUE THREAD

**Issue by niamster** [confluentinc/confluent-kafka-go#731]
Description
===========

Are there any plans to implement custom *consumer* assignor strategy (similar to what Sarama implements [here](https://pkg.go.dev/gopkg.in/Shopify/sarama.v1#BalanceStrategy))?
Are there any blockers?

How to reproduce
================

N/A

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): Any
 - [x] Apache Kafka broker version: N/A
 - [x] Client configuration: N/A
 - [x] Operating system:  N/A
 - [x] Provide client logs (with `"debug": ".."` as necessary):  N/A
 - [x] Provide broker log excerpts:  N/A
 - [ ] Critical issue

**Comment by edenhill** [comment]
There are no immediate such plans, and we typically recommend to use the builtin partitioners as much as possible since they are compatible with partitioners in other languages (e.g., murmur2_random is compatible with the default Apache Kafka java producer partitioner).

**Comment by niamster** [comment]
Hi @edenhill . Thank you for the prompt reply. In this card I'm talking about the consumer assigner, I'm sorry I was not clear (I will update the card description).
My use case: sometimes, due to the user data submission patters, the partitions are not equally balanced from the consumers point of view, and to achieve better load distribution I would like to have a custom partition assignment strategy based on custom heuristic (for example CPU load).

**Comment by edenhill** [comment]
Oh sorry, that's my bad.

We don't have any immediate plans for that either, it is a niche use-case and requires a lot of work both in librdkafka and confluent-kafka-go.

**Comment by niamster** [comment]
Ok, thanks for the confirmation!

**Comment by niamster** [comment]
Found a sibling https://github.com/edenhill/librdkafka/issues/2284
