### ISSUE TITLE
Exception on Lambda Environment: /lib64/libc.so.6: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by zbyrdh** [confluentinc/confluent-kafka-go#735]
Description
===========

Hello,

I have created a Lambda function that uses confluent-kafka client, all works fine in my local yet when I deploy app to AWS I get the following exception;

`/lib64/libc.so.6: version GLIBC_2.25 not found`

So my deployment is using `circleci/golang:1.15.8` container and below is the version inside container;

```

circleci@1f0b693c577a:/go$ ldd --version
ldd (Debian GLIBC 2.28-10) 2.28
```

Here is the config;

```
kafka.ConfigMap{
					"bootstrap.servers": SERVER,
					"sasl.mechanisms":   "PLAIN",
					"security.protocol": "SASL_SSL",
					"sasl.username":     KEY,
					"sasl.password":     SECRET}

```

How to reproduce
================
Use CircleCI container and deploy Lambda function to AWS

What I have tried so far
================
- I have installed librdkafka directly before building project, didnt work
- I have created custom docker container (very plain one) and installed everything separately, didnt work
- I have created custom docker container and used example (works on local) directly, didnt work
- I have created custom docker container with Alpine, worked on my local but not on AWS
- I am using package from Github, not from Gopkg.in

Only thing I havent try so far is I havent install GLIBC_2.25 explicitly which I think its a lot of effort considerin that what I am using here is bundle. So I want to make sure that I am not missing anything else before going any further

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Can't reproduce on that docker image:
```
circleci@f040fb297e19:/go/src/github.com/confluentinc/confluent-kafka-go/examples/go-kafkacat$ go run go-kafkacat.go produce --topic=test --broker 1.1.1.1 -X security.protocol=SASL_SSL -X sasl.mechanism=PLAIN -X sasl.username=a -X sasl.password=b
%4|1643900558.884|CONFWARN|rdkafka#producer-1| [thrd:app]: Configuration property session.timeout.ms is a consumer property and will be ignored by this producer instance
%4|1643900558.884|CONFWARN|rdkafka#producer-1| [thrd:app]: Configuration property produce.offset.report is deprecated: No longer used.
Created Producer rdkafka#producer-1, topic test [-1]
^C% Terminating on signal interrupt
% Flushing 0 message(s)
% Closing

...
circleci@f040fb297e19:/go/src/github.com/confluentinc/confluent-kafka-go/examples/go-kafkacat$ go run go-kafkacat.go produce --link-info --broker 0 --topic 0
librdkafka link information: static glibc_linux from librdkafka-static-bundle-v1.8.2.tgz
```



Are you trying to build with `-tags dynamic` instead of using the bundled librdkafka (default build)?

**Comment by zbyrdh** [comment]
@edenhill app is successfully being deployed to AWS, exception occurs when lambda has been triggered. 

And no, Im not using `-tags dynamic` , this is how I build

`GOARCH=amd64 GOOS=linux go build -o output_dir my_file`

**Comment by edenhill** [comment]
Works for me:
```
$ GOARCH=amd64 GOOS=linux go build -o output_dir go-kafkacat.go
$ output_dir/go-kafkacat produce --topic 0 --broker 0 --link-info
librdkafka link information: static glibc_linux from librdkafka-static-bundle-v1.8.2.tgz
```

**Comment by zbyrdh** [comment]
@edenhill can you please share the example that you made?

**Comment by edenhill** [comment]
I just build go-kafkacat (from confluent-kafka-go/examples/go-kafkacat directory) in the docker image you linked to.

**Comment by Venkat2382** [comment]
@zbyrdh i am facing the same issue. When you say packaged you mean you created and docker image and changed the km da type to image?

**Comment by zbyrdh** [comment]
Exactly

> @zbyrdh i am facing the same issue. When you say packaged you mean you created and docker image and changed the lambda type to image?

**Comment by utkarsh-mt** [comment]
@edenhill This needs to be reopened. I'm facing the exact issue at work. I'm building a project that uses the library, the build runs successfully, and a zip is created and pushed to AWS lambda. It fails during invocation, as @zbyrdh mentioned. Below are the steps this issue could be reproduced:

**main.go**
```
package main

import (
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/confluentinc/confluent-kafka-go/kafka"
)

func hello() (string, error) {
	c, _ := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers": "localhost",
		"group.id":          "myGroup",
		"auto.offset.reset": "earliest",
	})

	c.Close()
	return "Hello λ!", nil
}

func main() {
	// Make the handler available for Remote Procedure Call by AWS Lambda
	lambda.Start(hello)
}
```

**Dockerfile**
```
FROM golang:1.15.8

ADD . /app/

WORKDIR /app/

RUN go mod download

RUN GOOS=linux GOARCH=amd64 go build -o /app/main /app/main.go
```

1. Run docker build to create a container image:
`docker build --platform linux/amd64 -t test-lambda .`
2. Run the container:
`docker run -it test-lambda`
3. Copy the final build from inside the container to your local:
`docker cp <running_container_id>:/app/main .`
4. Create a zip that will be uploaded to lambda
`zip function.zip main`
5. Create a lambda on AWS Console, select the runtime as Go1.x, x86. Upload the zip, try invoking this lambda via the Test section. You'll see this error.
