### ISSUE TITLE
Unable to create kafka producer Configuration property "ssl.ca.location" not supported in this build

### ISSUE THREAD

**Issue by ICUMD** [confluentinc/confluent-kafka-go#736]
Description
===========
Hey Guys,

I am new to kafka and librdkafka. I am using this go library to build a **Kafka producer**, with security protocol as **SASL_SSL** and mechanism as **GSSAPI**(Kerberos). Since I need GSSAPI/Kerberos support, I installed the librdkafka using source build on target and build systems using:
```
git clone https://github.com/edenhill/librdkafka.git
cd librdkafka
./configure --prefix /usr
make
sudo make install
```
and made the build using "go build -tags=dynamic. However when I run the producer, I get the following error ***"Configuration property "ssl.ca.location" not supported in this build: OpenSSL not available at build time"***

It happens on configurations security.protocol=sasl_ssl & on ssl.ca.location.

Relevant output of ./configure
```
checking for libcrypto (by pkg-config)... ok
checking for libssl (by pkg-config)... ok
checking for libsasl2 (by pkg-config)... ok
```
Does anyone have any tips, what maybe causing it? What else can I try?

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.8.2
 - [ ] Apache Kafka broker version: NA
 - [ ] Client configuration: `ConfigMap{...}`
``` 
producer, err := kafka.NewProducer(&kafka.ConfigMap{
		"bootstrap.servers":       "10.57.124.132:9092,10.57.124.133:9092",
		"security.protocol":       "sasl_ssl",
		"sasl.mechanism":          "GSSAPI",
		"sasl.kerberos.keytab":    "userdev.key",
		"sasl.kerberos.principal": "userdev@ACC.AZ.DHS",
		"ssl.ca.location":         "/etc/ssl/certs/InternalROOTCA.crt",
		"request.timeout.ms": 3000,
		"acks":              "1",
	})
```
 - [ ] Operating system: Redhat

**Comment by edenhill** [comment]
That is weird indeed, can you do `grep WITH_SSL *` in the librdkafka top directory? Should say y and 1.

Also make sure you don't have a system installed librdkafka somewhere that interferes.

Try removing all ssl config from the ConfigMap but add `"debug": "all"` and see what version and features it reports on startup.

**Comment by ICUMD** [comment]
@edenhill I am sorry that was weird, maybe I did a silly mistake and missed out some step but I am not getting that error now. Regardless, Thanks for the response.
