### ISSUE TITLE
How to check if adminclient is connected to broker or not before checking the existence of topic.

### ISSUE THREAD

**Issue by amanjain08** [confluentinc/confluent-kafka-go#743]
Description
===========

I have created the admin client and check for the existence of topics, but before that I want to check wheather admin client is connected to the kafka-broker or not, kind of isConnected or isSessionClosed?

I am not able to find the method to check the current state.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.8.2
 - [ ] Client configuration: kafka.NewAdminClient(&kafka.ConfigMap{"bootstrap.servers": kafkaBootstrapServers, "allow.auto.create.topics": "false"})
 - [ ] Operating system: macos
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
"error":"Local: Broker transport failure","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nservice.CheckIfTopicsExist\n\t kafka_service.go:44\ncontroller/checkKafkaTopics\n\twebserver.go:139\ncontroller/StartWebServer.func4\n\twebserver.go:38\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2046\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.2/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2878\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1929"}

%3|1645616466.980|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 1ms in state CONNECT)
%3|1645616467.979|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1645616469.979|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1645616471.984|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 1ms in state CONNECT)
%3|1645616473.985|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT)
%3|1645616475.985|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)

**Comment by edenhill** [comment]
There's no such method, mainly because there is no simple answer to that question in a distributed system such as Kafka (https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down)

It is better to perform your op (admin API call) and handle the error there (typically Transport errors) instead, since that also covers the case where the client is first connected to the cluster but subsequently gets permanently disconnected while performing the admin operation.

**Comment by amanjain08** [comment]
Thanks.
