### ISSUE TITLE
Hi, what is the difference between "ack = 1" and write msg with the delivery channel?

### ISSUE THREAD

**Issue by xin-au** [confluentinc/confluent-kafka-go#745]
Description
===========
Hi, what is the difference between "ack = 1" and write msg with the delivery channel?
Ack = 1 means producer wait for one broker to send ack signal
But with the delivery channel, it is also waiting for a confirmation( same as ack? ) from brokers?

**Comment by xin-au** [comment]
Does `delivery channel` means exactly once?

**Comment by milindl** [comment]
'acks' refers to the acknowledgements received on the broker side.

delivery channel is on the client side when we get back the response from the server.

Here's the flow:
1. we send a produced message to the cluster
2. depending on the values of ack, the broker will wait for 0, 1 or all the brokers and then send back the produce response.
3. client sends the report on delivery channel

Hope that clears it up.
