### ISSUE TITLE
Manuall install reporting error on aarch64 instance.

### ISSUE THREAD

**Issue by nazar200** [confluentinc/confluent-kafka-go#749]
Description
===========

We are getting below error when we try to install the librdkafka on aarch64 instance.

bash-5.1# go get -u gopkg.in/confluentinc/confluent-kafka-go.v1/kafka
go: downloading gopkg.in/confluentinc/confluent-kafka-go.v1 v1.8.2
go: downloading github.com/confluentinc/confluent-kafka-go v1.8.2
# gopkg.in/confluentinc/confluent-kafka-go.v1/kafka
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/../../../../aarch64-alpine-linux-musl/bin/ld: go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.8.2/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_error.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/../../../../aarch64-alpine-linux-musl/bin/ld: go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.8.2/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_error.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/../../../../aarch64-alpine-linux-musl/bin/ld: go/pkg/mod/gopkg.in/confluentinc/confluent-kafka-go.v1@v1.8.2/kafka/librdkafka_vendor/librdkafka_glibc_linux.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
bash-5.1# go version
go version go1.17.4 linux/arm64
root@gravitonpoc:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

How to reproduce
================

We are testing on AWS Graviton instance.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jliunyu** [comment]
`We will transition to another CI provider soon, which will allow us to provide arm64 builds.`

Refer to :https://github.com/confluentinc/confluent-kafka-go/issues/576#issuecomment-1009766473

**Comment by milindl** [comment]
Closing this, as now arm64 builds are provided. Please reopen if issue persists in latest version.
