### ISSUE TITLE
ConfigEntryResult is missing IsDefault

### ISSUE THREAD

**Issue by MatthL-SwiftC** [confluentinc/confluent-kafka-go#750]
Description
===========

The documentation and source code specifies that `ConfigEntryResult.IsDefault` can be used to exclude topic default configurations when listing via `AdminClient.DescribeConfigs`, however `IsDefault` is missing from `ConfigEntryResult`. Furthermore, it is available in the Java library.

https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/adminapi.go#L829-L833
```
// DescribeConfigs retrieves configuration for cluster resources.
//
// The returned configuration includes default values, use
// ConfigEntryResult.IsDefault or ConfigEntryResult.Source to distinguish
// default values from manually configured settings.
```

https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/adminapi.go#L242-L259
```
// ConfigEntryResult contains the result of a single configuration entry from a
// DescribeConfigs request.
type ConfigEntryResult struct {
	// Name of configuration entry, e.g., topic configuration property name.
	Name string
	// Value of configuration entry.
	Value string
	// Source indicates the configuration source.
	Source ConfigSource
	// IsReadOnly indicates whether the configuration entry can be altered.
	IsReadOnly bool
	// IsSensitive indicates whether the configuration entry contains sensitive information, in which case the value will be unset.
	IsSensitive bool
	// IsSynonym indicates whether the configuration entry is a synonym for another configuration property.
	IsSynonym bool
	// Synonyms contains a map of configuration entries that are synonyms to this configuration entry.
	Synonyms map[string]ConfigEntryResult
}
```

How to reproduce
================

Nothing to reproduce.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): master
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: `ConfigMap{...}`: N/A
 - [ ] Operating system: N/A
 - [ ] Provide client logs (with `"debug": ".."` as necessary): N/A
 - [ ] Provide broker log excerpts: N/A
 - [ ] Critical issue: No

**Comment by jliunyu** [comment]
We are looking into it.
