### ISSUE TITLE
Failed to recover from Timed out OffsetCommitRequest in flight

### ISSUE THREAD

**Issue by eran-levy** [confluentinc/confluent-kafka-go#753]
Its a critical issue that we aren't sure how to resolve and it already happened few times, sometimes it happens just every few months.

Description
===========
we are using golang kafka sdk ([github.com/confluentinc/confluent-kafka-go](http://github.com/confluentinc/confluent-kafka-go) v1.8.2)
we have a service that suddenly stopped to consume (it was running with 6 consumer  pods on the group)
we scaled the consumer pods to 0 and than adding 1 by 1. with 1 pod it is consuming. when adding another pod it stop consuming. It happens when the lag is getting huge after its stuck and getting these errors on startup right after starting to consume:

{"level":"error","ts":"2022-03-21T06:48:58.467Z","Message":"[thrd:main]: Consumer group session timed out (in join-state steady) after 10000 ms without a successful response from the group coordinator (broker 1, last error was Success): revoking assignment and rejoining group","Tag":"SESSTMOUT"}

{"level":"error","ts":"2022-03-21T06:49:01.472Z","code":"Local: Timed out","err":"GroupCoordinator: kafka1:9092: 1 request(s) timed out: disconnect (after 37671622ms in state UP)"}

{"level":"error","ts":"2022-03-21T06:49:01.472Z","Message":"[thrd:GroupCoordinator]: GroupCoordinator/1: Timed out HeartbeatRequest in flight (after 10005ms, timeout #0)","Tag":"REQTMOUT"}

{"level":"error","ts":"2022-03-21T06:49:02.522Z","Message":"[thrd:GroupCoordinator]: GroupCoordinator/1: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests","Tag":"REQTMOUT"}

{"level":"error","ts":"2022-03-21T06:49:29.895Z","msg":"Failed to commit offset: Local: Waiting for coordinator"}

{"level":"error","ts":"2022-03-21T06:49:50.117Z","Message":"[thrd:kafka1:9092/bootstrap]: kafka1:9092/3: Timed out FetchRequest in flight (after 60907ms, timeout #0)","Tag":"REQTMOUT"}

{"level":"error","ts":"2022-03-21T06:49:50.608Z","Message":"[thrd:kafka2:9092/bootstrap]: kafka2:9092/2: Timed out FetchRequest in flight (after 61434ms, timeout #0)","Tag":"REQTMOUT"}

{"level":"error","ts":"2022-03-21T06:49:50.526Z","Message":"[thrd:kafka1:9092/bootstrap]: kafka1:9092/1: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests","Tag":"REQTMOUT"}

{"level":"error","ts":"2022-03-21T06:50:51.222Z","Message":"[thrd:GroupCoordinator]: GroupCoordinator/1: Timed out OffsetCommitRequest in flight (after 60101ms, timeout #0): possibly held back by preceeding blocking JoinGroupRequest with timeout in 242897ms","Tag":"REQTMOUT"}

Im not sure why it happened - can it happen that the business logic stuck, no heartbeat poll events, pass the session timeout without consuming and thats why its getting stuck with the above logs of "Timed out OffsetCommitRequest in flight" ?

Any other things that we should look for? 

How to reproduce
================
it happened 3 weeks ago as well but its not reproduce-able, we arent sure how to reproduce it. its a very strange behaviour. 

We didnt see anything special in the kafka broker logs - no under replicated partitions, all of our other services that using the same lib and config consumed well. 

ConfigMap:
	"bootstrap.servers":      ...,
		"client.id":              ...,
		"session.timeout.ms":  45000  ,
		"heartbeat.interval.ms":  3000, 
		"socket.timeout.ms":      45000,     
		"group.id":               ...,
		"auto.offset.reset":      "latest",
		"enable.partition.eof":   true,
		"enable.auto.commit":     false,
		"go.logs.channel.enable": true,
		"go.logs.channel":        chLogEvent,
 
- [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.8.2
 - [x] Apache Kafka broker version: 2.6.0
 - [x] Client configuration: `ConfigMap{...}` - see config map above under ConfigMap
 - [x] Operating system: golang:1.17.2-alpine3.14
 - [x] Provide client logs (with `"debug": ".."` as necessary): debug all attached below
 - [x] Provide broker log excerpts: kafka brokers attached below
 - [x] Critical issue

**Comment by jliunyu** [comment]
Can you please fill up the above checklist and also enable the debug log(Add "debug": "all") to your Config?

**Comment by eran-levy** [comment]
[consumers.log](https://github.com/confluentinc/confluent-kafka-go/files/8374872/consumers.log)

**Comment by eran-levy** [comment]
closing and created another issue here - https://github.com/edenhill/librdkafka/issues/3790
