### ISSUE TITLE
when consume  from aphine pod in k8s  the error  Host resolution failure occurs

### ISSUE THREAD

**Issue by ucanme** [confluentinc/confluent-kafka-go#754]
Description
===========
when i consume from alpine pod in k8s this error happens:

Local: Host resolution failure: sasl_plaintext://[kafkahost.com:9092/bootstrap](http://kafkahost:9092/bootstrap): Failed to resolve '[kafkahost:9092](http://kafkahost.com:9092/)': Bad address (after 0ms in state CONNECT, 12 identical error(s) suppressed)

the base image:
`FROM golang:1.13

FROM alpine:latest

RUN apk --no-cache add ca-certificates
RUN apk add busybox-extras curl wget curl
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

COPY --from=0 /usr/local/go/lib/time/zoneinfo.zip /opt/zoneinfo.zip

ENV ZONEINFO /opt/zoneinfo.zip`

run my code in this base image

kafka configmap
`kafka.ConfigMap{
		"bootstrap.servers": strings.Join(kafkaConf.Addr, ","),
		// Avoid connecting to IPv6 brokers:
		// This is needed for the ErrAllBrokersDown show-case below
		// when using localhost brokers on OSX, since the OSX resolver
		// will return the IPv6 addresses first.
		// You typically don't need to specify this configuration property.
		"broker.address.family": "v4",
		"group.id":              kafkaConf.GroupId,
		"session.timeout.ms":    6000,
		"auto.offset.reset":     "earliest",
		"sasl.mechanisms":       "PLAIN",
		"security.protocol":     "SASL_PLAINTEXT",
		//"max.poll.records":      1,
		"max.poll.interval.ms": "400000",
		"sasl.username":        kafkaConf.User,
		"sasl.password":        kafkaConf.Password,
	}` 

How to reproduce
================

consume  from aphine pod in k8s 

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://rmoff.net/2018/08/02/kafka-listeners-explained/
