### ISSUE TITLE
Add support for the topic admin APIs

### ISSUE THREAD

**Issue by dasch** [confluentinc/confluent-kafka-go#76]
I'd like to start work on a [Terraform](https://www.terraform.io/) provider for Kafka (unless you're already planning on doing that yourselves) that can give me a way to declaratively define topics and their configurations, but I'd need to use the new Kafka 0.11 APIs for creating, modifying and deleting topics. Is this something you plan to support in the Go library?

**Comment by edenhill** [comment]
Yes, Topic admin APIs are on the backlog (but not yet scheduled).
It will first need to be implemented in librdkafka, tracking issue here: https://github.com/edenhill/librdkafka/issues/986

**Comment by ewoutp** [comment]
Seems to be in librdkafka now. Any updates?

**Comment by edenhill** [comment]
It is not yet in librdkafka, unfortunately.
We're aiming for Q1 for both librdkafka and Go (and Python)

**Comment by ewoutp** [comment]
thx for the feedback

**Comment by edenhill** [comment]
Topic Admin API is now available for preview in the adminapi branch and this PR:
https://github.com/confluentinc/confluent-kafka-go/pull/173

Feedback welcome!

**Comment by ldrrp** [comment]
Any updates on when this will be on master? Does it just need testing?

**Comment by ldrrp** [comment]
I don't see an adminapi branch is why im asking.

**Comment by rnpridgeon** [comment]
Closing since thie has now been merged: 

https://github.com/confluentinc/confluent-kafka-go/commit/b2918d4d9d4f29ca4e92431325dcff49c4afe61a
