### ISSUE TITLE
同一个进程中，不同goroutine 使用同一个 consumer group id 消费不同的topic 卡死

### ISSUE THREAD

**Issue by xiazemin** [confluentinc/confluent-kafka-go#771]
Description
===========

goroutine1    group_id  topic1
 goroutine2    group_id  topic2
goroutine3   group_id  topic3

How to reproduce
================

当goroutine2 卡住的时候，goroutine3也被卡住

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
google translate tells me:
> In the same process, different goroutines use the same consumer group id to consume different topics and get stuck

you'll need to provide code / more information.

note that in most cases you wouldn't use the same group.id to consume from different topics.
