### ISSUE TITLE
can't running in Mac OSX M1 System!

### ISSUE THREAD

**Issue by smarttang** [confluentinc/confluent-kafka-go#773]
Description
===========

# github.com/confluentinc/confluent-kafka-go/kafka
ld: warning: ignoring file ../../../go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/librdkafka_vendor/librdkafka_darwin.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_rd_kafka_AdminOptions_destroy", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_destroy in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_destroy)
  "_rd_kafka_AdminOptions_new", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_new in _x004.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_new)
  "_rd_kafka_AdminOptions_set_operation_timeout", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_set_operation_timeout in _x004.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_set_operation_timeout)
  "_rd_kafka_AdminOptions_set_request_timeout", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_set_request_timeout in _x004.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_set_request_timeout)
  "_rd_kafka_AdminOptions_set_validate_only", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_set_validate_only in _x004.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_AdminOptions_set_validate_only)
  "_rd_kafka_AlterConfigs", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_AlterConfigs in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_AlterConfigs_result_resources, __cgo_a0f51a566a6d_Cfunc_rd_kafka_AlterConfigs )
  "_rd_kafka_AlterConfigs_result_resources", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_AlterConfigs_result_resources in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_AlterConfigs_result_resources)
  "_rd_kafka_ConfigEntry_is_read_only", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_is_read_only in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_is_read_only)
  "_rd_kafka_ConfigEntry_is_sensitive", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_is_sensitive in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_is_sensitive)
  "_rd_kafka_ConfigEntry_is_synonym", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_is_synonym in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_is_synonym)
  "_rd_kafka_ConfigEntry_name", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_name in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_name)
  "_rd_kafka_ConfigEntry_source", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_source in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_source)
  "_rd_kafka_ConfigEntry_synonyms", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_synonyms in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_synonyms)
  "_rd_kafka_ConfigEntry_value", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_value in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigEntry_value)
  "_rd_kafka_ConfigResource_configs", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_configs in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_configs)
  "_rd_kafka_ConfigResource_destroy", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_destroy in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_destroy)
  "_rd_kafka_ConfigResource_error", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_error in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_error, __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_error_string )
  "_rd_kafka_ConfigResource_error_string", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_error_string in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_error_string)
  "_rd_kafka_ConfigResource_name", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_name in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_name)
  "_rd_kafka_ConfigResource_new", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_new in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_new)
  "_rd_kafka_ConfigResource_set_config", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_set_config in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_set_config)
  "_rd_kafka_ConfigResource_type", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_type in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigResource_type)
  "_rd_kafka_ConfigSource_name", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigSource_name in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ConfigSource_name)
  "_rd_kafka_CreatePartitions", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreatePartitions in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreatePartitions_result_topics, __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreatePartitions )
  "_rd_kafka_CreatePartitions_result_topics", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreatePartitions_result_topics in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreatePartitions_result_topics)
  "_rd_kafka_CreateTopics", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreateTopics in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreateTopics_result_topics, __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreateTopics )
  "_rd_kafka_CreateTopics_result_topics", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreateTopics_result_topics in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_CreateTopics_result_topics)
  "_rd_kafka_DeleteTopic_destroy", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_DeleteTopic_destroy in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_DeleteTopic_destroy)
  "_rd_kafka_DeleteTopic_new", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_DeleteTopic_new in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_DeleteTopic_new)
  "_rd_kafka_DeleteTopics", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_DeleteTopics in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_DeleteTopics_result_topics, __cgo_a0f51a566a6d_Cfunc_rd_kafka_DeleteTopics )
  "_rd_kafka_DeleteTopics_result_topics", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_DeleteTopics_result_topics in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_DeleteTopics_result_topics)
  "_rd_kafka_DescribeConfigs", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_DescribeConfigs in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_DescribeConfigs_result_resources, __cgo_a0f51a566a6d_Cfunc_rd_kafka_DescribeConfigs )
  "_rd_kafka_DescribeConfigs_result_resources", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_DescribeConfigs_result_resources in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_DescribeConfigs_result_resources)
  "_rd_kafka_NewPartitions_destroy", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewPartitions_destroy in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewPartitions_destroy)
  "_rd_kafka_NewPartitions_new", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewPartitions_new in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewPartitions_new)
  "_rd_kafka_NewPartitions_set_replica_assignment", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewPartitions_set_replica_assignment in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewPartitions_set_replica_assignment)
  "_rd_kafka_NewTopic_destroy", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewTopic_destroy in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewTopic_destroy)
  "_rd_kafka_NewTopic_new", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewTopic_new in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewTopic_new)
  "_rd_kafka_NewTopic_set_config", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewTopic_set_config in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewTopic_set_config)
  "_rd_kafka_NewTopic_set_replica_assignment", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewTopic_set_replica_assignment in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_NewTopic_set_replica_assignment)
  "_rd_kafka_ResourceType_name", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_ResourceType_name in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_ResourceType_name)
  "_rd_kafka_abort_transaction", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_abort_transaction in _x020.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_abort_transaction)
  "_rd_kafka_assign", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_assign in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_assignment_lost, __cgo_a0f51a566a6d_Cfunc_rd_kafka_assignment , __cgo_a0f51a566a6d_Cfunc_rd_kafka_assign )
  "_rd_kafka_assignment", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_assignment in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_assignment_lost, __cgo_a0f51a566a6d_Cfunc_rd_kafka_assignment )
  "_rd_kafka_assignment_lost", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_assignment_lost in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_assignment_lost)
  "_rd_kafka_begin_transaction", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_begin_transaction in _x020.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_begin_transaction)
  "_rd_kafka_clusterid", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_clusterid in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_clusterid)
  "_rd_kafka_commit_queue", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_commit_queue in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_commit_queue)
  "_rd_kafka_commit_transaction", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_commit_transaction in _x020.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_commit_transaction)
  "_rd_kafka_committed", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_committed in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_committed)
  "_rd_kafka_conf_destroy", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_destroy in _x006.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_destroy)
  "_rd_kafka_conf_new", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_new in _x006.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_new)
  "_rd_kafka_conf_set", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_set in _x006.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_set, __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_set_default_topic_conf , __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_set_events )
  "_rd_kafka_conf_set_default_topic_conf", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_set_default_topic_conf in _x006.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_set_default_topic_conf)
  "_rd_kafka_conf_set_events", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_set_events in _x003.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_conf_set_events)
  "_rd_kafka_consumer_close", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_close in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_close)
  "_rd_kafka_consumer_group_metadata", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata, __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_read , __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_destroy , __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_write , __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_new )
  "_rd_kafka_consumer_group_metadata_destroy", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_destroy in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_destroy)
  "_rd_kafka_consumer_group_metadata_new", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_new in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_new)
  "_rd_kafka_consumer_group_metadata_read", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_read in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_read)
  "_rd_kafka_consumer_group_metadata_write", referenced from:
      __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_write in _x007.o
     (maybe you meant: __cgo_a0f51a566a6d_Cfunc_rd_kafka_consumer_group_metadata_write)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by OneCricketeer** [comment]
Duplicate #591

**Comment by smarttang** [comment]
use another one package finish my work.
