### ISSUE TITLE
Add Committed() API

### ISSUE THREAD

**Issue by holgerw** [confluentinc/confluent-kafka-go#78]
I am trying to combine enable.auto.commit with a manual rewind of the offset on partition assignment. This is my strategy to reprocess any messages that might have been in transit in my application (not yet completely processed), when the application crashes.

The problem is, when the consumer connects, and "kafka.AssignedPartitions" fires, the received TopicPartitions always have **Offset "unset"**. So I am not able to adjust the Offset before starting consumption.

Is there a proper way to start consuming messages at a position "Offset - delta"?

```go
func main() {
  loop = true
  for loop {
    select {
    case <-sigchan:
      loop = false
    case ev := <-consumer.Events():
      switch e := ev.(type) {
      case kafka.AssignedPartitions:
        log.Infof("Assigned %v", e.Partitions)
        rewindOffset(e.Partitions)
        log.Infof("Rewound %v", e.Partitions)
        consumer.Assign(e.Partitions)
      case kafka.RevokedPartitions:
        log.Infof("Revoked %v", ev)
        consumer.Unassign()
      case *kafka.Message:
        out <- processMsg(e.Value)
      case kafka.PartitionEOF:
        log.Infof("Reached %v", ev)
      case kafka.Error:
        log.Infof("Error: %v", ev)
      case kafka.OffsetsCommitted:
        log.Infof("Commited %v", ev)
      }
    }
  }
  consumer.Close()
}

func rewindOffset(partitions []kafka.TopicPartition) {
  for _, p := range partitions {
    var saveOffset kafka.Offset
    if p.Offset < pipelineBufferLength {
      saveOffset, _ = kafka.NewOffset("earliest")
    } else {
      saveOffset, _ = kafka.NewOffset(p.Offset - pipelineBufferLength)
    }
    p.Offset = saveOffset
  }
}
```

**Comment by holgerw** [comment]
Is it possible that some misconfiguration causes **kafka.AssignedPartitions** to always deliver the Offset value "unset"? 

I observe the following sequence of logs, that makes me think the **kafka.AssignedPartitions** event does not pick up the real Offset commited before:

```raw
INFO[0005] Commited OffsetsCommitted (<nil>, [sara[0]@9711 sara[1]@unset])
INFO[0005] Commited OffsetsCommitted (<nil>, [sara[0]@9713 sara[1]@unset])
INFO[0005] Revoked RevokedPartitions: [sara[0]@beginning sara[1]@beginning]
INFO[0005] Assigned [sara[0]@unset]
INFO[0005] Rewound [sara[0]@beginning]
INFO[0009] Commited OffsetsCommitted (<nil>, [sara[0]@9969])
INFO[0010] Commited OffsetsCommitted (<nil>, [sara[0]@13003])
```

The revocation was triggered by another consumer joining the consumer group. "consumer.Assign(e.Partitions)" happens with offset=beginning (after the log line "Rewound..").

2 thinks stand out:

1) **kafka.AssignedPartitions** event does not deliver the most recently commited Offset.

2) Somehow consumption goes on from the latest commit, even partition assigning was done with the value "beginning".

(As context, the consumer is configured with "default.topic.config=earliest".)

**Comment by edenhill** [comment]
> Is it possible that some misconfiguration causes kafka.AssignedPartitions to always deliver the Offset value "unset"?

The starting offset is not yet known at the time the Assignment event is triggered.
The Go bindings are currently missing the `Committed()` API to retrieve the committed offset, but when it is made available you can call Committed() when you receive the new assignment, rewind those offsets accordingly, and then provide the TopicPartitions with the offset manually set to start consuming off that position.

**Comment by edenhill** [comment]
Now on master
