### ISSUE TITLE
OAuth token refresh issue

### ISSUE THREAD

**Issue by nkostoulas** [confluentinc/confluent-kafka-go#782]
Description
===========
I'm creating a Consumer client that uses OAUTHBEARER but never get an OAuthBearerTokenRefresh event when Polling. I've tried the same thing with Producer/Admin client and listenting to the Events() channel. 

I have the following config:
```
confluentConfig.SetKey("security.protocol", "sasl_ssl")
confluentConfig.SetKey("sasl.mechanism", "OAUTHBEARER")
```

I asume an Ory Hydra server and a token provider with client credentials. I initially get the Token and set that using `SetOAuthBearerToken`, which works fine since I can consume messages (and do admin operations). I've checked that the Token returned expires after one hour and this is the value I set to `OAuthBearerToken` passed as well. 

After 1 hour passes I can still consume but never receive a Refresh event.

I noticed I had not set `sasl.oauthbearer.config`, on which I now only set the `principal` to the same value as the `Principal` in `OAuthBearerToken`. Hopefully that will fix this but still how does the token work even after having expired?

**Comment by nkostoulas** [comment]
I was matching for `*confluentKafka.OAuthBearerTokenRefresh` not `confluentKafka.OAuthBearerTokenRefresh`...

**Comment by dixontan14** [comment]
Hi. @nkostoulas i am facing a similar issue as you but have yet to find any workaround. 

Do you mind showing what is your implementation on this event - confluentKafka.OAuthBearerTokenRefresh?

**Comment by nkostoulas** [comment]
I use `Poll` and then check that the event type received is `confluentKafka.OAuthBearerTokenRefresh`.

**Comment by dixontan14** [comment]
do you mean by if the event is `confluentKafka.OAuthBearerTokenRefresh`, the action you would do is create token and `consumer. SetOAuthBearerToken` again?


I am using [aws-msk-signer](https://github.com/aws/aws-msk-iam-sasl-signer-go) to generate the oauth token for confluent kafka client. 

And I have a function to create token 
```
func createToken() (confluentkafka.OAuthBearerToken, error) {
	token, tokenExpirationTimeMs, err := signer.GenerateAuthToken(context.Background(), "us-east-1")
	if err != nil {
		return confluentkafka.OAuthBearerToken{}, err
	}

	seconds := tokenExpirationTimeMs / 1000
	nanoseconds := (tokenExpirationTimeMs % 1000) * 1000000
	bearerToken := confluentkafka.OAuthBearerToken{
		TokenValue: token,
		Expiration: time.Unix(seconds, nanoseconds),
	}

	return bearerToken, nil
}
```
So would the implementation be like this? 

```
ev := consumer.Poll(100)
if ev == nil {
continue
}


switch e := ev.(type) {
			case *confluentkafka.Message:
				// do your processing
			case confluentkafka.Error:
				// Handle error
			case confluentkafka.OAuthBearerTokenRefresh:
				log.Info().Msg("Received token refresh event.")
				token, err := createToken()
				if err != nil {
					return
				}

				if err := consumer.SetOAuthBearerToken(token); err != nil {
					return
				}
			}
```

**Comment by nkostoulas** [comment]
Correct you need to use `SetOAuthBearerToken`. If for any reason there is a failure though you should use `SetOAuthBearerTokenFailure` instead. I believe this will re-trigger the event. 

You also need to use `SetOAuthBearerToken` when you first set up your consumer before calling `Poll`.

**Comment by dixontan14** [comment]
got it! let me try and let you know the result. In the meantime, if you have any pseudocode that can show me your implementation, that would be great 😄 

thanks @nkostoulas

**Comment by dixontan14** [comment]
@nkostoulas do you also mind sharing the `configMap` you have for your confluent kafka client?

Mine looked something like this
```
configMap := &confluentkafka.ConfigMap{
		"bootstrap.servers":  config.KafkaBootstrapServers,
		"group.id":           config.KafkaGroupID,
		"security.protocol":  "SASL_SSL",
		"sasl.mechanism":     "OAUTHBEARER",
		"auto.offset.reset":  "latest",
		"enable.auto.commit": true,
		"session.timeout.ms": 60000,
	}
``` 

I did not set `sasl.oauthbearer.config`. Does it matter if I do not set it?

**Comment by nkostoulas** [comment]
I noticed we set `security.protocol` to lower-case but otherwise looks okay. Are you getting any errors?
