### ISSUE TITLE
v0.11.0 tag

### ISSUE THREAD

**Issue by charkost** [confluentinc/confluent-kafka-go#79]
Hello, 

Do you have any plan for a v0.11.0 tag in the near future? 
librdkafka v0.11.0 is now part of debian unstable and we would like to upgrade the go client package too. 
We rely on upstream tags for pulling changes & package versioning. 

Thanks in advance!

**Comment by edenhill** [comment]
Imminent!

**Comment by charkost** [comment]
thanks :)
