### ISSUE TITLE
Running Go app on ARM64 arch. fails with: `error while loading shared libraries: librdkafka.so.1: cannot open shared object file`

### ISSUE THREAD

**Issue by mohitreddy1996** [confluentinc/confluent-kafka-go#791]
Description
===========
We are trying to build and run our Go server using Docker on linux/arm64 platform.

Since this is an ARM64 platform, AFAIU, librdkafka is not prebuilt with the go client (https://github.com/confluentinc/confluent-kafka-go#librdkafka).

We tried installing `librdkafka-dev` and tried building the binary with `-tags dynamic`, but it failed with: 

```
#18 17.23 # github.com/confluentinc/confluent-kafka-go/kafka
#18 17.23 /go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.8.2/kafka/generated_errors.go:138:46: could not determine kind of name for C.RD_KAFKA_RESP_ERR__AUTO_OFFSET_RESET
------
executor failed running [/bin/sh -c go build -tags dynamic -o server path/to/binary]: exit code: 2
```

Docker file (platform is passed as linux/arm64 as the build-arg):
```
ARG platform

FROM --platform=$platform golang:1.18-bullseye AS builder
RUN apt-get update
RUN apt-get install -y librdkafka-dev:arm64
RUN go build -tags dynamic -o server path/to/binary
```

So we tried building librdkafka from the source. Docker file:
```
ARG platform

FROM --platform=$platform golang:1.18-bullseye AS builder

WORKDIR /kafka
RUN git clone https://github.com/edenhill/librdkafka.git
WORKDIR /kafka/librdkafka
RUN ./configure
WORKDIR /kafka/librdkafka
RUN make
WORKDIR /kafka/librdkafka
RUN make install
WORKDIR /kafka/librdkafka

WORKDIR /app
COPY appcode/ ./
WORKDIR /app/appcode
RUN go build -tags dynamic -o server path/to/app

FROM --platform=$platform golang:1.18-bullseye
WORKDIR /root/
COPY --from=builder /app/appcode/path/to/app ./
CMD ["./server"]
```

Here the build passes, but running the container fails with:
```
./server: error while loading shared libraries: librdkafka.so.1: cannot open shared object file: No such file or directory
```

Is it related to dynamic linking? Not sure which generated binary file should be linked?

How to reproduce
================
Documented above

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): librdkafka from HEAD
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: `ConfigMap{...}`: Fails on setup
 - [ ] Operating system: linux/arm64
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue: yes, blocks our path to production

**Comment by mohitreddy1996** [comment]
Closing this, we were able to resolve this.

The dockerfile is incorrect (installing librdkakfa and building/running our program should be in the same multi-build step).

Secondly, we had to link the librdkafka installed - 

```
RUN touch /etc/ld.so.conf.d/librdkafka.conf
RUN echo /usr/local/lib >> /etc/ld.so.conf.d/librdkafka.conf
```

**Comment by niels-s** [comment]
FYI: you need to run `ldconfig` after those commands too. See https://github.com/edenhill/librdkafka/issues/466#issuecomment-166417304 otherwise it won't work
