### ISSUE TITLE
Dealing gracefully with ErrQueueFull

### ISSUE THREAD

**Issue by jimrobinson** [confluentinc/confluent-kafka-go#80]
When one calls the kafka.Producer's Produce method the error ErrQueueFull is returned if the internal queue is full.

This is reasonable enough behavior as it gives the caller a chance to decide what they want to do, bail or wait for a slot to be freed.  But I'm not sure what the best method is for dealing with the error if we want to try blocking until the message can make its way to the internal queue.

Is it intended that the client should actively attempt to produce the message, and on ErrQueueFull take alternative action such as flushing and then retrying the Produce, in a loop, until either it succeeds or it hits whatever retry/time limits one cares to impose?

Is there a better solution available via the API that I'm overlooking?

```
func (p *Producer) PartitionSend(topic string, part int32, key string, value []byte) *Future {
	f := newFuture(topic, part, []byte(key), value)
	select {
	case <-p.done:
		f.err <- ErrProducerClosed
	default:
		err := p.client.Produce(f.msg, f.ch)

		// on kafka.ErrQueueFull, attempt to flush and resend
		for i := 0; i < maxDrainAttempts; i++ {
			kerr, ok := err.(kafka.Error)
			if ok && kerr.Code() == kafka.ErrQueueFull {
				// wait up to 1ms per pending message before retrying
				p.client.Flush(p.client.Len())
				err = p.client.Produce(f.msg, f.ch)
			} else {
				break
			}
		}

		// if an err is set at this point, return it to the caller
		if err != nil {
			if warnFn, warnOk := trace.M(traceId, trace.Warn); warnOk {
				trace.T(warnFn, "kovka.Producer unable to send message: %v", err)
			}
			f.err <- err
		}
	}
	return f
}
```

**Comment by alphazero** [comment]
@jimrobinson Flush and retry works.

**Comment by edenhill** [comment]
You can also use the channel based Producer that does this for you, just make sure to read delivery reports from the p.Events() channel (as delivery reports are counted as messages too).
Example here: 
https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/producer_channel_example/producer_channel_example.go

**Comment by edenhill** [comment]
The `Message.Opaque` field is meant for this, it allows you to attach any object of your liking to a message and you'll receive the same .Opaque in the delivery report.
There's also the per-message delivery report channel.

**Comment by jimrobinson** [comment]
Ahh, thank you very much for that pointer!
