### ISSUE TITLE
Unreachable code in README docs

### ISSUE THREAD

**Issue by snosratiershad** [confluentinc/confluent-kafka-go#806]
Description
===========
In "High-level balanced consumer" part of "Examples" section of README file, it's impossible to reach `c.Close` method because for loop doesn't have any conditions and will run for ever.

How to reproduce
================
I think it can be proved by linting code with `go vet` and `staticcheck`.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
thanks for pointing this out!

**Comment by milindl** [comment]
Closed with #846
