### ISSUE TITLE
kafka send fail:Local: Queue full

### ISSUE THREAD

**Issue by ucanme** [confluentinc/confluent-kafka-go#807]
Description
===========
the error "kafka send fail:Local: Queue full" occurs where i async produce msg.
go-confluent-kafka 1.9.0 on mac.

How to reproduce
================
send many message.

i don't know how to solve it.is there anyone who can help me

**Comment by mhowlett** [comment]
have you confirmed the messages getting to the broker? are you producing at high throughput? (if so you might want to tune `queue.buffering.max.messages/kbytes` up). are you reading delivery reports?

**Comment by huantt** [comment]
1. You can produce messages synchronously. But it's a bad idea since it decreases throughput.
2. You can Flush all pending message then retry to produce the new one.
```golang
func (k *Producer) PublishMessage(ctx context.Context, key string, payload interface{}, topic string, headers map[string]string) error {
	value, err := json.Marshal(payload)
	if err != nil {
		return err
	}

	message := &confluentKafka.Message{
		Value: value,
		Key:   []byte(key),
		TopicPartition: confluentKafka.TopicPartition{
			Topic:     &topic,
			Partition: confluentKafka.PartitionAny,
		},
	}
	if len(headers) > 0 {
		var kafkaHeaders []confluentKafka.Header
		for key, value := range headers {
			kafkaHeaders = append(kafkaHeaders, confluentKafka.Header{
				Key:   key,
				Value: []byte(value),
			})
		}
		message.Headers = kafkaHeaders
	}
	err = k.kafkaProducer.Produce(message, k.deliveryChan)

	if kafkaError, ok := err.(confluentKafka.Error); ok && kafkaError.Code() == confluentKafka.ErrQueueFull {
		log.Error("Kafka local queue full error - Going to Flush then retry...")
		flushedMessages := k.kafkaProducer.Flush(30 * 1000)
		log.Infof("Flushed kafka messages. Outstanding events still un-flushed: %d", flushedMessages)
		return k.PublishMessage(ctx, key, payload, topic, headers)
	}

	return err
}
```

**Comment by shanweidi** [comment]
> 

used this solution, our producer environment find in event.go can't out select{},because  of this event chain is full.How can I resolve?
`case C.RD_KAFKA_EVENT_DR:
			// Producer Delivery Report event
			// Each such event contains delivery reports for all
			// messages in the produced batch.
			// Forward delivery reports to per-message's response channel
			// or to the global Producer.Events channel, or none.
			rkmessages := make([]*C.rd_kafka_message_t, int(C.rd_kafka_event_message_count(rkev)))

			cnt := int(C.rd_kafka_event_message_array(rkev, (**C.rd_kafka_message_t)(unsafe.Pointer(&rkmessages[0])), C.size_t(len(rkmessages))))

			for _, rkmessage := range rkmessages[:cnt] {
				msg := h.newMessageFromC(rkmessage)
				var ch *chan Event

				if rkmessage._private != nil {
					// Find cgoif by id
					cg, found := h.cgoGet((int)((uintptr)(rkmessage._private)))
					if found {
						cdr := cg.(cgoDr)

						if cdr.deliveryChan != nil {
							ch = &cdr.deliveryChan
						}
						msg.Opaque = cdr.opaque
					}
				}

				if ch == nil && h.fwdDr {
					ch = &channel
				}

				if ch != nil {
					select {
					case *ch <- msg:
					case <-termChan:
						retval = nil
						term = true
						break out
					}

				} else {
					retval = msg
					break out
				}
			}`
