### ISSUE TITLE
go build -tags static failing on macOS: ld: unknown option: -Bstatic

### ISSUE THREAD

**Issue by tchap** [confluentinc/confluent-kafka-go#81]
Hi,

I am trying to build my project using `confluent-kafka-go` with `-tags static` and I am getting

```
ld: unknown option: -Bstatic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It's macOS Sierra 10.12.6.

**Comment by edenhill** [comment]
Thank you, will look into it.

**Comment by edenhill** [comment]
Duplicate of #59

**Comment by tchap** [comment]
@edenhill I created a separate issue because I could see #59 mentioning `-Bstatic` in any way. But if you think that this issue will be fixed by fixing the other issue, no problem in closing this one...
