### ISSUE TITLE
Add conf_dump API

### ISSUE THREAD

**Issue by jefftt** [confluentinc/confluent-kafka-go#817]
Description
===========
In order to debug different behavior, it can be useful to see the full producer/consumer config to ensure values are set as you expect. This can be done with the [conf_dump](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2484-L2493). There is currently no equivalent go API

**Comment by edenhill** [comment]
You can also configure `"debug": "conf"` in the ConfigMap passed to the NewProducer/Consumer and it will emit the configured properties and their values.

**Comment by jefftt** [comment]
ah this is exactly what i was looking for, thanks!
