### ISSUE TITLE
Unable to connect to Kafka with TLS certificate

### ISSUE THREAD

**Issue by enesyalinkaya** [confluentinc/confluent-kafka-go#822]
Description
===========
Hi, I try to connect to Kafka with TLS client certificates but I am getting the error  "Disconnected while requesting ApiVersion", any help ?

LibraryVersion = 1.9.0
Apache Kafka broker version = 2.2.0

```
kafka.ConfigMap{
	"bootstrap.servers":             kafkaConfig.ConnectionAddress,
	"group.id":                      kafkaConfig.ConsumerGroupNameForPromotion,
	"partition.assignment.strategy": kafkaConfig.PartitionAssignmentStrategy,
	"enable.auto.commit":            enableAutoCommit,
	"auto.commit.interval.ms":       autoCommitIntervalMs,
	"auto.offset.reset":             autoOffsetReset,
	"sasl.mechanism":                "SCRAM-SHA-512",
	"broker.address.family":         "v4",
	"security.protocol":             "SASL_SSL",
	"sasl.username":                 kafkaConfig.SaslUsername,
	"sasl.password":                 kafkaConfig.SaslPassword,
	"ssl.ca.location":               "./kafka-ca.pem",
	"debug":                         "all",
}
```

client logs

```
Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is \u003c 0.10 (see api.version.request) (after 48ms in state APIVERSION_QUERY
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by bbq2100** [comment]
@enesyalinkaya did you find a solution in the end? asking since i am seeing the same error when targeting a new env...
