### ISSUE TITLE
Request: add AdminClient.DeleteGroups

### ISSUE THREAD

**Issue by jflambert** [confluentinc/confluent-kafka-go#826]
Description
===========
I already use `kafka.AdminClient.DeleteTopics`
I would like to use `kafka.AdminClient.DeleteGroups` the same way

Looks like all the proper types are already in `rdkafka.h` for example: operation `RD_KAFKA_ADMIN_OP_DELETEGROUPS` and result `RD_KAFKA_EVENT_DELETEGROUPS_RESULT`

How to reproduce
================
N/A

Checklist
=========
 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.9.1

**Comment by milindl** [comment]
Thanks for submitting this issue, we're working on adding this.

**Comment by milindl** [comment]
Closing with #923
