### ISSUE TITLE
the max messages can be send in one kafka transaction

### ISSUE THREAD

**Issue by guotie** [confluentinc/confluent-kafka-go#838]
Description
===========

the max messages can be send in one kafka transaction

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
  v1.5.2
 - [ ] Apache Kafka broker version:
 2.6
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
there isn't a maximum.

note though that the time between transaction commits will impact latency when reading (assuming isolation.level is read_committed).

**Comment by guotie** [comment]
I know.

it's a config in kafka broker.
