### ISSUE TITLE
Enterprise-Control-Center Interceptor

### ISSUE THREAD

**Issue by eblock-fw** [confluentinc/confluent-kafka-go#84]
I see that support for the enterprise-control-center interceptor was released with librdkafka v0.11.0 and is compatible with cp-3.3.0... but I am having trouble implementing it.

In setting up my producer or consumer, I use:
```
consumer, err = kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers":    brokers,
		"group.id":             group,
		...other configs...
		"plugin.library.paths": "monitoring-interceptor",
})
```

But at runtime I get an error: `dlopen() failed: monitoring-interceptor.so: cannot open shared object file: No such file or directory` (on debian) or `dlopen() failed: monitoring-interceptor.dylib: cannot open shared object file: No such file or directory` (on OSX).

How do I get the proper object/dylib? Is there a configuration during `librdkafka` install in order to make and install the proper object/dylib? I see the [http://docs.confluent.io/current/control-center/docs/clients.html](installation instructions) reference installing the appropriate package... but am not sure where those are.

**Comment by edenhill** [comment]
You need to install the `confluent-librdkafka-plugins` deb/rpm package after adding the appropriate apt/yum repo from here: http://docs.confluent.io/current/installation.html

After that your configuration should work.

**Comment by eblock-fw** [comment]
Thank you! That worked well for the debian install.
