### ISSUE TITLE
Protobuf serialization bug

### ISSUE THREAD

**Issue by Shukla-Ankur** [confluentinc/confluent-kafka-go#847]
Description
===========
Confluent-kafka-go v1.9.2

I am running a grpc server in go language. The APIs are defined using protobuf. 
Clients send data in a generic API where input object is defined as:
```
message Document {
    DocumentMeta meta = 1;
    bytes data = 2;
    google.protobuf.Any details = 3;
}
```

The details field uses Any type so that clients can send any type of message using this API. On server-side, the .proto files are used to register Message types 
```

protoFile, err := ioutil.ReadFile(tmp_file)
pb_set := new(descriptorpb.FileDescriptorSet)
if err := proto.Unmarshal(protoFile, pb_set); err != nil {
			return err
	}
pb := pb_set.GetFile()[0]
fd, err := protodesc.NewFile(pb, protoregistry.GlobalFiles)
msgType = dynamicpb.NewMessageType(fd.Messages().Get(0))
protoregistry.GlobalTypes.RegisterMessage(msgType)

```

The types get registered successfully and I can check them.

Data from any field is unmarshalled as follows to a protoreflect.ProtoMessage type
`msg, err := anypb.UnmarshalNew(doc.GetDetails(), proto.UnmarshalOptions{})`

When running `protobuf.serialize(topic, msg)`,  it fails in the `s.toProtobufSchema(protoMsg)` step with error
`error interface conversion: *dynamicpb.Message is not desc.protoMessage:  missing method Descriptor`

How to reproduce
================
Run the above steps, it can be deterministically reproduced.
1. Create an API with **Any** type field
2. Create a proto file on client-side, 
3. server will use the proto file from client to register message descriptors
4. Client will use proto file to send data via above API
5. On server-side, Unmarshal the data from Any field like `anypb.UnmarshalNew(doc.GetDetails(), proto.UnmarshalOptions{})`
7. serialize using protobuf.serialize(topic, msg) of confluent-kafka-go.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 Confluent-kafka-go v1.9.2
 - [x] Apache Kafka broker version:
 NA since code does not reach schema-registry server, and fails before itself
 - [x] Client configuration: `ConfigMap{...}`
 NA
 - [x] Operating system:
 Mac Monterey 12.5
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by paulolimarb** [comment]
Hi @Shukla-Ankur 

Did you get any solution to this problem? 

I'm also encountering this same error.

Thanks

**Comment by Shukla-Ankur** [comment]
@paulolimarb No, I ended up dropping the idea of developing this as an application. To still allow dynamic types, I developed this as an sdk so that type information is not lost. So essntially I removed the part where protos are needed

**Comment by mhowlett** [comment]
see also #867 - seems like we should take a look into these to see what's up.

**Comment by PrasanthV454** [comment]
@paulolimarb @Shukla-Ankur 

Currently we don't support protobuf messages built on fly for example dynamicob.Message type. We don't have a plan either at the current moment. We will discuss internally on this on when to take up this.
