### ISSUE TITLE
 always start from offset 0 when restart the client,Assign partition consumption

### ISSUE THREAD

**Issue by heketong** [confluentinc/confluent-kafka-go#851]
Description
===========
Assign partition consumption scenario, always start from offset 0 when restart the client.
The test code is as follows:
when Not specifying a partition,that's fine,I'm so confused.Somebody help?

How to reproduce
================
func TestConsumerMsg(b *testing.T){
conf := kafka.ConfigMap{
		"bootstrap.servers": "127.0.0.x:9092,127.0.0.x:9093,127.0.0.x:9094",
		"group.id":             "gotest1",
		"auto.offset.reset":     "earliest",
                 "auto.commit.interval.ms": 50,
	}
topic:="test5"
	partitions := kafka.TopicPartitions{
		{Topic: &topic, Partition: 1}}
err = c.Assign(partitions)
	if err != nil {
		b.Fatalf("Assign failed: %s", err)
	}
	assignment, err := c.Assignment()
	if err != nil {
		b.Fatalf("Assignment() failed: %s", err)
	}
	b.Logf("Compare Assignment %v to original list of partitions %v\n",
		assignment, partitions)
       var CCount int = 0
	for{
		msg, err := c.ReadMessage(100 * time.Millisecond)
		if err!=nil{
			if !strings.Contains(err.Error(), "Timed out") {
				fmt.Println("ReadMessage err:", err.Error())
			}
		}else{
			fmt.Println(string(msg.Value),"parttion in",msg.TopicPartition.Partition)
		}
		time.Sleep(100*time.Millisecond)
		CCount++
		if CCount>1000{
			//c.Unsubscribe()
			c.Close()
			break
		}
	}
}

Checklist
=========
Please provide the following information:

 - [v1.9.2 ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ kafka_2.12-3.0.0] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ always start from offset 0 when restart the client] Critical issue

**Comment by mhowlett** [comment]
I think the issue is that in go struct values are initialized to 0 by default. Try setting `Offset: kafka.OffsetInvalid`.
