### ISSUE TITLE
__isnan: symbol not found on docker run 

### ISSUE THREAD

**Issue by dhav01** [confluentinc/confluent-kafka-go#868]
Description
===========
I am building a go application and a worker having confluent kafka. When I updated the Dockerfile, main application built and ran successfully. In case of worker, docker build was successful but it failed on docker run with the error of isnan not found.
Other services which were not using kafka ran successfully so I feel this is some kind of incompatibility issue between alpine and kafka.

How to reproduce
================
This is the Dockerfile which is used to build main app binary and worker binary
```
FROM golang:1.15 AS build

RUN mkdir -p /go/api/proj

WORKDIR /go/api/proj

COPY go.* ./

RUN go mod download

COPY . .

RUN go mod tidy

RUN go build -o proj ./api/

RUN go build -o worker ./worker/

FROM alpine:3.14

WORKDIR /

RUN apk add libc6-compat cmake

RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

COPY . .

COPY --from=build /go/api/proj/proj .

COPY --from=build /go/api/proj/worker .

EXPOSE 80

CMD ["./worker"]
```

I am building the image using docker buildx build --platform linux/amd64 -t img-name . 

This is the error I received on Docker run
```
Error relocating ./worker: __strdup: symbol not found
Error relocating ./worker: __isnan: symbol not found
Error relocating ./worker: __strndup: symbol not found
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go: confluent-kafka-go v1.5.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}` 
 - [x] Operating system: Mac M1 pro
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by milindl** [comment]
Hi @dhav01 , thanks for reporting this issue.
Could you try using the  golang:1.15-alpine image instead?
And, if that doesn't work, can you try using these instructions to see if they help? https://github.com/confluentinc/confluent-kafka-go#static-builds-on-linux
It seems to be a linking issue at a first glance.

**Comment by edenhill** [comment]
You must build with `-tags musl` on musl-based Linux distros, such as Alpine.

**Comment by mhowlett** [comment]
triaging this as investigate further/low as it would be worth
