### ISSUE TITLE
Question about max.poll.interval.ms, max.poll.records and the method Poll of consumers

### ISSUE THREAD

**Issue by n4d13** [confluentinc/confluent-kafka-go#871]
Hi!
I wish to know how interacts [consumer's Poll](https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/consumer.go#L343)  and max.poll.interval.ms/max.poll.records
Having those configurations their default values:
max.poll.interval.ms=300000
max.poll.records=500
when we call consumer.Poll(-1) until exhaust librdkafka's queue there is any way to poll records again to refill the queue of messages?
In cases of very variable message processing time, we can't prior know how many messages can processed before reaching max.poll.interval.ms but a good mitigation can be commit offsets and forcing a new poll from broker, so...

[consumer's Poll](https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/consumer.go#L343) calls a real poll from brokers or only extract messages from internal queue and poll a new set of message on queue's exhaustion?

**Comment by mhowlett** [comment]
the go client doesn't have a max.poll.records config property, the poll method returns at most one message.

librdkafka fetches messages from assigned-to partitions autonomously behind the scenes. when or how often you call the poll method has no impact on when or how the fetching is done. max.poll.interval.ms is a safety parameter which is the maximum time program execution can be in application code before the client will assume something is wrong and leave the group (if you're subscribed to a group).
