### ISSUE TITLE
Kafka consumer stuck_Application maximum poll interval (300000ms) exceeded by 381ms (

### ISSUE THREAD

**Issue by sunilob** [confluentinc/confluent-kafka-go#873]
Description
===========
Received below error message in kafka consumer

Application maximum poll interval (300000ms) exceeded by 381ms (adjust max.poll.interval.ms for long-running message processing): leaving group

code:

from confluent_kafka import Consumer

consumer = Consumer({
        'bootstrap.servers': kafka_server,
        'group.id': 'xxxxxxxxxxxxxxxxxxxxx',
        'auto.offset.reset': 'earliest',
        'sasl.mechanism': 'PLAIN',
        'security.protocol': 'SASL_SSL',
        'ssl.ca.location': 'xxxxx.pem',
        'session.timeout.ms': 299000,
        'fetch.wait.max.ms': 1000,
        'sasl.username': 'xxxxx',
        'sasl.password': 'xxxxx'
    })
   

    consumer.subscribe(kafka_topic)
    
    while True:
       message = consumer.poll(1.0)
       if message is None:
            print('Listening...')
            continue
        if message.error():
            print("Consumer error: {}".format(message.error()))
            continue

using Name: confluent-kafka (Version: 1.9.0)
What is the solution to fix this

**Comment by sunilob** [comment]
I use Confluent-kafka only.  Below is the complete code to fetch from kafka. i am new to this. Please modify the code if you suggest any


from time import sleep
import json
from confluent_kafka import Consumer, KafkaException, KafkaError
# import psutil
from datetime import datetime
import logging
import sys


time_interval = 1/2 # how often the data is checked in seconds (half second would be 1/2)

def main():
    kafka_server="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

    kafka_topic = ['xxxxxxxx']

    consumer = Consumer({
        'bootstrap.servers': kafka_server,
        'group.id': 'xxxxxxxx',
        'auto.offset.reset': 'earliest',
        'sasl.mechanism': 'PLAIN',
        'security.protocol': 'SASL_SSL',
        'ssl.ca.location': 'xxxx.pem',
        'session.timeout.ms': 299000,
        'fetch.wait.max.ms': 1000,
        'sasl.username': 'xxxxxx',
        'sasl.password': 'xxxxxx'
    })
    print('Consumer created')
    
    try:
        consumer.subscribe(kafka_topic)
        while True:
            message = consumer.poll(1.0)

            if message is None:
                print('Listening...')
                continue
                            
            elif message.error():
                print("Consumer error: {}".format(message.error()))
                if message.error().code() == KafkaError._PARTITION_EOF:
                  # End of partition event
                  sys.stderr.write('%% %s [%d] reached end at offset %d\n' %
                                         (message.topic(), message.partition(),
                                          message.offset()))
                elif message.error():
                   sys.stderr.write(
                            'Consumer Error {message.error()}\n')
                   raise KafkaException(message.error())
            elif message.error() is None:
                input_data = json.loads(message.value().decode('utf-8'))
                print(input_data)
    
    except Exception as error:
        sys.stderr.write(' EXCEPTION %s on the consumer for topic(s) %s\n' % (error, kafka_topic))

    finally:
        sys.stderr.write('CLOSING consumer %s with topic(s): %s\n' % (consumer, kafka_topic))
        consumer.close()
        return 1    
    

if __name__ == '__main__':
    main()

**Comment by mhowlett** [comment]
> What confluent-kafka-go version are you using?
1.9.0

this looks more like python to my untrained eye - maybe ask in that repo? make sure the indentation is right, it's not in your pasted code above.

suggest taking an example (which should work) and modifying it one bit at a time until you work out what's causing the issue.
