### ISSUE TITLE
How to get topic name with message.value() if have multiple topics

### ISSUE THREAD

**Issue by sunilob** [confluentinc/confluent-kafka-go#874]
we have multiple topics in single consumer call using confluent_kafka in python code, 
we use message.value() to retrieve the data, How to get relevant topic name along with message.value()
input_data = json.loads(message.value().decode('utf-8'))

**Comment by edenhill** [comment]
https://pkg.go.dev/github.com/confluentinc/confluent-kafka-go/kafka#Message

`*msg.TopicPartition.Topic`
