### ISSUE TITLE
Cannot use Poll to poll the consumer for messages or events for MockCluster

### ISSUE THREAD

**Issue by clyang82** [confluentinc/confluent-kafka-go#875]
Description
===========

I am using the `MockCluster` for testing. It is working well for this example - https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/mockcluster_example/mockcluster.go

the example is using `c.ReadMessage(-1)`  to poll the consumer for a message. I am trying to use `c.Poll(-1)` to poll the consumer for a message. it does not work. Do we support it? @emasab any comments? Thanks.

How to reproduce
================

just modify the mockcluster.go with
```
+++ b/examples/mockcluster_example/mockcluster.go
@@ -85,12 +85,12 @@ func main() {
                os.Exit(1)
        }

-       msg, err := c.ReadMessage(-1)
+       event := c.Poll(-1)
        if err != nil {
                fmt.Fprintf(os.Stderr, "Failed to read message: %s\n", err)
                os.Exit(1)
        }

-       fmt.Println("received message: ", string(msg.Value))
+       fmt.Println("received message: ", event)
```

the result is 
```
%5|1666703831.886|CONFWARN|rdkafka#producer-1| [thrd:app]: No `bootstrap.servers` configured: client will not be able to connect to Kafka cluster
Created Producer rdkafka#producer-2
Delivered message to topic Test [0] at offset 0
Created Consumer rdkafka#consumer-3
received message:  <nil>
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.9.2
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
the mock consumer api that is used to set everything up is pretty large, and not exposed in the go client. i wasn't involved in the decision to expose the mock cluster in this binding, but i suspect it's not useful for anything in it's current form except allowing a client to be instantiated.
