### ISSUE TITLE
Panic when creating Schema Registry Client with SSL Ca certificate

### ISSUE THREAD

**Issue by HansK-p** [confluentinc/confluent-kafka-go#876]
Description
===========
When  running schemaregistry.NewClient() with the default config + SslCaLocation set, this results in an panic due to a nil pointer. It might be this isn't supposed to work, but I assume the application shouldn't panic.

How to reproduce
================
<pre>
package main

import (
        "github.com/confluentinc/confluent-kafka-go/schemaregistry"
)

func main() {
        schemaRegistryConfig := schemaregistry.NewConfig("https://schemaregistry.test.com")
        schemaRegistryConfig.SslCaLocation = "certs/gandi.pem"
        _, _ = schemaregistry.NewClient(schemaRegistryConfig)
}
==

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x578803]

goroutine 1 [running]:
crypto/x509.(*CertPool).addCertFunc(...)
	/usr/lib/go-1.19/src/crypto/x509/cert_pool.go:189
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, {0xc0000ec900?, 0x7fa521729fff?, 0x7fa5203d8bb8?})
	/usr/lib/go-1.19/src/crypto/x509/cert_pool.go:227 +0x263
github.com/confluentinc/confluent-kafka-go/schemaregistry.configureTLS(0x0?, 0xc000108000)
	/home/hkno/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.2/schemaregistry/rest_service.go:175 +0x2a8
github.com/confluentinc/confluent-kafka-go/schemaregistry.configureTransport(0xc0000c5ec0)
	/home/hkno/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.2/schemaregistry/rest_service.go:192 +0x3b
github.com/confluentinc/confluent-kafka-go/schemaregistry.newRestService(0xc0000c5ec0)
	/home/hkno/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.2/schemaregistry/rest_service.go:126 +0x125
github.com/confluentinc/confluent-kafka-go/schemaregistry.NewClient(0xc0000c5ec0)
	/home/hkno/go/pkg/mod/github.com/confluentinc/confluent-kafka-go@v1.9.2/schemaregistry/schemaregistry_client.go:229 +0x1a6
main.main()
	/home/hkno/Docker/K8s/Golang/confluent-schema-reg-bug/main.go:10 +0xfb
exit status 2
</pre>

Checklist
=========
Please provide the following information:

 - [ x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): github.com/confluentinc/confluent-kafka-go v1.9.2
 - [ x] Apache Kafka broker version: NA
 - [ x] Client configuration: See above
 - [ x] Operating system: Ubuntu, but does affect any OS
 - [ x] Provide client logs (with `"debug": ".."` as necessary): See above
 - [ x] Provide broker log excerpts See above
 - [ x] Critical issue: No

**Comment by NDoBln** [comment]
Hi @milindl 
I also ran into the same error as already reported in this issue (see attachement below). 
Might it be that the bug fix has not been implemented into the recent client version or is not publicly available yet?

<img width="1446" alt="Bildschirmfoto 2023-03-23 um 09 57 49" src="https://user-images.githubusercontent.com/93553703/227154130-c237bf92-fad3-4a6f-811e-88e0d4c22061.png">

**Comment by NDoBln** [comment]
Thanks for your quick response. The new version is working as you said :)!
