### ISSUE TITLE
Check compatible librdkafka at runtime

### ISSUE THREAD

**Issue by kevinburke** [confluentinc/confluent-kafka-go#88]
The consumer_example.go has this example for a Consumer:

```
	c, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers":    broker,
		"group.id":             group,
		"session.timeout.ms":   6000,
		"default.topic.config": kafka.ConfigMap{"auto.offset.reset": "earliest"}}
```

I had to change "earliest" to `kafka.OffsetBeginning` to get it to work. Currently the Kafka consumer is failing on `No such configuration property: "session.timeout.ms"`. I'm not sure what's going on there, I'm currently trying to debug it.

**Comment by kevinburke** [comment]
The odd thing is these work locally (on Mac) but not in my CI environment (ubuntu). I installed librdkafka by running `add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/3.3 stable main" && apt-get update && apt-get install librdkafka1`.

**Comment by kevinburke** [comment]
Ah, turns out I was using librdkafka 0.8.4 or so on that machine..

**Comment by edenhill** [comment]
So old!
We'll add a runtime check to verify the librdkafka version.
