### ISSUE TITLE
Question about using events channel and auto commit

### ISSUE THREAD

**Issue by mdotv** [confluentinc/confluent-kafka-go#881]
Hi. I have a question about using events channel and enable.auto.commit=true. Can you explain me how it works in that case? What happens when I close consumer? I see, it closes events channel, but does it commit messages that stayed in closed channel, or only messages were read from the channel before closing?

**Comment by mhowlett** [comment]
this has been deprecated (due to race conditions related to your questions, i believe). we recommend using the function apis.

https://github.com/confluentinc/confluent-kafka-go#api-strands
https://github.com/confluentinc/confluent-kafka-go/tree/master/examples/legacy
