### ISSUE TITLE
call flush() but Len() not reduce

### ISSUE THREAD

**Issue by xiaoxinsfdsfds** [confluentinc/confluent-kafka-go#882]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
not enough information to comment... perhaps try setting the "debug" config property to "all" to get more visibility what's going on inside the client.
