### ISSUE TITLE
rebalanceCb example [enhancement]

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-go#886]
we don't have any good examples of using a rebalance callback - we need one, with plenty of commenting to explain what is going on and the possibilities. if the erroneous state error case is possible with the go client when storing / committing offsets, we should also document this here as well.

**Comment by mhowlett** [comment]
#884

**Comment by VipulZopSmart** [comment]
When can we expect this, as we're in the middle of creating a microservice. We're left with the rebalancing part of that. @mhowlett @milindl
