### ISSUE TITLE
Unable to Produce More than 100k messages 

### ISSUE THREAD

**Issue by aakarshit-batchu** [confluentinc/confluent-kafka-go#89]
Here is the code which i am running. After Producing 100k messages the program gets stuck. It neither throws error nor produces any message.I have tried using function based producer as well. And it's the same.Can you resolve the issue for me please. Also i want to know which producer runs faster (channel based vs function based)

```
package main

import (
        "fmt"
        "github.com/confluentinc/confluent-kafka-go/kafka"
        "os"
)

func main() {

        broker := ip:9092
        topic := "pro-temp"

        p, err := kafka.NewProducer(&kafka.ConfigMap{"bootstrap.servers": broker})

        if err != nil {
                fmt.Printf("Failed to create producer: %s\n", err)
                os.Exit(1)
        }

        fmt.Printf("Created Producer %v\n", p)

        doneChan := make(chan bool)

        go func() {
                defer close(doneChan)
                for e := range p.Events() {
                        switch ev := e.(type) {
                        case *kafka.Message:
                                m := ev
                                if m.TopicPartition.Error != nil {
                                        fmt.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
                                } else {
                                        fmt.Printf("Delivered message to topic %s [%d] at offset %v\n",
                                                *m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
                                }
                                return

                        default:
                                fmt.Printf("Ignored event: %s\n", ev)
                        }
                }
        }()

        for i:=0;i<200000;i++ {
        value :="{\" dropoff_datetime\":\"2014-08-16 22:43:55\",\" dropoff_latitude\":\"40.756548000000002\",\" dropoff_longitude\":\"-73.964157999999998\",\" fare_amount\":\"16\",\" mta_tax\":\"0.5\",\" passenger_count\":\"2\",\" payment_type\":\"CSH\",\" pickup_datetime\":\"2014-08-16 22:23:42\",\" pickup_latitude\":\"40.740574000000002\",\" pickup_longitude\":\"-74.005691999999996\",\" rate_code\":\"1\",\" store_and_fwd_flag\":\"N\",\" surcharge\":\"0.5\",\" tip_amount\":\"0\",\" tolls_amount\":\"0\",\" total_amount\":\"17\",\" trip_distance\":\"3.3999999999999999\",\"vendor_id\":\"CMT\"}"
        p.ProduceChannel() <- &kafka.Message{TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny}, Value: []byte(value)}
}
        // wait for delivery report goroutine to finish
        _ = <-doneChan

        p.Close()
}
```

**Comment by edenhill** [comment]
I'm not sure I understand your program logic: you produce 200k messages but close down after the first message has been delivered (return statement in the go-routine).

**Comment by aakarshit-batchu** [comment]
Yeah, my bad. Thanks for that. Can you also tell me what's wrong with this program?
`package main

import (
        "fmt"
        "github.com/confluentinc/confluent-kafka-go/kafka"
        "os"
)

func main() {

        broker := "ip:9092"
        topic := "pro-temp"

        p, err := kafka.NewProducer(&kafka.ConfigMap{"bootstrap.servers": broker})

        if err != nil {
                fmt.Printf("Failed to create producer: %s\n", err)
                os.Exit(1)
        }

        fmt.Printf("Created Producer %v\n", p)

        deliveryChan := make(chan kafka.Event)
        value := "{\" dropoff_datetime\":\"2014-08-16 22:43:55\",\" dropoff_latitude\":\"40.756548000000002\",\" dropoff_longitude\":\"-73.964157999999998\",\" fare_amount\":\"16\",\" mta_tax\":\"0.5\",\" passenger_count\":\"2\",\" payment_type\":\"CSH\",\" pickup_datetime\":\"2014-08-16 22:23:42\",\" pickup_latitude\":\"40.740574000000002\",\" pickup_longitude\":\"-74.005691999999996\",\" rate_code\":\"1\",\" store_and_fwd_flag\":\"N\",\" surcharge\":\"0.5\",\" tip_amount\":\"0\",\" tolls_amount\":\"0\",\" total_amount\":\"17\",\" trip_distance\":\"3.3999999999999999\",\"vendor_id\":\"CMT\"}"

go func() {
for i:=0;i<300000;i++ {
        err = p.Produce(&kafka.Message{TopicPartition: kafka.TopicPartition{Topic: &topic, Partition: kafka.PartitionAny}, Value: []byte(value)}, deliveryChan)
        }
}()

for j:=0;j<300000;j++ {
        e := <-deliveryChan
        m := e.(*kafka.Message)

        if m.TopicPartition.Error != nil {
                fmt.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
        } else {
                fmt.Printf("Delivered message to topic %s [%d] at offset %v\n",*m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
        }
        }
        fmt.Println("Success")
        close(deliveryChan)
}
`

**Comment by edenhill** [comment]
tip: to quote a multi-line blurb in (github) markdown, envelope the blurb with triple back-ticks on their own lines.

**Comment by edenhill** [comment]
There will be one delivery report `Message` event sent on the delivery report cchannel per message accepted by `Produce()`.
However, you are setting up an unbuffered deliveryChan (has room for 1 Message event), try to produce 300,000 messages and then start reading off the deliveryChan, but since the default value of `queue.buffering.max.ms` is 100,000 messages, Produce() will accept the first 100,000 messages and then fail with Buffer full (you are not handling Produce() errors either).

The proper way to do this is to put the delivery report message loop in its own go-routine that runs simultaneously and starts reading delivery reports as soon as messages are getting produced.
For performance you should also increase the deliveryChan size, or use the standard `p.Events()` channel.

go-kafkacat might be a better example:
https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/go-kafkacat/go-kafkacat.go#L51
