### ISSUE TITLE
Consumer App Hanging

### ISSUE THREAD

**Issue by VipulZopSmart** [confluentinc/confluent-kafka-go#893]
Description
===========
The consumer app seems to be hanging in closing(by pressing control X several times). I've tried to write a code for a sample app by using confluent-kafka-go library but even after trying to interrupt the app several times, the app is not stopping until i close the terminal window. Sample code provided code in this issue: https://github.com/confluentinc/confluent-kafka-go/issues/884
let me know if more details are needed.

How to reproduce
================

<img width="714" alt="Screenshot 2022-11-08 at 12 37 42 AM" src="https://user-images.githubusercontent.com/77278140/200393902-3eca0c7d-46d1-4ffc-98e8-0f8d078df59b.png">

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.9.2
 - [x] Apache Kafka broker version: local kafka
 - [x] Client configuration: `ConfigMap{...}` default properties
 - [x] Operating system: macOS
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
librdkafka does not detect SIGINT/SIGTERM - if you are specifying an infinite poll timeout, try using a shorter one, and looping instead.
