### ISSUE TITLE
Add SeekPartitions wrapper for rd_kafka_seek_partitions function to support seeking multiple partitions at a time

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [confluentinc/confluent-kafka-go#902]
Description
===========

The [Seek](https://github.com/confluentinc/confluent-kafka-go/blob/561a26092b1678e2ddcddbff6b2720ee4e85aaf9/kafka/consumer.go#L323) function only supports seeking one partition at a time.  This is due to the underlying limitation of the [rd_kafka_seek](https://github.com/edenhill/librdkafka/blob/51985c7eb287d4a7df93487c90372d239cf0d572/src/rdkafka.h#L3673) function also only seeking one partition at a time.

However, the rd_kafka_seek function was marked as deprecated, with [rd_kafka_seek_partitions](https://github.com/edenhill/librdkafka/blob/51985c7eb287d4a7df93487c90372d239cf0d572/src/rdkafka.h#L3712-L3713) being the new preferred alternative.  This function takes a list of partitions.

Please consider adding a new function named `SeekPartitions` or similar to the Go consumer, which wraps `rd_kafka_seek_partitions`.  This will allow us to avoid having to write loops like this:

```
	assigned, _ := consumer.Assignment()
	for i := range assigned {
		assigned[i].Offset = 0
	}
	for _, a := range assigned {
		_ = consumer.Seek(a, 0)
	}
```
and instead write:
```
	assigned, _ := consumer.Assignment()
	for i := range assigned {
		assigned[i].Offset = 0
	}
	_ = consumer.SeekPartitions(assigned, 0)
```

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`LibraryVersion()`): `master` branch: a reference to `rd_kafka_seek_partitions` cannot be found anywhere indicating that there is no existing wrapper function
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: `ConfigMap{...}` N/A
 - [ ] Operating system: N/A
 - [ ] Provide client logs (with `"debug": ".."` as necessary): N/A
 - [ ] Provide broker log excerpts: N/A
 - [ ] Critical issue

**Comment by milindl** [comment]
Assigning it to myself as we're taking a look at this in our internal tasks loop.

**Comment by milindl** [comment]
Closing with #940, PR merged to master. It will be there in next release.
