### ISSUE TITLE
Question Regarding Kafka Protobuf Producer - Specifying Schemas and Versions

### ISSUE THREAD

**Issue by pchang388** [confluentinc/confluent-kafka-go#911]
Description
===========
Hi,

I am new to Kafka Connect and working with Protobuf serialization and also this entire process in general. My current task is to evaluate the data flow process between Kafka topics and inserts into TimescaleDB using JDBC sink connector with Kafka Schema Registry. I have almost everything up and running and am trying to test the E2E flow using a sample producer. 

However, I had a few general questions on Kafka Protobuf Producer, an example is provided in this repo here: https://github.com/confluentinc/confluent-kafka-go/blob/5ba3caae52b04aaf7b4e22d5e30737b42ca948cd/schemaregistry/serde/protobuf/protobuf.go

I was hoping someone could explain to me a few things here:

In the referenced example above, only the schema URL is given. But let's say that you had multiple proto schema subjects available (example: `proto.testrecord` and `proto.anotherrecord`) in the Schema Registry. In this new example, we have the two schemas showing as:

`proto.testrecord`
```
message TestRecord {
    string cluster_name = 1;
    string id = 2;
    string hostname = 3;
    string metric = 4;
    int64 value = 5;
    string value_text = 6;
    int64 timestamp = 7;
} 
```
`proto.anotherrecord`
```
message AnotherRecord{
    string source_name= 1;
    string map_id= 2;
    string hostname = 3;
    string metric_group = 4;
    int64 value = 5;
    string value_text = 6;
    int64 timestamp = 7;
} 
```

Let's say you also have two topics and one (producer 1) should use the first schema subject and the second (producer 2) should use the second schema subject to validate/conform the data for inserts. Now let's you are creating a producer for first topic (producer 1) and it should use the `proto.testrecord` subject from the Schema Registry for serialization. How would you configure/tell the producer to use the correct schema subject and also the exact version (if multiple existed)? Or are not supposed to specify those due to the way the process works?

I noticed the repo example provided doesn't specify any of that information and I am trying to understand exactly how it knows or defaults to a certain subject and version. 

According to this: https://github.com/confluentinc/confluent-kafka-go/blob/5ba3caae52b04aaf7b4e22d5e30737b42ca948cd/schemaregistry/serde/config.go#L36. Looks like you can specify the SchemaId (via `UseSchemaID` var) which tells it which schema subject to use but unsure about how to specify versioning. 

I probably missed something during my reading and am not understanding things correctly and could use some help/discussion.

Any help is appreciated, thanks!

**Comment by pchang388** [comment]
So I did a bit more reading on some examples, docs, etc. and what I've found so far is that Confluent recommends:

https://docs.confluent.io/platform/current/schema-registry/schema_registry_onprem_tutorial.html#auto-schema-registration
```
By default, client applications automatically register new schemas. If they produce new messages to a new topic, then they will automatically try to register new schemas. This is very convenient in development environments, but in production environments we recommend that client applications do not automatically register new schemas. Best practice is to register schemas outside of the client application to control when schemas are registered with Schema Registry and how they evolve.
```

So from that snippet, a new user like me would logically create schemas (in my case using API) beforehand to prepare for production environment. I create the schemas as noted above and generate `*.pb.go` files using `protoc`. Then import the generated struct into my producer test script. 

I tried setting the `UseSchemaId` but in my example/demo, it does not seem to do anything. In my example, I am using test topic (does not exist yet but we have `auto.create.topics=true` ): `keeper_test`. 

Test script
```
package main

import (
	"fmt"
	"os"
	"strings"
	"time"

	pb "dell.com/kopje/kafka-connect-test-producer/protobuf/compiled/testrecord"
	"github.com/confluentinc/confluent-kafka-go/kafka"
	"github.com/confluentinc/confluent-kafka-go/schemaregistry"
	"github.com/confluentinc/confluent-kafka-go/schemaregistry/serde"
	"github.com/confluentinc/confluent-kafka-go/schemaregistry/serde/protobuf"
	log "github.com/sirupsen/logrus"
)

// env var
var (
	logLevel string
)

// constants/defaults
const (
	logLevelDefault   = "info"
	brokers           = "XXXXXXXX:9094,XXXXXX3:9094,XXXXXX9094"
	lingerTime        = 500
	schemaRegistryUrl = "http://localhost:8081"
	// schemaSubject     = "proto.testrecord"
)

// test data struct
// type TestRecord struct {
// 	ClusterName string
// 	VropsId     string
// 	Hostname    string
// 	Metric      string
// 	Value       int64
// 	ValueText   string
// 	Timestamp   int64
// }

/* CreateAsyncProducer: Create a new kafka producer instance to use globally
 */
func CreateAsyncProducer() *kafka.Producer {
	kp, err := kafka.NewProducer(&kafka.ConfigMap{
		"bootstrap.servers":  brokers,
		"compression.type":   "gzip",
		"linger.ms":          lingerTime,
		"retries":            "999",
		"enable.idempotence": "true",
		"acks":               "all",
		// "debug":              "all",
	})

	if err != nil {
		log.WithError(err).Error("Failed to create Kafka Producer")
		panic(err)
	}

	// return &KafkaProducer{Brokers: brokers, Producer: kp}
	return kp
}

func main() {
	testTopicName := "test_keeper"
	schemaSubject := "proto.testrecord"

	client, err := schemaregistry.NewClient(schemaregistry.NewConfig(schemaRegistryUrl))

	if err != nil {
		log.WithError(err).Fatal("Failed to create schema registry client")
	}

	// SerializerConfig is used to pass multiple configuration options to the serializers.
	// type SerializerConfig struct {
	// 	// AutoRegisterSchemas determines whether to automatically register schemas during serialization
	// 	AutoRegisterSchemas bool
	// 	// UseSchemaID specifies a schema ID to use during serialization
	// 	UseSchemaID int
	// 	// UseLatestVersion specifies whether to use the latest schema version during serialization
	// 	UseLatestVersion bool
	// 	// NormalizeSchemas determines whether to normalize schemas during serialization
	// 	NormalizeSchemas bool
	// }

	serConfig := protobuf.NewSerializerConfig()
	serConfig.AutoRegisterSchemas = false
	serConfig.UseSchemaID = 3
	log.Info(serConfig)

	ser, err := protobuf.NewSerializer(client, serde.ValueSerde, serConfig)
	log.Info(ser)
	if err != nil {
		log.WithError(err).Fatal("Failed to create serializer")
	}
	// ser.SubjectNameStrategy = getSubjectName

	schema, err := client.GetLatestSchemaMetadata(schemaSubject)
	if err != nil {
		log.WithError(err).Fatal("Failed to get schema metadata")
	}
	log.Info("Received schema metadata")
	log.Info(schema)

	deliveryChan := make(chan kafka.Event)

	data := pb.TestRecord{
		ClusterName: "test-cluster",
		VropsId:     "someId-123",
		Hostname:    "testhostname",
		Metric:      "system.status",
		Value:       0,
		Timestamp:   time.Now().UnixMilli(),
	}

	payload, err := ser.Serialize(testTopicName, &data)
	if err != nil {
		log.WithError(err).Fatal("Failed to serialize payload")
	}

	p := CreateAsyncProducer()
	err = p.Produce(&kafka.Message{
		TopicPartition: kafka.TopicPartition{Topic: &testTopicName, Partition: kafka.PartitionAny},
		Value:          payload,
		Headers:        []kafka.Header{{Key: "myTestHeader", Value: []byte("header values are binary")}},
	}, deliveryChan)
	if err != nil {
		log.WithError(err).Fatal("Produce failed")
	}

	e := <-deliveryChan
	m := e.(*kafka.Message)

	if m.TopicPartition.Error != nil {
		fmt.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
	} else {
		fmt.Printf("Delivered message to topic %s [%d] at offset %v\n",
			*m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
	}

	close(deliveryChan)
	time.Sleep(10 * time.Second)
	p.Close()
}

func LogLevelTranslate(lvl string) log.Level {
	switch lvl {
	case "debug":
		return log.DebugLevel
	case "info":
		return log.InfoLevel
	case "warn":
		return log.WarnLevel
	case "error":
		return log.ErrorLevel
	case "fatal":
		return log.FatalLevel
	default:
		return log.InfoLevel
	}
}

func init() {
	// Log as JSON instead of the default ASCII formatter.
	logLevel = logLevelDefault
	if env, found := os.LookupEnv("LOG_LEVEL"); found {
		logLevel = strings.ToLower(env)
	} else {
		log.Warnf("LOG_LEVEL not specified, using default: %s", logLevelDefault)
	}

	log.SetFormatter(&log.JSONFormatter{})

	// Output to stdout instead of the default stderr
	// Can be any io.Writer, see below for File example
	log.SetOutput(os.Stdout)

	// Only log the warning severity or above.
	log.SetLevel(LogLevelTranslate(logLevel))
}
```

In the output I see: 
```
WARN[0000] LOG_LEVEL not specified, using default: info 
{"level":"info","msg":"\u0026{{false 3 false false}}","time":"2022-12-12T18:32:24-05:00"}
{"level":"info","msg":"\u0026{{{0xc0003f43f0 2 0x7ce980} 0xc000421c08}}","time":"2022-12-12T18:32:24-05:00"}
{"level":"info","msg":"Received schema metadata","time":"2022-12-12T18:32:24-05:00"}
{"level":"info","msg":"{{syntax = \"proto3\";\npackage XXXX.XXXX.protobuf.testrecord;\n\nmessage TestRecord {\n  string cluster_name = 1;\n  string vrops_id = 2;\n  string hostname = 3;\n  string metric = 4;\n  int64 value = 5;\n  string value_text = 6;\n  int64 timestamp = 7;\n}\n PROTOBUF []} 3 proto.testrecord 2}","time":"2022-12-12T18:32:24-05:00"}
{"error":"schema registry request failed error code: 40401: Subject 'test_keeper-value' not found.
...
...
LONG error message...
...
...
}
```

As we can see it is using the `topicName` to generate the `subjectName` and according to these, I don't see a straightforward way to set `subjectName` for the producer:
https://github.com/confluentinc/confluent-kafka-go/issues/677
https://github.com/confluentinc/confluent-kafka-go/issues/848

From what the recommendations/docs say, the flow/process in a prod environment might look like from a new user:
1. Create a subject (you might not have a topic created yet in Kafka so logically a user might opt to set it to a unique name that is meaningful for them), in this case - I used `proto.testrecord` and add the schema for that subject. 
```
POST http://localhost:8081/subjects/proto.testrecord/versions

{
    "schemaType": "PROTOBUF",
    "schema": "syntax = \"proto3\";\npackage XXXX.XXXX.protobuf.testrecord;\n\nmessage TestRecord {\n  string cluster_name = 1;\n string vrops_id = 2; \n string hostname = 3; \n string metric = 4; \n int64 value = 5; \n string value_text = 6; \n int64 timestamp = 7; \n}\n"
}

```
2. They now have a schemaId, subject, and version in the Schema Registry after successful HTTP post
3. User then generates `pb.go` file from `test_record.proto` file and imports into producer code/script.
4. User then extends the producer and may attempt to specify schemaId, subjectName, and version (if required) for the protobuf serializer being used.
5. User looks at example code provided by this repo and sees no mention of any of those 3 fields and may not be clear to them what needs to be configured if anything.
6. If he/she/they is able to figure out step 5, they may wonder how to follow the recommendation of creating subjects/schemas first and also how to just use custom `subjectNames` if they wanted to with protobuf producers.

As stated, it's most likely I am misunderstanding the core concepts here but I am struggling to see how we can specify `subjectName`. Also since `schemaId` is global unique identifier in the Registry, shouldn't setting `UseSchemaId` make it use the `subjectName` tied to that schema by default?

**Comment by PrasanthV454** [comment]
Hi @pchang388 , 

Schema subject is associated with [Serialization Config](https://github.com/confluentinc/confluent-kafka-go/blob/5ba3caae52b04aaf7b4e22d5e30737b42ca948cd/schemaregistry/serde/serde.go#:~:text=*BaseSerializer)-,ConfigureSerializer,-(client%20schemaregistry). It is serdes who have the information regarding the subject name. 

There are three different ways of SubjectNameStrategy. 

1. TopicName
2. RecordName
3. TopicRecordName

Please check this [link](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#subject-name-strategy) for more info.

Currently go-client offers only one strategy which is TopicNameStrategy. 

You can check [this](https://github.com/confluentinc/confluent-kafka-go/blob/5ba3caae52b04aaf7b4e22d5e30737b42ca948cd/examples/protobuf_producer_example/protobuf_producer_example.go) for better understanding.
