### ISSUE TITLE
How do you check the unflushed messages post a Flush call?

### ISSUE THREAD

**Issue by AyushAngelOne** [confluentinc/confluent-kafka-go#915]
Description
===========
During server shutdown I am flushing to my producer using 

> kafkaProducer.Flush(5_000) .

However, it's possible that the messages might not be flushed in this interval due to various reasons, including broker connectivity issues. So I'm wondering if there's a way I can get all unflushed messaged the library is holding, so that I can push it to my fallback queue?

Library Version:
```
github.com/confluentinc/confluent-kafka-go v1.9.2
````

**Comment by edenhill** [comment]
librdkafka has an `rd_kafka_purge()` that can be used to fail messages in queue, not sure it is exposed in the Go client though.

**Comment by AyushAngelOne** [comment]
@edenhill thanks for that!

I founs `kafkaProducer.Purge(flags int)` is exposed so I can use that to purge messages in queue, followed by another `Flush()` call and handle the events. Not optimal but this works.

The [docs for Purge](https://pkg.go.dev/github.com/confluentinc/confluent-kafka-go/kafka#Producer.Purge) do mention

> The application will need to call Poll(), Flush() or read the Events() channel
> after this call to serve delivery reports for the purged messages.

but I am able to find any Reference to `Poll` on the producer which I can use. Is this a problem with the documentation?

**Comment by edenhill** [comment]
reading the Events() channel is analogue to calling Poll(), or Flush().

**Comment by AyushAngelOne** [comment]
Got it, thanks for the help! I'll close this.
