### ISSUE TITLE
SchemaRegistryClient handleRequest not honoring original schema registry URL with path

### ISSUE THREAD

**Issue by huizhilu** [confluentinc/confluent-kafka-go#943]
Description
===========

https://github.com/confluentinc/confluent-kafka-go/blob/ff4c2c5a6f2c6555ed53f208c173954bb2bcc243/schemaregistry/rest_service.go#L275

If the schema registry URL has a path: `https://api-proxy/schema-registry`, the final endpoint url for GetSubjects() becomes `https://api-proxy:8082/subjects`, which doesn't include `/schema-registry` path.

Is this expected? Using `url.Parse()` will replace the path. If `JoinPath()` is used, it'll give the correct result. Shall we use `JoinPath()`?

How to reproduce
================

1. Set the schema registry URL to have a path like `https://api-proxy/schema-registry`
2. Init the schema registry client
3. call GetSubjects() API

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by huizhilu** [comment]
Add the owner of the original PR #776  
cc @rayokota  Can you take a look if this can be fixed? Thanks!

**Comment by huizhilu** [comment]
+ @jordaniversen  @mhowlett @perdue @emasab for more visibility. Thank!

**Comment by PrasanthV454** [comment]
Hi @huizhilu, thanks for reporting this. We will make required changes and commit them in the next release.

JoinPath() do give a correct result but requires go 1.19 or later versions.

**Comment by milindl** [comment]
Closing with #950, it will make its way to the next release since it's merged.
