### ISSUE TITLE
Unable to compile with library when GOARCH is set to arm64

### ISSUE THREAD

**Issue by Subbiah-N-V** [confluentinc/confluent-kafka-go#947]
Description
===========
Hi, I have been struggling with an issue where no matter what I do, I cannot get my code to compile with GOARCH set to arm64. My project structure is as follows:
```
proj_folder
  - go.mod
  - go.sum
  - vendor
     - github.com/confluentinc/confluent-kafka-go/v2/kafka/ 
  - service
     - src
        - mainFolder
           - main.go
        - msgbus
           - kafka.go
```

My main.go looks like this:
```
package main

import (
	"fmt"
	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
)

func main() {
	var kClient kafka.Producer
	
	fmt.Printf("Hello world.\n")
	fmt.Printf("%v\n", kClient)
}
```

This is my compile script:
```
GOARCH=amd64 go build -o exec-amd64 ./service/src/mainFolder
GOARCH=arm64 go build -o exec-arm64 ./service/src/mainFolder
```

Result of the compilation:
```
+ GOARCH=amd64
+ go build -o exec-amd64 ./service/src/mainFolder
+ GOARCH=arm64
+ go build -o exec-arm64 ./service/src/mainFolder
# proj_folder/service/src/mainFolder
service/src/mainFolder/main.go:9:20: undefined: kafka.Producer
```

I am using v2.0.2 of the library since that comes with the arm64 library. I didn't use dynamic linking at first since the library has arm64 library with the package. That didn't work. I then tried cross compiling librdkafka versions 1.9.2 and 2.0.2 for arm64 but I still get the same error even though I set `tags` to `dynamic`. No matter what I do, it always compiles for amd64. However, for arm64, it always fails with the message that it cannot find kafka.(any member of the package I try to access).

In an act of desperation to remove any doubts about go.mod, I copied the entire kafka folder under src as a kafka folder and changed my import to that folder. That compiled for amd64 but not for arm64. It is always the same error that it is unable to find kafka and its members.

Does anyone have any clue as to what is going on here? It's likely I am doing something very dumb without realizing it but I have exhausted all avenues that I can think of.

Here's my go env:
```
dev:~/repo/ws/proj_folder$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/lib/go/bin"
GOCACHE="/home/dev/.cache/go-build"
GOENV="/home/dev/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dev/repo/ws/proj_folder/go.mod"
GOWORK="/home/dev/repo/ws/proj_folder/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build520739889=/tmp/go-build -gno-record-gcc-switches"
```

How to reproduce
================
Set GOARCH to arm64 and try to compile a file that imports kafka.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v2.0.2, v1.9.2
 - [ ] Apache Kafka broker version: N/A
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: Ubuntu 22.04
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
It may be because we're using cgo, and cross compilation isn't as straightforward in that case.

I installed gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu packages (which are probably available to you, since I'm using Ubuntu 22.04 too), and then tried using this: 
```
$ export CC=aarch64-linux-gnu-gcc ; GOOS=linux GOARCH=arm64 CGO_ENABLED=1 go build -v  -ldflags="-extld=$CC"
```
That worked for me to cross compile.

**Comment by Subbiah-N-V** [comment]
Thank you very much! That worked for me.

**Comment by ORESoftware** [comment]
use version 2+, see readme
