### ISSUE TITLE
A question regarding manual offset committing and message order

### ISSUE THREAD

**Issue by tchap** [confluentinc/confluent-kafka-go#95]
Description
===========

I have a question considering the behaviour of my program which I cannot really explain.

There is a channel-based consumer that is consuming messages. As they are consumed, they are passed over a channel to another component, which passes it to another component, which eventually passes it to a channel-based producer, which produces a message while storing the source Kafka message in Opaque. Now, when the producer receives a message sent confirmation on the events channel, it gets the source message stored in Opaque and passes it over a channel back to the consumer, which uses the source message to get the last partition offset successfully processes and the consumer eventually commits that offset. So the offset committing is manual.

Now, I am seeing some weird behaviour. I added a log statement that prints a warning when the consumer receives a message with a lower offset than it already saw:

```golang
// Print a warning in case the offset is going down.
if msg.TopicPartition.Offset < partitions[partition].Offset {
    logger.Warn(
        "partition offset has decreased",
        zap.Object("stored_partition", zapkafka.TopicPartition(partitions[partition])),
        zap.Object("message_partition", zapkafka.TopicPartition(msg.TopicPartition)),
    )
}
```

To my surprise, the program is printing a lot of warnings. What follows is a re-formatted output that schematically captures what is printed:

```
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428335},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428199}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428411},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428248}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428401},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428193}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428427},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428424}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428436},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428433}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428439},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428434}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428445},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428442}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428458},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428455}}

COMMIT: {"topic": "data.messages", "partition": 3, "offset": 27428457}

{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428457},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428452}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428464},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428462}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428463},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428460}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428475},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428472}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428473},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428471}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428472},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428470}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428736},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428734}}
{"stored_partition":  {"topic": "data.messages", "partition": 3, "offset": 27428743},
 "message_partition": {"topic": "data.messages", "partition": 3, "offset": 27428741}}
```

So, I would like to know how this is possible? Note that it is not only that the message offset is lower than the last stored offset, it also happens that the offset of a messages arriving after another message is lower that the offset of the previous message. How is all this possible?

How to reproduce
================

Nothing to reproduce really.

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v0.11.0, recent master commit 1a88e42dd84e077e9a84c511dfef2ca76da2000f
 - [X] Apache Kafka broker version: 0.11.0
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by tchap** [comment]
I should probably say explicitly that I am not reordering the messages in any way in the whole pipeline.

**Comment by tchap** [comment]
@edenhill I am kinda blocked on this. I would need to know whether this is a desired behaviour or not so that I can file a bug report or buffer the messages locally so know what is the smallest processed offset for each partition... Cheers!

**Comment by edenhill** [comment]
Is it possible that the consumer is rebalancing prior to offsets have been committed, and thus re-winding to a previously committed offset?
You can check this by enabling application rebalances and handling the Assign/RevokePartitions as we do here: https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/consumer_channel_example/consumer_channel_example.go#L70

I also suggest printing the message offset you get from the consumer channel to see if things are being rewinded.

**Comment by tchap** [comment]
Ah, I think that I know the reason. I store the consumer message in `Opaque` of the message being produces, but then that message can go to any partition based on the key, so I am probably receiving the source messages sorted within one producer partition, but in general the stream of source messages cannot be sorted as the producer messages they are tied with go to various partitions.

**Comment by tchap** [comment]
On the other hand I hit another thing:

Let's print the message offset for messages acknowledged:

```golang
case *kafka.Message:
    msg := e

    if err := msg.TopicPartition.Error; err != nil {
        return s.logError(
	    logger, err, "failed to deliver a message to Kafka",
	    zap.String("#message_key", string(msg.Key)),
            zap.Object("partition", zapkafka.TopicPartition(msg.TopicPartition)),
        )
    }

    if ce := logger.Check(zapcore.DebugLevel, "message delivered to Kafka"); ce != nil {
        ce.Write(
            zap.String("#message_key", string(msg.Key)),
            zap.Object("partition", zapkafka.TopicPartition(msg.TopicPartition)),
        )
    }
}
```

Then I used `grep 'message delivered' service.log | grep '"partition": 0' | grep -o '"offset": [0-9]\+' | awk '{ print $2 }' > offsets.delivered.txt`. The thing is, there are quite some zero offsets there: 
[offsets.delivered.txt](https://github.com/confluentinc/confluent-kafka-go/files/1317718/offsets.delivered.txt)

It does not really affect my service, but now I am not sure whether this is a bug or a feature 😄

**Comment by edenhill** [comment]
Try setting `produce.offset.report` to true for the producer, otherwise it will only report the offset of the last message in each batch/messageSet.

The go client should really do this by default.

**Comment by tchap** [comment]
Ok, that fixed things. I guess that I can close this, cheers!
