### ISSUE TITLE
server response: not found: github.com/confluentinc/confluent-kafka-go@v2.0.2: invalid version: go.mod has post-v2 module path "github.com/confluentinc/confluent-kafka-go/v2" at revision v2.0.2

### ISSUE THREAD

**Issue by baganokodo2022** [confluentinc/confluent-kafka-go#956]
Description
===========
go get github.com/confluentinc/confluent-kafka-go@v2.0.2
go: github.com/confluentinc/confluent-kafka-go@v2.0.2: reading https://gomodules.cbhq.net/github.com/confluentinc/confluent-kafka-go/@v/v2.0.2.info: 404 Not Found
	server response: not found: github.com/confluentinc/confluent-kafka-go@v2.0.2: invalid version: go.mod has post-v2 module path "github.com/confluentinc/confluent-kafka-go/v2" at revision v2.0.2

How to reproduce
================
go get github.com/confluentinc/confluent-kafka-go@v2.0.2

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
Can you try `go get github.com/confluentinc/confluent-kafka-go/v2@v2.0.2` ?

**Comment by baganokodo2022** [comment]
works
