### ISSUE TITLE
Pattern subscription

### ISSUE THREAD

**Issue by vinceprignano** [confluentinc/confluent-kafka-go#96]
Is pattern subscription supported? As far as I can tell I can only blacklist topics from the metadata in the configuration reported [here](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md). 

If this feature is not supported and the consumer is thread-safe, I guess one possible approach would be to check and subscribe on demand when the metadata changes at runtime from a goroutine running on a timer.

**Comment by treziac** [comment]
`SubscribeTopics` support regex when prefixed with `^`

**Comment by edenhill** [comment]
To extend on what @treziac says: patterned topics (`"^my.*pattern.."`) and fixed topics can be freely mixed in the subscription list.

**Comment by vinceprignano** [comment]
Perfect, thanks!
