### ISSUE TITLE
[AdminClient] memory leak in long-lived AdminClient 

### ISSUE THREAD

**Issue by jamiealquiza** [confluentinc/confluent-kafka-go#967]
Description
===========

Version: `confluent-kafka-go:1.8.2`

When creating an admin client via `NewAdminClient`, a [producer is initialized](https://github.com/confluentinc/confluent-kafka-go/blob/3d9047adc3ae9b41069988298906624497175962/kafka/adminapi.go#L2371-L2376). This effectively causes a memory leak if the underlying Events channel isn't consumed.

How to reproduce
================

- Initialize admin client via `NewAdminClient`
- Fetch topic metadata via `GetMetadata` (did not verify whether this step is required for the event channel to begin filling)
- Keep admin client alive (ie don't call `Close()`)

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
Hi @jamiealquiza , thanks for the report. As far as I can see, the Events channel of the underlying producer remains empty during the time it's being used as an adminclient (there's actually no events channel created at all, I'm talking about the queue of librdkafka that it corresponds to).

However, if you're seeing some memory leaks while profiling your code, please let me know, we can look into that. It's possible that there's a different cause or some other queue is getting filled up.

**Comment by milindl** [comment]
Closing this due to above comment, please reopen if it occurs with the extra logs or code.
