### ISSUE TITLE
sonarQube show Security Hotspots

### ISSUE THREAD

**Issue by caioformiga** [confluentinc/confluent-kafka-go#978]
Description
===========

sonarQube show Security Hotspots to review on lines 14 and 19 of confluent-kafka-go/kafka/api.html file on v1.8.2 and v1.9.0

![image](https://user-images.githubusercontent.com/2387851/230377295-09216080-a1da-4f02-a6e3-1d58b5226601.png)

![image](https://user-images.githubusercontent.com/2387851/230377363-b30111ed-7c52-4504-8ccd-f6fb86fad17a.png)

![image](https://user-images.githubusercontent.com/2387851/230377430-d19ee869-b702-4eff-917e-38171d7a2935.png)

How to reproduce
================

Just checking code quality and it show this as a security issue

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.8.2 and v1.9.0
 - [ ] Apache Kafka broker version: 
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
I'm closing this because the api.html file is generated by the official [go doc](https://pkg.go.dev/go/doc) tool, and the links are to go.dev pages. While this may be a security issue, this would best be filed in the repository of the `go doc` tool.
