### ISSUE TITLE
Go process killed

### ISSUE THREAD

**Issue by simpajj** [confluentinc/confluent-kafka-go#98]
Description
===========
I'm running a single producer-consumer setup, similar to the kafkacat example. The producer sends 100k 1024-byte messages, after which a consumer subscribes and consumes all of the messages. I know that this is a bit of strange setup, having the consumer not subscribe before the producer has sent its messages, but I just want to get idea of the throughput of both clients. 

After about 65-75 iterations, the Go process is abruptly killed. At first I thought that this might have to do with [confluentinc/confluent-kafka-go#94](https://github.com/confluentinc/confluent-kafka-go/issues/94), so I updated to librdkafka-HEAD-3546acd via Homebrew but the issue still prevailed. I also tried updating this library from 0.11 to master, but still encountered the same issue.

I'm not sure if it's related to this library or if it's a general Go issue similar to [golang/go#19734](https://github.com/golang/go/issues/19734), but I've also tried building with '-ldflags=-s', which also didn't help. I am running macOS High Sierra with the latest command line tools. 

Using a message size of 512 bytes does not trigger the error within 100 iterations at least, so I'm wondering if this has to do with some unbuffered channel that I've not properly configured?

How to reproduce
================

Producer:
```go
func (kb *KafkaBenchmark) Produce() {
	kb.producer.ProduceChannel() <- &kafka.Message{
		TopicPartition: kafka.TopicPartition{Topic: &kb.topic, Partition: kafka.PartitionAny},
		Value:          kb.msg,
	}
	go func(events chan kafka.Event) {
		for ev := range events {
			switch e := ev.(type) {
			case *kafka.Message:
				if e.TopicPartition.Error != nil {
					log.Printf("Warning: error publishing msg to topic: %v\n", e.TopicPartition.Error.Error())
					kb.errors++
				} else {
					// do nothing for now
				}
			}
		}
	}(kb.producer.Events())
}
```

Consumer: 
```go
func (kb *KafkaBenchmark) Consume() {
	err := kb.consumer.Subscribe(kb.topic, nil)
	if err != nil {
		log.Fatalf("Failed to subscribe to topic %s: %v", kb.topic, err)
	}
	go func() {
		for {
			select {
			case ev := <-kb.consumer.Events():
				switch e := ev.(type) {
				case kafka.AssignedPartitions:
					kb.consumer.Assign(e.Partitions)
				case kafka.RevokedPartitions:
					kb.consumer.Unassign()
				case *kafka.Message:
					kb.recv <- e.Value
				}
			}
		}
	}()
}
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): master + HEAD-3546acd
 - [x] Apache Kafka broker version: 0.11.0.1
 - [x] Client configuration: `ConfigMap{
		"bootstrap.servers":               fmt.Sprintf("%s:%d", kb.host, kb.port),
		"group.id":                        "test",
		"go.application.rebalance.enable": true,
		"go.events.channel.enable":        true,
		"go.events.channel.size":          int(kb.numMsgs),
		"queued.max.messages.kbytes":      10000,
		"default.topic.config":            kafka.ConfigMap{"auto.offset.reset": "earliest"},
	}`
 - [x] Operating system: macOS High Sierra
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Have you tried reproducing this with only the producer or consumer side?
Is there anything relevant in `sudo dmesg`?
Have you monitored the memory usage of the process before it dies? (e.g., by `top ..`)

Comments on https://github.com/golang/go/issues/19734 also suggest upgrading to Go 1.8.x fixes the problem, what Go version are you on?

**Comment by simpajj** [comment]
Thanks for the quick reply! 

I'm on Go 1.9, so shouldn't be the issue unless that same bug has been reintroduced. 
From `sudo dmesg`: 

```
low swap: killing largest compressed process with pid 52791 (mqbenchmark) and size 756 MB
memorystatus: killing_idle_process pid 768 [ReportCrash]
Starting poll type 4
Restarting poll type 4
```

The memory usage fluctuates a bit, soaring up to about 9000M for the first 20 or so iterations, after which it declines to around 6600-7000M until it is killed at about 8000M. I'll do as you suggested next and try to reproduce it with only a producer or a consumer and let you know what I find.

**Comment by simpajj** [comment]
Found the issue. The consumer sends all consumed messages on a buffered channel, for which I had set the buffer way too high. Apologies for having bothered you with this :)

**Comment by edenhill** [comment]
Good to know, thanks!
