### ISSUE TITLE
Need api info to get a lag of a topic

### ISSUE THREAD

**Issue by jayeshvaltix** [confluentinc/confluent-kafka-go#995]
Team,

I need to fetch the lag of given topics based on group passed, is there any api available ?
Something similar to this command
kafka-consumer-groups --bootstrap-server <> -describe --group mygroup --command-config <>
this fetches info about all the topics assigned to group mygroup

I'm using a new kafka.NewAdminClient in GO. I want this lag info without being a consumer.
Please provide details of api available ?

**Comment by jayeshvaltix** [comment]
Team, can you get any info on this

**Comment by milindl** [comment]
Ideally, you would be able to use the ListOffsets method to get the end offset and the ListConsumerGroupOffsets method to get consumer group's committed offsets and take the difference of the two to find the lag.
However, ListOffsets is not yet implemented for the underlying library, though we do plan to implement it in our internal roadmap. 

In the meanwhile, as a workaround, you can create a dummy consumer (which doesn't subscribe to any topics), and use QueryWatermarkOffsets method of the consumer to fetch the high watermark offset, and use the admin client ListConsumerGroupOffsets to fetch the commited offset.

Hope that helps.

**Comment by milindl** [comment]
Closing this, please reopen for further clarifications about this.
